### ISSUE TITLE
System.ArgumentOutOfRangeException when attempting to draw text that is not out of bounds

### ISSUE THREAD

**Issue by QuantumToasted** [SixLabors/ImageSharp#1013]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Similar to #688, attempting to use `IImageProcessingContext#DrawText` with a moderately specific set of arguments produces a `System.ArgumentOutOfRangeException`. However, unlike this issue, it does not *seem* to have anything to do with the bounds of the image, instead some unknown factors that someone might be able to pinpoint better than I can.

### Steps to Reproduce

The code below works properly, and produces the following image:
![image](https://user-images.githubusercontent.com/30324210/65359801-45f06980-dbc3-11e9-90e6-d293776765c6.png)
```cs
var canvas = new Image<Rgba32>(Configuration.Default, 450, 300);
canvas.Mutate(cnvs =>
{
    cnvs.Fill(SixLabors.ImageSharp.Color.Gray);
    cnvs.DrawText(new TextGraphicsOptions {HorizontalAlignment = HorizontalAlignment.Center},
        "a", SystemFonts.CreateFont("Arial", 11),
        SixLabors.ImageSharp.Color.WhiteSmoke, new PointF(255, 248));
});
```

Changing the `"a"` string in the above code to `"ab"` or any longer sequence of characters seems to trigger this exception. I didn't test a large range of strings, I tried the smallest possible number of characters and added a single extra character at a time until it started throwing the exception.

Update: I have been trying other combinations of letters, and I seem to be struggling to get this to work with anything other than just `"a"`. `"ab"` doesn't work as I said before, but...just `"b"` doesn't work, either? It's extremely inconsistent for me.

### System Configuration

- ImageSharp version: Latest nightlies `1.0.0-dev002988`
- Other ImageSharp packages and versions: ImageSharp.Drawing - `1.0.0-dev002988`
- Environment (Operating system, version and so on): Windows 10 x64
- .NET Framework version: .NET Core 3.0.100-preview3-010431
- Additional information: This is a very simplified version (for the sake of testing) of code I wrote which worked perfectly fine in November 2018. Porting this code over to another project made this bug surface for the first time for me.

**Comment by QuantumToasted** [comment]
Alright, upon further inspection it seems to be something to do with .NET Core 3.0's previews. Changing to .NET Core 2.2 or earlier does not seem to create this exception, and the code works fine.

**Comment by JimBobSquarePants** [comment]
Thanks for adding so much information, very much appreciated!

That’s a pretty early NET Core 3 preview, does it replicate in the new RC? If so we better tell Microsoft so we can work with them on a solution.

**Comment by QuantumToasted** [comment]
Well I feel like a moron now. I was running on some arbitrary preview and haven't updated in a while. I just updated to the new RC and the problem seems to have fixed itself! I'm glad it didn't need to result in a headache for anyone else at least. We can close this unless you see a need to provide compatibility for this random preview build.

**Comment by JimBobSquarePants** [comment]
No worries, easy mistake to make! :smile: We plan to add a target to 3.0 when it comes out but not before, as you can see, a bit to unstable in previous builds
