### ISSUE TITLE
difference in dev mode and release mode

### ISSUE THREAD

**Issue by marcopoloIR** [SixLabors/ImageSharp#1023]
i use sixlabors in my web application.
in local and dev mode, everything is ok,
but when publish, i get this erros:

**Could not load file or assembly 'SixLabors.ImageSharp.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Format of the executable (.exe) or library (.dll) is invalid.**

**Comment by JimBobSquarePants** [comment]
Please fill in the provided issue template
