### ISSUE TITLE
Error reading image from TCP NetworkStream

### ISSUE THREAD

**Issue by Sheyne** [SixLabors/ImageSharp#1029]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
If I try to read a PNG image from a NetworkStream, my app hangs

### Steps to Reproduce

Set `mode = 0` or `mode = 1` and the app hangs, set `mode = 2` and the test passes as expected. 

```c#
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Sockets;
using System.Threading.Tasks;
using FluentAssertions;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Advanced;
using SixLabors.ImageSharp.Formats.Png;
using SixLabors.ImageSharp.PixelFormats;
 
namespace NextGen.Test.TesterApp
{
    internal class Program
    {
        private static async Task Main(string[] args)
        {
            // create a tcp socket to play with
            var listener = new TcpListener(IPAddress.Loopback, 0);
            listener.Start();
            var acceptanceTask = listener.AcceptTcpClientAsync();
 
            {
                // dump a PNG image into the TCP port
                var client = new TcpClient();
                var endPoint = (IPEndPoint)listener.LocalEndpoint;
                await client.ConnectAsync(IPAddress.Loopback, endPoint.Port);
 
                var stream = client.GetStream();
                var encoder = new PngEncoder
                {
                    BitDepth = PngBitDepth.Bit16,
                    ColorType = PngColorType.Grayscale
                };
 
                var image = Image.LoadPixelData<Gray16>(new byte[] { 1, 2, 3, 4, 5, 6, 7, 8 }, 2, 2);
                encoder.Encode<Gray16>(image, stream);
            }
 
            {
                // get a handle to the other end of the tcp socket
                var client = await acceptanceTask;
                Stream stream = client.GetStream();

                // play with this value to choose test mode
                var mode = 1;
                switch (mode)
                {
                    case 0:
                        // use the TCP NetworkStream directly
                        // This fails
                        break;
                    case 1:
                        // buffer the TCP NetworkStream, but still use it with the normal paradigm
                        // This fails
                        stream = new BufferedStream(stream, 4096);
                        break;
                    case 2:
                        // read all the bytes from the stream and use them to create a MemoryStream
                        // This works!
                        var bytes = new byte[4096];
                        stream.Read(bytes, 0, bytes.Length);
                        stream = new MemoryStream(bytes);
                        break;
                }
 
                // this call will hang in cases 0 and 1, but succeed and decode correctly for case 2
                var image = Image.Load<Gray16>(stream);
 
                image.GetPixelSpan().ToArray().Should()
                    .BeEquivalentTo(new ushort[]
                    {
                        0x201, 0x403, 0x605, 0x807
                    }.Select(x=>new Gray16(x)));
            }
        }
    }
}
```
### System Configuration

- ImageSharp version: 1.0.0-beta0007
- Other ImageSharp packages and versions: N/A
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: Core 3.0 and Framework 4.8
- Additional information:

**Comment by benaadams** [comment]
`Image.Load<Gray16>(stream)` is waiting for the end of the stream; however the stream never ends; because the client's stream remains open:

`var stream = client.GetStream();`

Can change it to 
```
using var stream = client.GetStream();
```
Or call 
```
stream.Close();
```

It works with MemoryStream as the MemoryStream as defined above has an end.

Aside: The memoryStream is too big as its set to the size of the array; not the size of what was read from `stream.Read`

**Comment by Sheyne** [comment]
What if I want to transmit several images on the same stream? Is this possible?

**Comment by benaadams** [comment]
You'd likely want to specify a length at the start; read that then wrap the network stream in a new stream that forwards the read/readasync calls to the underlying stream, but only up to that maximum length and then returns -1. So it acts a smaller stream, then pass that to `.Load`; when it returns you can then read the next length etc.

**Comment by JimBobSquarePants** [comment]
Thanks for chipping in here @benaadams very much appreciated! 👍 

I'll close this off now @Sheyne since we've been able to determine there isn't an issue with the library.

**Comment by Sheyne** [comment]
Thanks everyone

**Comment by omariom** [comment]
@Sheyne [Nerdbank.Streams](https://github.com/AArnott/Nerdbank.Streams/blob/master/doc/Substream.md) has what you need.
