### ISSUE TITLE
PNG from web url fails to load or identify.

### ISSUE THREAD

**Issue by EelhandsMcCoy** [SixLabors/ImageSharp#1047]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Downloading certain png as a byte array or a stream results in errors.  Either "stream is invalid" or "png contains no data chunk" etc.

### Steps to Reproduce
                    var client = _httpClientFactory.CreateClient();
                    var bytes = await client.GetStreamAsync(p.ImageUrl);
                    var image = SixLabors.ImageSharp.Image.Load(bytes, new PngDecoder());

### System Configuration
- ImageSharp version: 1.0.0 beta 7.
- Other ImageSharp packages and versions: 
- Environment (Operating system, version and so on): Windows 10 x64.
- .NET Framework version: .Net Core 3.
- Additional information:

Here are the images:
![75c585ba-a391-e811-ad47-b8ca3a6870b8](https://user-images.githubusercontent.com/34070111/68345081-839b4a00-00be-11ea-968e-f9baeb16c3f7.png)
![0a2d3ae2-4f6e-e711-8cac-b8ca3a687730](https://user-images.githubusercontent.com/34070111/68345082-839b4a00-00be-11ea-8740-7d06b006a9ee.png)

**Comment by JimBobSquarePants** [comment]
Try the following: 

```c#
var client = _httpClientFactory.CreateClient();
using(var bytes = await client.GetStreamAsync(p.ImageUrl)) {
    // Remember to dispose of this image once you are finished.
    var image = SixLabors.ImageSharp.Image.Load(bytes, new PngDecoder());
}
```

It looks to me like you're having the same issue as https://github.com/SixLabors/ImageSharp/issues/1029#issuecomment-544061230

**Comment by EelhandsMcCoy** [comment]
Switched to the suggested code, same issue. ImageFormatException: Image stream is not valid.

**Comment by JimBobSquarePants** [comment]
What happens when you copy your input stream to a memorystream and load via that? Something is causing your stream not to flush.

**Comment by EelhandsMcCoy** [comment]
Same thing happens.

**Comment by JimBobSquarePants** [comment]
Thanks for the extra info, I appreciate it. 

> I ran both files through pngcheck, and it reports "EOF while reading CRC value.
I have done some investigation and confirmed your findings. However we are attempting to read the crc data from those images and throwing an error whether they are critical or not. I will work on a fix asap.
