### ISSUE TITLE
Exception when resizing an image (Unable to cast object of type 'System.UInt32[]' to type 'System.UInt32')

### ISSUE THREAD

**Issue by xhafan** [SixLabors/ImageSharp#1049]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Exception when resizing an image `(Unable to cast object of type 'System.UInt32[]' to type 'System.UInt32')`. Image url: https://media-cdn.sygictraveldata.com/media/612664395a40232133447d33247d383335343639373137.jpg (the image copy: https://www.dropbox.com/s/5j8j01esni9p5ho/612664395a40232133447d33247d383335343639373137.jpg?dl=0)

### Steps to Reproduce
```
    var image = Image.Load(imageStream);
    image.Mutate(x => x.Resize(700, 700));
```
The stacktrace:
```
SixLabors.ImageSharp.ImageProcessingException : An error occurred when processing the image using ResizeProcessor`1. See the inner exception for more detail.
  ----> System.InvalidCastException : Unable to cast object of type 'System.UInt32[]' to type 'System.UInt32'.
   at SixLabors.ImageSharp.Processing.Processors.CloningImageProcessor`1.CloneAndApply(Image`1 source, Rectangle sourceRectangle)
   at SixLabors.ImageSharp.Processing.Processors.CloningImageProcessor`1.Apply(Image`1 source, Rectangle sourceRectangle)
   at SixLabors.ImageSharp.Processing.DefaultInternalImageProcessorContext`1.ApplyProcessor(IImageProcessor`1 processor, Rectangle rectangle)
   at SixLabors.ImageSharp.Processing.DefaultInternalImageProcessorContext`1.ApplyProcessor(IImageProcessor`1 processor)
   at SixLabors.ImageSharp.Processing.ResizeExtensions.Resize[TPixel](IImageProcessingContext`1 source, Int32 width, Int32 height)
   at SmartGuide.Core.ImageResizers.ImageResizer.<>c.<ResizeImage>b__0_0(IImageProcessingContext`1 x) in ImageResizer.cs:line 17
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Action`1 operation)
   at SmartGuide.Core.ImageResizers.ImageResizer.ResizeImage(Stream imageStream, Int32 newWidth, Int32 jpegQuality)
```

### System Configuration
- ImageSharp version: 1.0.0-beta0007
- Other ImageSharp packages and versions: 1.0.0-beta0006, 1.0.0-dev003081 (all versions listed has the issue)
- Environment (Operating system, version and so on): Windows 10 Pro (10.0.17763.615), Linux (Amazon Linux AMI 2.0.20190614 x86_64 ECS HVM)
- .NET Framework version: .NET Core 2.2.104

**Comment by JimBobSquarePants** [comment]
![612664395a40232133447d33247d383335343639373137](https://user-images.githubusercontent.com/385879/68560827-1ceba700-0497-11ea-85f8-16f7fc2b7029.jpg)

**Comment by JimBobSquarePants** [comment]
Looks like another EXIF issue. @dlemstra I'd really like to revisit this API to make it typesafe.

**Comment by JimBobSquarePants** [comment]
@dlemstra I had a look at the updated code in the your Magick.NET version of the EXIF profile (Much better btw!) and as I understand the code your changes pretty much eradicate issues such as this. 

I have an idea that would make getting and setting values type safe also.

Consider the following methods, they remove any guesswork and ambiguity from the API:

``` c#
public ExifValue<TValueType> GetValue<TValueType>(ExifTagKey<TValueType> key)
{
    foreach (var exifValue in Values)
    {
        if (exifValue.Tag == key.Tag)
            return (ExifValue<TValueType>)exifValue;
    }

    return null;
}

public void SetValue<TValueType>(ExifKey<TValueType> key, TValueType value)
{
    foreach (var exifValue in Values)
    {
        if (exifValue.Tag == key.Tag)
        {
            exifValue.Value = value;
            return;
        }
    }

    var newExifValue = ExifValues.Create(tag.Tag, value);
    _values.Add(newExifValue);
}
```
Instead of using `ExifTag` enum as the external key the trick is to define a class similar to your `ExifValue<TValueType>` and then define a constant for each tag as you have the values.

``` c#
public abstract class ExifKey<TValueType>
{
    internal ExifKey(ExifTag tag)
    {
        Tag = tag;
    }

    public ExifTag Tag { get; }
}
```
What do you think?

**Comment by dlemstra** [comment]
This issues also occurs in the Magick.NET library and I just pushed a patch there to resolve this.

I like your idea but I am not sure about the naming and implementation yet. Will do some experiments to figure out what would work the best.

**Comment by JimBobSquarePants** [comment]
Great! Looking forward to it.
