### ISSUE TITLE
how to make tiling watermark by ImageSharp simply?

### ISSUE THREAD

**Issue by Calx-Takeno** [SixLabors/ImageSharp#1051]
I have done this effect but not very good I think so.
I am using DrawText method and pre-calculate every text watermark point to do.
But I haven't found how to roate this text watermark when DrawText.
I want to make every text watemark rotate 45-degree angle. Like below image effect
Wolud you have another simple way to do this？
![preview](https://user-images.githubusercontent.com/22338989/68639979-4a8d2a80-0541-11ea-967b-4cdc1b7a7df2.png)

**Comment by antonfirsov** [comment]
@Calx-Takeno you can draw the text along a straight line as an `IPath`. Here is a sample for a more complex case:
https://github.com/SixLabors/Samples/blob/master/ImageSharp/DrawingTextAlongAPath/Program.cs

Does this help?
