### ISSUE TITLE
How to add an image watermark

### ISSUE THREAD

**Issue by siddharthyadav01** [SixLabors/ImageSharp#1056]
Hi,
  The code being used to create image using SixLabors.ImageSharp(1.0.0-beta0006) nuget is as below

```
using (var image = Image.Load(filePath, out var imageFormat))
                  
{
                        image.Mutate(imageProcess => imageProcess.Resize(new ResizeOptions
                        {
                            Mode = ResizeMode.Max,
                            Size = CalculateDimensions(image.Size(), targetSize)
                        }));
                        var pictureBinary = EncodeImage(image, imageFormat);
                        SaveThumb(thumbFilePath, thumbFileName, imageFormat.DefaultMimeType, pictureBinary);

}
```

I also want to add an image watermark on the current image being saved with some opacity. I tried several ways but was unable to do it. Please let me know how this can be done.

**Comment by JimBobSquarePants** [comment]
As indicated by the template guide we highlighted (you deleted) when creating the issue we do not answer questions in the issue tracker. We have a [Gitter channel](https://gitter.im/ImageSharp/General) specifically for that purpose.
