### ISSUE TITLE
Support for keeping aspect ratio and using dimensions parameters when resizing as max dimensions

### ISSUE THREAD

**Issue by JadaVonRuth** [SixLabors/ImageSharp#1063]
It would be ideal if no other computation regarding dimensions would necessary to place despite it is not anything hard, but in terms of usability it would be more benefitial.

**Comment by tocsoft** [comment]
you can do this today just pass `Max` as the resize mode in while resizing.
The various options are detailed here 
https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Processing.ResizeMode.html#fields
