### ISSUE TITLE
Incompatible with `netcoreapp3.1` framework

### ISSUE THREAD

**Issue by define-private-public** [SixLabors/ImageSharp#1077]
I tried grabbing the latest release of ImageSharp for a website I'm trying to make.  When adding the package, I got the error message

    error:   - Found 7 version(s) in nuget.org [ Nearest version: 1.0.0-beta0007 ]
    error: Package 'SixLabors.ImageSharp' is incompatible with 'all' frameworks in project `MyProject.csproj`

Right now my target framework is `netcoreapp3.1`.  Will this be supported?

**Comment by brianpopow** [comment]
yes ImageSharp works with target framework `netcoreapp3.1`, there must be something else wrong with your project file. Without knowing how your project file looks, its hard to tell.

**Comment by JimBobSquarePants** [comment]
[ImageSharpCompatibilityDemo.zip](https://github.com/SixLabors/ImageSharp/files/4045249/ImageSharpCompatibilityDemo.zip)
Yup. Works perfectly. I've attached a working website here. 

P.S Please use the issue template when raising issues. It's important for us to be able to effectively triage.

**Comment by define-private-public** [comment]
That's my .csproj file.  Is it possible there's a dependency that's blocking the use for ImageSharp?

```<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UserSecretsId>It's a secret!</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.Storage.V1" Version="2.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="3.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="3.1.0" />
  </ItemGroup>

</Project>
```

**Comment by brianpopow** [comment]
@define-private-public i have just tried this project file and it compiles just fine with a ImageSharp reference `1.0.0-beta0007`

**Comment by define-private-public** [comment]
Okay.  When I tried to add `ImageSharp`.  I didn't specify the `--version`.  doing that works for me.
