### ISSUE TITLE
Expose members so can subclass Image

### ISSUE THREAD

**Issue by UkooLabs** [SixLabors/ImageSharp#1080]
Please change from internal so I can subclass Image the following methods...

 Accept
 EnsureNotDisposed 

Doing so will allow me to create a MipMap class based off of Image for the ImageSharp.Textures library

**Comment by antonfirsov** [comment]
As always, I strongly oppose allowing `Image<T>` to be subclassed. [Composition Over Inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance) approach leads to better solutions on consumer side.

Is `MipMap` indeed an Image according to the rules of the [Liskov Substitution Principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle)?

As far as I understand the answer is a definite NO:
- MipMap is a serie of power of two sized images
- One should not pass a `MipMap` to an arbitrary `ImageProcessor`

Consequence: a `MipMap<T> : Image<T>` inheritance would be an LSP violation.

**Comment by JimBobSquarePants** [comment]
@antonfirsov Was hoping you'd have a look at this 👍

**Comment by UkooLabs** [comment]
Maybe I can achieve same desired goal using decorator pattern.
