### ISSUE TITLE
Looking for methods to Plot Single Pixel

### ISSUE THREAD

**Issue by StevenGann** [SixLabors/ImageSharp#1088]
### Description
Attempting to use the following code results in a compile-time error:

```
using (Image image = new Image<Rgba32>(1920, 1080))
{
    for (int i = 0; i < 1920; i++)
    {
        for (int j = 0; j < 1080; j++)
        {
            double A = tree.Get(i, j, 0, 4).A;
            byte a = (byte)(A * 255);
            Rgba32 pixel = new Rgba32(a, a, a);
            image[i, j] = pixel;
        }
    }
}
```

Error message:

```
Error	CS0021	Cannot apply indexing with [] to an expression of type 'Image'
```

- ImageSharp 1.0.0-beta0007 from Nuget
- .NET Core 2.5
- Windows 10

All I need is a way to plot greyscale pixels onto an image in .NET Core. How am I supposed to plot individual pixels with ImageSharp?

**Comment by JimBobSquarePants** [comment]
As indicated by the issue template. Please do not ask questions in the issues tracker.

> You should not create an issue but use Gitter instead: https://gitter.im/ImageSharp/General

_(This is your first issue though so I can understand and appreciate an honest mistake)_

So to answer your question. `Image` is a pixel agnostic abstraction of your pixel buffer that allows operating on pixel data via the processing pipeline without being concerned by the pixel format. If you look at our readme we are actually using the implicit typed local variable `var` to represent `Image<Rgba32>`  which contains the indexer you are looking for.

`Image<TPixel>` inherits `Image` adding direct pixel access.

```c#
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;

// Individual pixels
using (var image = new Image<Rgba32>(400, 400))
{
    image[200, 200] = Rgba32.White;
}
```

Our API docs. Linked from the repository representing the [`Image<TPixel>[x, y]`](https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Image-1.html#SixLabors_ImageSharp_Image_1_Item_System_Int32_System_Int32_) indexer can be found here.

In your scenario though I would recommend using [`image.GetPixelRowSpan<TPixel>(y)`](https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Advanced.AdvancedImageExtensions.html#SixLabors_ImageSharp_Advanced_AdvancedImageExtensions_GetPixelRowSpan__1_SixLabors_ImageSharp_Image___0__System_Int32_) since that allows you to operate on a per-row basis removing the need to calculate the pixel offset in the buffer per pixel operation.

``` c#
using (Image<Rgba32> image = new Image<Rgba32>(1920, 1080))
{
    for (int y = 0; y < image.Height; y++)
    {
        Span<Rgba32> row = image.GetPixelRowSpan(y);

        for (int x = 0; x < row.Length; x++)
        {
            double A = tree.Get(y, x, 0, 4).A;
            byte a = (byte)(A * 255);

            ref Rgba32 pixel =  ref row[x];
            pixel.R = a;
            pixel.G = a;
            pixel.B = a;
            pixel.A = 255;
        }
    }
}
```

I hope that all makes sense. 😄

**Comment by StevenGann** [comment]
I mean, this is less a question and more a bug report, but I'll post it to gitter instead. I thought gitter was a chat room, not an issue tracker.

**Comment by StevenGann** [comment]
Just as well, the `Span<Rgba32>` has a similar problem:

`CS1061	'Image<Rgba32>' does not contain a definition for 'GetPixelRowSpan' and no accessible extension method 'GetPixelRowSpan' accepting a first argument of type 'Image<Rgba32>' could be found`

**Comment by tocsoft** [comment]
closing as its a question raised due to not knowing how to use the APIs and where to find them not because APIs in ImageSharp are broken.

**Comment by StevenGann** [comment]
No, I know where the APIs are. The package distributed through NuGet does not implement the APIs as documented. The issue is that the code presented by @JimBobSquarePants does not work.

It's not a question. It's an error message. If you struggle with the English language I can understand but I feel like critical thought should transcend linguistic differences. If you could provide a demonstration of code that actually works, that'd be super, but as it stands the NuGet package does not function using the example code provided.

If you'd like, I can go through your source and figure out the actual API that's implemented and edit your docs for you.

**Comment by StevenGann** [comment]
`CS1061 'Image<Rgba32>' does not contain a definition for 'GetPixelRowSpan' and no accessible extension method 'GetPixelRowSpan' accepting a first argument of type 'Image<Rgba32>' could be found`

Now, if you can step off your enormous ego and consider that maybe compiler errors in your own code could possibly be because you've made a mistake, please review your own docs:

https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Image-1.html#SixLabors_ImageSharp_Image_1_Item_System_Int32_System_Int32

As the compiler error points out, the `Image<Rgba32>` class has no method called `GetPixelRowSpan`, nor is there one in the NuGet package.

I didn't write these docs, or the example code above, so please direct your juvenile attitude at whoever did instead of the end user who's trying to make use of your software and is quickly realizing he'd be better off using a library maintained by professionals instead.

**Comment by JimBobSquarePants** [comment]
>so please direct your juvenile attitude at whoever did instead of the end user who's trying to make use of your software and is quickly realizing he'd be better off using a library maintained by professionals instead.

You owe everyone here an apology for your incredibly unprofessional behavior. The working code attached here is a copy/paste from the sample I posted [above](https://github.com/SixLabors/ImageSharp/issues/1088#issuecomment-576954752).

[ISPixelDemo.zip](https://github.com/SixLabors/ImageSharp/files/4100001/ISPixelDemo.zip)

**Comment by StevenGann** [comment]
1. My original ticket was quite polite. The maintainers of this library have been extraordinarily rude and ignore the actual content of messages, responding instead with ego and spite. 

2. As for the code listed above, please see the error message from Visual Studio:

`CS1061	'Image<Rgba32>' does not contain a definition for 'GetPixelRowSpan' and no accessible extension method 'GetPixelRowSpan' accepting a first argument of type 'Image<Rgba32>' could be found (are you missing a using directive or an assembly reference?)` 

I don't know what to tell you other than I reported an issue I thought might be a bug, I was told to report it on a chat room instead, was told that I was wrong for using the code you'd provided or for following the API docs, my issue was closed, I was then asked to report any errors, and the project you attached has exactly the same compile-time error as it did when I copy-pasted it into a clean project.

There's a number of problems here, and one may just be my own .NET install. One thing I know for sure is that lack of professionalism and excess of ego is a major one. In the future, when dealing with end users, it is worth actually reading tickets instead of falsely categorizing them and rudely dismissing them.

**Comment by StevenGann** [comment]
But, to be sure there's no hard feelings, I apologize to @tocsoft and @JimBobSquarePants for reporting a possible issue with their NuGet package and/or docs on GitHub instead of posting it on gitter first.

**Comment by StevenGann** [comment]
Though, perhaps I was too subtle with my title. I should have explicitly stated that I was referencing issue #458 and had found that the prescribed approach provided in that ticket was not working, hence the issue coming back. Maybe I should have commented on that issue instead of creating a new one, but live and learn.

**Comment by JimBobSquarePants** [comment]
Here's a working (compiled, run) version of the example application targeting NET Core 2.1

[ISPixelDemo_2_1.zip](https://github.com/SixLabors/ImageSharp/files/4100516/ISPixelDemo_2_1.zip)

**Comment by dolkensp** [comment]
> There's a number of problems here, and one may just be my own .NET install. One thing I know for sure is that lack of professionalism and excess of ego is a major one. In the future, when dealing with end users, it is worth actually reading tickets instead of falsely categorizing them and rudely dismissing them.

As an outsider looking in - @JimBobSquarePants answered you quite professionally by directing you to the correct place to receive the support you needed, and *still* attempted to help you in here.

Not only that, but you're citing #458 as the your reference issue, and the exact same message is provided there: For Q&A, use Gitter, for bugs, use Github.

To be honest, the only ego I really saw here was yours when you attacked the repo maintainers for explaining to you that you didn't quite understand the API implementation, that there was no bug, and then provided working sample code that solved your problem.

This guy's been maintaining this library for longer than you've been out of school, so perhaps consider that next time you accuse him of not understanding his own creation?

**Comment by merarischroeder** [comment]
I wonder, is "incorrect" documentation considered a bug by the maintainers here? I suggest that clarification of this will help others in the future.

That will help the maintainers and newcomers alike.

**Comment by tocsoft** [comment]
@merarischroeder  yes it is I we welcome a docs issues being pointed out.

Thing we consider official documentation however is limited to our docs website (https://docs.sixlabors.com), the README files on our repos and our xml code comments (as they get presented in visual studio).

**Comment by tocsoft** [comment]
Something I would like to clarify on this particular issue is we believe at no point have we been presented with an identified issue with the docs. i.e. a link pointing a a piece of our official documentation that is incorrect. What we were provided with was a code snippet from the developers own code that would not able to be compiled directly as it was missing core code (the `tree.Get()` stuff) which is why this ticket was deamed a question and as by our guidelines was directed over to gitter for more real time/direct help. (despite this we actually did answer the question here.)

I hope this helps to clarify why this ticket was handled in the way it was.

**Comment by dolkensp** [comment]
For reference @StevenGann, @merarischroeder - the documentation for the method in question is here:

https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Advanced.AdvancedImageExtensions.html

    public static Span<TPixel> GetPixelRowSpan<TPixel>(this Image<TPixel> source, int rowIndex)
    where TPixel : struct, IPixel<TPixel>

Visual Studio will generally suggest the required includes automatically these days too if you simply right click on the error, and view the recommended fixes.

**Comment by StevenGann** [comment]
@JimBobSquarePants @tocsoft @peter-dolkens 
Hey I just wanted to toss a final comment here.
I came across this issue while troubleshooting _exactly the same issue_ 4 years later and reading back over my comments here I feel terrible, but at least I hope I've grown a bit as a person since then.

Anyway, thanks for maintaining this project and trying to assist with my issue, even if I wasn't very appreciative at the time.

**Comment by antonfirsov** [comment]
> exactly the same issue 4 years later 

In case anyone would land on this page in the future, here are the docs for the 2.0+ pixel manipulation APIs: https://docs.sixlabors.com/articles/imagesharp/pixelbuffers.html
