### ISSUE TITLE
EXIF tag LensInfo = 0xA432 is treated as Rational but it is actually Rational[4]

### ISSUE THREAD

**Issue by neilebrown** [SixLabors/ImageSharp#1091]
When reading EXIF data ImageSharp tries to read the tag LensInfo = 0xA432 as a Rational but fails. The LensInfo is actually an array of Rational with size 4 according to 

https://exiftool.org/TagNames/EXIF.html

and 

https://www.exiv2.org/tags.html

and the image files I have.

To reproduce the issue:

1. In the method ExifReader.TryReadValue put a break point in the places where the method returns false. It the last case:

            if (!exifValue.TrySetValue(value))
            {
                return false;
            }

that fails since exifValue is expecting Rational but value is Rational[4].

2. Using 

var image= Image.Load("filename.jpg");

load the attached image.

![exif](https://user-images.githubusercontent.com/39619741/73035542-8a0ab800-3e9c-11ea-893e-4a95830676a4.jpg)

I am using the source code from today (24 January 2020) on a Windows 10 PC and targeting .Net Core 3.1.

The issue can be fixed by changing the value type return by ExifValues.CreateValue(ExifTagValue tag)

I am inexperienced using GitHub but can attempt to make a pull request if you agree that this is a bug.

**Comment by JimBobSquarePants** [comment]
Thanks for raising this, I've confirmed it in the specification - should be a simple fix. 

We should rename the property to LensSpecification to match the specification also.

**Comment by neilebrown** [comment]
Great, thank you.
