### ISSUE TITLE
GIF Repeatcount is lost when loading a gif

### ISSUE THREAD

**Issue by bds8510** [SixLabors/ImageSharp#1098]
**Prerequisites**
- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both DEBUG and RELEASE mode
- [x] I have searched open and closed issues to ensure it has not already been reported

**Description**
When loading a GIF which repeats all its frames only once (RepeatCount = 1), we noticed the RepeatCount in the GifMetaData is always set to 0 after loading the image via SixLabors.ImageSharp.Image.Load:
![image](https://user-images.githubusercontent.com/42264809/73360026-5d8edb80-42a2-11ea-8bf7-34b40436dccd.png)
In this case, a RepeatCount of 0 implies to repeat indefinitly.

This breaks the resized gif, as the resized gif will loop indefnitetly, while the input gif only looped once. Attached input gif to simulate this behaviour:

**Steps to Reproduce**
Load provided GIF via Image.Load
![input](https://user-images.githubusercontent.com/42264809/73360405-21a84600-42a3-11ea-8394-59339aeef89b.gif)

The code which loads the file:
![image](https://user-images.githubusercontent.com/42264809/73360323-f58cc500-42a2-11ea-8b5e-bc9e6f2ef649.png)

**System Configuration**
ImageSharp version: 1.0.0-beta0007
Other ImageSharp packages and versions: /
Environment (Operating system, version and so on): Win10 Pro, VS2019
.NET Framework version: 3.1.100
Additional information:

**Comment by JimBobSquarePants** [comment]
@bds8510 Can you please use the provided issue template.

**Comment by bds8510** [comment]
@JimBobSquarePants done

**Comment by JimBobSquarePants** [comment]
Thanks. We might have already fixed this in the nightlies but I'll have a look tomorrow.

**Comment by bds8510** [comment]
Sounds promising!
Thanks for the quick feedback.

**Comment by JimBobSquarePants** [comment]
Fixed in the latest nightlies.

**Comment by bds8510** [comment]
@JimBobSquarePants , ok, thank you for the feedback!

Will this fix be included in the next prerelease (1.0.0-beta0008)?
Also, when is the ETA of this prerelease?

**Comment by JimBobSquarePants** [comment]
There won't be a beta0008 release. The next release is RC1 which I have scheduled hopefully for the beginning of March. 

For now I recommend grabbing a nightly build from our MyGet feed.

Those releases are actually super stable (despite saying unstable in the name) and go through the same rigorous testing as the betas. They're much closer to the final API also.
