### ISSUE TITLE
DenseMatrix<T>.GetHashCode is incorrect

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#1116]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
`DenseMatrix<T>` equality + hash code is incorrect:
```C#
       public bool Equals(DenseMatrix<T> other) =>
            this.Columns == other.Columns
            && this.Rows == other.Rows
            && this.Span.SequenceEqual(other.Span);

        /// <inheritdoc/>
        public override int GetHashCode() => this.Data.GetHashCode();
```

For matrices having same content but different arrays `a.Equals(b) == true`, but `a.GetHashCode() != b.GetHashCode()`, which is a bug.

**Comment by JimBobSquarePants** [comment]
>For matrices having same content but different arrays

What do you mean by this. I don't understand.
