### ISSUE TITLE
Issu empty folder

### ISSUE THREAD

**Issue by Mrbo80** [SixLabors/ImageSharp#1123]
You should first discuss the feature on Gitter: https://gitter.im/ImageSharp/General

You should first discuss the feature on Gitter: https://gitter.im/ImageSharp/General

You should first discuss the feature on Gitter: https://gitter.im/ImageSharp/General

You should first discuss the feature on Gitter: https://gitter.im/ImageSharp/General

**Comment by Mrbo80** [comment]
Please help me

**Comment by Mrbo80** [comment]
Please

**Comment by dlemstra** [comment]
Please don't spam our issues. You can ask for help here: https://gitter.im/ImageSharp/General
