### ISSUE TITLE
Error CS0012 when I call the Image.Load function.

### ISSUE THREAD

**Issue by Jeremy0Pace** [SixLabors/ImageSharp#1135]
### Prerequisites

- [✔️ ] I have written a descriptive issue title
- [✔️ ] I have verified that I am running the latest version of ImageSharp
- [❌ ] I have verified if the problem exists in both `DEBUG` and `RELEASE` mode
- [ ✔️] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I am trying to load an image to use texture in my game engine, but when I compile my program, it says there are the following errors where I call the `Image.Load` function;
```
src\texture.cs(18,7): error CS0012: The type `System.IDisposable' is defined in an assembly that is not referenced. Consider adding a reference to assembly `netstandard, Version=2.0.0.0, Culture=neutral,
PublicKeyToken=cc7b13ffcd2ddd51'

src\SixLabors.ImageSharp.dll (Location of the symbol related to previous error)

src\texture.cs(18,7): error CS0012: The type `System.ValueType' is defined in an assembly that is not referenced. Consider adding a reference to assembly `netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

src\SixLabors.ImageSharp.dll (Location of the symbol related to previous error)

src\texture.cs(18,7): error CS0012: The type `System.IEquatable`1<TSelf>' is defined in an assembly that is not referenced. Consider adding a reference to assembly `netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

src\SixLabors.ImageSharp.dll (Location of the symbol related to previous error)

src\texture.cs(18,7): error CS0315: The type `SixLabors.ImageSharp.PixelFormats.Rgba32' cannot be used as type parameter `TPixel' in the generic type or method 

`SixLabors.ImageSharp.Image<TPixel>'. There
is no boxing conversion from `SixLabors.ImageSharp.PixelFormats.Rgba32' to `System.ValueType'
src\texture.cs(22,13): error CS0012: The type 

`System.Action`1<SixLabors.ImageSharp.Processing.IImageProcessingContext>' is defined in an assembly that is not referenced. Consider adding a reference to assembly `netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

src\SixLabors.ImageSharp.dll (Location of the symbol related to previous error)

src\texture.cs(25,35): error CS0012: The type `System.Span`1<TPixel>' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

src\SixLabors.ImageSharp.dll (Location of the symbol related to previous error)
```

### Steps to Reproduce

1.Simply use the example texture loading snippet on the [OpenTK Tutorials](https://opentk.net/learn/chapter1/4-textures.html#imagesharp)
```csharp
Image<Rgba32> image = Image.Load(path);

//ImageSharp loads from the top-left pixel, whereas OpenGL loads from the bottom-left, causing the texture to be flipped vertically.
//This will correct that, making the texture display properly.
image.Mutate(x => x.Flip(FlipMode.Vertical));

//Get an array of the pixels, in ImageSharp's internal format.
Rgba32[] tempPixels = image.GetPixelSpan().ToArray();

//Convert ImageSharp's format into a byte array, so we can use it with OpenGL.
List<byte> pixels = new List<byte>();

foreach (Rgba32 p in tempPixels)
{
    pixels.Add(p.R);
    pixels.Add(p.G);
    pixels.Add(p.B);
    pixels.Add(p.A);
}
```

2. Compile the project with the `mcs` command.
3. The errors will be right there.

### System Configuration

- ImageSharp version: `1.0.0-beta0007`
- Other ImageSharp packages and versions: none.
- Environment (Operating system, version and so on): 
Windows: `Windows 10 1809 17763.1039` 
Mono: `Mono JIT compiler version 6.8.0`
- .NET Framework version: .NET 4.7
- Additional information:

**Comment by antonfirsov** [comment]
@Jeremy0Pace that OpenTK sample code seems to be outdated. There were some small API changes in beta 7:
https://sixlabors.com/blog/beta-7/

**Comment by Jeremy0Pace** [comment]
> @Jeremy0Pace that OpenTK sample code seems to be outdated. There were some small API changes in beta 7:
> https://sixlabors.com/blog/beta-7/

What's the part that's outdated? I can't really find or think of anything that's different!

**Comment by JimBobSquarePants** [comment]
Shouldn’t this issue be raised on the OpenTK docs tracker? They should verifying everything works as expected if documenting a third party library.

**Comment by Jeremy0Pace** [comment]
That's true.

**Comment by Jeremy0Pace** [comment]
Well, I tried using one of the examples in the readme and it still shows the same errors when I compile it.

**Comment by antonfirsov** [comment]
@Jeremy0Pace check out the blog post. `Image.Load` no longer returns a generic type. I also think you might have some compilation errors from dependency issues not related to ImageSharp.

I suggest to create and build dummy project first. Doing something like `SixLabors.ImageSharp.Image img = null` in `Program.cs` and see if that builds.

**Comment by Jeremy0Pace** [comment]
Okay, I'll try that.

**Comment by Jeremy0Pace** [comment]
> @Jeremy0Pace check out the blog post. `Image.Load` no longer returns a generic type. I also think you might have some compilation errors from dependency issues not related to ImageSharp.
> 
> I suggest to create and build dummy project first. Doing something like `SixLabors.ImageSharp.Image img = null` in `Program.cs` and see if that builds.

Yeah, I  tried that, it still showed the same errors.

**Comment by antonfirsov** [comment]
@Jeremy0Pace it indicates that something is wrong with your project setup. Looks like you are using mono, I would google for mono-related build issues if I was you.

This clearly has nothing to do with ImageSharp:
> src\texture.cs(18,7): error CS0012: The type `System.IDisposable' is defined in an assembly that is not referenced.

**Comment by Jeremy0Pace** [comment]
Okay, thanks for the help I guess.
