### ISSUE TITLE
Image Resize results in shearing distortion

### ISSUE THREAD

**Issue by jimn-purecars** [SixLabors/ImageSharp#1149]
# Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When using the `Resize` extension method against the `IImageProcessingContext` during either a `Mutate` or `Clone` operation against an image, the resulting output is erroneously distorted. We have observed this issue with several images, one example is attached, see 'Actual output' below. 
The distortion has a shearing effect on the upper portion of the image, which also causes the upper right corner of the output image to expose the background color, shown in this example in hot pink. 

Input image:
![input](https://user-images.githubusercontent.com/47226834/77320827-a2a21d80-6ce7-11ea-9af9-eb71955e27db.jpg)

Expected output:
![expected](https://user-images.githubusercontent.com/47226834/77320831-a59d0e00-6ce7-11ea-871e-df901a0b90cb.png)

Actual output:
![actual](https://user-images.githubusercontent.com/47226834/77320835-a7ff6800-6ce7-11ea-9179-ffc1da84c800.png)

### Steps to Reproduce
The behavior can be reproduced with the following imagesharp code:
```
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;
using SixLabors.Primitives;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var image = Image.Load<Rgba32>("input.jpg");

            image.Mutate(c =>
            {
                c.Resize(
                    width: 300,
                    height: 165,
                    sampler: KnownResamplers.Bicubic,
                    sourceRectangle: new Rectangle(0, 0, 8688, 7260),
                    targetRectangle: new Rectangle(-212, -260, 658, 551),
                    compand: true);

                c.BackgroundColor(Color.HotPink);
            });

            image.Save("output.png");
        }
    }
}
```

The correct expected output can be created with the following `System.Drawing` code:
```
using System.Drawing;
using System.Drawing.Imaging;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var input = Bitmap.FromFile("input.jpg");

            var output = new Bitmap(300, 165, PixelFormat.Format24bppRgb);

            var graphics = Graphics.FromImage(output);

            graphics.DrawImage(
                image: input,
                destRect: new Rectangle(-212, -260, 658, 551),
                srcRect: new Rectangle(0, 0, 8688, 7260),
                srcUnit: GraphicsUnit.Pixel);

            output.Save("expected.png", ImageFormat.Png);
        }
    }
}
```

### System Configuration
This has been observed on Windows 10 x64 running full framework 4.6.2 or .NET Core 2.2, as well as Linux on .NET Core 2.2.

- ImageSharp version: 1.0.0-beta0007
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): Windows 10 x64, Linux
- .NET Framework version: .NET Framework 4.6.2, .NET Core 2.2
- Additional information:

**Comment by jimn-purecars** [comment]
Notably, this issue does not occur with 1.0.0-beta0005, the version we were using previously.

**Comment by JimBobSquarePants** [comment]
@jimn-purecars Have you tried the [latest version of ImageSharp - `1.0.0-unstable0961`](https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp)?

**Comment by JimBobSquarePants** [comment]
@jimn-purecars Looks like we've already fixed.it. 

![1149](https://user-images.githubusercontent.com/385879/77324339-82398980-6d0e-11ea-98d8-04e174068861.png)

Despite the name, the "unstable" builds are actually rock solid and I would recommend switching to them while we ready the RC1 release. 

Thanks for taking the time and filling in the issue template. Much appreciated!
