### ISSUE TITLE
wrong image width height in linux

### ISSUE THREAD

**Issue by godshades** [SixLabors/ImageSharp#1150]
### Description
Hi, my project running .net core 2.0 and lastest ImageSharp 4.7.0
I use ImageSharp to get width heigh of image
It's running fine in window pc, but when I publish to aws server it's alway return wrong size
I try publish many times but not work
Does someone have same problem ?
( I was used System.common dll from MS but aws can't install gdiplus so not work...)

### Steps to Reproduce
Code:

```
private string ProcessUrl(string url)
{
	var req = (HttpWebRequest)WebRequest.Create(url);
	var response = (HttpWebResponse)req.GetResponse();
	using (Stream stream = response.GetResponseStream())
	{
		var img = Image.Load(stream);
		string size = img.Width.ToString() + "x" + img.Height.ToString() ;
	}
	return size ;
}
```

Input URL: https://internal.codenet.fointl.com/product/f.o.online/V249070/V249070_sub01_2.jpg
When I running on visual studio for window it return: 750x750
But when I deploy Linux return: 1800x1800
Here is my publish profile:
![image](https://user-images.githubusercontent.com/12244851/77383226-f75f9a00-6db4-11ea-80ae-894925b14c11.png)

### System Configuration

- ImageSharp version: 1.0.0-beta0007
- Environment (Operating system, version and so on): Window 10 x64 and Amazon Linux AMI
- .NET Framework version: .net core 2.0

**Comment by JimBobSquarePants** [comment]
Hi @godshades 

Please use the issue template we provided when raising issues. The information you have provided to us is insufficient and incorrect and we cannot act upon it. For example, there is no such thing as ImageSharp 4.7.0

Please also provide basic, relevant additional information such as...

- The image used
- The expected dimensions 
- The returned dimensions 

Thanks

**Comment by godshades** [comment]
@JimBobSquarePants sorry, here is my image: https://internal.codenet.fointl.com/product/f.o.online/V249070/V249070_sub01_2.jpg

Right dimensions: 750x750
Linux return: 1800x1800

**Comment by antonfirsov** [comment]
@godshades thanks for the update! We are still missing important information needed for efficient investigation. Can you please fill the issue template? (The default content you see when opening a new issue.)

**Comment by godshades** [comment]
@antonfirsov hi, I have updated first comment

**Comment by antonfirsov** [comment]
@godshades what is ImageSharp version: 4.7.0? We have only beta's on [NuGet](https://www.nuget.org/packages/SixLabors.ImageSharp/1.0.0-beta0007) and nightly builds on MyGet. Can you check and what version are you actually using?

**Comment by godshades** [comment]
@antonfirsov sorry for wrong number. I'm using 1.0.0-beta0007 get from nuget

**Comment by JimBobSquarePants** [comment]
> When I running on visual studio for window it return: 750x750
> But when I deploy Linux return: 1800x1800

@godshades That image you provided is 1800x1800 pixels. I have loaded it in a Windows environment and it correctly reports the same value. 

I'm closing this as it appears there is no issue to fix.

**Comment by godshades** [comment]
@JimBobSquarePants sorry, i understand where is the problem
this link above only return image when access at ip X, and my server IP Y cannot access this
so it return 1800x1800 xD
