### ISSUE TITLE
Image.SaveAsPng doesn't fill Stream variable

### ISSUE THREAD

**Issue by echiabra** [SixLabors/ImageSharp#1159]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I've loaded this image https://cdn.wallpapersafari.com/64/71/psJRWl.jpg from my local filesystem and resized by using the Mutate() method, then I was trying to fill the System.IO.Stream local variable with the SaveAsPng() method, but it doesn't assign nothing after its execution.
This happens even if I avoid to "Mutate" the Image.

On the other hand, the Save() method saves the image perfectly fine on my local fs.

### Steps to Reproduce
```
[HttpGet]
[Route("Images/{size}/{imageid}")]
public IActionResult Images(string mediatype, string size, string imageid)
{
    string filePath = Path.Combine(_hostingEnvironment.ContentRootPath, "testingfiles", imageid);
    if (!System.IO.File.Exists(filePath))
        return NotFound();

    string[] desiredSize = size.ToLower().Split('x');

    using (Image desiredImg = Image.Load(filePath))
    {
        desiredImg.Mutate(img => img.Resize(int.Parse(desiredSize[0]), int.Parse(desiredSize[desiredSize.Length - 1])));

        Stream pngImage = Stream.Null;
        desiredImg.SaveAsPng(pngImage);
        desiredImg.Save("prova.jpg");

        return File(pngImage, "image/png");
    }
}
```
Immediate window after breakpoint says that 'pngImage' is null:
```
pngImage
{System.IO.Stream.NullStream}
    CanRead: true
    CanSeek: true
    CanTimeout: false
    CanWrite: true
    Length: 0
    Position: 0
    ReadTimeout: 'pngImage.ReadTimeout' threw an exception of type 'System.InvalidOperationException'
    WriteTimeout: 'pngImage.WriteTimeout' threw an exception of type 'System.InvalidOperationException'
```

I've tried both debug and release, as you've asked.

### System Configuration
Windows 10 Pro 1809 64bit
Microsoft Visual Studio Professional 2019 v16.3.9
ASP.NET Core 3.0
SixLabors.ImageSharp v1.0.0-beta0007

**Comment by brianpopow** [comment]
you are assigning null to the stream yourself.

here is a example howto use it:

```
using (var ms = new MemoryStream())
using (var image = Image.Load<Rgba32>(@"lena.png"))
{
    image.SaveAsPng(ms);
}
```

Those kind of questions can be asked in our gitter channel: https://gitter.im/ImageSharp/General

**Comment by JimBobSquarePants** [comment]
I really, really don’t recommend exposing ActionResults like this. You’re essentially creating a DDOS entry point. If you want to resize images in ASP.NET Core use our ImageSharp.Web middleware.

**Comment by ewhoambra** [comment]
@brianpopow my apologies. Then, shouldn't a NullReferenceException be thrown?

@JimBobSquarePants thanks for the kind advice.

**Comment by dlemstra** [comment]
I am doing the following inside Magick.NET:

```C#
internal static class Throw
{
    public static void IfNullOrEmpty(string paramName, Stream value)
    {
        IfNull(paramName, value);

        if (value.CanSeek)
        {
            if (value.Length == 0)
                throw new ArgumentException("Value cannot be empty.", paramName);

            if (value.Position == value.Length)
                throw new ArgumentException("Stream position is at the end of the stream. Make sure to reset the stream position to 0.", paramName);
        }
    }
}
```

Maybe we could add something similar here to improve the error reporting?

**Comment by JimBobSquarePants** [comment]
I actually think the code is running as expected. `Stream.Null` is designed to return on write.

**Comment by antonfirsov** [comment]
> Then, shouldn't a NullReferenceException be thrown?

@ewhoambra `Stream.Null != null`. It's a [special stream](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.null), there are no `null` references.
