### ISSUE TITLE
Failed NuGet installation: Unable to resolve dependency 'SixLabors.ImageSharp'.

### ISSUE THREAD

**Issue by finnagrab** [SixLabors/ImageSharp#1162]
### Description
I'm trying to install this package, but Visual Studio 2019 gives the error "Unable to resolve dependency 'SixLabors.ImageSharp'."

### Steps to Reproduce
1. Open Visual Studio 2019
2. Create new C# console application
3. Install this package through the built-in NuGet package manager

- ImageSharp version: 4.7.0
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): Intel Processor, Windows 10, Visual Studio 2019, .NET Framework v4.7.2, C# Project
- .NET Framework version: v4.7.2

**Comment by JimBobSquarePants** [comment]
There is no such thing as ImageSharp 4.7.0

**Comment by saucecontrol** [comment]
Ha, probably Veldrid.ImageSharp, which is the first match when you search in VS without the prerelease checkbox checked

![image](https://user-images.githubusercontent.com/7929102/77948268-02fe0580-727a-11ea-9850-03a2f24c030f.png)

**Comment by JimBobSquarePants** [comment]
@saucecontrol Yeah that make sense, thanks!

@finnagrab Can you confirm? If so you need to get the SixLabors.ImageSharp library. The Veldrid one is a plugin for another system.

**Comment by JimBobSquarePants** [comment]
Closing through lack of activity.
