### ISSUE TITLE
System.ArgumentOutOfRangeException from Image Constructor (large image)

### ISSUE THREAD

**Issue by jogibear9988** [SixLabors/ImageSharp#1163]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I trie to create a really huge image:

     using (var outputImage = new SixLabors.ImageSharp.Image<Rgba32>(80000, 40000)

it results in this Exception:

    System.ArgumentOutOfRangeException: 'Value -1094967296 must be greater than or equal to 0. Parametername: length'

**Comment by JimBobSquarePants** [comment]
@jogibear9988 This should be fixed in the nightly builds on MyGet. Please install the package from there and let us know how you get on.

**Comment by jogibear9988** [comment]
This one is solved, I now get another exception...
