### ISSUE TITLE
Images 2 pixels wide can not be resized

### ISSUE THREAD

**Issue by AlexDenton** [SixLabors/ImageSharp#1195]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When trying to resize an image that's 2px wide or less a `ArgumentOutOfRangeException` is thrown with the message: `Parameter "width" (System.Int32) must be greater than 0, was 0`.

This happens at 1 pixels and 2 pixels, but not 3 pixels. Practically speaking this probably won't matter in most scenarios but I thought I'd let you guys know.

### Steps to Reproduce
This code snippet will repro:

```
var memoryStream = new MemoryStream(File.ReadAllBytes("player-min-px.jpg"));
using (var image = Image.Load(memoryStream))
{
    var size = new Size(50, 50);
    image.Mutate(x => x
        .Resize(
            new ResizeOptions
            {
                Size = size,
                Mode = ResizeMode.Max
            }));
}
```

### System Configuration
- ImageSharp version: 1.0.0-rc0001
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: Dotnet Core 2.2

**Comment by JimBobSquarePants** [comment]
Hi @AlexDenton I'm sorry but I don't quite understand. Are you saying that your input image is 2px wide? What is the height?

**Comment by AlexDenton** [comment]
If the input image has a dimension of either width or height that is less than 2 pixels you will get this exception.

**Comment by JimBobSquarePants** [comment]
Perfect. Thanks for the detail, should be a simple enough fix.
