### ISSUE TITLE
SixLabors.ImageSharp Final Stable Versione When?

### ISSUE THREAD

**Issue by next100years** [SixLabors/ImageSharp#1199]
Hi
Now the SixLabors.ImageSharp package is RC1, when the final stable version?

thanks

**Comment by JimBobSquarePants** [comment]
Some time within the NEXT 100 YEARS..... (I'm sorry, I couldn't help myself)

We've not set a concrete date for the for v1.0.0 final. We'd like to ship it hopefully within the next 3 months but it depends on how much time (and funding) is available.

That said the RC1 release has full go-live support so you can use it safely in a production environment with our blessing and support. 

I hope that is all useful information.

P.S
I would ask that in the future, please don't use the issue tracker for questions like this. We have a [Gitter Channel](https://gitter.im/ImageSharp/General) dedicated for general questions and answers.
