### ISSUE TITLE
Benchmark Impact of Multithreading in ImageProcessors

### ISSUE THREAD

**Issue by Toxantron** [SixLabors/ImageSharp#120]
The ImageProcessors for Resize etc. currently have multiple usages of `Parallel.For(..)` which might have undesirable side-effects.

We need benchmarks to compare different degrees of parallalism and alternative solutions to make a balanced decision between number of occupied cores and processing time. Based on this decision the different processors can then be refactored.

**Comment by antonfirsov** [comment]
Parallelism has been made [configurable](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Configuration.cs#L62) for all algorithms. We have integrated parameters controlling the level of parallelism into our [most important benchmarks](https://github.com/SixLabors/ImageSharp/blob/master/tests/ImageSharp.Benchmarks/Samplers/Resize.cs#L73).

The effects of [false sharing](https://www.drdobbs.com/parallel/eliminate-false-sharing/217500206) are minimized by [ParallelHelper](https://github.com/SixLabors/ImageSharp/blob/92f3adac9be06ee323ab9c5580f33476bbd35007/src/ImageSharp/Processing/Processors/Filters/FilterProcessor%7BTPixel%7D.cs#L44).

**In services under high load**, it's recommended to set `MaxDegreeOfParallelism = 1`, to maximize throughput. In desktop/mobile applications or in services with sparse image processing requests it's worth to keep the parallelism.
