### ISSUE TITLE
SixLabors.ImageSharp.UnknownImageFormatException: Width or height cannot be 0

### ISSUE THREAD

**Issue by americanslon** [SixLabors/ImageSharp#1205]
### Description
I am getting the above error on ` using (var image = Image.Load(inStream))` 

### Steps to Reproduce
```
async Task Upload(IMatFileUploadEntry file)
    {
        if (file != null)
        {
            byte[] bytes;
            using (var inStream = new MemoryStream())
            {
                await file.WriteToStreamAsync(inStream);

                using (var outStream = new MemoryStream())
                using (var image = Image.Load(inStream))
                {
                    image.Mutate(x => x.Resize(new ResizeOptions
                    {
                        Size = new SixLabors.ImageSharp.Size(Settings.LOGO_LENGTH, Settings.LOGO_HEIGHT),
                        Mode = ResizeMode.Pad
                    }).BackgroundColor(new Color(new Rgba32(255, 255, 255, 1))));

                    image.SaveAsPng(outStream);

                    bytes = outStream.ToArray();
                    Item.Icon = Convert.ToBase64String(bytes);
                    Console.WriteLine(Item.Icon);
                }
            }
        }
```

### System Configuration
Blazor WASM.
The image is coming from https://www.matblazor.com/FileUpload. 

- ImageSharp version: **1.0.0-beta0008**
- Environment (Operating system, version and so on): **Win 10**
- .NET Framework version: **netstandard 2.1**

**Comment by JimBobSquarePants** [comment]
Hi @americanslon 

Just checking. That's **ImageSharp.Drawing 1.0.0-beta0008** yeah which is referencing the **ImageSharp 1.0.0-rc0001** release?

Is there a way to access the underlying data from the `IMatFileUploadEntry` to check the contents and copy it rather than using the in built method. The error suggests to me we're not receiving all the data.

**Comment by americanslon** [comment]
Yeah that's SixLabors.ImageSharp.Drawing 1.0.0-beta0008
 
I am not really sure to be honest. This stream/image processing stuff not something I deal with usually so I am just trying to cobble up some basic resizing functionality from examples. I know that the uploader generally works fine as I have been using it to capture and turn the file into base64 string for a some time now with no problems.

Here is the link to the uploader code (not mine) https://github.com/SamProf/MatBlazor/tree/master/src/MatBlazor/Components/MatFileUpload

How would we go about checking that the contents has what imagesharp needs?

**Comment by JimBobSquarePants** [comment]
Are you able to share the image? if not does it work in a non asynchronous environment?

**Comment by americanslon** [comment]
Just a random screenshot form PC.

![2020-05-20](https://user-images.githubusercontent.com/10237524/82705152-1cea1200-9c45-11ea-8b99-f896c37f4acc.png)

**Comment by JimBobSquarePants** [comment]
This is definitely an issue with the stream contents not being completely flushed before we attempt to load it. I was able to load the given image without issue. 

I suggest you raise an issue in that repository to track how streams are buffered/written.

**Comment by JimBobSquarePants** [comment]
@americanslon We've just added an asynchronous API to our development builds. Please check them out (in about 12 minutes once they finish building). The link to the MyGet feed is in our readme. 

This may make the problem go away.

**Comment by JimBobSquarePants** [comment]
@americanslon Try the Async API from this build please.

https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp/1.0.0-unstable0052

**Comment by americanslon** [comment]
I added to `https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp/1.0.0-unstable0052` to NuGet package sources but when I go into NuGet screen to update the package the latest version is the same as in regular NuGet package source 1.0.0 - beta0009

How do I import the unstable package?

**Comment by JimBobSquarePants** [comment]
Why are you updating? Use the source versions as specified.

**Comment by americanslon** [comment]
What do I do with that source?
Latest version showing up in nuget is beta009

**Comment by JimBobSquarePants** [comment]
It’s MyGet not NuGet. You’re adding a specific ImageSharp version NOT ImageSharp.Drawing

**Comment by americanslon** [comment]
Yes I noticed is MyGet. I don't know what that is. Googling suggested that the way you add MyGet packages in VS is adding the myge url  you provided as a new package source.

I am not sure what you are referring to as SDK style package. The only thing I do is import stuff with nuget. I don't know how to import the specific version, if it's now showing up in package manager and the unstable version is not showing up.

The only thing in my csproj that is related to SixLabors is `<PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta0009" />`

**Comment by americanslon** [comment]
FYI is just run `Install-Package SixLabors.ImageSharp -Version 1.0.0-unstable0052 -Source https://www.myget.org/F/sixlabors/api/v3/index.json`

I get a fail and 

`The 'Source' parameter is not respected for the transitive package management based project(s) Web. The enabled sources in your NuGet configuration will be used. `

**Comment by JimBobSquarePants** [comment]
> Yes I noticed is MyGet

> Latest version showing up in nuget is beta009

Then why say NuGet? They are two entirely different package sources.

SDK style projects/packages are the new csproj format used by .NET Core. https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#sdk-attribute

They use the csproj file to manage packages rather than the old `packages.config` file, since we have established that you have the reference in the file we can safely say that you are using the new format.

>The 'Source' parameter is not respected for the transitive package management based project(s) Web. The enabled sources in your NuGet configuration will be used.

This means you don't have the feed in your global package sources. 

> I added to https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp/1.0.0-unstable0052 to NuGet package sources

That's the direct link to the package details, not the package source. 

So... Add the correct url to your package sources. 
```
https://www.myget.org/F/sixlabors/api/v3/index.json
```
Ideally, if anyone else is potentially working on the codebase, you should add it to a [`nuget.config`](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#example-config-file) file alongside the default sources and save that file to your solution root. (You will need to restart Visual Studio to get it to recognize a new config file).

Then, the quickest way to add the package is to update your csproj file directly with the new line directly referencing the package. 

``` xml
<PackageReference Include="SixLabors.ImageSharp" Version="1.0.0-unstable0052" />
<PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta0009" />
```
Does all that make sense?

**Comment by americanslon** [comment]
Yep, thanks!
All  I needed is a bit less attitude and a bit more of this `https://www.myget.org/F/sixlabors/api/v3/index.json`. The original link you sent was to the package itself just like you are saying. That threw me off. You have to remember that those of us that don't write packages for public consumption don't know intricacies of all that off the top of our heads. All I care about for my project manager needs is that the versions, that work, shows up in NuGet in VS. I didn't even know you could have different sources in NuGet until this morning.

In any case with
`<PackageReference Include="SixLabors.ImageSharp" Version="1.0.0-unstable0052" />
<PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta0009" />`

and the same code snippet from the original comment I still get an error but a different one.
`Error: SixLabors.ImageSharp.UnknownImageFormatException: Image cannot be loaded`

Originally I thought this may be progress, but after googling this error and reading some of your comments for people with the same error I am not so sure anymore. Seems like it may still be `await file.WriteToStreamAsync(inStream);` that's crapping out and that is outside of my control, but obviously you'll know better.

I did open an issue with MatBlazor folks about this per your suggestion couple of weeks ago to no avail yet.

**Comment by JimBobSquarePants** [comment]
Ah... I think we've got our wires crossed here. You should now be able to use our Asynchronous API to load the image. 

```c#
using (var image = await Image.LoadAsync(inStream))
```

**Comment by americanslon** [comment]
Same thing unfortunately :(

`Error: SixLabors.ImageSharp.UnknownImageFormatException: Image cannot be loaded`

**Comment by JimBobSquarePants** [comment]
Hmmm... try resets the position of `inStream` to 0 before loading

**Comment by americanslon** [comment]
That worked!

Any general idea when this functionality is making it's way to the general/beta branch?

**Comment by JimBobSquarePants** [comment]
There you go!

https://www.nuget.org/packages/SixLabors.ImageSharp/1.0.0-rc0003
