### ISSUE TITLE
UnknownImageFormatException when trying to load certain JPEG images

### ISSUE THREAD

**Issue by kroymann** [SixLabors/ImageSharp#1207]
### Description
While reviewing logs from my company's image processing server, I recently discovered a handful of JPEG images that are failing with the following exception:

```
UnknownImageFormatException: Image cannot be loaded. Available decoders:
- BMP : BmpDecoder
- PNG : PngDecoder
- JPEG : JpegDecoder
- TGA : TgaDecoder
- GIF : GifDecoder

SixLabors.ImageSharp.Image.Load<TPixel>(Configuration configuration, Stream stream, out IImageFormat format)
SixLabors.ImageSharp.Web.FormattedImage.Load(Configuration configuration, Stream source)
SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.ProcessRequestAsync(HttpContext context, bool processRequest, IImageResolver sourceImageResolver, ImageContext imageContext, IDictionary<string, string> commands)
SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
```

All of the images processed by our system are generated by the same encoder (the JPEG encoder built into the Unity game engine), so I'm not sure what is special about these images.  A sample of three such images can be found [here](https://drive.google.com/drive/folders/11BwYs3_6dqEIw3AOOmn2fRhYjf2dj2iG?usp=sharing).

### Steps to Reproduce
Simply try to load any of the any of [these images](https://drive.google.com/drive/folders/11BwYs3_6dqEIw3AOOmn2fRhYjf2dj2iG?usp=sharing).

### System Configuration
- ImageSharp version: Reproduced with both beta0007 and rc0001
- Other ImageSharp packages and versions: ImageSharp.Web (beta0009 and rc0001)
- Environment (Operating system, version and so on): Windows 10, as well as in a Windows based Azure App Service
- .NET Framework version: .Net Core 3.1

**Comment by kroymann** [comment]
More info on some of these files:
- Trying to open them in MS Paint, paint.net, Image Magick or the Photos app in Windows all fails.
- Irfanview is able to open them just fine (according to one of my co-workers who is testing this remotely)

**Comment by JimBobSquarePants** [comment]
They're not valid jpegs. There's two bytes of data before the `SOI` marker `FF` `D8`

![image](https://user-images.githubusercontent.com/385879/82960393-46db6580-9fb2-11ea-9375-f078918ddbda.png)

If you remove them then the images decode just fine. 
![68279749d40046e582fd97e382108fe6](https://user-images.githubusercontent.com/385879/82960632-ea2c7a80-9fb2-11ea-8cde-16644f83427d.jpg)

If those two bytes are consistent across all output we could add another recognized header to our decoder so it could handle them. Might want to raise an issue with Unity though.

**Comment by kroymann** [comment]
Thanks for the quick response!  Given that we've had tens of millions of images successfully processed through this pipeline, I don't think you should bother adding anything to the ImageSharp codebase to handle this particular form of corruption.

In looking at those two bytes that shouldn't be there, I just realized that they are the ASCII encoding of CR-LF.  And given that these images are uploaded to our system via a multi-part form HTTP POST, I wouldn't be surprised if there is some edge-case bug in our HTTP library that is adding an extra CR-LF into the HTTP body.  I'll take a look at the HTTP library code that our game client uses and potentially add some special case handling on our upload server to detect and strip that prefix from uploaded files.

**Comment by JimBobSquarePants** [comment]
>I wouldn't be surprised if there is some edge-case bug in our HTTP library that is adding an extra CR-LF into the HTTP body. 

I think you might have hit the nail on the head there.
