### ISSUE TITLE
Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.

### ISSUE THREAD

**Issue by YuanfanHu** [SixLabors/ImageSharp#1209]
Hello I was using 4.7.1 framework but I receive {"ErrorDetails":"Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"}
I am pretty sure that I have updated the version to 4.1.4.0. Do you know if the problem is causing by 4.7.1 framework?
thanks

**Comment by JimBobSquarePants** [comment]
Please use the template for future issues.

**Comment by YuanfanHu** [comment]
I am using version rc-0001.Indeed I checked in appconfig with following version.But I got error while deploying           
<dependentAssembly>
                <assemblyIdentity name="System.Numerics.Vectors" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
                <bindingRedirect oldVersion="0.0.0.0-4.1.4.0" newVersion="4.1.4.0" /></dependentAssembly>
