### ISSUE TITLE
System.NullReferenceException when attempt to Mutate.Draw on a new created Image<L8>

### ISSUE THREAD

**Issue by sn4k3** [SixLabors/ImageSharp#1224]
### Description

**What i'm trying to do:** Resize white pixels but keep original image Width & Height

Error: newImage=error CS0103: The name 'newImage' does not exist in the current context

![image](https://user-images.githubusercontent.com/113281/84296971-bc177080-ab44-11ea-9e95-05237de00968.png)

void Resize() is called under a Task
this[layerIndex].Image; // Creates a new Image<L8> that loads compressed bytes in
Parallel Loop is executed once, every image instance are new objects created inside the loop (Not shared with other iterations)
Only line "newImage.Mutate(o => o.DrawImage(image, location, 1f));" can trigger the error, Resize operation always pass.

Collection is from 500 to 1000 images but i also tried with just one, same behaviour
This error don't always happens, if i keep redoing same operation sometimes it finish ok without error, others dont.

If i turn **Parallel for** into a normal **for loop** problem seens to never happen but of course way slower than using parallel which is what make me use Parallel instead.

### System Configuration

- ImageSharp version: 1.0.0-rc0002
- Environment (Operating system, version and so on): Windows 10 v1909
- .NET Framework version: .NET Standard 2.0 library, method called from .NET Framework 4.8 WinForm

**Comment by JimBobSquarePants** [comment]
I think this might be related to #1230 @sn4k3 if you can provide a stack trace that would be really useful.

**Comment by sn4k3** [comment]
System.NullReferenceException
  HResult=0x80004003
  Message=A referência de objecto não foi definida como uma instância de um objecto.
  Source=mscorlib
  StackTrace:
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at SixLabors.ImageSharp.GraphicOptionsDefaultsExtensions.GetGraphicsOptions(Configuration configuration)
   at SixLabors.ImageSharp.GraphicOptionsDefaultsExtensions.GetGraphicsOptions(IImageProcessingContext context)
   at SixLabors.ImageSharp.Processing.DrawImageExtensions.DrawImage(IImageProcessingContext source, Image image, Point location, Single opacity)
   at UVtools.Parser.FileFormat.<>c__DisplayClass124_1.<Resize>b__2(IImageProcessingContext o) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.Parser\FileFormat.cs:line 687

**Comment by JimBobSquarePants** [comment]
@sn4k3 Perfect. Yep, definitely the same issue. I've got #1234 waiting for review to fix this.
