### ISSUE TITLE
System.MissingMethodException: Method not found: 'System.Numerics.Vector4 SixLabors.ImageSharp.PixelFormats.Bgra32.ToVector4()'

### ISSUE THREAD

**Issue by Ziriax** [SixLabors/ImageSharp#1237]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I'm using the latest release candidate `1.0.0-rc0002`.

I have a .NET Standard 2.0 library that internally uses ImageSharp, and a .NET Framework 4.8 and unit test project (mstest) that references that library. 

The tests fail with:

`System.MissingMethodException: Method not found: 'System.Numerics.Vector4 SixLabors.ImageSharp.PixelFormats.Bgra32.ToVector4()`

Note that a .NET Core 3.1 unit test project with the same code runs fine.

### Steps to Reproduce

1) Create a .NET Standard 2.0 library
2) Add the following code to `Class1`:
```
public static void Buggy() =>  new Bgra32(255, 255, 255, 255).ToVector4();
```
3) Create a .NET Framework 4.8 unit test project (mstest)
4) Reference the library, and call `Class1.Buggy()`
5) Run the unit test project

### System Configuration

- ImageSharp version:  `1.0.0-rc0002` 
- Other ImageSharp packages and versions: none
- Environment (Operating system, version and so on): Windows 10 x64 2004
- .NET Framework version: 4.8
- Additional information: Creating a .NET FX 4.8 console app that calls the same code results in `Could not load file or assembly 'SixLabors.ImageSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13' or one of its dependencies. The system cannot find the file specified.`. Adding the package `System.Numerics.Vectors` to the app fixed it, but doesn't seem to work for the unit test project.

**Comment by JimBobSquarePants** [comment]
Hi @Ziriax 

The issue you are seeing is not actually exclusive to ImageSharp. It happens with certain assemblies when reference by NET Framework applications.

There's a fantastic writeup here describing the problem and workarounds. 

https://nickcraver.com/blog/2020/02/11/binding-redirects/#the-fix-if-youre-using-net-framework

**Comment by peymannj** [comment]
These are the packages that we use:
```
    <PackageReference Include="SixLabors.ImageSharp" Version="2.0.0" />
    <PackageReference Include="ZXing.Net" Version="0.16.8" />
    <PackageReference Include="ZXing.Net.Bindings.ImageSharp" Version="0.16.12" />
```

We have almost similar issue:

System.MissingMethodException: Method not found: 'System.Span`1<SixLabors.ImageSharp.PixelFormats.Argb32> SixLabors.ImageSharp.Image`1.GetPixelRowSpan(Int32)'.
at ZXing.ImageSharp.ImageSharpLuminanceSource`1..ctor(Image`1 bitmap)

**Comment by tocsoft** [comment]
@peymannj that's a different issue, that will be related to a breaking API change between v1 and v2 of ImageSharp and `ZXing.Net.Bindings.ImageSharp` looks like is not compatible with the v2 version... looks like you want to reference `ZXing.Net.Bindings.ImageSharp.V2` instead.

**Comment by peymannj** [comment]
@tocsoft  Thanks a lot! I wasn't aware of new library `ZXing.Net.Bindings.ImageSharp.V`
The problem was solved!
