### ISSUE TITLE
The pricing page is broken

### ISSUE THREAD

**Issue by provegard** [SixLabors/ImageSharp#1246]
I just went there to see the commercial licensing options, and got:

> Cannot bind source type SixLabors.Logic.Models.RenderModels.RenderCart to model type SixLabors.Logic.Models.RenderModels.RenderPage`1[[SixLabors.Logic.Models.Pages.PublishedPage, SixLabors.Logic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].

![image](https://user-images.githubusercontent.com/795010/85505467-ae56f600-b5ee-11ea-9300-eb740afa7f5c.png)

**Comment by JimBobSquarePants** [comment]
Thanks @provegard 

Azure had a hiccup. All fixed now.
