### ISSUE TITLE
Exception while loading PNG image from FileStream

### ISSUE THREAD

**Issue by i-to** [SixLabors/ImageSharp#1254]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

The following exception is thrown while trying to read the attached image from file stream: `SixLabors.ImageSharp.InvalidImageContentException: 'PNG Image does not contain a data chunk'`.

### Steps to Reproduce

Place the [attached image file](https://user-images.githubusercontent.com/8507472/86499025-147b1000-bd89-11ea-8733-00bd83ac9f98.png) in the working directory and run the following program:

``` C#
public static void Main()
{
    var name = "StanfordDragon.png";
    using var stream = new FileStream(name, FileMode.Open);
    var image = Image.Load<Rgba32>(stream, new PngDecoder());
    Console.WriteLine($"Loaded image size: {image.Width}x{image.Height}.");
}
```

### System Configuration

- ImageSharp version: 1.0.0-rc0003
- Other ImageSharp packages and versions: --
- Environment (Operating system, version and so on): Windows 7
- .NET Framework version: Core 3.1, Framework 4.6
- Additional information: --

**Comment by JimBobSquarePants** [comment]
Hi @i-to 

It's not a png file, its a bmp and you're trying to load it with the wrong decoder. 

You don't need to specify the decoder when loading a file, ImageSharp will automatically detect the correct decoder to use.

![image](https://user-images.githubusercontent.com/385879/86500322-2b6d3280-bd88-11ea-9c56-0fb8ad8a9280.png)

**Comment by i-to** [comment]
Thanks for clarification.
