### ISSUE TITLE
'IImageProcessingContext' does not contain a definition for 'ApplyScalingWaterMark'

### ISSUE THREAD

**Issue by SibeeshVenu** [SixLabors/ImageSharp#1281]
### Description
I am running the latest version and I am getting the error as preceding.

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS1061	'IImageProcessingContext' does not contain a definition for 'ApplyScalingWaterMark' and no accessible extension method 'ApplyScalingWaterMark' accepting a first argument of type 'IImageProcessingContext' could be found (are you missing a using directive or an assembly reference?)	GitHubFuncs	C:\Sibeesh\Github\GitHubFuncs\GetLatestPosts.cs	39	Active

When I run the code below.
```
using(var img = Image.Load("canvas.jpg")) {
    Font font = SystemFonts.CreateFont("Arial", 10);
    using
    var img2 = img.Clone(ctx => ctx.ApplyScalingWaterMark(font, feedItem.Summary.Text, Color.HotPink, 5, true));
    img2.Save("images/wrapped.png");
}
```

Already added the using statements.

```
using SixLabors.Fonts;
using SixLabors.ImageSharp.Drawing;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
```
What am I missing here? Is this an issue with latest version?

**Comment by JimBobSquarePants** [comment]
There’s no such method. Where did you get the name from?

**Comment by dlemstra** [comment]
Seems to be a custom extension method in this issue: #484?

**Comment by JimBobSquarePants** [comment]
Thanks @dlemstra It'll require updating to `IImageProcessingContext` instead of IImageProcessingContext<TPixel> then. 

Not a bug though @SibeeshVenu , this should have been added to the Help section of our Discussions forum. I'll transfer it now.
