### ISSUE TITLE
Add Abgr32 pixel type

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#1345]
Follow up on https://github.com/SixLabors/ImageSharp/discussions/1344#discussioncomment-63349

We have: `Rgba32`, `Argb32`, `Bgra32`
`Abgr32` looks like a missing piece. Can be optimized using [existing patterns](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/PixelFormats/PixelImplementations/Generated/_Common.ttinclude#L20).

**Comment by ynse01** [comment]
Now that #1886 is merged into master, we can close this issue, right?

**Comment by JimBobSquarePants** [comment]
Yep! Thanks!
