### ISSUE TITLE
File is in use after calling Image.SaveAsJpeg()

### ISSUE THREAD

**Issue by SoftCircuits** [SixLabors/ImageSharp#1357]
### Description

I'm calling `Image.SaveAsJpeg()`, and then I try to load the file right after that (using `System.Drawing.Image.FromFile()`). When I do, I get an exception.

> System.IO.IOException: The process cannot access the file 'D:\Users\Jwood\Desktop\Image.jpg' because it is being used by another process.

Does the `Image.SaveAsJpeg()` not immediately release the file or something?

### System Configuration
- ImageSharp version: Just downloaded it 15 minutes ago.
- Other ImageSharp packages and versions: None
- Environment (Operating system, version and so on): Windows 10, WinForms app.
- .NET Framework version: 3.1

**Comment by FM1973** [comment]
I got the same problem using .net in an asp.net mvc application.
I´m generating thumbnails from an image.

@SoftCircuits: you closed the issue. How did you solve the problem?

**System Configuration**

- ImageSharp version: Just downloaded it 15 minutes ago.
- Other ImageSharp packages and versions: None
- Environment (Operating system, version and so on): Windows 10, Web-App.
- .NET Framework version: 5

**Comment by FM1973** [comment]
Sorry!
Never mind. I forgot a using statement.
