### ISSUE TITLE
Gifs with frames with transparent backgrounds have a ghosting problem

### ISSUE THREAD

**Issue by zedseven** [SixLabors/ImageSharp#1369]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
As the title says. If a frame of a gif has a transparent background, the frame from before will remain visible behind the current one. As far as I have been able to tell, there is no way to adjust or fix this behaviour. If there is, I apologize for creating an issue about it.

### Steps to Reproduce
Make a gif out of a few frames with changing transparent regions, such as the following:
![frame0](https://user-images.githubusercontent.com/25164338/94889170-c8646800-046a-11eb-8cee-10e6ad1fb245.png)
![frame1](https://user-images.githubusercontent.com/25164338/94889176-cbf7ef00-046a-11eb-93f0-878c3ac703ed.png)
![frame2](https://user-images.githubusercontent.com/25164338/94889179-cdc1b280-046a-11eb-84f6-d04bd8210b51.png)
![frame3](https://user-images.githubusercontent.com/25164338/94889181-cf8b7600-046a-11eb-817d-cdae982e2920.png)
![frame4](https://user-images.githubusercontent.com/25164338/94889183-d0bca300-046a-11eb-9b0e-bfa4d2ed0621.png)

And you will get a gif that looks like the following:
![icon](https://user-images.githubusercontent.com/25164338/94889199-dc0fce80-046a-11eb-81d3-5d0875e85995.gif)

(image frames courtesy of 'Go Fetch! 2's icon as an example)

### Expected Behaviour
Each frame clears the pixel data showing in transparent regions that is from the previous frame.

### System Configuration
- ImageSharp version: v1.0.1
- Other ImageSharp packages and versions: None
- Environment: Windows 10 v10.0.19041 Build 19041
- .NET Framework version: .NET Core 3.1

**Comment by JimBobSquarePants** [comment]
You haven't set the correct [`GifDisposalMethod`](https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Formats.Gif.GifDisposalMethod.html). It's likely that you need `GifDisposalMethod.RestoreToBackground`

**Comment by zedseven** [comment]
Thank you. Apologies for opening the issue.

**Comment by JimBobSquarePants** [comment]
No problem. Some of this stuff requires some knowledge of the Gif specification. I'll try to get some examples documented.
