### ISSUE TITLE
throw UnknownImageFormatException when Stream position not 0.

### ISSUE THREAD

**Issue by git-Charlie** [SixLabors/ImageSharp#1382]
### Prerequisites

- [ x] I have written a descriptive issue title
- [ x] I have verified that I am running the latest version of ImageSharp
- [ x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

throw UnknownImageFormatException when Stream position not 0.

```
var stream= Request.Files[0].OpenReadStream();
var image1 =Image.Load(fileStream);
// here 
var image2 =Image.Load(fileStream);
 ```

### System Configuration

- ImageSharp version:
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by tocsoft** [comment]
this is expected behaviour and by design... ImageSharp never assumes anything around streams you provide... we will read the stream from the position you pass it in and will not try resetting the position it once we have read it once as we can't assume we would be allowed... and we even can't if the stream is not seekable (unbuffered network streams for example).

**Comment by antonfirsov** [comment]
Actually, we have a feature for this:
[`Configuration`'s `ReadOrigin`](https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Configuration.html#SixLabors_ImageSharp_Configuration_ReadOrigin) has to be set to `ReadOrigin.Begin`.

Although I'm not sure if this is something we'd recommend, or we just overdid this thing. @JimBobSquarePants ?

**Comment by JimBobSquarePants** [comment]
It's left up to the user. Realistically no-one should ever expect us to make assumptions about an input stream.
