### ISSUE TITLE
Extend 32bit test coverage

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#1386]
A follow up on https://github.com/SixLabors/ImageSharp/pull/1378#discussion_r505056731.

Currently 32 bit test execution is only done for .NET Framework, with `dotnet xunit` which is an obsolete tool today, we need to adapt `dotnet test`, and add 32 bit CI targets for both `net5.0` and `netcoreapp3.1`. Opening an issue to remember and track this debt.

See:
https://twitter.com/tannergooding/status/1316755685938393089

**Comment by JimBobSquarePants** [comment]
I've established that we can already use dotnet test on our Windows CI environments to run with 32bit coverage without xunit.

https://github.com/JimBobSquarePants/PlatformBuildTests/runs/1259919494

Doesn't work on Ubuntu.

**Comment by antonfirsov** [comment]
Windows-only coverage is already much better, than no coverage :)

**Comment by JimBobSquarePants** [comment]
I think we can close this now. We don't do any 32bit test runs

**Comment by antonfirsov** [comment]
We don't do, but IMO we should. 32bit is still relevant and memory + runtime behavior is different there. Runtime deviations between 32bit and 64bit are less common these days, so no need to replicate all the configurations, but having at least one 32bit CI leg would be nice.
