### ISSUE TITLE
Improve ResizeProcessor performance

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#139]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
This issue has been opened to track and discuss perf improvements that could be made to ResizeProcessor:
- [x] Use `PinnedBuffer<Vector4>` for `firstPassPixels` and utilize bulk conversion
- [x] Apply microoptimizations to `ResamplingWeightedProcessor<TColor>.Weights` to make it more cache friendly

~Investigate possibilities to reduce the size of resampler windows without loss of quality.~ 
- [ ] Operate on a transposed variant of [firstPassPixels](https://github.com/JimBobSquarePants/ImageSharp/blob/c0042041fcf6e7bfed445d5c606bcebb2d3b8896/src/ImageSharp/Processing/Processors/Transforms/ResizeProcessor.cs#L109) to utilize `BulkPixelOperations<TColor>.PackFromVector4()`.
- [ ] Drop repetitive weight values in `WeightsBuffer`
- [ ] Use Value Type Kernels as Weights windows
- [ ] Investigate possibilities for faster [Compress](https://github.com/JimBobSquarePants/ImageSharp/blob/760439185e24b5fa562cce06a67a42e9cf60ccf0/src/ImageSharp/Common/Extensions/Vector4Extensions.cs#L24) and [Expand](https://github.com/JimBobSquarePants/ImageSharp/blob/760439185e24b5fa562cce06a67a42e9cf60ccf0/src/ImageSharp/Common/Extensions/Vector4Extensions.cs#L37) execution to speedup the Compand variant.

## Update
After analyzing the precomputed weights data, I found out the windows are much smaller than I thought (I misread the code first time), so we can not reduce the window size.

However:
- [This is](https://gist.github.com/antonfirsov/39760ca9cef7c66f281a4a20ce4d06a1) how the `WeightsBuffer` looks like with a Bicubic 500->200 resize operation. 90% of the data is repetitive. We can allocate + precalculate less!
- The size of `IResampler.Radius` is known at compile time for each reasmpler. It means we can achieve significant improvements by utilizing Value Type Kernels. (See #142)

**Comment by antonfirsov** [comment]
Completed the first 2 points in #141 resulting in a 30% drop in execution time. Switching to a `Vector4` -based pixeltype could bring in additional 20% for the non-compand case because of the faster bulk-conversions.

I'm not planning to touch the others before the beta. Anyone who has interest: feel free to contribute or write your suggestions :)

**Comment by JimBobSquarePants** [comment]
Thanks for working on this. It's great improvement. 💯

**Comment by JimBobSquarePants** [comment]
Closing. We've come a long way since this was opened. And with #888 we've dramatically  reduced memory pressure. 

Any further changes can be opened as individual issues.
