### ISSUE TITLE
Colour saturation gets incorrect

### ISSUE THREAD

**Issue by hghansen** [SixLabors/ImageSharp#1397]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp.Drawing
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp.Drawing/issues) and [closed](https://github.com/SixLabors/ImageSharp.Drawing/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When loading an existing image into a new canvas the colour saturation gets changed.
Is there a way to get around this or can it be considered a bug?

It does not happen for all images but can clearly be seen in the ones attached.

### Steps to Reproduce
```
static void TestDrawImage(string inputPath, string outputPath)
{
    using (var inputImage = Image.Load(File.ReadAllBytes(inputPath)))
    using (var canvas = new Image<Rgba32>(SixLabors.ImageSharp.Configuration.Default, inputImage.Width, inputImage.Height))
    using (var ms = new MemoryStream())
    {
        canvas.Mutate(ctx => ctx.DrawImage(inputImage, 1f ));
        canvas.SaveAsJpeg(
            ms,
            new JpegEncoder()
            {
                Quality = 100,
                Subsample = JpegSubsample.Ratio444
            }
        );
        File.WriteAllBytes(outputPath, ms.ToArray());
    }
}
```

### System Configuration
This has been tested both on local developer pc (Windows 10) and hosted in docker-container (Debian 9).

- ImageSharp.Drawing version: 1.0.0-beta0010
- Other ImageSharp packages and versions: SixLabors.ImageSharp version 1.0.1
- Environment (Operating system, version and so on): Tested with same reesults on Windows 10 and Debian 9 
- .NET Framework version: .net Core 2.2
- Additional information:

Sample image original:
![test_draw_image_input](https://user-images.githubusercontent.com/28715861/96697509-4a6def80-138c-11eb-8f89-80ff48cdaaf6.jpg)

Sample image output:
![test_draw_image_output](https://user-images.githubusercontent.com/28715861/96697520-4e017680-138c-11eb-8d64-56503f919a37.jpg)

**Comment by JimBobSquarePants** [comment]
Hi @hghansen 

The difference between the input and output is images is caused by the presence (or lack of) of the ICC profile in the saved image. 

We do have plans to allow the optional automatic conversion of input pixels to sRGB color space. See #273 but in the interim a workaround would be to copy the profile from the input image to the output canvas.

```
using (var inputImage = Image.Load(inputPath))
using (var canvas = new Image<Rgba32>(Configuration.Default, inputImage.Width, inputImage.Height))
{
    canvas.Mutate(ctx => ctx.DrawImage(inputImage, 1F));

    canvas.Metadata.IccProfile = inputImage.Metadata.IccProfile?.DeepClone();

    canvas.SaveAsJpeg(
        outputPath,
        new JpegEncoder()
        {
            Quality = 100,
            Subsample = JpegSubsample.Ratio444
        }
    );
}
```

Here's the result of persisting the profile.

![issue_95](https://user-images.githubusercontent.com/385879/96722049-d9870180-13a4-11eb-83ae-c52e12028c90.jpg)
