### ISSUE TITLE
SixLabors.ImageSharp.UnknownImageFormatException: Image cannot be loaded

### ISSUE THREAD

**Issue by Henry-Keys** [SixLabors/ImageSharp#1406]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Trying to load the JPG image below throws the following
![images](https://user-images.githubusercontent.com/3662164/97466441-67359480-1943-11eb-87a5-29fa92ae88d9.jpg)

```
SixLabors.ImageSharp.UnknownImageFormatException: Image cannot be loaded. Available decoders:
 - TGA : TgaDecoder
 - PNG : PngDecoder
 - BMP : BmpDecoder
 - JPEG : JpegDecoder
 - GIF : GifDecoder
```

### Steps to Reproduce
The sample code
```csharp
using (Image image = await Image.LoadAsync(imageStream))
{
    PngEncoder pngEncoder = new PngEncoder();
    pngEncoder.CompressionLevel = PngCompressionLevel.BestCompression;
    await image.SaveAsync(imageStream, pngEncoder);
    imageStream.Seek(0, SeekOrigin.Begin);
}
```

### System Configuration

- ImageSharp version: 1.0.1
- Environment (Operating system, version and so on):
   - Windows 10 Pro - Version 1903 - Build 18362.1139
- .NET Core version: 2.1

**Comment by JimBobSquarePants** [comment]
Unless you have reset the position of the input stream before the code sample you posted then it looks like your input stream is in the wrong position. We do not reset that position for you on load unless [explicitly instructed](https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Configuration.html#SixLabors_ImageSharp_Configuration_ReadOrigin) to do so.

Here's the result of loading the image and saving it as a png.

![1406](https://user-images.githubusercontent.com/385879/97488552-4b87b980-1956-11eb-9425-7bf9abef02f0.png)

**Comment by Henry-Keys** [comment]
Hey @JimBobSquarePants 

Thanks for the tip, I'll try it out.

Cheers.

**Comment by Henry-Keys** [comment]
Still not working. I suspect Github altered the original image.
Can you try again, please?
https://we.tl/t-85LLGWncqZ

**Comment by JimBobSquarePants** [comment]
You haven't populated the new `Configuration` you have generated with any codecs.

If you want to return a new configuration containing all the existing codecs you should do this.

```c#
private static Configuration GetImageSharpConfiguration()
{
    var config = new Configuration(
        new PngConfigurationModule(),
        new JpegConfigurationModule(),
        new GifConfigurationModule(),
        new BmpConfigurationModule(),
        new TgaConfigurationModule());

    config.ReadOrigin = ReadOrigin.Current;
    return config;
}
```

If you want to reset the stream everywhere you use the library you can set the default config instead.

```c#
var config = Configuration.Default;
config.ReadOrigin = ReadOrigin.Begin;
```

**Comment by antonfirsov** [comment]
Or change `Configuration.Default.ReadOrigin`, or (IMO the best solution) just `imageStream.Seek(0, SeekOrigin.Begin)` before the image loads on misaligned streams.

**Comment by JimBobSquarePants** [comment]
Yup, I would choose to be explicit and reset my stream positions. Less possibility of unintended results.

**Comment by xiaoxstz** [comment]
I also came across this issue. The code is put below
```CSharp
      byte[] pixelData = new byte[16] { 0, 0 ,0,0,
                                            1,1,1,1,
                                            2,2,2,2,
                                            3,3,3,3};
       Image image = Image<Rgba32>.Load(pixelData);
       image.SaveAsBmp("pixelData.bmp");
```
