### ISSUE TITLE
BrightnessProcessor incorrectly scales HalfSingle values.

### ISSUE THREAD

**Issue by maxvoxel8** [SixLabors/ImageSharp#1459]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
`BrightnessProcessor` simply scales values with no regard for values like `HalfSingle` whose minimum value is not zero. Presumably other FilterProcessors also have this problem.

### Steps to Reproduce
Create an `Image<HalfSingle>` with -1 pixel values and apply a brightness scale to it. The image should remain the same, instead -1 values will be multiplied by the scale.

**Comment by antonfirsov** [comment]
@JimBobSquarePants `To/FromScaledVector4` should also apply an offset?

**Comment by JimBobSquarePants** [comment]
@antonfirsov ScaledVector is fine, we’re just not using it in the processor.

**Comment by JimBobSquarePants** [comment]
Should be an easy PR if you’re keen @maxvoxel8 ?

**Comment by maxvoxel8** [comment]
Sure, I can take a look.
