### ISSUE TITLE
PNG - System.ArgumentOutOfRangeException: Parameter "Position" (System.Int64) must be less than or equal to 1317080, was 1317088

### ISSUE THREAD

**Issue by DaveSenn** [SixLabors/ImageSharp#1482]
### Description

We use ImageSharp to resize PNG images. In our Log i found the following issue:

```
Exception => System.ArgumentOutOfRangeException: Parameter "Position" (System.Int64) must be less than or equal to 1317080, was 1317088
Parameter name: Position
   at SixLabors.ThrowHelper.ThrowArgumentOutOfRangeException(String name, String message)
   at SixLabors.ThrowHelper.ThrowArgumentOutOfRangeExceptionForMustBeLessThanOrEqualTo[T](T value, T maximum, String name)
   at SixLabors.ImageSharp.IO.BufferedReadStream.set_Position(Int64 value)
   at SixLabors.ImageSharp.IO.BufferedReadStream.Seek(Int64 offset, SeekOrigin origin)
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.Decode[TPixel](BufferedReadStream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, Func`3 largeImageExceptionFactory)
   at SixLabors.ImageSharp.Formats.Png.PngDecoder.Decode(Configuration configuration, Stream stream)
  
```

The error occurred when we tried to open a PNG image:

```
  using var originalImageStream = new MemoryStream( originalImageBytes );
  using var image = Image.Load( originalImageStream, new PngDecoder() );
```

The steam was only 1317080 long, but somehow the lib tried to set the position of the stream to 1317088. I have no explanation and I'm also not able to reproduce this problem with the same image.

### Steps to Reproduce
I was NOT able to reproduce this. I'm still trying to find more clues, but I'm not sure if i fill find something.

### System Configuration

- ImageSharp version: 1.0.2.0
- Environment (Operating system, version and so on): Windows Server 2016 x64
- .NET Framework version: .NET 4.8
- Additional information: Was running in a ASP.NET MVC application.

**Comment by JimBobSquarePants** [comment]
Do you have the image?

**Comment by JimBobSquarePants** [comment]
Also, are you sure the input image is a valid png? You’re forcing the decoder to attempt to decode it rather than allowing ImageSharp to detect the correct one.

**Comment by DaveSenn** [comment]
@JimBobSquarePants yes it is a valid png. i pulled the exact same file from the server and tried to reproduce the problem on my machine....without success. so fare i can't reproduce the error on any machine.

**Comment by JimBobSquarePants** [comment]
Can I have it? There's nothing we can do without it.

**Comment by DaveSenn** [comment]
i absolutely understand this. sadly i'm not allowed to share this data.
i will try to find more information about the problem and will post my findings here. 
i can understand if you want to close the issue.

**Comment by JimBobSquarePants** [comment]
I think I've actually found the issue. 

https://github.com/SixLabors/ImageSharp/blob/611ff85836549b03009b88191845b1a6c5319416/src/ImageSharp/Formats/Png/PngDecoderCore.cs#L141-L143

This should be safe but it looks like you are already at the end of your stream. It's the first call to decode to skip the png header.

Are you sure your streams are always rewound to the correct starting position before passing to ImageSharp?

Normally we would attempt to identify the image format from the stream and you would get a message saying we cannot identify the format if you are at the end of a stream but since you are choosing the decoder directly you're bypassing that.

**Comment by JimBobSquarePants** [comment]
@DaveSenn I'm going to close this as I believe I have identified the issue as not with the ImageSharp codebase and rather a case of incorrect input stream position.

**Comment by DaveSenn** [comment]
@JimBobSquarePants  Sorry I didn't saw your question till now...
This is my code (with some parts removed):

```
var originalImageBytes = File.ReadAllBytes( imagePath );
using var originalImageStream = new MemoryStream( originalImageBytes );

foreach ( var (height, width) in displayResolutions )
{
    using var image = Image.Load( originalImageStream, new PngDecoder() );
    image.Mutate( x => x.Resize( width, height ) );
    using var targetStream = new MemoryStream();
    image.Save( targetStream, new PngEncoder() );
    var resizedImageBytes = targetStream.ToArray();
    // ... Do something with the data
}

```

After creation the position of `originalImageStream` is **0**.
But after the first itteration the position is set to the end of the stream... And we try to use the same input stream again without reseting its position.
So i guess the bug is in our code. Thanks for the hint about the stream position reset.

**Comment by JimBobSquarePants** [comment]
No worries, happy to help!

**Comment by tocsoft** [comment]
@DaveSenn 
FYI based your sample above you will probably find you get better performance (at the cost of some memory) refactoring your code to make use of `image.Clone()`  in places of `image.Mutate` as it'll save performing the more costly decode stage inside a loop.

so this instead:
```csharp
var originalImageBytes = File.ReadAllBytes( imagePath );
using var originalImageStream = new MemoryStream( originalImageBytes );
using var image = Image.Load( originalImageStream, new PngDecoder() );
foreach ( var (height, width) in displayResolutions )
{
    using var clonedImg = image.Clone( x => x.Resize( width, height ) );
    using var targetStream = new MemoryStream();
    clonedImg.Save( targetStream, new PngEncoder() );
    var resizedImageBytes = targetStream.ToArray();
    // ... Do something with the data
}
```

assuming the  `displayResolutions` collection is generally grater than 1.
