### ISSUE TITLE
Image.Load missing System.Linq Version 4.1.1.0

### ISSUE THREAD

**Issue by KHALED-LAKEHAL** [SixLabors/ImageSharp#1503]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Trying to execute the method, Image.Load(FileStream fs), I get an exception saying:

System.IO.FileNotFoundException was thrown: "Could not load file or assembly 'System.Linq, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Le fichier spécifié est introuvable."

### System Configuration

- ImageSharp version: 1.0.2
- Other ImageSharp packages and versions: 
  - System.Threading.Tasks.Parallel" version 4.3.0
  - System.IO.UnmanagedMemoryStream  version 4.3.0
- Environment (Operating system, version and so on): Windows 7 x32 bit
- .NET Framework version: 4.6.2
- Additional information:

### My Code
```cs
public static Byte[] ResizeImage(this Byte[] data, int width, int height)
{
    using (MemoryStream inStream = new MemoryStream(data))
    using (MemoryStream outStream = new MemoryStream())
    using (SixLabors.ImageSharp.Image image = SixLabors.ImageSharp.Image.Load(inStream))
    {
        IImageEncoder format;
        ImageFormat imageFormat = data.GetImageFormat();
        image.Mutate(x => x.Resize(new ResizeOptions()
        {
            Mode = ResizeMode.Crop,
            Size = new SixLabors.ImageSharp.Size(width, height),
            Position = AnchorPositionMode.Center
        }));
        if (imageFormat.Equals(ImageFormat.Gif))
        {
            format = new GifEncoder();
        }
        else if (imageFormat.Equals(ImageFormat.Png))
        {
            format = new PngEncoder();
        }
        else if (imageFormat.Equals(ImageFormat.Jpeg))
        {
            format = new JpegEncoder();
        }
        else if (imageFormat.Equals(ImageFormat.Bmp))
        {
            format = new BmpEncoder();
        }
        else
        {
            format = new PngEncoder();
        }
        image.Save(outStream, format);
        outStream.Position = 0;
        return outStream.ToArray();
    }
}

public static ImageFormat GetImageFormat(this Byte[] data)
{
    Byte[] bmp = Encoding.ASCII.GetBytes("BM");
    Byte[] gif = Encoding.ASCII.GetBytes("GIF");
    Byte[] png = new Byte[] { 137, 80, 78, 71 };
    Byte[] tiff = new Byte[] { 73, 73, 42 };
    Byte[] tiff2 = new Byte[] { 77, 77, 42 };
    Byte[] jpeg = new Byte[] { 255, 216, 255, 224 };
    Byte[] jpeg2 = new Byte[] { 255, 216, 255, 225 };
    if (bmp.SequenceEqual(data.Take(bmp.Length)))
    {
        return ImageFormat.Bmp;
    }
    if (gif.SequenceEqual(data.Take(gif.Length)))
    {
        return ImageFormat.Gif;
    }
    if (png.SequenceEqual(data.Take(png.Length)))
    {
        return ImageFormat.Png;
    }
    if (tiff.SequenceEqual(data.Take(tiff.Length)))
    {
        return ImageFormat.Tiff;
    }
    if (tiff2.SequenceEqual(data.Take(tiff2.Length)))
    {
        return ImageFormat.Tiff;
    }
    if (jpeg.SequenceEqual(data.Take(jpeg.Length)))
    {
        return ImageFormat.Jpeg;
    }
    if (jpeg2.SequenceEqual(data.Take(jpeg2.Length)))
    {
        return ImageFormat.Jpeg;
    }
    return null;
}
```

**Comment by antonfirsov** [comment]
@KHALED-LAKEHAL could you please fill the issue template we provided? The report is not actionable for us without that.

**Comment by JimBobSquarePants** [comment]
MS recommend in the docs not to use anything less than 4.7.2 when targeting NET Standard libraries. 

https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

This is due to issues with binding redirects and legacy FX versions.

https://nickcraver.com/blog/2020/02/11/binding-redirects/

The fix.... Either upgrade you target framework or add the relevant binding redirects. This is not specific to ImageSharp and there is nothing we can do to fix it.

**Comment by JimBobSquarePants** [comment]
P.S.

`GetImageFormat` is redundant. We already choose the correct decoder to use.

https://docs.sixlabors.com/articles/imagesharp/gettingstarted.html#loading-and-saving-images

**Comment by JimBobSquarePants** [comment]
P.S You don't need all the format detection methods.
Load
https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Image.html#SixLabors_ImageSharp_Image_Load_SixLabors_ImageSharp_Configuration_System_IO_Stream_SixLabors_ImageSharp_Formats_IImageFormat__

Save
https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.ImageExtensions.html#SixLabors_ImageSharp_ImageExtensions_Save_SixLabors_ImageSharp_Image_System_IO_Stream_SixLabors_ImageSharp_Formats_IImageFormat_
