### ISSUE TITLE
Vectorized 4:2:0 subsampling leads to artifacts during Jpeg encoding. 

### ISSUE THREAD

**Issue by JimBobSquarePants** [SixLabors/ImageSharp#1549]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Issue originally identified by @jrdiver in #1547 Thanks for that!

The new vectorized subsampling algorithm introduced in #1517 by @tkp1n is creating artifacts in our jpeg output. Unfortunately our regression tests did not capture the issue. 

#### v1.0.3-alpha.0.28
![fb](https://user-images.githubusercontent.com/385879/107850268-11550180-6df9-11eb-8bd2-2f292ab9e177.jpg)

#### v1.0.3-alpha.0.29
![fb - Copy](https://user-images.githubusercontent.com/385879/107850267-10bc6b00-6df9-11eb-83a1-4cb9123dc502.jpg)

### Steps to Reproduce

Simply resaving the input image is enough ensuring the quality is low enough to trigger 4:2:0 subsampling.

```c#
using (var image = Image.Load(Path.Combine(inPath, "fb.jpg")))
{
    image.Save(Path.Combine(outPath, "fb.jpg"), new JpegEncoder { Quality = 75 });
}
```

### System Configuration

- ImageSharp version: v1.0.3-alpha.0.29
- Other ImageSharp packages and versions: NA
- Environment (Operating system, version and so on): All
- .NET Framework version: NET Core 3.1+ 
- Additional information:

**Comment by antonfirsov** [comment]
I'm not sure quality matters here. This is the output `EncodeBaseline_WorksWithDifferentSizes_Rgba32_TestPattern600x400_Ratio420-Q100.jpeg` which should run with `Quality=100` if everything is correct:

![image](https://user-images.githubusercontent.com/6835152/107850546-73b2ff80-6e03-11eb-823a-f862124cb98b.png)

**Comment by JimBobSquarePants** [comment]
Quality just triggers the subsampling when < 91 so yes, explicitly setting the property  would be enough.

**Comment by antonfirsov** [comment]
This should have been caught by our tests. Opened #1550.

@tkp1n any chance you can take a look?

**Comment by tkp1n** [comment]
I found the issue.. expect a PR coming soon
