### ISSUE TITLE
Consider renaming BinaryThresholdColorComponent

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#1556]
Didn't have a chance to react on #1555, but looking at the new specs, I think `BinaryThresholdColorComponent` should be rather  `BinaryThresholdMode`. (It doesn't seem like a color component in a given color space.)

@JimBobSquarePants @Franz1960 thoughts?

If you agree I'll go ahead with the rename.

**Comment by JimBobSquarePants** [comment]
`BinaryThresholdComponent` was what we decided on before actually without the color.

**Comment by antonfirsov** [comment]
Yeah probably wasn't the wisest choice. This is definitely not the most important thing right now, but if we can agree on a better name before 1.1 that would be great.

**Comment by JimBobSquarePants** [comment]
Let's go with `BinaryThresholdMode`. We need to ship a 1.0.3 today to fix the versioning issue. Our nightlies are currently broken.

**Comment by Franz1960** [comment]
BinaryThresholdMode is good for me.
