### ISSUE TITLE
Android emulator freezes after loading an image with Image.Load()

### ISSUE THREAD

**Issue by YJH16120** [SixLabors/ImageSharp#1563]
### Description
As said in the title. Whenever I try to load an image, with the Image.Load() method it just freezes the emulator, the screen goes black. And I can't do anything else. I can't step in, out, over. I can only stop the debugging session or restart it.

```csharp
var stream = File.Open(readPath, FileMode.Open, FileAccess.Read);

SixLabors.ImageSharp.Image newImage = SixLabors.ImageSharp.Image.Load(stream); // < -- freezes after this line
double height = (double)newImage.Height; double width = (double)newImage.Width;

List<int> dim = Compress.Deduction(width, height);
newImage.Mutate(x => x.Resize(dim[0], dim[1]));

newImage.SaveAsJpeg(save);
```
### Steps to Reproduce

Have an image, any image, available in the android emulator in Xamarin. 

Required permissions in android manifest's properties are: READ_EXTERNAL_STORAGE, and WRITE_EXTERNAL_STORAGE
### System Configuration

- ImageSharp version: 1.0.3 as of 19/2/2021
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: 5.0.103 as of 19/2/2021

**Comment by JimBobSquarePants** [comment]
You've should have raised this with Xamarin. It's not an issue with the library, rather with their emulator.

**Comment by YJH16120** [comment]
> 
> 
> You should have raised this with Xamarin. It's not an issue with the library, rather with their emulator.

noted
