### ISSUE TITLE
Crop not working correctly when the image height is the same size as the crop height. (haven't tested the width)

### ISSUE THREAD

**Issue by SomeProgrammerGuy** [SixLabors/ImageSharp#1572]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Crop not working correctly when the image height is the same size as the crop height. (haven't tested the width).

Use case resize to 200px high then crop to a 200px by 200px image.

### Steps to Reproduce

```
static void Test1()
{
    // Test image size (Width = 4288px, Height = 2848px).

    using Image imageToCrop = Image.Load(Path.Combine("test_folder", "4288_2848.jpg"));

    // Make the image 200px height.
    imageToCrop.Mutate(ctx => ctx.Resize(0, 200));

    // We want to cut 200px by 200px from the center.
    int xPosition = Convert.ToInt32((imageToCrop.Width / 3));

    // Fails on Mutate with:
    // System.ArgumentException: 'Crop rectangle should be smaller than the source bounds. Arg_ParamName_Name'
    // Rectangle rectangle = new(xPosition, 1, 200, 200);

    // WORKS but the images height is now 1 pixel to short.
    Rectangle rectangle = new(xPosition, 1, 200, 199);

    imageToCrop.Mutate(ctx => ctx.Crop(rectangle));

    imageToCrop.Save(Path.Combine("test_folder", "out_4288_2848.jpg"));
}

// Attempted from a file already at 200px Height.
static void Test2()
{
    // Test image Pre Resized (Width = 301px, Height = 200px).

    using Image imageToCrop = Image.Load(Path.Combine("test_folder", "301_200.jpg"));

    // We want to cut 200px by 200px from the center.
    int xPosition = Convert.ToInt32((imageToCrop.Width / 3));

    // Fails on Mutate with:
    // System.ArgumentException: 'Crop rectangle should be smaller than the source bounds. Arg_ParamName_Name'
    // Rectangle rectangle = new(xPosition, 1, 200, 200);

    // WORKS but the images height is now 1 pixel to short.
    Rectangle rectangle = new(xPosition, 1, 200, 199);

    imageToCrop.Mutate(ctx => ctx.Crop(rectangle)); 

    imageToCrop.Save(Path.Combine("test_folder", "out_301_200.jpg"));
}

```

I attempted to pull the library so I could debug through it but I couldn't get it to compile without a lot of errors.

Visual Studio 2019

.NET Core 3.1 SDK installed

git clone https://github.com/SixLabors/ImageSharp

git config --system core.longpaths true

git submodule update --init --recursive

(To many errors to list).

Most seemed of the nature:

"Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0579	Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute	ImageSharp (net472)	C:\BitBucket\ImageSharp\artifacts\obj\src\ImageSharp\Debug\net472\.NETFramework,Version=v4.7.2.AssemblyAttributes.cs	4	Active"

for many .NET versions. 

I haven't tried to fix or investigated this further. It could simply be the way my environment is setup.

### System Configuration
Windows 10, Visual Studio 2019 latest updates 08 Mar 2021.

- ImageSharp version: 1.0.2 from NuGet
- Environment (Operating system, version and so on): 
  - Windows 10 Pro Latest Updates 08 Mar 2021.
  - Visual Studio 2019 latest updates 08 Mar 202
- .NET Framework version: .NET 5 (CORE)

**Comment by JimBobSquarePants** [comment]
>Crop rectangle should be smaller than the source bounds

There’s nothing to debug. The error message is explicit and by design.

**Comment by JimBobSquarePants** [comment]
Yep...

Latest ImageSharp is v1.0.3
https://www.nuget.org/packages/SixLabors.ImageSharp/1.0.3

Latest ImageSharp.Web is v1.0.2
https://www.nuget.org/packages/SixLabors.ImageSharp.Web/1.0.2

More sleep is always useful! 😄 

Yeah a source image bounds always has X and Y of 0 since that the first top/left coordinates so when you crop you need to ensure your crop rectangle fits those bounds. We basically use `Rectangle.Contains` to sanitize.

>Yes this is rather harder to pin down though I do have a lot going on on my development VM. If I get time later this week ill try it on a fresh VM with fresh VS install.

Please let me know if you do have issues. There maybe something I have overlooked that I always have installed.
