### ISSUE TITLE
Can't Load PNG in Pixel Format based on format of PNG

### ISSUE THREAD

**Issue by WalkerCodeRanger** [SixLabors/ImageSharp#1592]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I have a large number of PNG images stored in Grayscale 8-bit and Grayscale 16-bit. If I load them using `Image.Load()` without a pixel type, they always load as `Image<Rgba32>`. I can load them as grayscale using `Image.Load<L8>()` or `Image.Load<L16>()` to load them as grayscale. However, I don't know in advance which format any given image is stored in. There doesn't seem to be any way to load an image from PNG where the `PixelType` is determined by the pixel format the PNG was saved in.

I tried using `PngDecoder` but it doesn't have any options which do this.

### Steps to Reproduce

```csharp
using (var inputFile = File.OpenRead(inputPath))
{
    return Image.Load(inputFile); // vs Image.Load<L8>(inputFile) or Image.Load<L16>(inputFile);
}
```

### System Configuration

- ImageSharp version: v1.0.3
- Other ImageSharp packages and versions: NA
- Environment (Operating system, version and so on): Windows 10 Pro 64-bit
- .NET Framework version: 4.7.2
- Additional information:

**Comment by antonfirsov** [comment]
@WalkerCodeRanger yeah, unfortunately current `PngDecoder` loads everything into `Rgba32`.

We plan to load into native pixel formats as an optimization, but we can't guarantee it will be 100% perfect. Basically you should assume that the non-generic `Image.Load()` is free to choose the pixel format based on it's own arbitrary logic.

There is a workaround for your use case though utilizing `Identify` and `PngMetadata`:

```
IImageInfo info = Image.Identify(path); // this will not load the pixel data, only parse headers & metadata
PngMetadata metaData = info.Metadata.GetPngMetadata();
```

Then use own logic switching on `metaData.ColorType` and `mataData.BitDepth` to determine the pixel type to use with `Image.Load<TPixel>(...)`.

**Comment by WalkerCodeRanger** [comment]
Thanks, doing the `Image.Identify(path)` and deciding based on the metadata worked.
