### ISSUE TITLE
4 pixel webp image decode failure.

### ISSUE THREAD

**Issue by zugolbr** [SixLabors/ImageSharp#1594]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When opening https://sylvain.debaudringhien.net/pic.webp (4 pixels image), the right column goes black.

### Steps to Reproduce
![Capture-2](https://user-images.githubusercontent.com/82333369/114318262-9bc19500-9b0c-11eb-8535-eec5690728ae.png)
(ùsio is a FileStream pointing to pic.webp)

The same 4 pixels, as png, are decoded correctly when using the png decoder.

### System Configuration

- ImageSharp version: webp #f99ed84

**Comment by brianpopow** [comment]
@zugolbr thanks for the report. I can reproduce the issue and will try to figure out whats wrong.

**Comment by brianpopow** [comment]
Fixed with d6520d25

**Comment by zugolbr** [comment]
Thank you!😀
