### ISSUE TITLE
ParallelRowIterator.Invoke should be able to take a factory method for a per-thread context

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#1611]
This is an important optimization enabler. Explanation:
https://github.com/SixLabors/ImageSharp.Drawing/issues/117#issuecomment-822473190

@Sergio0694 any guidance do it simply/quickly?

**Comment by Sergio0694** [comment]
If adding new overloads is a concern, wouldn't it be possible to just have consumers opt-in into whatever thread-local storage they need, by having their value-closure also capture a [`ThreadLocal<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.threadlocal-1) instance? That class already has constructors taking a factory, and it's fairly optimized internally as well. This solution would also allow `ParallelRowIterator` itself to be unaware of these details.

By that I mean, they could just capture a `ThreadLocal<T>` as another field into their value-closure type implementing `IRowOperation`, and then keep using `ParallelRowIterator.Invoke` as usual, with all other things being the same there.

Might be worth trying out to see if performance is good enough before going ahead and thinking about a more specialized design that would require changes to `ParallelRowIterator` and related APIs, and new overloads? Just a thought 🙂

**Comment by antonfirsov** [comment]
@Sergio0694 wow `ThreadLocal<T>` is cool, wasn't aware of it, let's give it a try first.

**Comment by antonfirsov** [comment]
I'm closing this, `ThreadLocal<T>` seems to do the job well enough.
