### ISSUE TITLE
Image in portrait load size-s as landscape

### ISSUE THREAD

**Issue by vorodot** [SixLabors/ImageSharp#1613]
Hi,

I have two images which thumbnails and real size images are shown properly in Windows Explorer and in image editors that I use.
Unfortunately when I load the size of the portrait image the SixLabors.ImageSharp library returns the dimensions as landscape. I cannot find a property that I can use to for orientation.

### Steps to Reproduce
There is attached zip with demo.

### System Configuration
.NET Core application with 1.0.3 version of SixLabors.ImageSharp. 
Windows 10

![Capture](https://user-images.githubusercontent.com/12648318/115298929-ca6fe900-a166-11eb-96b4-5460a932ed11.JPG)
[netcoreapp3.1.zip](https://github.com/SixLabors/ImageSharp/files/6338896/netcoreapp3.1.zip)

The code of the program:

```c#
using (var image = Image.Load("DSC_9396.JPG"))
{
  Console.WriteLine("Landscape: DSC_9396.JPG");
  Console.WriteLine("Width: " + image.Width);
  Console.WriteLine("Height: " + image.Height);
}
Console.WriteLine("");
using (var image = Image.Load("DSC_9398.JPG"))
{
  Console.WriteLine("Portrait: DSC_9398.JPG");
  Console.WriteLine("Width: " + image.Width);
  Console.WriteLine("Height: " + image.Height);
}

Console.ReadLine();
```

**Comment by JimBobSquarePants** [comment]
ImageSharp is doing the correct thing here. 

The second portrait image is actually 6000 pixels wide but has an EXIF orientation property which rotates the image for display to portrait mode. Windows returns the EXIF dimensions in it's details info but that wouldn't be correct for pixel processing. 

Here's System.Drawing returning the same results.

![image](https://user-images.githubusercontent.com/385879/115303764-efab2a00-a15b-11eb-9ed9-735ed81dd046.png)

**Comment by antonfirsov** [comment]
@vorodot [`AutoOrient`](https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Processing.AutoOrientExtensions.html#SixLabors_ImageSharp_Processing_AutoOrientExtensions_AutoOrient_SixLabors_ImageSharp_Processing_IImageProcessingContext_) will help you out:
```C#
image.Mutate(c => c.AutoOrient());
```
