### ISSUE TITLE
Overflow in `LeastCommonMultiple` leads to exception during resize operation

### ISSUE THREAD

**Issue by ptasev** [SixLabors/ImageSharp#1616]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When doing a resize operation of an image with a particularly large height, I got an exception that ImageSharp was trying to allocate memory of negative total length.  I tracked this down to this line where period is calculated. The period calculation overflows making period become negative which ends up failing when it creates the kernel map several line below (158) while allocating memory in the constructor.
https://github.com/SixLabors/ImageSharp/blob/a6c17854684edaa998080233273d19d987174bb5/src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeKernelMap.cs#L135

One possible solution for this particular case could be to change that line to use greatest common divisor instead and calculate period using:
```csharp
int period = destinationSize / Numerics.GreatestCommonDivisor(sourceSize, destinationSize);
```

### Steps to Reproduce
With a height of 207773, and a destination height of 51943, the GCD is 1 causing an overflow when multiplying both of those numbers in `Numerics.LeastCommonMultiple(a, b)`.
```csharp
var width = 5000;
var height = 207773;
using (var img = new Image<L16>(width, height))
{
    using var clone = img.Clone(ctx =>
    {
        var factor = 4;
        ctx.Resize(img.Width / factor, img.Height / factor, KnownResamplers.Bicubic);
    });
}
```

### System Configuration
I don't think it's relevant.

- ImageSharp version: 1.0.3
- Other ImageSharp packages and versions: N/A
- Environment (Operating system, version and so on): Win 10
- .NET Framework version: NET 3.1, NET 5.0
- Additional information: N/A

**Comment by JimBobSquarePants** [comment]
That’s a big image! I think a cast to long will likely be sufficient, we had similar issues elsewhere previously.

**Comment by ptasev** [comment]
Yeah, getting real close to the int.Max limit in terms of bytes.

The overflow happens inside of `Numerics.LeastCommonMultiple(a, b)` so the return type would have to be changed to long instead of int. I don't think we can solve this with only a cast. Not sure if you want to take that approach or just fix it locally in that method by using GCD instead.

**Comment by antonfirsov** [comment]
Just to explain the math behind the suggestion:

Since `LCM(a,b)*GCD(a,b)=a*b`

```
period = d / LCM(s,d) = d / ( s*d / GCD(s,d) ) = 1 / (s * GCD(s,d)) = GCD(s,d) / s
```

LCM is actually implemented by GCD:
https://github.com/SixLabors/ImageSharp/blob/97dde7fb2f0ac97b5b1f9e6b0555a53d2e270c46/src/ImageSharp/Common/Helpers/Numerics.cs#L47-L48

Replacing it in the KernelMap would make things simpler, and makes sense to me. Looks like a very easy thing to PR, just let's make sure to add test coverage by adding a few lines stressing high values [here](https://github.com/SixLabors/ImageSharp/blob/a6c17854684edaa998080233273d19d987174bb5/tests/ImageSharp.Tests/Processing/Processors/Transforms/ResizeKernelMapTests.cs#L81)

**Comment by antonfirsov** [comment]
Marked this as `good first issue` since it should be easy for anyone, but @ptasev if you feel like fixing it, don't hold yourself back :)

**Comment by ptasev** [comment]
I have to jump through some hoops to be able to make this contribution since I found and investigated this bug for work and not on my personal free time.  I'll try to get the permission to do this, but it may take some time to get approved.
