### ISSUE TITLE
Resizing operation throws InvalidOperationException with exotic image resolution

### ISSUE THREAD

**Issue by br3aker** [SixLabors/ImageSharp#1625]
- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Custom debug logs from `MemoryGroup<T>.Allocate(...)` call during steps stated below:
```
// Loading & decoding initial image from disk, 10x10=100 pixels - ok
// Minimal contiguous memory line 40 bytes - ok
Requesting Rgba32[100] (400 bytes) with stride of 40/1000 bytes
Allocation of 1 buffers 100 elements/400 bytes each

// Image cloning with bigger size for resizing, 15x15=225 pixels - ok
// Minimal contiguous memory line for 60 bytes - ok
Requesting Rgba32[225] (900 bytes) with stride of 60/1000 bytes
Allocation of 1 buffers 225 elements/900 bytes each

// Something related to resizing I guess - ok
Requesting Single[35] (140 bytes) with stride of 20/1000 bytes
Allocation of 1 buffers 35 elements/140 bytes each

// Something related to resizing I guess - ok
Requesting Single[35] (140 bytes) with stride of 20/1000 bytes
Allocation of 1 buffers 35 elements/140 bytes each

// That's where everything breaks due to non-contiguous memory allocation
Requesting Vector4[150] (2400 bytes) with stride of 160/1000 bytes
Allocation of 3 buffers 60 elements/960 bytes each
<-- After this call exception occurs -->
```

Last allocation from log allocates 150 Vector4 elements with a stride of 10 elements which is done by allocating 3 separate buffers of 60 elements each which fullfils requested "contiguous chunks of 10 elements each", so far so good.

Real problem lies inside [ResizeWorker](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeWorker.cs) class:
https://github.com/SixLabors/ImageSharp/blob/993f96eb7d90e05dbf2039c116d44be8fb081cd8/src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeWorker.cs#L117-L118

Although comment states that buffer is ensured to be contiguous it's not:
https://github.com/SixLabors/ImageSharp/blob/993f96eb7d90e05dbf2039c116d44be8fb081cd8/src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeWorker.cs#L88-L91

Allocate2D only ensures that requested memory is aligned by at least chunks of `width` parameter:
https://github.com/SixLabors/ImageSharp/blob/993f96eb7d90e05dbf2039c116d44be8fb081cd8/src/ImageSharp/Memory/MemoryAllocatorExtensions.cs#L25-L35

Which is what happened in logs, ResizeWorker requested 10 strides of 15 elements with alignment of 15. 

Atm given Buffer2D API doesn't provide any way to ensure that requested memory occupies single contiguous buffer but I suppose it should be something like this:
```csharp
public static Buffer2D<T> AllocateContiguous2D<T>(
    this MemoryAllocator memoryAllocator,
    int width,
    int height,
    AllocationOptions options = AllocationOptions.None)
    where T : struct
{
    long groupLength = (long)width * height;
    MemoryGroup<T> memoryGroup = memoryAllocator.AllocateGroup<T>(
       groupLength, // passing total size as buffer size
       groupLength, // passing total size as alignment
       options);
    return new Buffer2D<T>(memoryGroup, width, height);
}
```

### Steps to Reproduce
Use this code snippet:
```csharp
Configuration.Default.MemoryAllocator =
    new ImageSharp.Memory.ArrayPoolMemoryAllocator(
        maxPoolSizeInBytes: 1000,
        poolSelectorThresholdInBytes: 1, // [not relevant]
        maxArraysPerBucketLargePool: 1000,
        maxArraysPerBucketNormalPool: 1, // [not relevant]
        bufferCapacityInBytes: 1000
    );
var image = Image.Load("IMAGE_PATH");
image.Mutate(op => op.Resize(15, 15));
```

With this 10x10 pixels plain black png image:
https://user-images.githubusercontent.com/20967409/117883361-fdb01e80-b2b3-11eb-850f-10c66309430d.png

Yes, it can be broken even with **current default config allocator** but with a bit more extreme example:

```csharp
var image = Image.Load("IMAGE_PATH");
image.Mutate(op => op.Resize(10000, 1));
```

With this 1x4096 pixels plain black png image:
https://user-images.githubusercontent.com/20967409/117890174-56d08000-b2bd-11eb-93f3-ad625787f0be.png

**Comment by br3aker** [comment]
`ResizeWorker` has some sort of checking for contiguous memory but it doesn't affect allocated buffer in any way:
https://github.com/SixLabors/ImageSharp/blob/993f96eb7d90e05dbf2039c116d44be8fb081cd8/src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeWorker.cs#L76-L79

I don't think that providing such internal detail about allocator is a good thing, memory user should work with size of the given memory, not with some configuration value from entierly different class  This is error prone and introduce dependency from underlying implementation.

Anyway, even if logic is correct, code fails on calling GetSingleSpan() on Buffer2D which is strange, shouldn't this code allocate `Memory<T>` directly via `allocator.Allocate(totalSize)`?

P.S.
Ashamed saying it but I don't have a slightest idea of what's going on in that processing code even in resize processor, are there any articles or study behind all of this so I can acquire necessary knowledge? :P

**Comment by antonfirsov** [comment]
@br3aker nice catch! I hope I will be able to look into this next week, this one is completely busy with other stuff.

**Comment by saucecontrol** [comment]
> Ashamed saying it but I don't have a slightest idea of what's going on in that processing code even in resize processor, are there any articles or study behind all of this so I can acquire necessary knowledge?

@br3aker resizing is one of the more complicated processors, but it's just based on convolution in the end, as are things like blur, sharpen, and edge detection.  This is probably the best intro to the math behind resizing I've seen:  http://entropymine.com/imageworsener/resample/

**Comment by br3aker** [comment]
@saucecontrol thanks a lot! Will definately take a look.

**Comment by JimBobSquarePants** [comment]
We'll need to look at this again now the memory allocator works differently.

**Comment by JimBobSquarePants** [comment]
@antonfirsov It appears to me that we can ensure the allocation is contiguous now via the new Allocate2D overload

https://github.com/SixLabors/ImageSharp/blob/bab74dc3e6a261713374d5d8afb6d3e960572a4f/src/ImageSharp/Memory/MemoryAllocatorExtensions.cs#L26-L32

Passing `true` as the 3rd parameter.

https://github.com/SixLabors/ImageSharp/blob/bab74dc3e6a261713374d5d8afb6d3e960572a4f/src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeWorker.cs#L88-L91

We could then drop the calculation, and property here and just enforce a 1MB limit internally.

https://github.com/SixLabors/ImageSharp/blob/bab74dc3e6a261713374d5d8afb6d3e960572a4f/src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeWorker.cs#L76-L79

Is that correct?

**Comment by antonfirsov** [comment]
@JimBobSquarePants yeah that would solve the problem, I will file a PR to fix this soon. Note that this is a corner case, you can't trigger it with sane code, especially hard with the new API.
