### ISSUE TITLE
Image.Clone(Configuration) should use the passed Configuration's MemoryAllocator

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#1642]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Discovered while thinking about the test in #1641.

`image.Clone(Configuration)` will call the following method eventually:

https://github.com/SixLabors/ImageSharp/blob/a2703b75a89d182e1dffa780e91ccaca2c375040/src/ImageSharp/ImageFrame%7BTPixel%7D.cs#L128-L136

We should use the passed `configuration`'s memory allocator instead of `this.GetConfiguration().MemoryAllocator`. Not a critical user scenario, so triaging to future.

PS:
Would have raised a PR by editing the `.cs` right away on GitHub, but my OCD doesn't let me to do it without also adding a test :)

**Comment by RobbyRobbyRobby** [comment]
Hi,

I just took a look at this, and see that the method from the base class which is called prior to the derived one does the following:

`this.configuration = configuration ?? Configuration.Default;`

Which means that `this.GetConfiguration()` does in fact use the passed configuration; but with the benefit of null checking.

**Comment by JimBobSquarePants** [comment]
Just double checked and confirmed. Thanks @RobbyRobbyRobby for looking into this.
