### ISSUE TITLE
StyleCop warnings no longer fail the build

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#1658]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

 #1632 resulted in merging a couple of build warnings, for example:
 ```
 FastFloatingPointDCT.cs(66,41): warning SA1306: Field 'C_V_InvSqrt2' should begin with lower-case letter
 JpegEncoderCore.cs(72,33): warning SA1201: A field should not follow a property
 JpegEncoderCore.cs(183,25): warning SA1101: Prefix local calls with this
 ...
 ```
 
We used to have some "warning as error" switch on this, looks like it no longer works, so they managed to sneak in through the CI.

**Comment by JimBobSquarePants** [comment]
@antonfirsov This is super weird. 

There have been no changes to the props files and having just experimented with putting the rule on every possible level with or without the condition I can confirm it simply does not work. I wonder whether something was broken in latest SDK + MSBuild?
