### ISSUE TITLE
RemoteExecutor does not work with 32bit .NET Framework

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#1661]
There is a leftover from #1376 / #1659, since RemoteExecutor does not work with `dotnet xunit`:

https://github.com/SixLabors/ImageSharp/blob/255802cd9b1e0e72b5c3399b8b19070971dd5328/tests/ImageSharp.Tests/TestUtilities/Tests/TestEnvironmentTests.cs#L118-L123

This means that RemoteExecutor/FeatureTestRunner test passes can be false positives on 32 bit .NET Framework. Ideally this should be addressed together with #1386 by replacing `dotnet xunit` with a local 32bit SDK installation + build + test run.

**Comment by JimBobSquarePants** [comment]
We can close this now since we no longer support .NET Framework
