### ISSUE TITLE
Jpeg colorspace is undefined after metadata only (Identify call) pass

### ISSUE THREAD

**Issue by br3aker** [SixLabors/ImageSharp#1692]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Jpeg color space is undefined after `metadataOnly` decoding pass. This is happening because colorspace deduction (and metadata population) logic is locked behind `if(!metadataOnly)` check in `SOF` marker parsing (line 916):

https://github.com/SixLabors/ImageSharp/blob/fe65a387a953c8b2e41ccb5d6a9c915585e90d8f/src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs#L868-L918

### Steps to Reproduce
```csharp
var info = Image.Identify("image_path");
Console.WriteLine(info.Metadata.GetFormatMetadata(JpegFormat.Instance).ColorType.HasValue); // prints false
```

```csharp
using var image = Image.Load("image_path");
Console.WriteLine(image.Metadata.GetFormatMetadata(JpegFormat.Instance).ColorType.HasValue); // prints true
```

**Comment by br3aker** [comment]
As this breaks existing jpeg decoder tests it'll be fixed as part of https://github.com/SixLabors/ImageSharp/issues/1597.

**Comment by JimBobSquarePants** [comment]
Ha! well spotted! We're deducing the colorspace 2 times. Once at line 884 and once at line 916 but hiding both in that block!
