### ISSUE TITLE
Half of specific PNG image fails to load on .NET 6

### ISSUE THREAD

**Issue by PJB3005** [SixLabors/ImageSharp#1728]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I have this specific PNG image of which the bottom half gets cut off when I try to load it with ImageSharp. It **only** happens on .NET 6 (preview 6), .NET 5 is fine. No other editor/viewer I tried it with (paint, paint.net, krita, windows photo viewer (old and windows 10 one), chrome, firefox) fails to load this image.

here is the image:

![000000drizzletest](https://user-images.githubusercontent.com/8107459/128563528-306817b1-5918-421b-81a5-4f133696f653.png) (`5C8E5A1B4B577E68A21E1384B5A11C5B1A38B59AC5210C583C6D577CCAF96E23` SHA256 hash but github shouldn't change it on upload).

If I load and save this with ImageSharp, I get the following result:
![foo](https://user-images.githubusercontent.com/8107459/128563632-19b7a124-6600-4b94-95a5-34a8edd36f0a.png)

Re-saving the image by, for example, running it through `optipng` magically fixes the problem.

### Steps to Reproduce
Download the image, then run it through some C# code like this:
```cs
var img = Image<Bgra32>.Load("000000drizzletest.png");

img.SaveAsPng("foo.png");
```

### System Configuration

- ImageSharp version: 1.0.3
- Other ImageSharp packages and versions: None
- Environment (Operating system, version and so on): Windows 10 Pro 19042.1110
- .NET Framework version: **.NET 6**
- Additional information: If you're wondering what made this cursed PNG file, it's an img Xtra for Adobe Director. No, you don't want to know.

**Comment by brianpopow** [comment]
that issue was fixed with #1707

You can try our nightly builds from here: [Nightly](https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp)
