### ISSUE TITLE
BGRA Jpg incorrectly decoded.

### ISSUE THREAD

**Issue by Drake53** [SixLabors/ImageSharp#1746]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Trying to load a .jpg file with BGRA data gets incorrectly decoded as if it's YCbCr. As a result, the colours are incorrect and there's no alpha channel.

### Steps to Reproduce
Simply load the example .jpg file:
https://github.com/Drake53/War3Net/blob/master/tests/War3Net.Common.Testing/TestData/Blp/VillageFallStonePath.jpg

Note that github doesn't display it correctly either, it should look like this:
https://github.com/Drake53/War3Net/blob/master/tests/War3Net.Common.Testing/TestData/Blp/VillageFallStonePath.png

### System Configuration

- ImageSharp version: 1.0.3
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version: .NET 5.0
- Additional information:

**Comment by br3aker** [comment]
If I got you right, you have an bgra image encoded via jpeg format, right?

Jpeg doesn't support bgra format;

> Images encoded with four components are assumed to be CMYK, with (0,0,0,0) indicating white unless the image contains an APP14 marker segment as specified in 6.5.3, in which case the colour encoding is considered either **CMYK** or **YCCK** according to the application data of the APP14 marker segment. The relationship between CMYK and YCCK is defined as specified in clause 7.

May I ask you where did you re-encode png -> jpeg with bgra colorspace?

**Comment by Drake53** [comment]
The jpeg data comes from a .blp file, which is a file format that contains embedded jpeg or dds images and supports mipmaps.
https://github.com/Drake53/War3Net/blob/master/tests/War3Net.Common.Testing/TestData/Blp/VillageFallStonePath.blp

I'm not familiar with jpeg specifications, all I know is that using BitmapSource I am able to decode the .jpg correctly.
https://github.com/Drake53/War3Net/blob/master/src/War3Net.Drawing.Blp/BlpFile.cs

However, WPF is windows only, so I'd prefer to use a cross-platform library instead.

**Comment by brianpopow** [comment]
The color space of this image is CMYK. It has no APP14 marker and has 4 components. I think we are just missing a check, if the adobe marker has its default value? 

https://github.com/SixLabors/ImageSharp/blob/9b09775d5e925d6dad2b559b3995567e69440b5d/src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs#L378

**Comment by br3aker** [comment]
@brianpopow seems like. Should be something like this:
```csharp
return !this.adobe.Equals(default) && this.adobe.ColorTransform == JpegConstants.Adobe.ColorTransformYcck
                    ? JpegColorSpace.Ycck
                    : JpegColorSpace.Cmyk;
```

**Comment by brianpopow** [comment]
Still does not look as expected with CMYK:

![cmyk](https://user-images.githubusercontent.com/38701097/130352512-6c53e0cb-61f7-4f28-9cf6-0f065669b186.png)

but it looks the same when i convert it with imagemagick to a png.

**Comment by JimBobSquarePants** [comment]
Does the image contain a color profile?

**Comment by brianpopow** [comment]
> Does the image contain a color profile?

no, there is no color profile

**Comment by JimBobSquarePants** [comment]
Odd. Try decoding it to rgb. I’m amazed WPF can decode it since it’s seems off spec.

**Comment by brianpopow** [comment]
looks pretty much the same, except the black area is white. 

![rgb](https://user-images.githubusercontent.com/38701097/130352932-fe0c3ae3-914e-4e42-8f81-fc4865a07639.png)

imagemagick identify says it should be CMYK

**Comment by JimBobSquarePants** [comment]
https://www.hiveworkshop.com/threads/blp-specifications-wc3.279306/

blp is pretty messed up. WCF must fall back to BGRA once it exhausts all standard possibilities.

**Comment by br3aker** [comment]
> imagemagick identify says it should be CMYK

It's a specification-complient fallback for 4-component image without APP14 marker.

Jpeg simply does not support alpha channels, Jpeg2000 does.

Link provided by @JimBobSquarePants even states that blp jpeg content type had some custom code via framework. I've failed to find anything related to it so it's impossible to say anything about how given file was produced.

> Blizzard uses the now discontinued Intel Imaging Framework to produce/decode the JPEG content meaning that each jpegHeaderChunk of official BLP files contains its signature. Photoshop, JPEGSnoop, Forensically and internet browsers treat this as a CMYK image.

Played a bit with the binary, provided .blp file is basically a container with jpeg at the top and something else after the image, it has an explicit valid `SOI -> ... -> EOI` marker sequence which leads to exact same jpeg provided by the OP. It has 4 components, nothing else -> it's a CMYK file according to jpeg specification.

If it's really a bgra image, CMYK components should store BGRA data in each channel so the only viable solution atm is (simplified):

```
foreach pixel in decodedImage:
    newImage[i] = new BGRA(pixel.C, pixel.M, pixel.Y, pixel.K)
```
--------------------------------
Decoding such 'custom' jpeg images is actually possible with decoder change in https://github.com/SixLabors/ImageSharp/pull/1694. Decoding is done by a virtual method of an internal class which can be exposed to the end user. Question is: do you guys want it to be exposed for cases like this? @JimBobSquarePants @brianpopow

**Comment by JimBobSquarePants** [comment]
Let me do some research. I want to figure out how `JpegBitmapDecoder` works.

**Comment by br3aker** [comment]
@JimBobSquarePants It does not work with given image, following code prints `Decoder format: Cmyk32`:

```csharp
const string pathTemplate = "path\\{0}.jpg";

using Stream inputStream = File.Open(string.Format(pathTemplate, "VillageFallStonePath"), FileMode.Open);

var decoder = new JpegBitmapDecoder(inputStream, BitmapCreateOptions.PreservePixelFormat, BitmapCacheOption.Default);

Console.WriteLine($"Decoder format: {decoder.Frames[0].Format}");
```

Saving it with `JpegBitmapEncoder` produces the same image:

```csharp
var encoder = new JpegBitmapEncoder();
encoder.Frames.Add(decoder.Frames[0]);

using Stream outputStream = File.Open(string.Format(pathTemplate, "re_VillageFallStonePath"), FileMode.OpenOrCreate);
encoder.Save(outputStream);
```

![re_VillageFallStonePath](https://user-images.githubusercontent.com/20967409/130426883-3632f04e-94e8-43c2-aecc-2d33aa7fd023.jpg)

**Comment by JimBobSquarePants** [comment]
Then @Drake53 we're going to need proof of this in code form. 

>all I know is that using BitmapSource I am able to decode the .jpg correctly.

**Comment by Drake53** [comment]
I use this code to compare the png and jpg files:

```csharp
using System.IO;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
    public class JpgWpfTests
    {
        [TestMethod]
        public void Test()
        {
            var pngFilePath = Path.Combine(path, "VillageFallStonePath.png");
            var jpgFilePath = Path.Combine(path, "VillageFallStonePath.jpg");

            using var expectedImageStream = File.OpenRead(pngFilePath);
            var expectedImageDecoder = new PngBitmapDecoder(expectedImageStream, BitmapCreateOptions.None, BitmapCacheOption.Default);
            var expectedPixelBytes = GetPixels(expectedImageDecoder, out var expectedPixelFormat);

            using var actualImageStream = File.OpenRead(jpgFilePath);
            var actualImageDecoder = new JpegBitmapDecoder(actualImageStream, BitmapCreateOptions.PreservePixelFormat, BitmapCacheOption.Default);
            var actualPixelBytes = GetPixels(actualImageDecoder, out var actualPixelFormat);

            Assert.AreEqual(expectedPixelFormat.BitsPerPixel, actualPixelFormat.BitsPerPixel);
            Assert.AreEqual(expectedPixelBytes.Length, actualPixelBytes.Length);

            for (var i = 0; i < actualPixelBytes.Length; i++)
            {
                actualPixelBytes[i] = (byte)(255 - actualPixelBytes[i]);

                Assert.AreEqual(expectedPixelBytes[i], actualPixelBytes[i], 1f);
            }
        }

        private static byte[] GetPixels(BitmapDecoder decoder, out PixelFormat pixelFormat)
        {
            var bitmap = decoder.Frames[0];
            pixelFormat = bitmap.Format;

            var bytesPerPixel = (pixelFormat.BitsPerPixel + 7) / 8;
            var stride = bitmap.PixelWidth * bytesPerPixel;

            var pixelData = new byte[stride * bitmap.PixelHeight];
            bitmap.CopyPixels(pixelData, stride, 0);

            return pixelData;
        }
    }
```

**Comment by JimBobSquarePants** [comment]
What’s going on here?

```c#
actualPixelBytes[i] = (byte)(255 - actualPixelBytes[i]);
```

**Comment by Drake53** [comment]
WPF doesn't do it 100% as I expect it either, so when I expect 255 I get 0 instead, and vice versa. This is for all 4 BGRA channels, so I simply adjust all bytes like that to get the values I expect.

**Comment by br3aker** [comment]
> so when I expect 255 I get 0 instead, and vice versa

Does `255 - pixelByte` formula based on these edge cases expectation only?

**Comment by JimBobSquarePants** [comment]
I think we're chasing ghosts here. Our jpeg decoder should match the specification and no existing standalone decoder can yield an expected result.

**Comment by Drake53** [comment]
Yes, it's only needed for this edge case.
I tested saving the .png as .jpg (losing the alpha channel in the process), then saving that .jpg as 24bpp .png, and comparing these two new files. To make the test succeed, I had to remove that `255 - pixelbyte` formula (and also use PreservePixelFormat for the .png so the format isn't changed to 32 BitsPerPixel).

**Comment by br3aker** [comment]
> I tested saving the .png as .jpg (losing the alpha channel in the process), then saving that .jpg as 24bpp .png, and comparing these two new files.

That is expected, you've literally re-encoded same pixel data via `png -> jpg -> png`. Problem with your file is that it's not a JPEG. It uses JPEG file structure and compression but actual color data is not CMYK as expected by a jpeg specification. 

Custom decoding can be supported - I've posted the solution above (I can work on it specifically a bit later, working on other things atm) but it really depends on the decision by @JimBobSquarePants whether it's worth the complexity of exposing internal stuff for specific cases like this one.

**Comment by antonfirsov** [comment]
I don't think that exposing internals for highly specialized use cases is a good direction, and I don't see that there is a way to define a thin, minimalistic API to tweak color channels. We need to be future proof against significant refactors like #1694 or the stuff we need to do if we want to address #1371.

**Comment by br3aker** [comment]
Minimalistic? Very unlikely.
I've actually thought about sort of a proposal for exposing it but for a different cause - re-encoding jpeg block by block like NetVips does it. It's not that significant in terms of refactoring and won't even introduce any breaking changes, the only thing is needed is to expose `SpectralConverter` base class is it's the only thing doing actual conversion from spectral to image:

https://github.com/SixLabors/ImageSharp/blob/5d82124370827dd9d242cfec163b3a670a773cce/src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs#L174-L188

Case-specific converter implementations are the main concern here but they can be flexible IMO.

This and provided topic about specific area decoding are very interesting situations for sure but I'm currently working on jpeg codec performance (get ready for a something huge in the following weeks btw :D) so I can't really deal with it atm but in the future maybe?...

**Comment by antonfirsov** [comment]
I'm closing this as wontfix for now. Opening up Jpeg decoder internals for very special use cases is not where our efforts should go today.
