### ISSUE TITLE
Spectral blocks rounding errors in jpeg encoder

### ISSUE THREAD

**Issue by br3aker** [SixLabors/ImageSharp#1751]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Jpeg encoder spectral block quantization code has rounding errors:
https://github.com/SixLabors/ImageSharp/blob/659daffad916a20a5b62399089c212033c7494e4/src/ImageSharp/Formats/Jpeg/Components/Block8x8F.cs#L484-L497

Let's say all values of aRow are `-0.6` and all values of bRow are `1`:
```
aRow = -0.6
bRow = 1.0

// voff calculation
max(-1, -0.6) = -0.6
min(-0.6, 1) = -0.6
mul(-0.6, 0.5) = -0.3

// division and 'rounding'
div(-0.6, 1) = -0.6
add(-0.6, -0.3) = -0.9
```

Ouput value is `-0.9` while expected rounded value is `-1` and that's a problem because actual encoding code truncates these:
https://github.com/SixLabors/ImageSharp/blob/659daffad916a20a5b62399089c212033c7494e4/src/ImageSharp/Formats/Jpeg/Components/Encoder/HuffmanScanEncoder.cs#L328

And we get `0` instead of `-1`. This error makes current implementation non-complient to the spec. Good news are that only values in range `(-1..1)` are affected by this.

### Steps to Reproduce
None. Changing it to a correct rounding intrinsic `vroundps` for example shows a significant difference in binary size. In the debugger you can actually spot the difference in the `WriteBlock` call values.

**Comment by br3aker** [comment]
Same problem for automatic vectorization `Vector4` fallback code:
https://github.com/SixLabors/ImageSharp/blob/2b85b553f34d6ebf8ded1b390da4e9231a5e4d28/src/ImageSharp/Formats/Jpeg/Components/Block8x8F.cs#L521-L531

Sign must be multiplied by `-1` or `1`, `Clamp` return **any** value between `-1` and `1`.

**Comment by JimBobSquarePants** [comment]
You absolutely rock mate. 🤘
