### ISSUE TITLE
Revise how constant SIMD vectors are defined

### ISSUE THREAD

**Issue by gfoidl** [SixLabors/ImageSharp#1762]
Starting with .NET 5 the JIT emits code to read constant SIMD vectors from the data section which gives nice machine code and some related advantages like the ones listed in https://github.com/SixLabors/ImageSharp/pull/1761#discussion_r708063156.
See also https://github.com/dotnet/runtime/issues/44115 for more context on that issue.

But changing the usage of constant vectors to the "inline variant" will regress pre .NET 5 targets, thus it seems best to keep current code with `static readonly`s, and update to the inline variant once .NET Core 3.1 will go out of support on [3rd Dec 2022](https://dotnet.microsoft.com/platform/support/policy) (the purpose of this issue is to have a remainder for that task).

**Comment by antonfirsov** [comment]
3rd Dec 2022 is pretty far, ideally we would release ImageSharp 3.0 before that, and personally I wouldn't remove .NET Core 3.1 without bumping the major version, so I'm afraid it's not anything for the near future.

Would an inclined property be equivalent of "inline vector create"? Can we do a trick like the following?

```C#
#if NET5_OR_NEWER
private static Vector256<float> Constant =>  Vector256.Create(0.707106781f);
#else
private static readonly  Vector256<float> Constant = Vector256.Create(0.707106781f);
#endif
```

I would only do it if there is measurable benefit justifying the increased complexity.

**Comment by gfoidl** [comment]
The trick [seems to work](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAJI8ovLrl5hcAbhr0mrTj36CRGMRKm4WADQAcSOdXkBmJqQYBhBjQDeNBk4YAHMQDdsGGIqQMAajBgGNCkAKxIADwAZgA2EF4AfNYQEhjYPAwAvMkBQSFQ4UgsVrBeMAAUdCwA7HQ15HRINfrk0QCUxs621N3E5oHBoREx8UkMALIVgwVFowkYydjtPd0Ovd3OxDUMAILuCCy7ACbHFdhoKWkZGJ2OzgC+907PTAP5w1FxC8kT5NMfQojb7jZavdabLY7faHE5nC55IZA4qlGDlKq1eqNZqtDp3DZOJ7UB5AA==) (at least for simple cases, where it's easy for the JIT to inline the property).

But, similar as you wrote, this makes the code awful to read. So I wouldn't do this now and keep the code that works for .NET Core 3.1 and .NET 5 onwards.
Once .NET 3.1 support will be dropped, this issue should be addressed in a batch-change. Code remains clean now and then.

> wouldn't remove .NET Core 3.1 support without bumping ImageSharp's major version, so I'm afraid it's not anything for the near future.

Agree.

**Comment by br3aker** [comment]
> I would only do it if there is measurable benefit justifying the increased complexity.

There's no benefit, at least in microbenchmarking: https://github.com/SixLabors/ImageSharp/pull/1761#discussion_r707769845.
While this does indeed produce better code it won't really change anything globally so I guess waiting for the end of core 3.1 is the way to go.

**Comment by JimBobSquarePants** [comment]
We're .NET 6 now so if someone wants to update the code to reflect the new pattern you have my blessing.

**Comment by gfoidl** [comment]
I can look into this next week.

**Comment by JimBobSquarePants** [comment]
Awesome @gfoidl thanks!
