### ISSUE TITLE
WebP: Missing features

### ISSUE THREAD

**Issue by brianpopow** [SixLabors/ImageSharp#1802]
### Description

This is a tracking issue for missing webp features.
The following features for webp are still missing.

- ~Decode animated webp images.~ done with #1985
- ~Encode animated webp images.
- ~Decode and store XMP profile.~ done with #1918
- ~Encode Alpha channel of Lossy images with the lossless encoder and store it in `ALPH` chunk.~ done in #1971

Any help from the community would be highly appreciated.

**Comment by JimBobSquarePants** [comment]
@bytehydrant Do you still have your fork with the in-progress animation support?

We're in a good place now to continue working against. https://github.com/SixLabors/ImageSharp/issues/121#issuecomment-890502421

**Comment by bytehydrant** [comment]
@JimBobSquarePants, sorry for the (yikes) 3-month delay in response. Apparently, I had notifications turned off and didn't see this 'til just now. Yeah, the fork linked from my original post is still there. I've not touched it since then.

**Comment by JimBobSquarePants** [comment]
No worries  @bytehydrant , Thanks for getting back to me. 

@brianpopow has recently opened a PR for supporting decoding animated Webp in #1985 It's be really useful to us if you could cast an eye over that code and do a review. Thanks!

**Comment by JimBobSquarePants** [comment]
Fixed with #2569
