### ISSUE TITLE
ImageSharp is slow to rotate an image

### ISSUE THREAD

**Issue by Metritutus** [SixLabors/ImageSharp#1809]
### Description

When rotating an image in ImageSharp, if the Visual Studio debugger is attached it takes a good 20-30 seconds for the rotate operation to occur.  If the debugger is not attached it takes 2-3 seconds.  Building for Debug or Release build makes little difference (the release build is _slightly_ faster but still takes 20+ seconds).

In addition, even when running without the debugger, System.Drawing out-performs it by a good second or two, although that is a bit less pressing than the experience with the debugger being attached.

I am unsure if I have done something fundamentally wrong in my usage of ImageSharp here or if this is a bug of some kind.

### Steps to Reproduce
I have created a repository demonstrating the issue [here](https://github.com/Metritutus/ImageSharpRotateTest001).

I have also included a method in there that uses System.Drawing for performance comparison purposes.

Run the project and you can observe the output.

### System Configuration

- SixLabors.ImageSharp version: 1.0.4
- Environment: Windows 10 Version 21H1 (OS Build 19043.1288)
- .NET version: .NET Core 3.1.
- Additional information: Running under Visual Studio 2019 Version 16.11.5.

**Comment by JimBobSquarePants** [comment]
They're not doing remotely the same operation.

Given your input image and sample [repository code](https://github.com/Metritutus/ImageSharpRotateTest001/blob/2d2b2d7e385362ec5dd43c0cac55f1fd7a2e787e/Program.cs).

![TestImage](https://user-images.githubusercontent.com/385879/140766480-d91d8dc5-1485-41db-8af1-49c6c9adb541.png)

ImageSharp is rotating the image using a high quality (bicubic) algorithm ensuring that the canvas size is updated to contain the rotated input. If you don't care much about quality you can always pass a different `IResampler` type like `KnownResamplers.NearestNeighbor` or `KnownResamplers.Triangle` 

![is](https://user-images.githubusercontent.com/385879/140766486-bf49463b-1dfb-456e-b77b-32f3de91a96c.png)

System.Drawing is drawing a section of the rotated image over the top of the input using the default low quality `InterpolationMode`. 

![sd](https://user-images.githubusercontent.com/385879/140766493-1ccb78f6-14d9-492f-b97b-e0a3ac6d780b.png)

Simply increasing the quality halves the performance with System.Drawing despite it doing the wrong thing.

>if the Visual Studio debugger is attached it takes a good 20-30 seconds for the rotate operation to occur

TBH I don't have a clue what you mean by this.

**Comment by Metritutus** [comment]
Ack, apologies, I completely missed the typo in `RotateImageWithSystemDrawing()`, causing it to overlay the images on rotate.  I've fixed that now.  It was never meant to be doing that and I evidently slipped when I added the `System.Drawing` method for comparison purposes.

> TBH I don't have a clue what you mean by this.

This is the primary reason I opened the case as it makes the debugging experience extremely painful.

It's exactly as I stated.  If I run it with the debugger attached (eg running the example project by pressing F5 or by clicking `Debug > Start Debugging`) it takes significantly longer to run than without the debugger being attached (eg running the example project by pressing CTRL+F5 or by clicking `Debug > Start Without Debugging`).

Output with the debugger attached:

```
RotateImageWithImageSharp()

Initialising input stream.
Input stream initialised in 00:00:00.0001798

Loading image.
Image loaded in 00:00:01.3846118

Rotating.
Rotation completed in 00:00:24.3354831

Saving as png to stream.
Save completed in 00:00:04.0281090

RotateImageWithImageSharp() completed in 00:00:29.7870931


RotateImageWithSystemDrawing()

Initialising input stream.
Input stream initialised in 00:00:00.0000537

Loading image.
Image loaded in 00:00:00.0637077

Creating bitmap.
Bitmap created in 00:00:00.0122137

Creating graphics.
Graphics created in 00:00:00.0009319

Rotating.
Rotation completed in 00:00:00.7298446

Saving as png to stream.
Save completed in 00:00:00.1744602

RotateImageWithSystemDrawing() completed in 00:00:01.0301476

Done.
```

Without the debugger attached:

```
RotateImageWithImageSharp()

Initialising input stream.
Input stream initialised in 00:00:00.0000556

Loading image.
Image loaded in 00:00:00.2171218

Rotating.
Rotation completed in 00:00:01.6716129

Saving as png to stream.
Save completed in 00:00:00.6247880

RotateImageWithImageSharp() completed in 00:00:02.5181581


RotateImageWithSystemDrawing()

Initialising input stream.
Input stream initialised in 00:00:00.0000673

Loading image.
Image loaded in 00:00:00.0578880

Creating bitmap.
Bitmap created in 00:00:00.0138647

Creating graphics.
Graphics created in 00:00:00.0005810

Rotating.
Rotation completed in 00:00:00.5862030

Saving as png to stream.
Save completed in 00:00:00.1402935

RotateImageWithSystemDrawing() completed in 00:00:00.8084714

Done.
```


Now, onto your more interesting point about the resamplers.   There do seem to be quite a few of these.  The default one is apparently `Bicubic`.  I have however run a Debug build of the project, looping through each of the resamplers (I've added this code to a `ResamplersTest` branch in the repo linked in the OP).

I did one run with the debugger attached to this build, and one run without the debugger attached.  The results are below are how long it took for the call to `Rotate()` with each resampler.

|Resampler|With debugger attached|Without debugger attached|
|-----------|----------------------------|------------------------------|
|Bicubic|00:00:20.2482172|00:00:01.8243311|
|Box|00:00:05.5413751|00:00:00.5528809|
|CatmullRom|00:00:19.4087677|00:00:01.6550851|
|Hermite|00:00:18.7555403|00:00:01.6882344|
|Lanczos2|00:00:20.2791139|00:00:02.2982647|
|Lanczos3|00:00:43.3403404|00:00:05.6871547|
|Lanczos5|00:01:55.2951032|00:00:12.5682738|
|Lanczos8|00:04:49.9617270|00:00:31.0004024|
|MitchellNetravali|00:00:19.2922252|00:00:02.0755763|
|NearestNeighbor|00:00:00.9369214|00:00:00.1186665|
|Robidoux|00:00:18.6609934|00:00:02.4191564|
|RobidouxSharp|00:00:18.4930355|00:00:02.1641479|
|Spline|00:00:18.6066660|00:00:02.1197142|
|Triangle|00:00:05.0932789|00:00:00.5644780|
|Welch|00:00:41.9249285|00:00:04.8107053|

I am uncertain why the debugger being attached here makes such a massive difference to the execution time here, and I have not observed this behaviour with any other code.

**Comment by antonfirsov** [comment]
@Metritutus do "With debugger attached" and "Without debugger attached" numbers both from Debug builds with the only difference if debugger is attached or not, or is "Without debugger attached" a run from Release build?

**Comment by Metritutus** [comment]
> @Metritutus do "With debugger attached" and "Without debugger attached" numbers come both from Debug builds with the only difference if debugger is attached or not, or is "Without debugger attached" a run from Release build?

Both numbers come from a Debug build where the only difference is whether the debugger is attached or not.

As I mentioned in the original post however, this behaviour appears to occur with release builds as well.

**Comment by JimBobSquarePants** [comment]
I'm not seeing this in the final preview of VS 2022. Rerunning the code I ran earlier using a Debug build triggered via F5

```
RotateImageWithImageSharp()

Initialising input stream.
Input stream initialised in 00:00:00.0001411

Loading image.
Image loaded in 00:00:00.6756388

Rotating.
Rotation completed in 00:00:04.4081353

Saving as png to stream.
Save completed in 00:00:01.2380619

RotateImageWithImageSharp() completed in 00:00:06.3429436


RotateImageWithSystemDrawing()

Initialising input stream.
Input stream initialised in 00:00:00.0001218

Loading image.
Image loaded in 00:00:00.0974044

Creating graphics.
Graphics created in 00:00:00.0011621

Creating bitmap.
Bitmap created in 00:00:00.0147809

Rotating.
Rotation completed in 00:00:01.0195349

Saving as png to stream.
Save completed in 00:00:00.1478866

RotateImageWithSystemDrawing() completed in 00:00:01.3187314

Done.
```

**Comment by br3aker** [comment]
Benchmarking with a single sample might be a big mistake here. ImageSharp being a pure C# implementation needs to compile a lot of things via JIT before actually executing while System.Drawing most likely relies on C++ implementation of either WIC or GDI (I didn't check their source code). Executing it at least twice or, better variant, using BenchmarkDotNet would produce actual results without JIT noise or some external factors like when CPU have lower frequency due to no actual workload before benchmarking.

**Comment by Metritutus** [comment]
Running under Visual Studio 2022 (Current), it is a lot faster than under Visual Studio 2019.  It's still a little slower with the debugger attached (taking around 7 seconds) to without the debugger being attached (4-5 seconds), but it's much more bearable and also, interestingly, does not seem to max out the CPU when it's processing, unlike under Visual Studio 2019.

I am still perplexed as to what could be causing the slowness on Visual Studio 2019, and may try to debug with the source code from this repository to see if I can observe where the slowdown seemingly is.

> Benchmarking with a single sample might be a big mistake here. ImageSharp being a pure C# implementation needs to compile a lot of things via JIT before actually executing while System.Drawing most likely relies on C++ implementation of either WIC or GDI (I didn't check their source code). Executing it at least twice or, better variant, using BenchmarkDotNet would produce actual results without JIT noise or some external factors like when CPU have lower frequency due to no actual workload before benchmarking.

I have tested it with multiple runs of the same resampler, and experienced the same slow behaviour on each run.  The significant difference between running with and without the debugger being attached seemed self-evident enough that I did not choose to supply multiple times of the same runs, as I felt it wouldn't provide much information of benefit here.

All that said, I've not used BenchmarkDotNet before, so may look into it for future testing.

**Comment by JimBobSquarePants** [comment]
I feel perhaps all this effort is misguided as we’re doing both special or different - It’s normal C# code. 

VS 2022 is clearly doing something different (and better) during debugging but if it’s still an issue I suggest taking it up with Microsoft.

**Comment by antonfirsov** [comment]
I wonder if this has to do something with the ["Just My Code" option](https://docs.microsoft.com/en-us/visualstudio/debugger/just-my-code?view=vs-2022)?

**Comment by Metritutus** [comment]
> I feel perhaps all this effort is misguided as we’re doing both special or different - It’s normal C# code.
> 
> VS 2022 is clearly doing something different (and better) during debugging but if it’s still an issue I suggest taking it up with Microsoft.

The question that I was trying to find the answer to was why ImageSharp was seemingly the only thing obviously affected in this way, at least for what I work with, as I hadn't noticed such extreme slowdowns elsewhere.

> I wonder if this has to do something with the ["Just My Code" option](https://docs.microsoft.com/en-us/visualstudio/debugger/just-my-code?view=vs-2022)?

Unchecking that option sadly did not appear to make any difference.  HOWEVER, whilst looking over the Debugging options, another option caught my eye...

### [Supress JIT optimization on  module load (Managed only)](https://docs.microsoft.com/en-us/visualstudio/debugger/jit-optimization-and-debugging)

It caught my eye that this option was checked!  I suspect I checked it long ago when investigating some other long-forgotten issue.

It's unchecked by default, which is why the new install of Visual Studio 2022 ran fine.  Checking this option in Visual Studio 2022 results in the same slow behaviour.

It seems pretty crazy that JIT optimization suppression had such a massive performance impact here, but I can only assume there's some incredible optimization going on.  This may somewhat relate to what you were talking about before, @br3aker.

Still, problem solved!  Thanks for the input, everyone! 😄

For future readers, if you've happened upon this issue because you're experiencing slow performance when debugging code that uses ImageSharp, double-check that this option isn't checked! 👍
