### ISSUE TITLE
Decode PNG to source stream's pixel type

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#1813]
PNG decoder is not CPU intensive compared to other codecs, but we can save some memory if there is no alpha or if the PNG is grayscale. We can instantiate the `Image<T>` after reading the header chunk depending on `header.ColorType` and `header.BitDepth`.

It would also help preserving the original images precision in case of `header.BitDepth == 16`.

**Comment by JimBobSquarePants** [comment]
Looking at the code it might be best to do it like this. Anything else get complicated quickly. 

In `PngDecoder.Decode[Async]`
`Identify` (skipping metadata)
Call correct `Decode<TPixel>` based upon `PngColorType` returned from `Identify`.

**Comment by tocsoft** [comment]
doing this will confuse users.. they will call `Image.Load()` and then when they try drawing etc then suddenly things wont work as expected.

This would be fine if its opt in, but by default we need to decode into a full feature rich pixel format that doesn't cause confusion and surprise to users... if we are 'broken' (in their eyes) they wont use the product and will tell everyone else to not use it either.

**Comment by JimBobSquarePants** [comment]
@SixLabors/core  I think we're going to need a larger conversation among the group to gain a consensus on what we want the non-generic API to do.

**Comment by antonfirsov** [comment]
I want to optimize for the 90%+ majority who don't do any alpha-sensitive operation. We already delivered a massive `Image != Image<Rgba32>` case with  #1773, and that helped us to [outperform standard SkiaSharp resize](https://github.com/SixLabors/ImageSharp/pull/1730#issuecomment-979286177) in terms of memory footprint, I really don't want to undo it, and I don't see why would be PNG special to deviate

> This would be fine if its opt in

I would better provide an easy, well communicated opt-out setting (Reason: optimize for perf of the 90% users)

```C#
Configuration.Default.ForceAlphaChannelPresence = true;
using var img = Image.Load(...);
img.Mutate(c => c.DrawXyz(....));
```

2.0 should come out with a detailed blogpost & conceptual doc explaining this property, and the main library where alpha can be a concern is Drawing, which is still in alpha.

-----

Another solution would be to make this this fully automatic, meaning that an ImageProcessor could alter the pixel type in a non-generic `Image`, so alpha could magically appear, when an operation needs it. This would require an implementation of the non-generic `Image` with composition over inheritance, and also some tweaks on the ImageProcessor API. This is non-trivial work that may delay the delivery of ImageSharp 2.0 by another month or two, which I believe may hurt as more than making alpha-aware drawing less convenient in certain cases.

I may be wrong, but as far as I'm aware, no other imaging API-s do this. If you load a PNG of 24 bit RGB with System.Drawing or skia, you have to deal with 24 bit pixel data.

**Comment by JimBobSquarePants** [comment]
> I may be wrong, but as far as I'm aware, no other imaging API-s do this. If you load a PNG of 24 bit RGB with System.Drawing or skia, you have to deal with 24 bit pixel data.

I don’t believe you are wrong here. That’s my understanding of how all the libraries I’ve researched work. 

The closest I’ve seen otherwise is WPF with `BitmapCreateOptions.PreservePixelFormat` but that’s opt in, not out.

I don’t believe we need any configuration additional properties though. We already have mechanisms to ensure alpha component preservation - The generic API. 

As a side note the generic API was always supposed to be the primary API. I’d like to keep an emphasis there. Non-generic should be considered a fallback.

**Comment by JimBobSquarePants** [comment]
>We should make `Image.Load<Rgba32>(...)` the default form in all Drawing code snippets, or other examples where alpha could matter. We can place a short comment in those samples, explaining why the alpha channel has significance, and we can extend non-generic `Image.Load` docs with a disclaimer "Depending on the source format, this may load an image without an alpha channel." or similar.
>
>But I don't think we should roll back our code samples, and start communicating the non-generic overload as secondary, that removes big portion of the value added here.

I agree. I just want to make it clear that we do not sacrifice the design of the generic API at any point for the non-generic one, nor pad out the API to compensate for a lack of functionality in the non-generic variant. Non-generic is strictly entry-level functionality.

**Comment by antonfirsov** [comment]
> nor pad out the API 

That also seems cleaner and simpler to me. We should improve our docs and our examples to warn users about the difference between the generic and the non-generic Load, and we should also mention this change in the 2.0 blog post. Alternative suggestions in https://github.com/SixLabors/ImageSharp/issues/1813#issuecomment-982668272 are here for completeness.
