### ISSUE TITLE
Do we really need exception-wrapping in ImageProcessingContext<T>.Execute() ?

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#1827]
I'm not sure about the benefits of the following general exception wrapping:

https://github.com/SixLabors/ImageSharp/blob/a39fe4c07c10a5c4e824f86f2fc5a979692e7a7e/src/ImageSharp/Processing/Processors/ImageProcessor%7BTPixel%7D.cs#L48-L68

To me it looks like what it would do most of the cases is to wrap processor implementation bugs making it harder to reason about  stack traces coming from Release builds. There are no tests asserting `ImageProcessingException` on invalid setup. Are there any valid cases for re-wrapping exceptions? Shouldn't we better throw right from the processor implementation code if something went wrong? If it happens because of wrong arguments, should we better throw `ArgumentExecption` earlier?

If we no longer thing it's the right thing to do, let's remove it for 2.0!

**Comment by JimBobSquarePants** [comment]
I can’t even remember why we did this tbh. You’re right though, makes stack traces much harder to follow and when you have those odd (and thankfully increasingly rare) release only issues, a chore to disable/enable. 

I’m more than happy to see it gone.
