### ISSUE TITLE
Missing target value when attempting to build Benchmarks

### ISSUE THREAD

**Issue by Dr-Kristau** [SixLabors/ImageSharp#1832]
### Description
I receive an error when running ImageSharp/tests/ImageSharp.Benchmarks/benchmark.sh on Ubuntu 20.04.3.

### Steps to Reproduce
![Screenshot from 2021-11-16 17-15-09](https://user-images.githubusercontent.com/32355001/142023410-6d9e6913-9dc7-4279-8d94-97b3a9738a27.png)

### System Configuration
Ubuntu 20.04.3
dotnet version 5.0.403
As of writing, the head revision of ImageSharp's master branch

**Comment by antonfirsov** [comment]
That script is terribly outdated, and I'm not sure why it was necessary to add it back in #117.

https://github.com/SixLabors/ImageSharp/blob/29ea6af0b8bbf7bdb480b4c4ad0655440c12a6de/tests/ImageSharp.Benchmarks/benchmark.sh#L1-L7

Ideally we should be able to run them without any script. What happens on good old `dotnet run -c Release -f net5.0` ?

**Comment by Dr-Kristau** [comment]
> What happens on good old `dotnet run -c Release -f net5.0` ?

Yes, that works just fine, thank you.
