### ISSUE TITLE
Too slow loading image

### ISSUE THREAD

**Issue by amyboose** [SixLabors/ImageSharp#1843]
Hello
I'm so confused that my little image loading a lot of time (1.5 sec).
My code:
`var hashAlgorithm = new AverageHash();
ulong hash1 = 0;
using (var image1 = SixLabors.ImageSharp.Image.Load<Rgba32>(imageBytes1))
{
    hash1 = hashAlgorithm.Hash(image1);
}`

My image:
https://drive.google.com/file/d/1eeZqoDzUOaZZHu6cpK-Jx7Mf2xh9XS_r/view?usp=sharing

My OS is windows 10. Package version is 1.04

**Comment by br3aker** [comment]
How execution time was measured? Did you measure only `Image.Load(...)` or entire code you've provided?

**Comment by JimBobSquarePants** [comment]
Hey @amyboose we have an issue template which we explicitly require in order to triage issues. Can you please resubmit your issue using that template.

**Comment by JimBobSquarePants** [comment]
I'm closing this due to a lack of information and response.
