### ISSUE TITLE
Do we need public setter for Configuration.ImageFormatManager?

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#1850]
Currently it's not guarded against setting it to `null`:

https://github.com/SixLabors/ImageSharp/blob/e11f318144d91bac6ed84c6b08e81c6d8850f292/src/ImageSharp/Configuration.cs#L114-L117

I'm wondering if we need the public setter at all? No test cases exercise it, every call site seems to modify the existing collection.

**Comment by JimBobSquarePants** [comment]
There doesn't seem to be a way to clear the collection. There's only `ClearImageFormatDetectors` which doesn't actually clear the `ConcurrentBag` and replaces it with a new instance instead.

This is an odd class....

**Comment by antonfirsov** [comment]
We should attempt to clean it up. 2.0 is a good chance to introduce breaking changes if necessary.

**Comment by JimBobSquarePants** [comment]
Yeah I think we definitely should.
