### ISSUE TITLE
Loading webp image throws UnknownImageFormatException

### ISSUE THREAD

**Issue by kobruleht** [SixLabors/ImageSharp#1855]
Loading webp image from https://1drv.ms/u/s!Ag6cTEBIEfFpinCDaUAj87FrAixs  using

`Image.Load
`
throws 

> SixLabors.ImageSharp.UnknownImageFormatException: Image cannot be loaded. Available decoders:
>  - TGA : TgaDecoder
>  - GIF : GifDecoder
>  - JPEG : JpegDecoder
>  - PNG : PngDecoder
>  - BMP : BmpDecoder
> 
>    at SixLabors.ImageSharp.Image.Load[TPixel](Configuration configuration, Stream stream, IImageFormat& format)
>    at SixLabors.ImageSharp.Image.Load[TPixel](Configuration configuration, Byte[] data)
> 

### Steps to Reproduce

```
byte[] source = <image from https://1drv.ms/u/s!Ag6cTEBIEfFpinCDaUAj87FrAixs>;
Image.Load(source);

```
- ImageSharp version:

1.0.4

- Environment (Operating system, version and so on):

Windows 10

- .NET Framework version:

6.0

**Comment by brianpopow** [comment]
This image is actually a webp image and not a png, but the good news is: we support that now. You can try our nightly build from the [MyGet Feed](https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp)

**Comment by kobruleht** [comment]
How to get it from regular nuget feed ?

**Comment by brianpopow** [comment]
You will have to wait for the release of version `2.0` of ImageSharp, which is not far away from now (but I cannot give an ETA).

**Comment by cresadu** [comment]
@kobruleht : you can add the following URL inside Visual Studio in "Packages Sources" to load it like a normal Nuget Package:

https://www.myget.org/F/sixlabors/

I've tested it and it worked!
Could convert my webP Files 👍

**Comment by kobruleht** [comment]
I prefer to load it from nuget. When it is available in nuget ?
