### ISSUE TITLE
Unable to find SixLabors.ImageSharp.Drawing in Blazor with .NET 6

### ISSUE THREAD

**Issue by bearsystems** [SixLabors/ImageSharp#1897]
Good Afternoon!

     I created a rather complex Blazor Server App using HTML5 and realized that I need to draw everything on the server side!  While technically System.Drawing.Common could solve this issue, its performance is terrible and comes with its own large set of issues.

     I am looking forward to using your library - thank you so much for providing it - but I cannot find the SixLabors.ImageSharp.Drawing library.  I used Nuget to obtain SixLabors.ImageSharp (v  1.0.4);  SixLabors.ImageSharp.Web (v 1.0.4); and MC.SixLabors.ImageSharp.Extensions (v 1.0.0) but none of those provide the Drawing class.  This is preventing me from using the IBrush and IPen classes as part of the GraphicsPaths example you provide.

     I am running Visual Studio 2021 with .NET 6.0.

     Thank you for your help!

**Comment by antonfirsov** [comment]
@bearsystems Drawing library is in preview, you need to make sure you include prerelease packages. In Visual Studio, this means setting a checkbox:
https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages#installing-and-updating-pre-release-packages
