### ISSUE TITLE
Jpeg unhandled System.ArgumentException with malformed image

### ISSUE THREAD

**Issue by br3aker** [SixLabors/ImageSharp#1900]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I've modified valid image from repo image base with actually itu spec complient numbers. I've changed component count from SOF segment from 3 to 255 and modified marker 'length' accordingly. Current master throws `System.ArgumentException`:

```
Unhandled exception. System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoderCore.ProcessStartOfFrameMarker(BufferedReadStream stream, Int32 remaining, JpegFileMarker& frameMarker, Boolean metadataOnly) in D:\Programming\C#\ImageSharp\src\ImageSharp\Formats\Jpeg\JpegDecoderCore.cs:line 1013
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoderCore.ParseStream(BufferedReadStream stream, HuffmanScanDecoder scanDecoder, CancellationToken cancellationToken) in D:\Programming\C#\ImageSharp\src\ImageSharp\Formats\Jpeg\JpegDecoderCore.cs:line 312
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoderCore.Decode[TPixel](BufferedReadStream stream, CancellationToken cancellationToken) in D:\Programming\C#\ImageSharp\src\ImageSharp\Formats\Jpeg\JpegDecoderCore.cs:line 183
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, Func`3 largeImageExceptionFactory) in D:\Programming\C#\ImageSharp\src\ImageSharp\Formats\ImageDecoderUtilities.cs:line 162
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream) in D:\Programming\C#\ImageSharp\src\ImageSharp\Formats\ImageDecoderUtilities.cs:line 149
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoder.Decode[TPixel](Configuration configuration, Stream stream) in D:\Programming\C#\ImageSharp\src\ImageSharp\Formats\Jpeg\JpegDecoder.cs:line 26

// Image.Load call site
```

`libjpeg-turbo` output: 
```
Corrupt JPEG data: 3016 extraneous bytes before marker 0xd9
Invalid JPEG file structure: missing SOS marker
```

### Steps to Reproduce
`Image.Load(...)` on this image:

[jpeg_components255.zip](https://github.com/SixLabors/ImageSharp/files/7734582/jpeg_components255.zip)

### How to fix
Source of the problem is that 255 component SOF marker would occupy `8 + 255 * 3 == 8 + 765` bytes, 2 of them are `0xFF SOFn` marker bytes, 6 of them are 'constant sized' and are read as 6 bytes package. Remaining 765 bytes are variable and depend on component count which is 255 in this case, they are read into intermediate buffer:
https://github.com/SixLabors/ImageSharp/blob/ecd3db2271c8c13f7ce20266191243ff2ef89985/src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs#L39

in one go:
https://github.com/SixLabors/ImageSharp/blob/ecd3db2271c8c13f7ce20266191243ff2ef89985/src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs#L1013

So decoder writes 765 bytes into 128 byte-sized buffer. We can enlarge buffer to handle up to 255 components but do we need to? I'm yet to see a JPEG color space with 255 dimensions. And even if such color space exists - right now decoder can handle up to 4 components color spaces (CMYK) so should we bother?

**Comment by antonfirsov** [comment]
If I get it right, the bug is that we throw `ArgumentException` instead of `InvalidImageContentException`. @br3aker is this correct?

**Comment by br3aker** [comment]
Technically, specification doesn't say anything about color spaces:
>The interchange format does not specify a complete coded image representation. Application-dependent information,
e.g. colour space, is outside the scope of this Specification,

They've decided to save color channel count to be saved into single `byte` without any constraints. Here's the SOF header segment structure, **Nf** variable is the number of channels in the image:

![image](https://user-images.githubusercontent.com/20967409/148073287-262e6c0c-3ba9-4591-af43-ae5d54cb1a83.png)

Maybe back in the day jpeg decided to give some flexibility allowing image to contain up to 255 channels. But we, libjpeg/libjpeg-turbo and most likely any other jpeg decoder on the planet only have 1/3/4 color channels converters. In fact, we even throw if image have `2` or `>4` channels:

https://github.com/SixLabors/ImageSharp/blob/e20410c412620537ca57126a6f3211458192d25c/src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs#L475

The only problem right now as we read possibly more bytes (255 * 3) than our buffer can handle (128) thus `System.ArgumentException` from some .net internal calls. @antonfirsov we should throw but not 'InvalidImageContent' imo, it's valid according to the spec, it's just not support by ImageSharp. Maybe one day we'll get 5 channel color, in fact, we already have [2 channel color space](https://en.wikipedia.org/wiki/RG_color_space). Yes, nobody uses it but it still possible and jpeg format allows that.

My take is that we should throw `NotSupportedException` either manually from SOF marker parsing method before reading the stream here:

https://github.com/SixLabors/ImageSharp/blob/e20410c412620537ca57126a6f3211458192d25c/src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs#L1012-L1013

Or move this code from end of the SOF parser method right before stream read from above because it checks for 1/3/4 color channels:
https://github.com/SixLabors/ImageSharp/blob/e20410c412620537ca57126a6f3211458192d25c/src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs#L1072-L1073

**Comment by antonfirsov** [comment]
`NotSupportedException` should is good enough for me, since seems to more or less match our current documentation:

https://github.com/SixLabors/ImageSharp/blob/e20410c412620537ca57126a6f3211458192d25c/src/ImageSharp/Image.FromStream.cs#L272-L280

Though I think it would be better if all exceptions thrown based on the stream content would derive from the same base type. I wonder which are other places throwing `NotSupportedException`?

**Comment by br3aker** [comment]
Didn't thought about actual exception handling before writing reply. Yep, one base exception is better in terms of quality of life for the end users.

Jpeg throws `NotSupportedExceptions` for any non-supported but valid headers:
https://github.com/SixLabors/ImageSharp/blob/39f37d09af1edb921a13b68cb31aeec809476df7/src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs#L315-L335

We can alter and revise all of the `InvalidImageContent` occurances but it's too much work for actually no gain. I believe most of the users don't care if we throw either `Invalid` or `NotSupported` exceptions, all they care is the actual exception occurance:

```cs
try { /* Load image */ }
// okay, we have unparsable image - log something or even do some UI stuff
catch(InvalidImageContentException ex) {...}
// yet another type of unparsable image, same semantics as above so is it worth it?
catch(NotSupportedException ex) {...} 
```

**Comment by JimBobSquarePants** [comment]
`InvalidImageContentException` has a very specific use case (_malformed or non spec_) so `NotSupportedException` is definitely the best approach here. I'd leave everything else untouched for now.
