### ISSUE TITLE
ImageProcessingException when resizing an image of similar size to the target.

### ISSUE THREAD

**Issue by maxvoxel8** [SixLabors/ImageSharp#1911]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Calling the transform processor on an image sometimes throws an exception:

```
SixLabors.ImageSharp.ImageProcessingException
  HResult=0x80131500
  Message=An error occurred when processing the image using AffineTransformProcessor`1. See the inner exception for more detail.
  Source=SixLabors.ImageSharp
  StackTrace:
   at SixLabors.ImageSharp.Processing.Processors.CloningImageProcessor`1.SixLabors.ImageSharp.Processing.Processors.ICloningImageProcessor<TPixel>.CloneAndExecute()
   at SixLabors.ImageSharp.Processing.Processors.CloningImageProcessor`1.SixLabors.ImageSharp.Processing.Processors.IImageProcessor<TPixel>.Execute()
   at SixLabors.ImageSharp.Processing.DefaultImageProcessorContext`1.ApplyProcessor(IImageProcessor processor, Rectangle rectangle)
   at SixLabors.ImageSharp.Processing.TransformExtensions.Transform(IImageProcessingContext ctx, Rectangle sourceRectangle, Matrix3x2 transform, Size targetDimensions, IResampler sampler)
   at VulcanTest.ImageOperationTest.<>c.<TestImageCrop>b__8_0(IImageProcessingContext x) in C:\Users\MaxE\source\repos\Vulcan\VulcanTest\ImageOperationTest.cs:line 485
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Configuration configuration, Action`1 operation)
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Action`1 operation)
   at VulcanTest.ImageOperationTest.TestImageCrop() in C:\Users\MaxE\source\repos\Vulcan\VulcanTest\ImageOperationTest.cs:line 483

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ArgumentOutOfRangeException: Parameter "Destination buffer too short!" (System.Int64) must be less than or equal to 14414946, was 14419587 (Parameter 'Destination buffer too short!')
```

I have only seen it happen with this combination of inputs, it seems to be caused by the image being very slightly larger than the destination rectangle.

### Steps to Reproduce

```C#
var image = new Image<Rgba32>(Configuration.Default, 3107, 4641, new Rgba32(30, 35, 36));

image.Metadata.ResolutionUnits = PixelResolutionUnit.PixelsPerInch;
image.Metadata.VerticalResolution = 300;
image.Metadata.HorizontalResolution = 300;

image.Mutate<Rgba32>(x => {
  var imageTransform = new Matrix3x2(1, 0, 0, 1, 0, 0);
  x = x.Transform(new SixLabors.ImageSharp.Rectangle(0, 0, 3106, 4641), imageTransform, new SixLabors.ImageSharp.Size(3106, 4641), new LanczosResampler());
});
```

### System Configuration
- ImageSharp version: >= 1.0.2
- Other ImageSharp packages and versions: N/A
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: 4.6.2
- Additional information:

**Comment by JimBobSquarePants** [comment]
Hi @maxvoxel8 

v1.0.2 is an old version (current NuGet release is v1.0.4). Can you please confirm that the issue still exists following upgrade.

**Comment by maxvoxel8** [comment]
Yes, I'm running on the 2.0 nightly now and it still exists.

**Comment by JimBobSquarePants** [comment]
Perfect, thanks!

**Comment by JimBobSquarePants** [comment]
@maxvoxel8 A side question.... Why are you using `Transform` over `Resize` to scale images? The latter is much faster and will likely yield a better quality result.

**Comment by JimBobSquarePants** [comment]
`new LanczosResampler()` is wrong btw. The struct requires a parameter. You should supply that parameter or use one of the `KnownResampler` enumerations.

**Comment by maxvoxel8** [comment]
In reality, the transform has the option of having a rotation and a translation as well, but in this case they were both 0.

I don't know why I wrote LanczosResampler in the sample, it must have been a typo. I use `new BoxResampler()` in my actual code.

**Comment by JimBobSquarePants** [comment]
I was able to trigger the exact exception chain you published using the identity matrix. (_The same as you provided just using the static instance_) 

This triggers a copy operation from source to destination buffer since there's no transform to calculate, the exception is caused because the destination buffer is smaller than the source. 

Now if your matrix is not identity (e.g. rotate) and you can prove that an exception is thrown then there is a different issue (_with different stacktrace_) which you'd need to report.

**Comment by maxvoxel8** [comment]
That makes a lot of sense. It must be a special case for the identity matrix.
