### ISSUE TITLE
Exif metadata for "User Comment" maybe encoded incorrectly?

### ISSUE THREAD

**Issue by danpetitt** [SixLabors/ImageSharp#1919]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I believe, when writing out a "User Comment" Exif tag, the tag is an 'undefined' type which means, according to the spec, that the encoding type should be written out in the first 8 bytes of the value data.

This is seen if you set the metadata and use https://www.metadata2go.com/ to verify the data, it will produce a warning for the "User Comment" tag saying "Invalid EXIF text encoding for UserComment".

If you then edit the metadata on the site and download you will get the additional 8 bytes written before the tag text area as defined in the spec and it then validates okay.

Refer to the specification at https://www.cipa.jp/std/documents/e/DC-008-2012_E.pdf on page 46 for user comment.

I couldnt see anywhere where it states this is optional; but I may be misreading things here so apologies.

On another site (https://www.exiv2.org/tags.html) it states that this may be applicable to other tags which are also of the 'undefined' or 'comment' type:
> The string encoding is defined using the same scheme as UserComment
* GPSProcessingMethod
* GPSAreaInformation

### Steps to Reproduce
```c#
using( var image = Image.Load( "metadata.jpg" ) )
{
  var exif = new ExifProfile();
  exif.SetValue<byte[]>( ExifTag.XPAuthor, Encoding.GetEncoding( "UCS-2" ).GetBytes( "Dan Petitt" ) );
  exif.SetValue<byte[]>( ExifTag.XPTitle, Encoding.GetEncoding( "UCS-2" ).GetBytes( "A bit of test metadata for image title" ) );
  exif.SetValue<byte[]>( ExifTag.UserComment, Encoding.ASCII.GetBytes( "A bit of normal comment text" ) ); // Possibly needs to a parameter to specify what encoding is being used to write the bytes out perhaps?
  image.Metadata.ExifProfile = exif;

  image.Save( "metadata-exif.jpg" );
}
```

`metadata.jpg` shows the file written out by ImageSharp:
![metadata](https://user-images.githubusercontent.com/1733292/147883725-a8e24d8b-7b45-4289-9008-212692346927.jpg)

The binary dump of the file showing no 8 byte prefix to the value data...
![image](https://user-images.githubusercontent.com/1733292/147883618-2e8209cb-753f-4941-bdb8-8afd85ac94d3.png)

`metadata-fixed.jpg` shows the file written out by metadata2go:
![metadata-fixed](https://user-images.githubusercontent.com/1733292/147883720-b5b25b24-3803-4f6b-9e3e-bebaddcfe6a8.jpg)

The binary dump of the fixed file showing the new 8 byte ASCII prefix:
![image](https://user-images.githubusercontent.com/1733292/147883698-3bdcc25a-e9ab-4751-a746-3da805d59ffc.png)

### System Configuration
- ImageSharp version: v1.0.4
- Environment (Operating system, version and so on): Windows 11, Visual Studio 2022
- .NET Framework version: .NET 6
- Additional information:

**Comment by JimBobSquarePants** [comment]
Thanks @danpetitt for such a detailed issue report. Much appreciated!

Yep, that certainly looks like an issue. I had a quick read of the relevant parts of the specification you highlighted and your findings looks correct to me. We should prioritize getting this fixed for V2.

@dlemstra this will interest you also I'm sure.

**Comment by IldarKhayrutdinov** [comment]
@danpetitt  You are create tags of a `byte` type:
`exif.SetValue<byte[]>`
So the dump viewer displays those bytes as ascii text.

By [tiff specification](https://www.awaresystems.be/imaging/tiff/specification/TIFF6.pdf) (page 15):
> 2 = ASCII 8-bit byte that contains a 7-bit ASCII code; the last byte
must be NUL (binary zero).

There are encodings problems on practice: https://stackoverflow.com/a/19284524/3189289
We need to consider the ability to create text type tags with an arbitrary encoding.

At the moment the strings are converted to bytes with `UTF8` encoding, it's required to be corrected:
https://github.com/SixLabors/ImageSharp/blob/e20410c412620537ca57126a6f3211458192d25c/src/ImageSharp/Metadata/Profiles/Exif/ExifWriter.cs#L369-L370

**Comment by danpetitt** [comment]
I dot not think, if I follow you correctly, that this is the problem.

The problem I report is specifically to do with the "UserComment" tag (and GPSProcessingMethod,  GPSAreaInformation tags  which follow the same scheme) which states that  the first 8 bytes must be the encoding signature which was used to encode the data.  Without these first  8 bytes, its invalid, but also cannot be decoded reliably by any readers ... as a decoder, someone can probably assume or try UTF8 if these 8 bytes do not match any of the signatures in Table 9 I guess, but its still invalid without.

![image](https://user-images.githubusercontent.com/1733292/148083554-b4c7b704-aa04-4f91-9f44-57fbe1ebcf5c.png)

I would suggest you receive a `string` generic and encode as Unicode then write the unicode signature for these fields. This should cover most cases and avoids having to create a new interface for the API user to specify the encoding of the byte array passed to ImageSharp.

**Comment by IldarKhayrutdinov** [comment]
@danpetitt  thanks for the explanation. I understand, it turns out we need to implement writing strings as in these tags
[UserComment](https://www.awaresystems.be/imaging/tiff/tifftags/privateifd/exif/usercomment.html)
[GPSProcessingMethod](https://www.awaresystems.be/imaging/tiff/tifftags/privateifd/gps/gpsprocessingmethod.html)  
[GPSAreaInformation](https://www.awaresystems.be/imaging/tiff/tifftags/privateifd/gps/gpsareainformation.html)

**Comment by danpetitt** [comment]
Yeah, I think thats my understanding of the spec. Thanks for your patience ![image](https://user-images.githubusercontent.com/1733292/148086520-ad4f219b-440a-4c7b-b347-987d17e04d59.png)

**Comment by IldarKhayrutdinov** [comment]
Draft PR: https://github.com/SixLabors/ImageSharp/pull/1935

**Comment by antonfirsov** [comment]
#1935 is merged, so I assume this is fixed.
