### ISSUE TITLE
Improve Jpeg Decoder

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#192]
Removed all my previous notes here, because my new investigations outdated them. 

This point should be replaced by a WIP PR. (Continuing #274 or open a new one for a clean start.) 

I'll try to put my notes here later.

**Comment by JimBobSquarePants** [comment]
Here's a list of additional issues related to jpeg that we would like to get help with.

https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aopen+label%3Aarea%3Aformats%3Ajpeg

**Comment by antonfirsov** [comment]
@FireNero thanks for the refactor help you done here!
We still need to implement that [MemoryManager](https://gist.github.com/antonfirsov/9a540359ffcbd0a4fc15ab921861f195) to provide more control over the ArrayPool behaviour, but it's not a Jpeg-specific task to implement it.

It would be nice to find people to help with the other (harder) points or the smaller issues [from this list](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aopen+label%3Aarea%3Aformats%3Ajpeg).

**Comment by FireNero** [comment]
@antonfirsov np, I'm glad to help!
I'm also going to help you with other things soon (just have a lack of time right now).

**Comment by antonfirsov** [comment]
I started to work on the generic compression stuff. See:
- [PackedBuffer](https://github.com/JimBobSquarePants/ImageSharp/blob/feature/compressed-buffer/src/ImageSharp/Memory/PackedBuffer.cs)
- [CompressedBuffer](https://github.com/JimBobSquarePants/ImageSharp/blob/feature/compressed-buffer/src/ImageSharp/Memory/CompressedBuffer.cs)
- [CompressedBufferTests](https://github.com/JimBobSquarePants/ImageSharp/blob/feature/compressed-buffer/tests/ImageSharp.Tests/Common/CompressedBufferTests.cs)

My plan is to store the `JpegDecoderCore.DecodedBlocks` in a `CompressedBuffer` when `PerformanceCharacteristic == LowestMemory` and use [DummyPackedBuffer](https://github.com/JimBobSquarePants/ImageSharp/blob/feature/compressed-buffer/src/ImageSharp/Memory/DummyPackedBuffer.cs) otherwise.

**Comment by antonfirsov** [comment]
Closing this in favor of #298.
