### ISSUE TITLE
Possible invalid/missing EXIF IFD end directory link

### ISSUE THREAD

**Issue by danpetitt** [SixLabors/ImageSharp#1921]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The IFD does not contain the final 4 byte 0 after the last directory which makes it hard to determine if there are any other linked directories or not.

From the TIFF specification (https://www.itu.int/itudoc/itu-t/com16/tiff-fx/docs/tiff6.pdf):
> An Image File Directory (IFD) consists of a 2-byte count of the number of directory entries (i.e., the number of fields), followed by a sequence of 12-byte field entries, followed by a 4-byte offset of the next IFD (or 0 if none). **(Do not forget to write the 4 bytes of 0 after the last IFD.)**

(the emphasis on the final sentence in brackets is mine).

### Steps to Reproduce
```c#
using( var image = Image.Load( "metadata.jpg" ) )
{
  var exif = new ExifProfile();
  exif.SetValue<byte[]>( ExifTag.XPAuthor, Encoding.GetEncoding( "UCS-2" ).GetBytes( "Dan Petitt" ) );
  image.Metadata.ExifProfile = exif;

  image.Save( "metadata-with-exif.jpg" );
}
```

Binary dump of above shows the beginning of the EXIF/TIFF chunk (showing the byte order marker bytes) which is where the data offsets will start from (`30`:
![image](https://user-images.githubusercontent.com/1733292/147985702-9845739f-2e89-4189-ba49-0a7a08a7b0c7.png)

Below shows the first offset (which is always 8 from the start offset):
![image](https://user-images.githubusercontent.com/1733292/147985869-f69b7790-0dd0-4516-bb06-b98ba0201922.png)

Then we start the 12 byte data chunks for each bit of metadata from offset `38`; the first 2 bytes shows the directory count:
![image](https://user-images.githubusercontent.com/1733292/147985949-07b98aac-7a54-4138-9166-618c79541377.png)

Next 10 bytes is the component size, count and the last 4 bytes will be the offset where the actual data lives which is `1A` or 26 + 30 start offset = 56:
![image](https://user-images.githubusercontent.com/1733292/147986137-2e377693-3580-402e-b340-2d99ab9efa23.png)

Actual data in UCS2 (double-byte) encoding:
![image](https://user-images.githubusercontent.com/1733292/147986252-692636b2-f080-447e-b940-b66767231c56.png)

After the 12 byte chunk we should get a 4 byte marker to next IFD or 4 bytes of 0 to show no more IFDs exist; here we get `2E`:
![image](https://user-images.githubusercontent.com/1733292/147986373-c2c420d5-2ef9-4214-a846-6187ff5489d3.png)

But the 4 bytes at offset `2E` (46 + 30 = 76) is not the start of a new IFD its 2 byte null and then a 2 byte JPEG marker FFDB for a quantization table:
![image](https://user-images.githubusercontent.com/1733292/147986885-2c262d57-f2e3-48ec-8d97-d36db2e11f5c.png)

This looks to me to be a bit of a bug; the 4 bytes at offset 50 should be 4 x `0`s.

But I may be incorrect; there does seem to be a bit of ambiguity amongst the various specs I have read where in some places the 12 byte chunks + 4 byte `next IFD` reference is fixed and always applicable (as in the TIFF spec above), and sometimes it seems to imply that perhaps it is only applicable to `IF0` IFDs.

Using metadata2go to edit and re-save the metadata, you can see that after the 12 byte chunk it writes out 4 byte 0 for the end of IFD which is what I was expecting:
![image](https://user-images.githubusercontent.com/1733292/147987464-f2409711-3f4b-4f5d-8793-fc64b4dd9279.png)

Image saved by ImageSharp:
![metadata](https://user-images.githubusercontent.com/1733292/147987755-1da03dbf-57e3-4506-bdf7-95725311f0c1.jpg)

Image fixed by metadata2go:
![metadata-fixed](https://user-images.githubusercontent.com/1733292/147987519-cd87dadf-97d8-480f-8bd0-9dcefa65be1c.jpg)

### System Configuration
- ImageSharp version: v1.04
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): Windows 11 Pro
- .NET Framework version: .NET 6
- Additional information: Visual Studio 2022

**Comment by JimBobSquarePants** [comment]
>But I may be incorrect; there does seem to be a bit of ambiguity amongst the various specs I have read where in some places the 12 byte chunks + 4 byte next IFD reference is fixed and always applicable (as in the TIFF spec above), and sometimes it seems to imply that perhaps it is only applicable to IF0 IFDs.

Yeah this seems ambiguous and the expected result, to me, unexpected. IFDs are specific to TIFF files. @IldarKhayrutdinov @brianpopow  @dlemstra would any of you be able to confirm?

**Comment by danpetitt** [comment]
> IFDs are specific to TIFF files
Yeah and the EXIF is written as a TIFF chunk if I read things properly; so should adhere to the same layout and specification I  think.

**Comment by IldarKhayrutdinov** [comment]
Indeed, at the end are write 2 bytes 

https://github.com/SixLabors/ImageSharp/blob/e20410c412620537ca57126a6f3211458192d25c/src/ImageSharp/Metadata/Profiles/Exif/ExifWriter.cs#L106

**Comment by JimBobSquarePants** [comment]
@IldarKhayrutdinov Thanks very much for confirming!!
