### ISSUE TITLE
Incorrect resolution reported for jpeg image

### ISSUE THREAD

**Issue by provegard** [SixLabors/ImageSharp#1932]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

This is possibly related to #745 but I don't really think so.

We currently use System.Drawing.Common for some image operations and ImageSharp for others. We plan to migrate to ImageSharp entirely when we go to .NET 6 (we're currently on .NET 5). Our target environment is Linux, so to compensate for the fact that libgdiplus is so broken, we actually use [MetadataExtractor](https://github.com/drewnoakes/metadata-extractor-dotnet) to be able to extract image resolution when System.Drawing.Common reports zero resolution. We'd like to not have to rely on MetadataExtractor going forward.

When running our test suite after migrating all image code to ImageSharp, a number of test cases that verify the resolution of test images started to fail. One such test case verifies that the resolution of the following image is 400x400 ppi. However, ImageSharp reports it as 96x96 ppi.

![palette](https://user-images.githubusercontent.com/795010/148693091-ee2a7079-8739-4311-9584-c642efd90946.jpg)

(I have anonymized the image by opening it in Paint (Windows) and painted over its original contents. Paint preserves the image metadata (or lack thereof), so this image exhibits the same behavior as the original.)

### Steps to Reproduce

I use the following test code:

```csharp
using System;
using MetadataExtractor;
using SixLabors.ImageSharp;

const string filePath = @"c:\temp\palette.jpg";

using var img = Image.Load(filePath);

Console.WriteLine($"ImageSharp horiz res = {img.Metadata.HorizontalResolution}, unit = {img.Metadata.ResolutionUnits}");
Console.WriteLine($"ImageSharp vert res  = {img.Metadata.VerticalResolution}, unit = {img.Metadata.ResolutionUnits}");
Console.WriteLine();
Console.WriteLine();

Console.WriteLine("MetadataExtractor:");
var directories = ImageMetadataReader.ReadMetadata(filePath);
foreach (var directory in directories)
foreach (var tag in directory.Tags)
    Console.WriteLine($"{directory.Name} - {tag.Name} = {tag.Description}");
```

The output is as follows:

```
ImageSharp horiz res = 96, unit = PixelsPerInch
ImageSharp vert res  = 96, unit = PixelsPerInch


MetadataExtractor:
JPEG - Compression Type = Baseline
JPEG - Data Precision = 8 bits
JPEG - Image Height = 6617 pixels
JPEG - Image Width = 9350 pixels
JPEG - Number of Components = 3
JPEG - Component 1 = Y component: Quantization table 0, Sampling factors 2 horiz/2 vert
JPEG - Component 2 = Cb component: Quantization table 1, Sampling factors 1 horiz/1 vert
JPEG - Component 3 = Cr component: Quantization table 1, Sampling factors 1 horiz/1 vert
JFIF - Version = 1.1
JFIF - Resolution Units = inch
JFIF - X Resolution = 400 dots
JFIF - Y Resolution = 400 dots
JFIF - Thumbnail Width Pixels = 0
JFIF - Thumbnail Height Pixels = 0
Exif IFD0 - Orientation = Top, left side (Horizontal / normal)
Huffman - Number of Tables = 4 Huffman tables
File Type - Detected File Type Name = JPEG
File Type - Detected File Type Long Name = Joint Photographic Experts Group
File Type - Detected MIME Type = image/jpeg
File Type - Expected File Name Extension = jpg
File - File Name = palette.jpg
File - File Size = 1126332 bytes
File - File Modified Date = sön jan. 09 17:34:09 +01:00 2022
```

In addition, if I run [exiftool](https://exiftool.org/) on the image, I get:

```
ExifTool Version Number         : 12.38
File Name                       : palette.jpg
Directory                       : .
File Size                       : 1100 KiB
File Modification Date/Time     : 2022:01:09 17:34:09+01:00
File Access Date/Time           : 2022:01:09 17:34:25+01:00
File Creation Date/Time         : 2022:01:09 17:19:04+01:00
File Permissions                : -rw-rw-rw-
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
JFIF Version                    : 1.01
Resolution Unit                 : inches
X Resolution                    : 400
Y Resolution                    : 400
Exif Byte Order                 : Big-endian (Motorola, MM)
Orientation                     : Horizontal (normal)
Image Width                     : 9350
Image Height                    : 6617
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Image Size                      : 9350x6617
Megapixels                      : 61.9
```

### System Configuration

- ImageSharp version: 1.0.4
- Other ImageSharp packages and versions: -
- Environment (Operating system, version and so on): Linux/Windows 11
- .NET Framework version: .NET 5, .NET 6
- Additional information:

**Comment by provegard** [comment]
Some more data points:
* The Linux `file` command says: `JPEG image data, JFIF standard 1.01, resolution (DPI), density 400x400, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=1, orientation=upper-left], baseline, precision 8, 9350x6617, components 3`
* Windows file properties show 400x400 as well.

**Comment by brianpopow** [comment]
It seems this image has two `APP0` markers: one with the correct 400x400 dpi info and one without it. The first is read correctly and sets the dpi to 400 dpi in the `JFifMarker`, then the next one is read which does not contain the dpi info and overrides the data of the previous one.

**Comment by JimBobSquarePants** [comment]
I guess we should just add a flag to say we have the data within the decoder then once we've read `APP0`. I'll get a PR created.

**Comment by JimBobSquarePants** [comment]
PR created. https://github.com/SixLabors/ImageSharp/pull/1933

**Comment by provegard** [comment]
That's great, thank you!
