### ISSUE TITLE
Looking for TIFF support

### ISSUE THREAD

**Issue by nonewthing** [SixLabors/ImageSharp#1964]
### Prerequisites

- [X ] I have written a descriptive issue title
- [X ] I have verified that I am running the latest version of ImageSharp
- [X ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X ] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
TIFF support was added to master according to this issue https://github.com/SixLabors/ImageSharp/issues/12 in May 2021, I am using 1.04 which was created after that.  The calls documented in that issue as having been merged, such as:

Configuration config = new Configuration();
config.AddTiff();

do not work, specifically the AddTiff method does not exist.  Has it been moved, or is my assumption it should be in 1.0.4 wrong maybe?

### Steps to Reproduce
Make a new c# console app containing code below, add nuget SixLabors.ImageSharp 1.0.4 package

// See https://aka.ms/new-console-template for more information
using SixLabors.ImageSharp;
Configuration c = new Configuration();
c.AddTiff();

### System Configuration

- ImageSharp version: 1.0.4
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: Net 6
- Additional information: Visual Studio 2022 (64bit) Version 17.0.5,

Thanks
John

**Comment by tocsoft** [comment]
[v1.04](https://github.com/SixLabors/ImageSharp/releases/tag/v1.0.4) was a hotfix/patch release with a single fix in that specifically targeted an issue effecting running the library using .NET 6.

**Comment by nonewthing** [comment]
thanks

**Comment by JimBobSquarePants** [comment]
@nonewthing V2 is coming very soon (planned for this coming week). We're already have builds available on our [MyGet](https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp) feed which you can develop against in the interim.
