### ISSUE TITLE
Image created from WrapMemory can not be mutated

### ISSUE THREAD

**Issue by ggolda** [SixLabors/ImageSharp#1984]
Image create from a `Image.WrapMemory` call can not be mutated using `image.Mutate` and throws an exception below:
```c#
Trying to copy/swap incompatible buffers. This is most likely caused by applying an unsupported processor to wrapped-memory images
```

Code example that helps to reproduce:
```c#
var memory = new Memory<Rgba32>(_pixelBuffer);
var image = Image.WrapMemory(memory, _width, _height);
image.Mutate(x => x.Crop(new Rectangle(0, 0, 200, 200)));
```

As I can see, memory block that I'm using in the example above is not disposed yet and is available, thus `Mutate` and other operations should work.

### System Configuration

- ImageSharp version: 1.0.3
- Other ImageSharp packages and versions: 
-- ImageSharp.Drawing: 1.0.0
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: 6.0.100

**Comment by JimBobSquarePants** [comment]
ImageSharp is V2 now. Please use the complete template for future issues.

The message is also very clear. 

>This is most likely caused by applying an unsupported processor to wrapped-memory images

You can't perform an operation that will result in a swap of buffers. See the docs.
https://docs.sixlabors.com/articles/imagesharp/memorymanagement.html#wrapping-existing-buffers-as-imagetpixel

**Comment by antonfirsov** [comment]
I'm wondering if there is a particular use case we could support better. Extending the size of an image wrapping an existing limited buffer is obviously impossible. Cropping is solvable though, the reason we can't do it today is that we do not support padding in backing buffers (meaning width = stride).

@ggolda can you share your full story? Maybe it's a form of  #1487 you need?
