### ISSUE TITLE
Setting Image's Metadata.ExifProfile to null still produces output images containing EXIF data

### ISSUE THREAD

**Issue by mdelvecchio99** [SixLabors/ImageSharp#1996]
### ImageSharp version

2.0.0

### Other ImageSharp packages and versions

5.0.0: System.Runtime.CompilerServices.Unsage, System.Text.Encoding.CodePages

### Environment (Operating system, version and so on)

macOS 12.2.1

### .NET Framework version

6

### Description

Attempts to delete an Image's EXIF data by setting its Metadata.ExifProfile to null and saving the image to the file system does not work as expected -- my new output images still retain about 22k in EXIF data, visible by my OS. Attached are sample input and outputs.

### Steps to Reproduce

```
public void TestExifClear()
{
	string testFolderPath = "/Users/matt/temp/";

	//my three test images
	string[] testImageNames = new string[3];
	testImageNames[0] = "IMG_1561.jpg";
	testImageNames[1] = "IMG_1564.jpg";
	testImageNames[2] = "IMG_1567.jpg";

	//set compression quality
	SixLabors.ImageSharp.Formats.Jpeg.JpegEncoder encoder = new SixLabors.ImageSharp.Formats.Jpeg.JpegEncoder();
	encoder.Quality = 30;

	Image image;
	string fileName, inputPath, outputPath;

	int i;
	for (i = 0; i < testImageNames.Length; i++)
	{
		fileName = testImageNames[i];
		inputPath = Path.Combine(testFolderPath, fileName);
		outputPath = testFolderPath + "/thumb_" + fileName;

		using (image = Image.Load(inputPath))
		{
			//scrub exif data. not working for my images
			image.Metadata.ExifProfile = null;

			image.Mutate(x => x.Resize(100, 75));
					
			image.Save(outputPath, encoder);					
		}

	}
}
```

### Images

[Input_and_output.zip](https://github.com/SixLabors/ImageSharp/files/8056889/Input_and_output.zip)

**Comment by JimBobSquarePants** [comment]
Are you sure it’s not XMP?

**Comment by mdelvecchio99** [comment]
Ah didn't even know there was such a thing as XMP. Ok setting both objects to null now properly removes what I thought was simply "EXIF data", but I see now is two different types of metadata. Thanks!

```
image.Metadata.ExifProfile = null;
image.Metadata.XmpProfile = null;
```

**Comment by mdelvecchio99** [comment]
There are two metadata repositories, not just EXIF. Clearing both is needed to guarantee no metadata is embedded in output.

**Comment by JimBobSquarePants** [comment]
<strike>There are two metadata repositories</strike> Three actually. IPTC also 😄

**Comment by antonfirsov** [comment]
Isn't it worth to have an encoder option to disable metadata writing?

**Comment by mdelvecchio99** [comment]
> There are two metadata repositories Three actually. IPTC also 😄

I also see an IccProfile. Is it necessary to set all 4 of these to null to remove undesired metadata from output?

**Comment by JimBobSquarePants** [comment]
>Isn't it worth to have an encoder option to disable metadata writing?

@antonfirsov yeah so that we can do it in a non-destructive manner. Only problem is ensuring other encoders not written by us respect that.

@mdelvecchio99 Only if you're confident the profile is sRGB otherwise you could mess up the color output.
