### ISSUE TITLE
SpectralConverter.CommitConversion fails in Debug

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#1998]
### ImageSharp version

2.0

### Other ImageSharp packages and versions

N/A

### Environment (Operating system, version and so on)

any

### .NET Framework version

any

### Description

The following assertion fails in almost all of our baseline jpeg tests:

https://github.com/SixLabors/ImageSharp/blob/e54219acec10d2d2dc247ed5fd4230204a89c07b/src/ImageSharp/Formats/Jpeg/Components/Decoder/SpectralConverter.cs#L47-L49

@br3aker any idea why is `CommitConversion` called multiple times? Could this lead to actual issues?

### Steps to Reproduce

Run `JpegDecoderTests.DecodeBaselineJpeg` in Debug.

**Comment by br3aker** [comment]
That's strange, I've tested it locally and it worked. Will wokr on it asap.

**Comment by antonfirsov** [comment]
>  I've tested it locally and it worked

Hm hope it's not some black magic on my machine only.

**Comment by br3aker** [comment]
Can confirm, already found a bug (it's a very silly one).

**Comment by antonfirsov** [comment]
> Why did CI passed it? Doesn't it have a `DEBUG` job?

Unfortunately, no. IMO, would be nice to have it at least against one target framework. Alternatively, we can introduce Checked build configuration, so avoid very long Debug test runs.
