### ISSUE TITLE
Animated GIF from documentation won't loop

### ISSUE THREAD

**Issue by kurattila** [SixLabors/ImageSharp#2007]
### ImageSharp version

2.0.0

### Other ImageSharp packages and versions

SixLabors.ImageSharp 2.0.0

### Environment (Operating system, version and so on)

Win10 x64, Debian 11 arm64

### .NET Framework version

.NET 6

### Description

Creating an animated GIF using [example code from ImageSharp documentation](https://docs.sixlabors.com/articles/imagesharp/animatedgif.html) produces a file which doesn't loop (stops after first animation) when opened in major browsers like Chrome or Firefox:

```
// Image dimensions of the gif.
const int width = 100;
const int height = 100;

// Delay between frames in (1/100) of a second.
const int frameDelay = 100;

// For demonstration: use images with different colors.
Color[] colors = {
    Color.Green,
    Color.Red
};

// Create empty image.
using Image<Rgba32> gif = new(width, height, Color.Blue);
for (int i = 0; i < colors.Length; i++)
{
    // Create a color image, which will be added to the gif.
    using Image<Rgba32> image = new(width, height, colors[i]);

    // Set the duration of the frame delay.
    GifFrameMetadata metadata = image.Frames.RootFrame.Metadata.GetGifMetadata();
    metadata.FrameDelay = frameDelay;

    // Add the color image to the gif.
    gif.Frames.AddFrame(image.Frames.RootFrame);
}

// Save the final result.
gif.SaveAsGif("output.gif");
```

### Steps to Reproduce

1. Run the example code from ImageSharp documentation for creating an animated GIF file: \
https://docs.sixlabors.com/articles/imagesharp/animatedgif.html
2. Open the resulting `output.gif` in either Chrome or Firefox.
3. Expected to see an infinite animation loop, but actually only a single animation happens. Animated GIF is stopped at the last frame and no looping occurs unfortunately.

### Images

![output](https://user-images.githubusercontent.com/12791722/154317863-e06da2c6-6e84-4eda-8554-9f27cffd580c.gif)

**Comment by kurattila** [comment]
Hint: when the `gifsicle` tool is applied to the GIF, the result already "loops" in browsers just fine.
```
gifsicle --loop output.gif > output.fixed.gif
```

**Comment by brianpopow** [comment]
You will need to edit the `RepeatCount` of the gif metadata.

```
using Image<Rgba32> gif = new(width, height, Color.Blue);
var gifMetaData = gif.Metadata.GetGifMetadata();
gifMetaData.RepeatCount = 10;
```

I will update the docs.

**Comment by JimBobSquarePants** [comment]
@kurattila This is not a bug and the appropriate property is clearly documented.

https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Formats.Gif.GifMetadata.html

Nothing in that sample suggests the animation should repeat indefinitely. 

In the future please use this issue tracker for actual library issues. The documentation has it’s own repository and if you feel something is unclear you are free to contribute a fix there.

**Comment by kurattila** [comment]
@brianpopow Thanks for the hint it, was really helpful!
@JimBobSquarePants Fair enough. In fact it seemed to be an actual library issue to me, since looking for words "repeat" or "loop" in the [API index](https://docs.sixlabors.com/api/index.html) yielded no results at all - which made me think that "looping" is not configurable at all and thus default looping must be broken. But you're right, had I used not only the "filter box" but also the less obvious "search box" on that page, then I would have discovered that a `RepeatCount` property actually exists. Thanks for the link!
