### ISSUE TITLE
Change in transparency handing in ImageSharp 2? [Drawing 1.0.0-beta14]

### ISSUE THREAD

**Issue by DaveSenn** [SixLabors/ImageSharp#2008]
### ImageSharp version

2.0.0

### Other ImageSharp packages and versions

SixLabors.ImageSharp.Drawing 1.0.0-beta14

### Environment (Operating system, version and so on)

Windows 10 21H2

### .NET Framework version

.NET 6 6.0.2

### Description

The example from here: [AvatarWithRoundedCorner](https://github.com/SixLabors/Samples/tree/main/ImageSharp/AvatarWithRoundedCorner) used to create iamges with a transparent background.
With ImageSharp 2 this creates iamges with a black background.

If the input image already has a transparent background the output will have a transparent backgroudn as well.

Is there an option which must be set for the output to have a transparent background in all cases?

### Steps to Reproduce

Run the sample with ImageSharp 1...

Update the nuget pacakges in the example. And run it with ImageSharp 2:

```
  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="2.0.0" />  
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta14" />
  </ItemGroup>
```

### Images

Version 2
![fb-round](https://user-images.githubusercontent.com/7510324/154478586-b93ad6db-7037-42e3-8276-50d585c87f03.png)

Version 1
![with version 1](https://user-images.githubusercontent.com/7510324/154478507-3a7b039e-fccd-42fc-a488-8ad68e3561de.png)

**Comment by JimBobSquarePants** [comment]
The change in jpeg decoder handling using the non-generic API is listed in the release notes under breaking changes.

https://github.com/SixLabors/ImageSharp/releases

It's also listed in the documented breaking changes in the accompanying blog post.

https://sixlabors.com/posts/announcing-imagesharp-200/#breaking-changes

**Comment by farooqiqbal1** [comment]
@JimBobSquarePants any way around these breaking changes?

**Comment by JimBobSquarePants** [comment]
Use the generic API passing a pixel format that supports alpha e.g. `Rgba32`
