### ISSUE TITLE
TiffMetadata doesn't contain bit depth information

### ISSUE THREAD

**Issue by PeteMichaud** [SixLabors/ImageSharp#2049]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.0.0

### Other ImageSharp packages and versions

none

### Environment (Operating system, version and so on)

win10 pro (Version 10.0.19043 Build 19043)

### .NET Framework version

4.7

### Description

Per the title, getting the metadata from a loaded tiff file doesn't provide bit depth information, so I can't tell if it's 8,16,32 or what. Since the metadata handling is all manual, there's no way for me to store that information for later so I can save to the correct depth after processing. It's not exactly a bug, but it's a feature that's missing that I suspect wouldn't be that hard to add since this information is required for opening the file in the first place.

### Steps to Reproduce

For example:

```
using (var imageStream = new FileStream(imagePath, FileMode.Open, FileAccess.Read))
{
    var loadTask = Image.LoadWithFormatAsync<RgbaVector>(imageStream);

    loadTask.Wait();
    (var image, var originalFormat) = loadTask.Result;
}

var meta = image.Metadata.GetTiffMetadata();

//meta.BitDepth or similar doesn't exist!
```

**Comment by JimBobSquarePants** [comment]
Tiff is a container format where different frames can have different bit depths. 

The information is stored in [`TiffFrameMetadata.BitsPerPixel`](https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Formats.Tiff.TiffFrameMetadata.html#SixLabors_ImageSharp_Formats_Tiff_TiffFrameMetadata_BitsPerPixel)

>It's not exactly a bug, but it's a feature that's missing that I suspect wouldn't be that hard to add since this information is required for opening the file in the first place.

It's really important that you do not use this issue tracker for feature requests. We have a dedicated [Discussions Channel](https://github.com/SixLabors/ImageSharp/discussions/categories/ideas)

**Comment by PeteMichaud** [comment]
For future reference, the discussion I opened: https://github.com/SixLabors/ImageSharp/discussions/2053
