### ISSUE TITLE
This PNG when converted to WebP by ImageSharp produces a corrupted WebP file

### ISSUE THREAD

**Issue by rwasef1830** [SixLabors/ImageSharp#2068]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.0

### Other ImageSharp packages and versions

ImageSharp.Web 2.0.0-alpha.0.18

### Environment (Operating system, version and so on)

Windows 10

### .NET Framework version

.NET 6.0.3

### Description

The attached image when converted to WebP at default quality, produces a file that doesn't render in any browser and is deemed as corrupt.

### Steps to Reproduce

Use standard ImageSharp.Web middleware to request conversion of the attached image to webp. The corrupt webp is also attached.

Thanks for the awesome library.

### Images

![nuclear](https://user-images.githubusercontent.com/4632253/159203140-cd8e372c-f295-41c3-94ab-b020e7aae3bd.png)

corrupted webp output (inside zip):
[converted.zip](https://github.com/SixLabors/ImageSharp/files/8312961/converted.zip)

Other pngs convert fine.

**Comment by rwasef1830** [comment]
Just in case there's any conversion by GitHub (the source image in zip file):
[nuclear.zip](https://github.com/SixLabors/ImageSharp/files/8312964/nuclear.zip)

**Comment by JimBobSquarePants** [comment]
Can you please run a test using ImageSharp as a standalone? There’s no published version of Web (not even alphas) built against 2.1.0 yet.

**Comment by rwasef1830** [comment]
oh, standalone it produces a correct file! Maybe it's some memory corruption due to mismatch between the web middleware and the main library. Ok, I mistakenly thought this case should work owing to semantic versioning. My apologies.

@JimBobSquarePants

**Comment by JimBobSquarePants** [comment]
I’ll double check my local web build anyway. I have a PR in motion that will bring direct support.

**Comment by JimBobSquarePants** [comment]
On versioning yeah…. We had to introduce a breaking change due to some IO blocking in our async workflow.

**Comment by JimBobSquarePants** [comment]
![image](https://user-images.githubusercontent.com/385879/159219288-67def129-07c0-4fe7-a881-ac40c640c4b5.png)

Just to confirm, here's my local build working well. I'm working hard to get a release out asap.

**Comment by rwasef1830** [comment]
@JimBobSquarePants I was able to isolate the issue, it was a bug in my file provider. There's no issue in ImageSharp.
