### ISSUE TITLE
[Question] Is it possible to get a gradient opacity effect in an image?

### ISSUE THREAD

**Issue by KazysNoobiys** [SixLabors/ImageSharp#2070]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

v2.1.0

### Other ImageSharp packages and versions

none

### Environment (Operating system, version and so on)

Win10

### .NET Framework version

.net5

### Description

In a mobile app on Xamarin.Forms I need to use an image with a gradient opacity. For example, the top of the image would be completely non-transparent and gradually become transparent to the bottom.
In WPF, there is an OpacityMask that allows you to do this. Xamarin doesn't have it. Is it possible to use 
 ImageSharp to generate an image with the required transparency on the server?

### Steps to Reproduce

none

**Comment by tocsoft** [comment]
Please don't open bug reports for questions.
