### ISSUE TITLE
Saving a jpg image as webp rotates the image when height > width

### ISSUE THREAD

**Issue by Markz878** [SixLabors/ImageSharp#2074]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.0

### Other ImageSharp packages and versions

None

### Environment (Operating system, version and so on)

Windows 10 Version 21H1

### .NET Framework version

.Net 6.0.102

### Description

When I try to save a jpg as a webp, the image rotates. This seems to only happen when the image's height is larger than it's width. Is this part of the webp spec, I could not find anything that said so?

### Steps to Reproduce

Save the attached image somewhere and create a console app:
```
string path = @"<path-to-img-folder>\dog.jpg";
using Stream s = File.OpenRead(path);
using Image image = await Image.LoadAsync(s);
await image.SaveAsJpegAsync("Doggo.jpg");
await image.SaveAsWebpAsync("Doggo2.webp");
```
Jpg image is normal and webp image has rotated.

### Images

![dog](https://user-images.githubusercontent.com/38662394/160168577-68aa465e-3d80-4749-b1cf-8a16e2f53d4f.jpg)

**Comment by tocsoft** [comment]
you can probably fix this by calling `image.Mutate(x=>x.AutoOrient());` before saving it.

It will be due to the source image actually being rotate in the first place but then using a metadata flag to inform the browser/viewer to draw it rotate 90 degrees before displaying.

I don't' know enough about our WebP implementation but I presume it doesn't support that (or uses a different metadata marker to denote the same effect).

**Comment by tocsoft** [comment]
the height/width thing is likely a bit of a red herring, and more likely its about how the picture was generated.

With mobile cameras utilising the exif/metadata flag to cheat and speed up processing by not encoding the picture any differently from the sensor between portrait and landscape shots but instead just toggling the metadata flag instead.

**Comment by Markz878** [comment]
Hi, that AutoOrient function fixed my issue. I wasn't aware of that metadata flag. Thanks a lot! Closing this.

**Comment by JimBobSquarePants** [comment]
I’ve written some EXIF helpers for the next version of ImageSharp.Web that can work out the correct orientation of resize dimensions, anchors, etc for different orientation values. I’ll probably upstream them and make orientation handling an option for ResizeOptions in v3.
