### ISSUE TITLE
namespaces for 'RendererOptions' and 'TextGraphicsOptions' could not be found  (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by bytesfrombits** [SixLabors/ImageSharp#2093]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

 ImageSharp 2.1.0

### Other ImageSharp packages and versions

 ImageSharp.Drawing 1.0.0-beta14

### Environment (Operating system, version and so on)

windows10

### .NET Framework version

.net core 6

### Description

In order to generate webp images and after upgrading a working project that was generating png images from SixLabors.ImageSharp 1.0.3 and SixLabors.ImageSharp.Drawing 1.0.0-beta11 to SixLabors.ImageSharp 2.1.0 and SixLabors.ImageSharp.Drawing 1.0.0-beta14 respectively, the following errors are now thrown on any attempt to build the project:

Errors:
error CS0246: The type or namespace name 'RendererOptions' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: The type or namespace name 'TextGraphicsOptions' could not be found (are you missing a using directive or an assembly reference?)

The updated .csproj has the following references:
<PackageReference Include="SixLabors.ImageSharp" Version="2.1.0" />
<PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta14" />

Before the upgrade, the working .csproj had the following references:
<PackageReference Include="SixLabors.ImageSharp" Version="1.0.3" />
<PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta11" />

Snippet of the affected function:
private static IImageProcessingContext DrawScaleCenterText(this IImageProcessingContext processingContext,Font font,string text,Color color,float padding, int VerticalPosition)
        {
            Size imgSize = processingContext.GetCurrentSize();

            float targetWidth = imgSize.Width - (padding * 2);
            float targetHeight = imgSize.Height - (padding * 2);

            // measure the text size
            FontRectangle size = TextMeasurer.Measure(text, new RendererOptions(font));

            //find out how much we need to scale the text to fill the space (up or down)
            float scalingFactor = Math.Min(imgSize.Width / size.Width, imgSize.Height / size.Height);

            //create a new font
            Font scaledFont = new Font(font, scalingFactor * font.Size);

            //var center = new PointF(imgSize.Width / 2, imgSize.Height / 2);
            var center = new PointF(imgSize.Width / 2, VerticalPosition);
            var textGraphicOptions = new TextGraphicsOptions()
            {
                TextOptions = {
                    HorizontalAlignment = HorizontalAlignment.Center,
                    VerticalAlignment = VerticalAlignment.Center
                }
            };
            return processingContext.DrawText(textGraphicOptions, text, font, color, center);
        }

Where/How to use the RendererOptions, TextGraphicsOptions, FontRectangle, TextMeasurer, TextOptions classes?

### Steps to Reproduce

Upgrade or Downgrade a project To/From as follows:
<PackageReference Include="SixLabors.ImageSharp" Version="2.1.0" />
<PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta14" />

Upgrade or Downgrade a project To/From as follows:
<PackageReference Include="SixLabors.ImageSharp" Version="1.0.3" />
<PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta11" />

**Comment by JimBobSquarePants** [comment]
Please do not use the issue tracker for questions, especially in the wrong repository.

**Comment by naveedahmed1** [comment]
I am also facing the same issue after upgrading from:

SixLabors.ImageSharp 1.0.2 **to** SixLabors.ImageSharp 2.1.1
SixLabors.ImageSharp.Drawing 1.0.0-beta11 **to** SixLabors.ImageSharp.Drawing 1.0.0-beta14

**My Code:**

```
TextOptions textOptions = new TextOptions()
                        {
                            HorizontalAlignment = HorizontalAlignment.Right,
                            VerticalAlignment = VerticalAlignment.Center
                        };

                        GraphicsOptions graphicsOptions = new GraphicsOptions()
                        {
                            Antialias = true
                        };

                        TextGraphicsOptions textGraphicsOptions = new TextGraphicsOptions(graphicsOptions, textOptions);
```

**Error**

```
Error	CS1729	'TextOptions' does not contain a constructor that takes 0 arguments


Error	CS0246	The type or namespace name 'TextGraphicsOptions' could not be found (are you missing a using directive or an assembly reference?)
```

Unfortunately, upgrading to a new version of ImageSharp is always very painful :(

**Comment by fivetaibin** [comment]
I meet the same problem，I used  .net core 6.0 webapi program，and ensure the SixLabors.ImageSharp.Drawing is the latesd.

**Comment by JimBobSquarePants** [comment]
https://docs.sixlabors.com/api/Fonts/SixLabors.Fonts.TextOptions.html?q=TextOptions

**Comment by fivetaibin** [comment]
Tip RendererOptions, TextGraphicsOptions, FontRectangle, TextMeasurer, TextOptions classes? does not exist

**Comment by JimBobSquarePants** [comment]
Nonsense! 

The following types exist and are linked.
 
- [`FontRectangle`](https://docs.sixlabors.com/api/Fonts/SixLabors.Fonts.FontRectangle.html)
- [`TextMeasurer`](https://docs.sixlabors.com/api/Fonts/SixLabors.Fonts.TextMeasurer.html)
- [`TextOptions`](https://docs.sixlabors.com/api/Fonts/SixLabors.Fonts.TextOptions.html)

`RendererOptions` and `TextGraphics` options have been removed as they are no longer required, and their functionality has been merged into `TextOptions` and `GraphicsOptions` respectively.

It's been like that for a long time now. This issue was opened over a year ago. 

Please do not spam closed issues again. You will be blocked.
