### ISSUE TITLE
webp (from jpeg) gives inaccurate colors

### ISSUE THREAD

**Issue by marklonquist** [SixLabors/ImageSharp#2107]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp.Web
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp.Web/issues) and [closed](https://github.com/SixLabors/ImageSharp.Web/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp.Web version

2.0.0

### Other Six Labors packages and versions

ImageSharp 2.1.1

### Environment (Operating system, version and so on)

Linux container in GCP running on Kubernetes

### .NET Framework version

NET6

### Description

Colors are inaccurate when setting format to webp from a jpeg original.

### Steps to Reproduce

Set `format=webp` on a jpeg original in a side-by-side comparison and observe the inaccurate colors

### Images

Left side: WebP - Right side: Original JPEG
![Screenshot 2022-05-06 at 10 00 51](https://user-images.githubusercontent.com/1456819/167091764-df4e6791-5e35-4332-b40c-8904b207839f.png)

**Comment by br3aker** [comment]
Can you provide an image? It's almost impossible to determine errors just from before/after comparison.

**Comment by brianpopow** [comment]
Converting to bmp and tga also has this incorrect color, while tiff seems to be ok.

**Comment by br3aker** [comment]
Yep, checked with JPEGsnoop - this image has color profile.

@marklonquist unfortunately, this is yet to be implemented in https://github.com/SixLabors/ImageSharp/issues/74.

**Comment by marklonquist** [comment]
> Yep, checked with JPEGsnoop - this image has color profile.
> 
> @marklonquist unfortunately, this is yet to be done in #1567.

Thanks for the info.

**Comment by brianpopow** [comment]
There is something we can do actually: Currently we are not preserving the ICCP when encoding webp and bmp. We can at least change that.

**Comment by brianpopow** [comment]
With #2108, #2109 and #2110 merged to `main` branch, the color profile will be preserved when encoding webp, bmp and png images. With that the image color should look correct when the viewer of the image supports color profiles (most browsers should do that).

**Comment by marklonquist** [comment]
That's awesome - any idea if there will be a 2.1.2 update where this might be in, or is this gonna be part of 3.0.0? 😄 Awesome work you guys are doing!

**Comment by JimBobSquarePants** [comment]
Thanks! 

3.0.0 I’m afraid. Only super critical security issues will be back ported to 2x now. It’s too much effort to maintain multiple majors.

**Comment by jaddie** [comment]
Wait V2 has only just come out and its already going to end up with rather critical bugs in it like this that basically render the use of webp pointless? This is a bit of a shame as Umbraco has just in V10 which is about to be released upgraded to V2 of ImageSharp & now its going to have a defective webp implementation all the way until V3 comes out presumably?

Apologies if I am being daft & missing something!

**Comment by JimBobSquarePants** [comment]
It’s not a critics bug. Color profiles are optional. 

We don’t want to support legacy target frameworks. It’s a ton of work that we don’t get paid to do nor are obligated in any way to do.

**Comment by br3aker** [comment]
> Apologies if I am being daft & missing something!

You can backport it to v2.0 it if you need/want to.

**Comment by jaddie** [comment]
So what needs to be done to fix the bug in ImageSharp that means its not generating the webp image correctly, an example case as attached:
[New folder (3).zip](https://github.com/SixLabors/ImageSharp/files/8833441/New.folder.3.zip)

The webp file in there, is generated at a width of 1500px from a webp file as the source by ImageSharp.
The jpg file in there is also generated from the same source webp file by ImageSharp but when doing this the bug isn't occurring with ImageSharp's output & the colours of the image are as expected instead of being washed out.


Hopefully that makes sense, based on this and the test case, is this a configuration issue of some sort that can be resolved or some way to fix it if its a bug in ImageSharp's generation of the image as having a media gallery site running on Umbraco powered by this & this outcome is a bit concerning 🙈

**Comment by jaddie** [comment]
Just to put a note here in case it helps anyone else, albeit not an ideal solution, in the mean time it seems that V3 does not suffer this issue, for any Umbraco users, if you upgrade your own project to the pre-release V3 of ImageSharp while still using ImageSharp.Web 2, the site will work fine and load but without this bug happening, hope that helps someone out! 👌

**Comment by JimBobSquarePants** [comment]
That is not a wise solution. There is guaranteed breaking changes to V3 including license changes. 

You can follow PRs linked to this issue to see required changes. If you want to put the effort in, we’ll accept that, otherwise this is just unhelpful noise.

**Comment by marklonquist** [comment]
Just out of curiosity; what kind of license changes? Anything us business users need to be aware of?

**Comment by JimBobSquarePants** [comment]
Nothing. Because business users should be buying commercial licenses

**Comment by JimBobSquarePants** [comment]
Fixed in v3 alpha
