### ISSUE TITLE
Base Image<IPixel> type for methods such as ProcessPixelRows

### ISSUE THREAD

**Issue by gabrielmaldi** [SixLabors/ImageSharp#2131]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.12

### Other ImageSharp packages and versions

-

### Environment (Operating system, version and so on)

macOS 12

### .NET Framework version

.NET 5

### Description

Since the method `ProcessPixelRows` is defined in [ImageFrame{TPixel}.cs](https://github.com/SixLabors/ImageSharp/blob/0eb411c5497b0ea3cb969bd7ff631f2d565b4f20/src/ImageSharp/ImageFrame%7BTPixel%7D.cs#L179), [Image](https://github.com/SixLabors/ImageSharp/blob/main/src/ImageSharp/Image.cs) (or `IImage`) cannot be used as a base class for calling it when different types of pixel formats may be used:

```csharp
Image image = pixelFormat switch
{
    MyPixelFormat.Rgb24 => new Image<Rgb24>(side, side, color),
    MyPixelFormat.Argb32 => new Image<Argb32>(side, side, color),
};

image.ProcessPixelRows(accessor => {}); // Compiler error: 'Image' does not contain a definition for 'ProcessPixelRows'
```

Also, `Image<IPixel>` cannot be used by itself:

```csharp
Image<IPixel> image; // Compiler error: the type 'IPixel' must be a non-nullable value type, along with all fields at any level of nesting, in order to use it as parameter 'TPixel' in the generic type or method 'Image<TPixel>'
```

Currently the only way of handling this is to write different calls to `ProcessPixelRows`, one for each `Image<TPixel>` type.

Perhaps the method could be defined in some base class/interface? Or we could have a way to declare an `Image<IPixel>`?

Thanks!

### Steps to Reproduce

Copy the sample code above and try to compile it in Visual Studio.

**Comment by br3aker** [comment]
> Currently the only way of handling this is to write different calls to ProcessPixelRows, one for each Image<TPixel> type.

I can't understand the problem here. How can we define `ProcessPixelRows` at the base class where we don't know the exact pixel type? What would be the delegate type for this? Right now it's defined this way:

```cs
public delegate void PixelAccessorAction<TPixel>(PixelAccessor<TPixel> pixelAccessor)
    where TPixel : unmanaged, IPixel<TPixel>;
```

In `Image<TPixel>` we know a `TPixel` type. The whole point of base `Image` class is the you don't know/care about the specific pixel type used. So there's no way to provide a 'base' delegate for that, pixels are structs, `IPixel` interface is only used for generics constraints so covariance also won't work. 

I don't know your setup but if you want to create some 'processing' code which is equal among different pixel types - you can create an image processor, AFAIR ImageSharp allows to extend current proccessors.

**Comment by gabrielmaldi** [comment]
@br3aker, thank you. I think I presented this issue in the wrong way by proposing a specific solution (i.e. defining the method in the base class) instead of stating the problem I'm facing.

My processing code is the same for all pixel types. Currently, I resorted to creating this generic method:

```csharp
Image ProcessPixelRows<TPixel>(Image<TPixel> image)
    where TPixel : unmanaged, IPixel<TPixel>
{
    image.ProcessPixelRows(accessor =>
    {
        for (var qrY = 0; qrY < size; qrY++)
        {
            for (var y = (qrY + border) * scale; y < (qrY + border + 1) * scale; y++)
            {
                var pixelRow = accessor.GetRowSpan(y);

                for (var qrX = 0; qrX < size; qrX++)
                {
                    var color = qrCode.GetModule(qrX, qrY) ? foregroundColor : backgroundColor;
                    for (var x = (qrX + border) * scale; x < (qrX + border + 1) * scale; x++)
                    {
                        pixelRow[x] = color.ToPixel<TPixel>();
                    }
                }
            }
        }
    });

    return image;
}
```

And I'm using it like this:

```csharp
Image image = myPixelFormat switch
{
    MyPixelFormat.Argb32 => ProcessPixelRows(new Image<Argb32>(side, side)),
    MyPixelFormat.Bgra5551 => ProcessPixelRows(new Image<Bgra5551>(side, side)),
    MyPixelFormat.Bgr24 => ProcessPixelRows(new Image<Bgr24>(side, side)),
    MyPixelFormat.Bgra32 => ProcessPixelRows(new Image<Bgra32>(side, side)),
    MyPixelFormat.Abgr32 => ProcessPixelRows(new Image<Abgr32>(side, side)),
    MyPixelFormat.L8 => ProcessPixelRows(new Image<L8>(side, side)),
    MyPixelFormat.L16 => ProcessPixelRows(new Image<L16>(side, side)),
    MyPixelFormat.La16 => ProcessPixelRows(new Image<La16>(side, side)),
    MyPixelFormat.La32 => ProcessPixelRows(new Image<La32>(side, side)),
    MyPixelFormat.Rgb24 => ProcessPixelRows(new Image<Rgb24>(side, side)),
    MyPixelFormat.Rgba32 => ProcessPixelRows(new Image<Rgba32>(side, side)),
    MyPixelFormat.Rgb48 => ProcessPixelRows(new Image<Rgb48>(side, side)),
    MyPixelFormat.Rgba64 => ProcessPixelRows(new Image<Rgba64>(side, side)),
};
```

But it feels like there might be a better way in the lines of:

```csharp
Image<IPixel> image = myPixelFormat switch
{
    MyPixelFormat.Argb32 => new Image<Argb32>(side, side),
    ...
};

image.ProcessPixelRows(accessor =>
{
    for (var ...
});
```

The problem is `Image<IPixel>` cannot be declared.

Maybe there is no other way to design this and I should just stick to my current solution; feel free to close if you think this is the case.

Thanks again for your time.

**Comment by br3aker** [comment]
@gabrielmaldi there's actually the only way to implement it, you have your own pixel type and want to map it to ImageSharp pixel type.

`Image<IPixel>` cannot be declared because all pixel types are value types.

**Comment by JimBobSquarePants** [comment]
Use this.

https://docs.sixlabors.com/articles/imagesharp/pixelbuffers.html#parallel-pixel-format-agnostic-image-manipulation

**Comment by gabrielmaldi** [comment]
@JimBobSquarePants, thank you! Looks promising, will take a look.

**Comment by antonfirsov** [comment]
Note that `ProcessPixelRowsAsVector4` can be a bit more expensive for this use case. Another way is to implement a custom `IImageProcessor`, but it's quite complex since it was designed for exposing library features.

The easiest trick to do generic pixel processing code is to implement an `IImageVisitor`:

```C#
class MyVisitor : IImageVisitor {
    public void Visit<TPixel>(Image<TPixel> image)
            where TPixel : unmanaged, IPixel<TPixel>
    {
        image.ProcessPixelRows(accessor =>
        {
            // Processing code
        }
    }
}

Image image = CreateImage(myPixelFormatDescriptor);
image.AcceptVisitor(new MyVisitor());
```

**Comment by gabrielmaldi** [comment]
@antonfirsov, thanks!

I tried `ProcessPixelRowsAsVector4`:

```csharp
var qrForegroundColor = Color.Parse(foregroundColor);
var qrBackgroundColor = Color.Parse(backgroundColor);

image.Mutate(new Configuration
{
    // In certain cases (typically desktop apps running on multi-core CPU) the processor-level parallelism might be faster
    // and desirable, but in case of high-load server-side applications it usually hurts throughput. To address this, the
    // level of parallelism can be customized via Configuration's MaxDegreeOfParallelism property.
    // https://docs.sixlabors.com/articles/imagesharp/pixelbuffers.html#parallel-pixel-format-agnostic-image-manipulation
    MaxDegreeOfParallelism = 1,
},
img => img.ProcessPixelRowsAsVector4(row =>
{
    // Scan the QR pattern row by row
    for (var qrY = 0; qrY < size; qrY++)
    {
        // Fill "scale" number image rows that correspond to the current QR pattern row
        for (var y = (qrY + border) * scale; y < (qrY + border + 1) * scale; y++)
        {
            // Loop through the values for the current QR pattern row
            for (var qrX = 0; qrX < size; qrX++)
            {
                // Fill "scale" number of image pixels that correspond to the current QR pattern value
                var qrColor = qrCode.GetModule(qrX, qrY) ? qrForegroundColor : qrBackgroundColor;
                for (var x = (qrX + border) * scale; x < (qrX + border + 1) * scale; x++)
                {
                    row[x] = (Vector4)qrColor;
                }
            }
        }
    }
}));
```

But for some reason my QR is not generated correctly (full vertical stripes across the image). I didn't want to spend more time on this so I stuck with my earlier solution.

I agree that an ImageVisitor is perhaps overkill for my current use-case, but it's good to know about it for future use!

Thanks again.
