### ISSUE TITLE
Loading TIFFs is 50x Slower

### ISSUE THREAD

**Issue by TonyValenti** [SixLabors/ImageSharp#2132]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.2

### Other ImageSharp packages and versions

???

### Environment (Operating system, version and so on)

Windows 11 x64

### .NET Framework version

6.0.5

### Description

Hi ImageSharp,
Run this code with the attached image and you'll see that loading TIFFs is 50x slower than SDI.
Can you please take a look?  Happy to buy a license / sponsorship if we can get this resolved sooner rather than later.

### Steps to Reproduce

            var Input = $@"C:\Users\TonyV\Downloads\Image1.tiff";
            
            var SW1 = System.Diagnostics.Stopwatch.StartNew();
            for (int i = 0; i < 100; i++) {
                System.Drawing.Image.FromFile(Input);
            }
            Console.WriteLine($@"SW1 {SW1.Elapsed}");

            var SW2 = System.Diagnostics.Stopwatch.StartNew();
            for (int i = 0; i < 100; i++) {
                SixLabors.ImageSharp.Image.Load(Input);
            }
            Console.WriteLine($@"SW2 {SW2.Elapsed}");

### Images

[Image1.zip](https://github.com/SixLabors/ImageSharp/files/8791665/Image1.zip)

**Comment by brianpopow** [comment]
@TonyValenti If you buy a license, I could take a look into this. I have some idea's why this might be slow.

**Comment by TonyValenti** [comment]
@brianpopow Done!  I'd be surprised if you got a 50x speedup as well, but I'd be quite happy with 49x.  :-)

**Comment by br3aker** [comment]
Won't be surprised if SDI uses the same 'optimization' technique as in jpeg decoder-encoder with caching the initial file if image wasn't changed. I'll actually test it right now.

**Comment by brianpopow** [comment]
@TonyValenti Is it ok for you, if we use the image you have provided in our benchmarks?

**Comment by TonyValenti** [comment]
Yep!

**Comment by TonyValenti** [comment]
Also, I'm sure you've noticed, but it seems like memory usage explodes too.

**Comment by JimBobSquarePants** [comment]
Let’s do some proper benchmarking. Those tests above will be wildly inaccurate

**Comment by brianpopow** [comment]
With #2134 merged to main, the image linked here should decode much faster. The image uses Fax4 compression, but all fax de-compression should be faster now.

You can try it out with our latest [nightly](https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp)
