### ISSUE TITLE
2.1.2: Jpeg YCbcr encode cause pink color blur

### ISSUE THREAD

**Issue by lifeglam** [SixLabors/ImageSharp#2133]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.2

### Other ImageSharp packages and versions

2.1.1

### Environment (Operating system, version and so on)

Windows 11, x86

### .NET Framework version

.Net Core 3.0

### Description

Jpeg image with YCbCR color space encode with pink blur (sample image added below). This only repros with latest 2.1.2. (2.1.1 works without issue)

### Steps to Reproduce

`using (Image<Rgba32> image = Image.Load<Rgba32>(File.OpenRead(sourceFilePath)))
            {
                using (var destinationImageStream = new MemoryStream())
                {
                    destinationImageStream.Position = 0;
                    image.SaveAsJpeg(destinationImageStream);
                }
            }`

### Images

![original](https://user-images.githubusercontent.com/13856985/170858158-9e55ea35-53ed-40e1-84e6-eff74b7c76f7.jpg)
![converted_pink](https://user-images.githubusercontent.com/13856985/170858177-58e820fa-5908-430c-a933-712d406ab494.jpeg)

**Comment by brianpopow** [comment]
closed via #2135
