### ISSUE TITLE
Memory allocation oversight when processing Image types

### ISSUE THREAD

**Issue by ethanrushh** [SixLabors/ImageSharp#2139]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.2

### Other ImageSharp packages and versions

None

### Environment (Operating system, version and so on)

Ubuntu 22.04, Jetbrains Rider

### .NET Framework version

Core 6.0

### Description

I seem to have found a memory leak I am unable to deal with using high level C# code. Running this method enough times will result in a crash due to being out of memory after consuming all available physical and logical (swap) memory.

### Steps to Reproduce

```
            var groups = orderTable.Select(layerTarget => Path.Combine(inputDirectory, layerTarget)).ToList();

            using var thisImage = new Image<Rgba32>(width, height);
            
            foreach (var nextFile in groups.Select(group => Directory.GetFiles(Path.Combine(inputDirectory, group))).Select(files => files[_generator.Next(0, files.Length)]))
            {
                using var img = await Image.LoadAsync(nextFile);
                
                thisImage.Mutate(ipc =>
                {
                    // ReSharper disable once AccessToDisposedClosure
                    ipc.DrawImage(img, new Point(0, 0), 1);
                });
            }

            await thisImage.SaveAsBmpAsync("output/preview.bmp");
            thisImage.Dispose();

            return "output/preview.bmp";
```

That is the snippet of my code that is causing the issue. Every time I run this a few dozen MB of memory gets leaked. Since I am attempting to process hundreds, maybe thousands of images the memory leak is enough to overcome my full 32GiB of installed physical memory. As you can see I am disposing of all of the images there either through a using statement's scope ending or explicitly. 

Rider's memory viewer detects that the System.Byte[] arrays are not being disposed of correctly as they are still present in memory as shown:
![Screenshot from 2022-06-03 10-35-52](https://user-images.githubusercontent.com/82483782/171762525-76d464cd-2f9c-4183-b867-6b6ebdbaa5ed.png)

I have tried setting:

```
            Configuration.Default.MemoryAllocator = MemoryAllocator.Create(new MemoryAllocatorOptions
            {
                MaximumPoolSizeMegabytes = 128
            });
```
to no avail. 

I am using about 11 different layers and they are all 3500x3500 in size.

**Comment by br3aker** [comment]
> System.Byte[] arrays

Managed types can't be leaked, only if they were allocated by `ArrayPool`, can you check their root object holding them?

**Comment by ethanrushh** [comment]
> 

I'm not 100% sure what you mean by that but this is the code thats calling my script. Its a public class with nothing in it really except that method (it could be static but I'm planning to add features that would mess that up)

```
        private async void RefreshPreview_Clicked(object? sender, RoutedEventArgs e)
        {
            (sender as Button)!.IsEnabled = false;
            var originalText = ((sender as Button)!.Content as TextBlock)!.Text;
            ((sender as Button)!.Content as TextBlock)!.Text = "Generating...";
            
            var generator = new ImageGenerator();
            PreviewImage.Source = new Bitmap(await generator.GenerateExample(_imagesFolderPath, CurrentListOrder()));
            generator.Dispose();

            (sender as Button)!.IsEnabled = true;
            ((sender as Button)!.Content as TextBlock)!.Text = originalText;

            GC.Collect();

            e.Handled = true;
        }
```

It should be noted that `generator.Dispose()` does nothing currently however the function being called by `generator.GenerateExample` is precisely the same as the example stated in the issue. For reference, this is an event from Avalonia however that isn't strictly relevent to this beyond the fact that this is being held in an event.

**Comment by br3aker** [comment]
That's strange, `GC.Collect()` does a full gen0-gen2 collection so if they has no root - they should be collected. Can you please attach a couple of example images so I can test it locally?

**Comment by ethanrushh** [comment]
Sure thing. 
https://drive.google.com/file/d/11uurQMojLmGc2eoEbS89oPL7c3s9divS/view?usp=sharing
There is a compressed folder of example images. I tested with those and the program did what I expected it to do just fine (including the proposed memory leak still)

**Comment by br3aker** [comment]
Okay, tested it locally - allocations are small enough to fit into ,net builtin `ArrayPool` allocator:

![image](https://user-images.githubusercontent.com/20967409/172024994-c3636726-3655-4894-a7cd-dadaca65b7c6.png)

@JimBobSquarePants this can be closed as invalid as it's working as intended but it got me thinking maybe we should make this unmanaged allocator ctor public?

```cs
internal UniformUnmanagedMemoryPoolMemoryAllocator(
    int sharedArrayPoolThresholdInBytes,
    int poolBufferSizeInBytes,
    long maxPoolSizeInBytes,
    int unmanagedBufferSizeInBytes) {}
```

Or add a flag of some kind to completely turn off managed memory allocations?

**Comment by ethanrushh** [comment]
We need a flag to turn off memory allocations. This isn't a memory leak then however it is still a bug as it will crash before reusing its own pools. If you run that enough times it'll keep filling up until there is no memory left and the application crashes instead of freeing up space. 

We need either a flag to disable the memory pool or a way of reliably resetting/clearing it.

**Comment by br3aker** [comment]
> This isn't a memory leak then however it is still a bug as it will crash before reusing its own pools.

No, it won't 'crash'. You didn't provide a code to actually crash or even test such behaviour. `ArrayPool` allocates up to X amount of buffers for an app lifetime and reuses them. If you don't like this behaviour - report it to the dotnet team then, this repo has nothing to do with dotnet internals.

> This isn't a memory leak then however it is still a bug as it will crash before reusing its own pools.

This isn't a:

1. memory leak as `byte[]` buffers are managed and retained by `ArrayPool` which is expected
2. bug as it's an expected behaviour which AFAIR is even documented

> If you run that enough times it'll keep filling up until there is no memory left and the application crashes instead of freeing up space.

Did **you** run it and have test results or expect me to do that for you? Ok, here you go: 4 images from your archive loaded 50 times and drawn into 3500x3500 'main' image:

![image](https://user-images.githubusercontent.com/20967409/172047887-03f076ba-31fb-46bf-a828-4d008cdf8d48.png)

Bytes per process is around 120-124 megabytes. No 'leak', no 'crash'.

P.S.

You don't need to be so hostile to prove a point.

**Comment by ethanrushh** [comment]
My apologies if that came across as hostile, it really wasn't meant to. I think the project is really awesome and fills a gap in .NET and I'm just looking to make this work for my project. Once again, apologies.

That is the expected behaviour but not what I'm seeing. They don't get freed for me like they do for you they just keep building up until all my 32GB of memory has been allocated and the program crashes as a result. The difference in what you're seeing vs what I'm seeing is why I thought it was a memory leak initially. 

I'll test this on Windows (which you seem to be on) and within Visual Studio 2019 and see if it does it there too and report back.

**Comment by br3aker** [comment]
> That is the expected behaviour but not what I'm seeing. They don't get freed for me like they do for you they just keep building up until all my 32GB of memory has been allocated and the program crashes as a result.

Test on a very basic scenario without any callbacks or UI. Just plain:

```
for X times:
    1. load image
    2. draw on top of 'main image'
save resulting image to any format
```

Otherwise we can catch some non-related memory leaks.

BTW it's really strange that you have these objects alive after GC collections and dispose:
![image](https://user-images.githubusercontent.com/20967409/172051834-eddcf2d7-de9c-4f31-a765-89b55cca46e9.png)

----------------------

For your project code you can also do this:

```cs
MemoryDiagnostics.UndisposedAllocation += stacktrace => Console.WriteLine(stacktrace);
```

This event is fired when whatever ImageSharp buffer was leaked in user code and provides allocation stacktrace which you can log. **DO NOT** use UI code in this event as it's executed in a 'implementation specific' context. You can schedule your UI callback there though.

**Comment by ethanrushh** [comment]
Looks like when not hooked up to any UI at all it doesn't happen. Sorry for my misunderstanding here. How would you suggest I get around that? I'm not entirely sure how I would dissociate the event handler from the instance of the generator from the perspective of the garbage collector. Any ideas?

Thanks so much for your time thus far, it means a lot that you'd look into this.

I did try doing that before and I can confirm that none are reported. After checking the count of undisposed allocations I can see that it is 0 when the event ends which is why I am so confused.




![image](https://user-images.githubusercontent.com/82483782/172052691-34c473a0-8374-47dc-95f0-72253d98dfc2.png)

As you can see there when running from a UI event the memory usage is extreme even on Windows in Visual Studio 2019.

**Comment by br3aker** [comment]
> Am I correct in saying it shouldn't matter that the method I shared with you is being run from an event?

It does matter if you catch variables from outer scope.

> Looks like when not hooked up to any UI at all it doesn't happen.

Wild guess: event handler memory leak.

If you have something like this:

```cs
var img = new Image<Rgba32>(3500, 3500);

// closure is generated to hold reference to 'img' variable
// it's an anonymous lambda expression which now will be held by this event handler forever
// thus GC won't be able to collect 'img' leading to this memory leak
someButton.Click += (sender, args) => DoSomethingWithImage(img);
```

> How would you suggest I get around that?

First of all, if you have dotMemory - take a couple of snapshots and look at the 'Event handlers leak', if you have increasing number of subscribers - most likely it's the only cause of this memory leak.

**Comment by ethanrushh** [comment]
I'm not catching any variables from an outer scope. My workflow consists of never touching any imagesharp functions outside of the method I shared with you. Instead, I save as a PNG and then load that using Avalonia's Bitmap toolkit (which can handle PNG files) *so that* none of the variables could be being used in an outer scope. 

I'll play around with it and see what I can do with some memory profiling tools. I'll give dotMemory a try and see if I can figure out where things go wrong.

Thank you so very much for your time and help through this. Since this seems to be a real me-problem I'll close this issue now.
