### ISSUE TITLE
ImageSharp generates Fatal error. Internal CLR error. (0x80131506) 

### ISSUE THREAD

**Issue by TonyValenti** [SixLabors/ImageSharp#2148]
### Prerequisites

- [X] I have bought a Commercial License
- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.2

### Other ImageSharp packages and versions

NA

### Environment (Operating system, version and so on)

Windows 10, x64

### .NET Framework version

6.0.5

### Description

When publishing a ReadyToRun executable that uses ImageSharp, ImageSharp crashes the CLR.
Please see:
https://github.com/dotnet/runtime/issues/70341#issuecomment-1150558094

### Steps to Reproduce

Please see:
https://github.com/dotnet/runtime/issues/70341#issuecomment-1150558094

### Images

A single image is included in the project file attached to:
https://github.com/dotnet/runtime/issues/70341#issuecomment-1150558094

**Comment by TonyValenti** [comment]
Also, please note, this only affects executables published with ReadyToRun.  "Regular" DEBUG and RELEASE executables work fine.

**Comment by brianpopow** [comment]
This could be related to https://github.com/SixLabors/ImageSharp.Drawing/issues/93

The error message in [ImageSharp.Drawing-Issue93](https://github.com/SixLabors/ImageSharp.Drawing/issues/93) and the stack trace in [.Net-Issue70341](https://github.com/dotnet/runtime/issues/70341) both suggest that it has something to do with `System.ValueTuple`, but I am not sure how.

**Comment by brianpopow** [comment]
@TonyValenti I am not sure what we can do about this issue. This looks for me like an upstream issue.

**Comment by JimBobSquarePants** [comment]
>@TonyValenti I am not sure what we can do about this issue. This looks for me like an upstream issue.

@TonyValenti has kindly already reported this upstream for us. Good to have a tracking issue I think for stuff like this despite us being unable to do much about it.

**Comment by JimBobSquarePants** [comment]
@TonyValenti It looks like the issue has been fixed upstream with .NET 7 so I'm going to close this now.

**Comment by TonyValenti** [comment]
Thanks so much!
