### ISSUE TITLE
Regression in TIF image loading

### ISSUE THREAD

**Issue by TonyValenti** [SixLabors/ImageSharp#2149]
### Prerequisites

- [X] I have bought a Commercial License
- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.0-alpha.0.19

### Other ImageSharp packages and versions

2.1.2

### Environment (Operating system, version and so on)

Windows 11 x64

### .NET Framework version

6.0.5

### Description

@brianpopow recently made a number of performance enhancements to TIF images, however, I believe he introduced a regression that occurs when processing certain tiff files.

### Steps to Reproduce

Run this with ImageSharp 2.1.2 and the PNG file looks identical to the TIF.
Run with the latest beta and the TIF shows duplicated, smudged content as shown here.

![image](https://user-images.githubusercontent.com/13609558/173144261-16af0808-c7bb-4912-878b-b47f28e88713.png)

```
using SixLabors.ImageSharp;

namespace ConsoleApp59 {

    public static class Program {
        public static void Main(string[] args) {

            var FileIn = @"0009e03b.tif";

            var FileOut = @"OUTPUT.png";

            var Image = SixLabors.ImageSharp.Image.Load(FileIn);

            Image.SaveAsPng(FileOut);

        }
    
    }

}
```

### Images

@brianpopow - I am not comfortable publicly sharing the source image at this time.  Can you please email TV@MatterMovers.net and I will provide the image to you?

**Comment by brianpopow** [comment]
The commit causing this seems to be: 57349fd0

Not sure why the tests did not catch this one.

**Comment by TonyValenti** [comment]
@brianpopow Is it an easy fix?  If so, can you let me know when you push the update?  I'm working on a time-sensitive project.

**Comment by JimBobSquarePants** [comment]
I’ll create a PR later.

**Comment by brianpopow** [comment]
I think we need to clear the destination for the decompressed data here to fix it: https://github.com/SixLabors/ImageSharp/blob/a194b9ead7e6a930f9545f63545ef7bc6bf8c96f/src/ImageSharp/Formats/Tiff/Compression/Decompressors/T6TiffCompression.cs#L54

**Comment by brianpopow** [comment]
The issue only happens when there are multiple strips in the image. The current test images only have one strip.

Here is a test image replicating the issue:
[Group4CompressionWithStrips.zip](https://github.com/SixLabors/ImageSharp/files/8884253/Group4CompressionWithStrips.zip)

```
TIFF Directory at offset 0x1058 (4184)
  Image Width: 205 Image Length: 305
  Resolution: 96, 96 pixels/inch
  Bits/Sample: 1
  Compression Scheme: CCITT Group 4
  Photometric Interpretation: min-is-white
  FillOrder: msb-to-lsb
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Rows/Strip: 100
  Planar Configuration: single image plane
  Software: IrfanView
```

**Comment by brianpopow** [comment]
I have opened a PR to fix this: #2150

**Comment by TonyValenti** [comment]
Thank you so much!

I'm not sure how imageSharp manages the PR > commit > beta build process but I'll check in on the MyGet page throughout the day and hopefully a new build will appear soon!

**Comment by brianpopow** [comment]
> I'm not sure how imageSharp manages the PR > commit > beta build process but I'll check in on the MyGet page throughout the day and hopefully a new build will appear soon!

There will be a new MyGet beta version, once the PR is merged to the main branch.

**Comment by TonyValenti** [comment]
Thanks!  Do the PRs merge automatically or manually?  I noticed that the PR says it is unable to merge.

**Comment by brianpopow** [comment]
> Thanks! Do the PRs merge automatically or manually? I noticed that the PR says it is unable to merge.

Its manually, another one from the ImageSharp team needs to review the changes first.

**Comment by brianpopow** [comment]
@TonyValenti there is now a `alpha.0.20` version with the fix.

**Comment by TonyValenti** [comment]
@brianpopow Thank you so much!  I'm testing it now.
