### ISSUE TITLE
Wrong colors when saving image

### ISSUE THREAD

**Issue by hey-red** [SixLabors/ImageSharp#2152]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.2

### Other ImageSharp packages and versions

2.1.2

### Environment (Operating system, version and so on)

Windows 10, Ubuntu 20.04

### .NET Framework version

NET 6

### Description

After upgrading from 2.1.1 to 2.1.2, some images has saved with incorrect colors:

![output](https://user-images.githubusercontent.com/1738743/173351785-c4d5486d-22f5-47cd-b89f-da66c051d07e.jpeg)

### Steps to Reproduce

```C#
using SixLabors.ImageSharp;

using var image = Image.Load("sample.jpeg");
image.SaveAsJpeg("output.jpeg");
```

### Images

![sample](https://user-images.githubusercontent.com/1738743/173351658-e659bfe7-9fb7-4eec-8b0a-9e6545abdea8.jpeg)

**Comment by brianpopow** [comment]
This could be a duplicate of #2141. Can you try our latest beta version from our [MyGet Feed](https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp)?

**Comment by hey-red** [comment]
@brianpopow Yes, it's works. Sorry, I didn't see that PR.
