### ISSUE TITLE
Get wrong RGB value

### ISSUE THREAD

**Issue by urcllr** [SixLabors/ImageSharp#2156]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.2

### Other ImageSharp packages and versions

2.1.2

### Environment (Operating system, version and so on)

linux-mint Mate Desktop 5.4.0-110-generic x64 (uname -a)

### .NET Framework version

.net 6.0.300 (dotnet --info)

### Description

When get the color of pixel in the image file below at coordinate of [943, 2270], ImageSharp returns a wrong RGB of (218,117,45). The color should be (232,104,75) here which is confirmed by various way including mspaint.exe and C#.net(framework 4.8) running in windows, and Pinta and PHP with Imagick extension running in same Linux as ImageShap.

There may be some bug in the mechanism .net running in linux because I got the same wrong value from ZKWeb.System.Drawing code. I haven't checked if there's more wrong RGB values in other position, or more images.

I don't know whether github will change the image when it is uploaded. The original file can be accessed via http://big.119safe.cn:1981/1.jpeg

![1](https://user-images.githubusercontent.com/38638662/174052211-93b64ee5-de8c-4c15-9d90-9ddf5d0c6622.jpeg)

### Steps to Reproduce

C# using ImageSharp under linux to reproduce the wrong result:
```using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;
var img = Image.Load("1.jpeg");
var c = (img as Image<Rgb24>)[943, 2270];
Console.WriteLine($"{c.R}, {c.G}, {c.B}");
```

C# using .net framework under window to reproduce the right result:
```using System.Drawing;
var img = new Bitmap("1.jpeg");
var c = img.GetPixel(943, 2270);
Console.WriteLine($"{c.R}, {c.G}, {c.B}");
```

PHP with Imagick extension under same linux to get the right result:
```$imagick = new Imagick('./1.jpeg');
$c = $imagick->getImagePixelColor(943, 2270);
print_r($c->getColor());
```

**Comment by brianpopow** [comment]
This could be a duplicate of #2141. Can you try our latest beta version from our [MyGet Feed](https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp)?

**Comment by urcllr** [comment]
> This could be a duplicate of #2141. Can you try our latest beta version from our [MyGet Feed](https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp)?

I read that post before but I dont think my problem is not so significant as his. Now the best way is to try beta version. Thanks all helpers and sorry for my bother.

**Comment by br3aker** [comment]
@urcllr be aware that your image has ICC profile which ImageSharp doesn't take into account during color conversions yet.
