### ISSUE TITLE
Why doesn't Image.Save have an overload for Save(Image, string, IImageFormat)

### ISSUE THREAD

**Issue by Kimi-Arthur** [SixLabors/ImageSharp#2163]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.3

### Other ImageSharp packages and versions

NA

### Environment (Operating system, version and so on)

M1 Mac OSX 12.4

### .NET Framework version

6.0.301

### Description

There are several overloads for `Image.Save`. Like `Save(Image, String)`, `Save(Image, String, IImageEncoder)`, `Save(Image, Stream, IImageFormat)`, but no `Save(Image, string, IImageFormat)`, which was what I intended to use.

Any reason for not having that?

### Steps to Reproduce

Use the example as [here](https://docs.sixlabors.com/articles/imagesharp/imageformats.html#loading-and-saving-specific-image-formats) and try the given invocation in the title.

**Comment by JimBobSquarePants** [comment]
Don’t use the issue tracker for questions. See the readme.
