### ISSUE TITLE
*. Png the value of "resolution" attribute obtained from "system.drawing.bitmap" and "image.metadata" is different

### ISSUE THREAD

**Issue by 929496959** [SixLabors/ImageSharp#2164]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.3

### Other ImageSharp packages and versions

2.1.3

### Environment (Operating system, version and so on)

.net core 5

### .NET Framework version

null

### Description

*. Png the value of "resolution" attribute obtained from "system.drawing.bitmap" and "image.metadata" is different

### Steps to Reproduce

MemoryStream stream = new MemoryStream(imagebytes);
Bitmap bitmap = (Bitmap)System.Drawing.Image.FromStream(stream);
var h = bitmap.HorizontalResolution;
var w = bitmap.VerticalResolution;

var image = SixLabors.ImageSharp.Image.Load(imagebytes);
var w = image.Metadata.HorizontalResolution;
var h = image.Metadata.VerticalResolution;

**Comment by 929496959** [comment]
![1655877357601](https://user-images.githubusercontent.com/49754986/174954008-1d388f88-ccef-4a5e-b16a-6e7b9a4313f2.png)

**Comment by 929496959** [comment]
`

HttpClient client = new HttpClient();
//https://up.enterdesk.com/edpic_source/f9/95/bc/f995bc5dde86c8a32c478ac2e4ba6bd0.jpg
//http://img2.3png.com/70ee2b9d2f33557d693baccdf7a79bcda3de.png
//http://i.qqkou.com/i/1a2152275414x3673602278b26.jpg
//http://img2.3png.com/b6004052068d422d69c02d1c1e3de494f5d5.png
var imagebytes = client.GetByteArrayAsync("http://img2.3png.com/b6004052068d422d69c02d1c1e3de494f5d5.png").Result;
MemoryStream stream = new MemoryStream(imagebytes);
Bitmap bitmap = (Bitmap)Image.FromStream(stream);
var h = bitmap.HorizontalResolution;
var w = bitmap.VerticalResolution;

var image2 = SixLabors.ImageSharp.Image.Load(imagebytes);
var w2 = image2.Metadata.HorizontalResolution; 
var h2 = image2.Metadata.VerticalResolution; 
Console.ReadLine();

`

**Comment by JimBobSquarePants** [comment]
Given `http://img2.3png.com/b6004052068d422d69c02d1c1e3de494f5d5.png` (_which is actually a jpeg_) and testing the file independently with [ExifTool](https://exiftool.org/) we can see that System.Drawing is incorrect in this case.

`X Resolution`  and `Y Resolution` properties both match our output. That would indicate that the `Metadata.ResolutionUnits` property is `PixelResolutionUnit.AspectRatio` which indicates no units.

```
ExifTool Version Number         : 12.42
File Name                       : 70ee2b9d2f33557d693baccdf7a79bcda3de.png
Directory                       : C:/Users/james/Downloads
File Size                       : 35 kB
Zone Identifier                 : Exists
File Modification Date/Time     : 2022:06:22 16:01:10+10:00
File Access Date/Time           : 2022:06:22 16:01:52+10:00
File Creation Date/Time         : 2022:06:22 16:01:09+10:00
File Permissions                : -rw-rw-rw-
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
JFIF Version                    : 1.01
Resolution Unit                 : None
X Resolution                    : 1
Y Resolution                    : 1
Comment                         : CREATOR: gd-jpeg v1.0 (using IJG JPEG v90), quality = 80.
Image Width                     : 610
Image Height                    : 610
Encoding Process                : Progressive DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Image Size                      : 610x610
Megapixels                      : 0.372
-- press ENTER --
C:\Users\james\Downloads\70ee2b9d2f33557d693baccdf7a79bcda3de.png
```

**Comment by 929496959** [comment]
Sorry, I didn't expect that the extension and file header don't correspond
