### ISSUE TITLE
Decoding DXT\Uncompressed SRGB DDS is broken

### ISSUE THREAD

**Issue by Bxaa** [SixLabors/ImageSharp#2168]
<a href="https://ibb.co/GTXbcLz"><img src="https://i.ibb.co/GTXbcLz/Wrong-Decode.jpg" alt="Wrong-Decode" border="0"></a>

Example DDS:
https://drive.google.com/file/d/1pPE6i9f1EIstbKnXi61xQZLB8OBrXqyb/view?usp=sharing

**Comment by tocsoft** [comment]
Can I ask why you thought it was appropriate to completely disregard our issue template? so much so you filled it in then promptly edited your ticket to remove it all?

if you don't have the respect for us to fill in a simple form which will help us reproduce your issue then what makes you think you will receive any kind of support for your issue.

**Comment by Bxaa** [comment]
Because I am using your latest version and platform of your version
Apparently I would not have reported the error if I was using an older version or a different platform for example.

I attached a texture for you to reproduce the problem. What else do you need? The title explicitly states that all srgb is not decoded correctly

**Comment by JimBobSquarePants** [comment]
This post is not constructive and will only serve to undermine a focus on actual technical concerns.

Please don't post issues like this. We have locked this issue and banned this account.
