### ISSUE TITLE
Webp with lossy conversion weighs a lot more than lossless.

### ISSUE THREAD

**Issue by MrZnake** [SixLabors/ImageSharp#2171]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.3

### Other ImageSharp packages and versions

-

### Environment (Operating system, version and so on)

x86-64 Win11

### .NET Framework version

.NET 6.0

### Description

Webp with lossy conversion weighs more than lossless regardless of quality used.

![image](https://user-images.githubusercontent.com/20782978/178638409-fd70af06-4624-4c02-8669-aa54a9d53740.png)

### Steps to Reproduce

```csharp
using SixLabors.ImageSharp;

var image = SixLabors.ImageSharp.Image.Load("startFile.png");

image.Save("outLossless.webp", new SixLabors.ImageSharp.Formats.Webp.WebpEncoder
{
    FileFormat = SixLabors.ImageSharp.Formats.Webp.WebpFileFormatType.Lossless
});

image.Save("outLosssy90.webp", new SixLabors.ImageSharp.Formats.Webp.WebpEncoder
{
    FileFormat = SixLabors.ImageSharp.Formats.Webp.WebpFileFormatType.Lossy,
    Quality = 90,
});

image.Save("outLosssy80.webp", new SixLabors.ImageSharp.Formats.Webp.WebpEncoder
{
    FileFormat = SixLabors.ImageSharp.Formats.Webp.WebpFileFormatType.Lossy,
    Quality = 80,
});

image.Save("outLosssy50.webp", new SixLabors.ImageSharp.Formats.Webp.WebpEncoder
{
    FileFormat = SixLabors.ImageSharp.Formats.Webp.WebpFileFormatType.Lossy,
    Quality = 50,
});

image.Save("outLosssy10+Alpha.webp", new SixLabors.ImageSharp.Formats.Webp.WebpEncoder
{
    FileFormat = SixLabors.ImageSharp.Formats.Webp.WebpFileFormatType.Lossy,
    UseAlphaCompression = true,
    Quality = 10,
});

image.Dispose();
```

### Images

Start image:
![startFIle](https://user-images.githubusercontent.com/20782978/178638280-f89c6b16-e014-40e5-b57a-c75920ae598c.png)

Result images:
[test.zip](https://github.com/SixLabors/ImageSharp/files/9098453/test.zip)

**Comment by brianpopow** [comment]
Thanks @MrZnake for this bug report. I am working on a fix for this.

**Comment by brianpopow** [comment]
@MrZnake this should be fixed with #2173. If you have time could you confirm that with our nightly [MyGet](https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp) build?

**Comment by MrZnake** [comment]
@brianpopow it looks like it's okay now. Output files looks like this:
![image](https://user-images.githubusercontent.com/20782978/182608794-50a233f3-63f4-403e-ab51-662895f65089.png)

**Comment by brianpopow** [comment]
Ok, thanks for confirming, closing this then.
