### ISSUE TITLE
Jpeg loaded with pink color blur

### ISSUE THREAD

**Issue by teamnimbus** [SixLabors/ImageSharp#2174]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.2

### Other ImageSharp packages and versions

2.1.3, 3.0.0-alpha.0.11, 3.0.0-alpha.0.21

### Environment (Operating system, version and so on)

Windows 10 21H1 x64

### .NET Framework version

.Net 6.0

### Description

We stumbled on a Jpeg image that gets loaded with wrong colors on all versions after 2.1.1. Tested with 2.1.2, 2.1.3, 3.0.0-alpha.0.11 and 3.0.0-alpha.0.21.
This is very similar to issues #2133, #2141 and #2152. However we don't think it's a duplicate since it's not fixed in either 2.1.3 (like #2133) or 3.0.0-alpha.0.11 (like #2141 / #2152).

### Steps to Reproduce

This NUnit test passes on 2.1.1 and fails on all later versions with "Expected: Rgba32(255, 255, 255, 255) But was:  Rgba32(255, 128, 128, 255)".

```
[Test]
public async Task ImageShouldNotBePink()
{
	var response = await new HttpClient().GetAsync("https://www.mottafashionplace.com/media/catalog/product/1/0/10085001_11.jpg");
	await using var imageStream = await response.Content.ReadAsStreamAsync();

	var image = Image.Load<Rgba32>(imageStream);

	Assert.That(image[0, 0], Is.EqualTo(new Rgba32(255, 255, 255, 255)));
}
```

### Images

We don't own the problematic image so we can't distribute it. You can [download it](https://www.mottafashionplace.com/media/catalog/product/1/0/10085001_11.jpg) and use it as a starting point to create another image with the same properties.

**Comment by brianpopow** [comment]
The image has 3 components with no subsampling, that's why ImageSharp deduces the colorspace to RGB. It seems it should be YCbCr instead, but I am not sure how we can come to this conclusion from the components info's. The component Id's are 0, 1 and 2.

I wish the jpeg spec would define the color space properly. This guessing the colorspace from the component info's really gets out of hand.

**Comment by br3aker** [comment]
> The image has 3 components with no subsampling, that's why ImageSharp deduces the colorspace to RGB. It seems it should be YCbCr instead, but I am not sure how we can come to this conclusion from the components info's. The component Id's are 0, 1 and 2.

Actually it should be ycbcr regardless of the components' ids: 3 components without APP14 marker is YCbCr. RGB colorspace is defined by App14 marker with `flag=0`.

AFAIR we had this check did we change it some time ago?

**Comment by br3aker** [comment]
> So this seems wrong then. It was introduced with #2124, with commit: [89668a6](https://github.com/SixLabors/ImageSharp/commit/89668a6e4d6d7d1a33f05f53b40458937b62130c).

I guess we just need to remove final if check here and return ycbcr as a fallback colorspace:

https://github.com/SixLabors/ImageSharp/blob/e7a10b0c23bc4dfe4e7254a17068234f9ed7b673/src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs#L534-L540

**Comment by JimBobSquarePants** [comment]
Was just reading through the decoder there as the condition looked incorrect. Agreed on the fix.

**Comment by br3aker** [comment]
I'll open PR today.
