### ISSUE TITLE
Tiff tests failure in Debug mode

### ISSUE THREAD

**Issue by br3aker** [SixLabors/ImageSharp#2179]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

main branch

### Other ImageSharp packages and versions

none

### Environment (Operating system, version and so on)

Windows 10

### .NET Framework version

net6

### Description

[These tests](https://github.com/SixLabors/ImageSharp/blob/a194b9ead7e6a930f9545f63545ef7bc6bf8c96f/tests/ImageSharp.Tests/Formats/Tiff/TiffEncoderTests.cs#L102) fail on Debug build: 

![image](https://user-images.githubusercontent.com/20967409/179361414-a48c3cc3-4dc3-4c12-8784-18ae4ec76750.png)

But pass on Release build:
![image](https://user-images.githubusercontent.com/20967409/179361554-cdd3ab18-ac72-4405-b1e3-2c2c60aa23f6.png)

Looks like CI doesn't launch tests on Debug builds right now.

### Steps to Reproduce

Launch mentioned tests on Debug build.

**Comment by br3aker** [comment]
@brianpopow

**Comment by brianpopow** [comment]
closed via #2201
