### ISSUE TITLE
Nuget Page License is Wrong

### ISSUE THREAD

**Issue by The-MAZZTer** [SixLabors/ImageSharp#2188]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

N/A

### Other ImageSharp packages and versions

N/A

### Environment (Operating system, version and so on)

N/A

### .NET Framework version

N/A

### Description

On the nuget package page for ImageSharp (and the other related ImageSharp package pages), the license is incorrect.

Example: https://www.nuget.org/packages/SixLabors.ImageSharp/

The license is listed as Apache 2.0. Clicking it shows the standard Apache 2.0 license.

However the actual license in the github repo here is very different: https://github.com/SixLabors/ImageSharp/blob/main/LICENSE

It indicates the software is only licensable under Apache 2.0 under specific conditions, instead of all the time as nuget suggests.

Please fix the nuget packages in the next releases to reflect the actual licenses. Currently it may be misleading to those who use that as a primary source of licensing information.

### Steps to Reproduce

1. Visit nuget package pages.
2. Click on license link.
3. Go to github repo.
4. Click on license file.
5. Observe terms between the two license files do not match, specifically no mention of commercial licensing in the nuget page license.

### Images

https://www.nuget.org/packages/SixLabors.ImageSharp/

**Comment by JimBobSquarePants** [comment]
No it’s not. That’s v2. Please read #2151

**Comment by The-MAZZTer** [comment]
Ah sorry. I was a bit confused and panicked since my coworkers at work have
been pushing ImageSharp and I am certain we have no commercial license.
Thanks for clarifying. Should have realized someone else would have
reported something like this already.

**Comment by JimBobSquarePants** [comment]
No worries. You’re coworkers are wise to push ImageSharp though. It’s awesome 😉
