### ISSUE TITLE
IPTC tags written on jpg files that contains non-English characters can't be correctly displayed on external apps

### ISSUE THREAD

**Issue by lmerino-ep** [SixLabors/ImageSharp#2212]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.3

### Other ImageSharp packages and versions

None

### Environment (Operating system, version and so on)

Windows 10 21H2

### .NET Framework version

6

### Description

The IPTC text tags on jpg files that contains non-English characters are displayed incorrectly on external apps, even though they are written using the default utf-8 encoding.

The use of utf-8 encoding is not indicated on the envelope record. External apps may use that record to identify the encoding and can assume the use of "ascii" encoding if not present.

I've written a patch that adds the optional tag (1:90 Coded Character Set) that indicates the use of utf-8 encoding on the text tags and solves this case.  I can open a pull request or share the code with you.

### Steps to Reproduce

1. Load any jpg file.
2. Write any text tag on IptcProfile, for example: Caption  using non-English characters, such as "ESPAÑA".
3. Save the changes on a new file.
4. Open the new file with Irfanview, menu "Image -> Information", button "IPTC info".
5. The caption tag shows "ESPAÃ‘A" instead of "ESPAÑA".

```
 void Test()
        {
            const string fileInput = "c:\\temp\\input1.jpg"; // whatever jpg file
            const string fileOutput = "c:\\temp\\output1.jpg";

            using (SixLabors.ImageSharp.Image img = SixLabors.ImageSharp.Image.Load(fileInput))
            {
                if (img.Metadata.IptcProfile == null)
                {
                    img.Metadata.IptcProfile = new IptcProfile();
                }
                img.Metadata.IptcProfile.SetValue(IptcTag.Caption, "ESPAÑA");
                img.SaveAsJpeg(fileOutput, new JpegEncoder() { Quality = 90 });
            }
        }
```
This is the actual result:
![wrong_iptc_irfanview](https://user-images.githubusercontent.com/111735602/185955404-ce29496a-3103-4dab-b338-85e0682d1fbe.PNG)

This is the expected result:
![ok_iptc_irfanview](https://user-images.githubusercontent.com/111735602/185956493-cef7ca3f-0250-4830-ab04-f5e5f846c561.PNG)

I've fixed this adding the 1:90 "Coded Character Set" to the Envelope record on IptcProfile.UpdateData() method. 

### Images

![input1](https://user-images.githubusercontent.com/111735602/185953183-2582ac33-d443-4822-ad53-d1ef0bb91401.jpg)

**Comment by tocsoft** [comment]
@lmerino-ep thanks for finding this. Please feel free to open a PR with the fix.
