### ISSUE TITLE
In a Blazor Web Assembly project, async function calls are blocking the execution of UI side

### ISSUE THREAD

**Issue by auyargicoglu** [SixLabors/ImageSharp#2214]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.3

### Other ImageSharp packages and versions

No other ImageSharp packages

### Environment (Operating system, version and so on)

Blazor Web Assembly

### .NET Framework version

Net Core 6.0

### Description

Although I've used **async** ImageSharp functions with **await** keyword, none of the **UI** callback functions are called, since all the processing power is somehow consumed by the **ImageSharp** library. At this point the only thing I want to achieve is to show and update a very simple progress bar. I believe that there should be a mechanism to give some breath to UI callbacks. For example when I give a derived MemoryStream to LoadAsync function with an overridden CopyToAsync function, which sometimes calls Task.Delay(1) inside of it,  UI becomes responsive as required. (Of course I know that, such a delay call slows down the code, but it is really better to give indication that code is still running!)  

As a result, on the single threaded environment of Blazor Web Assembly, async functions aren't working as expected , they are executed just like sync functions and block the program until their return. 

### Steps to Reproduce

1. Take a large image and store it a MemoryStream, in my case it is downloaded my image from my backend side
2. Try to create an Image instance by calling LoadAsync
3. After creating the image, I used Mutate to rotate the image (There isn't any async versions of this function)
4. Save it into a MemoryStream in order to upload it to mybackend
5. Problem occurs between 1 and 4, the library can successfully give the rotated image, but at this time user interface becomes unresponsive. As the input image file becomes larger, UI becomes unresponsive for a longer time.

**Comment by JimBobSquarePants** [comment]
I'd raise this with the dotnet team.

**Comment by louisjrdev** [comment]
Maybe not 100% the solution you are after, but perhaps move all that code into a [WebWorker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers), the browser only runs JS on a single thread ordinarily

**Comment by Webreaper** [comment]
This will likely improve once the .Net Blazor WebAssembly Multi-threading issue is completed (https://github.com/dotnet/aspnetcore/issues/17730). I haven't read the whole thread, but I think it might not make it into .Net 7 this year, but it is coming...

**Comment by JimBobSquarePants** [comment]
That's the exact issue I was thinking about. We can't do anything about this here. If we're lucky we'll get out of band support but I think .NET 8 is more likely. 

I'm gonna close this and mark as an upstream issue.
