### ISSUE TITLE
AdaptiveThresholdProcessor throws IndexOutOfRangeException

### ISSUE THREAD

**Issue by mjeanrichard** [SixLabors/ImageSharp#2217]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.3

### Other ImageSharp packages and versions

none

### Environment (Operating system, version and so on)

Windows 10

### .NET Framework version

.net 6

### Description

The attached image produces a IndexOutOfRangeException when mutated with the AdaptiveThresholdProcessor.
It might be because the Image is black and white already?

### Steps to Reproduce

1. Create a new console application
2. Add the attached image as embedded resource
3. Put the following code in `Program.cs`
```csharp
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;
using SixLabors.ImageSharp.Processing.Processors.Binarization;

Stream? stream = typeof(Program).Assembly.GetManifestResourceStream("ConsoleApp1.TestImage.png");
Image<Rgba32> image = await Image.LoadAsync<Rgba32>(stream);
AdaptiveThresholdProcessor p = new();

image.Mutate(i => i.ApplyProcessor(p));
```
5. Run

### Images

![TestImage](https://user-images.githubusercontent.com/778448/187073251-5d23775b-f4b9-459b-a686-e2556401a1f7.png)

**Comment by brianpopow** [comment]
closed via #2221
