### ISSUE TITLE
CRC Error. PNG IDAT chunk is corrupt

### ISSUE THREAD

**Issue by klou456** [SixLabors/ImageSharp#2223]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.3

### Other ImageSharp packages and versions

non

### Environment (Operating system, version and so on)

Windows 10

### .NET Framework version

.net 6

### Description

See the .Net 6.0 Blazor Server code  below
When upload a file, I get Error  "CRC Error. PNG IDAT chunk is corrupt" on   using (Image image = Image.Load(buffer))
However, it works on .net 5.0

@page "/largefiles"
@using SixLabors.ImageSharp;
@using SixLabors.ImageSharp.PixelFormats;
@using SixLabors.ImageSharp.Processing;
<h3>Upload file</h3>

<InputFile  OnChange="@( (InputFileChangeEventArgs e) => OnLargeFileInputFileChange(e, "P") )"  />
@code
{
//@*OnChange="OnLargeFileInputFileChange"*@
    long UploadedBytes;
    async Task OnLargeFileInputFileChange(InputFileChangeEventArgs args, string type)
    {
        await InvokeAsync(StateHasChanged);
        string justFileName = Path.GetFileNameWithoutExtension(args.File.Name);
        string extension = Path.GetExtension(args.File.Name);
        string newFileNameWithoutPath = $"{justFileName}-{DateTime.Now.Ticks.ToString()}{extension}";
        string filename = $"{Environment.CurrentDirectory}\\files\\{newFileNameWithoutPath}";

        long TotalBytes = args.File.Size;
        int ImageWidth = 1600;
        int ImageHeight = 1200;
        if (File.Exists(filename))
        {
            File.Delete(filename);
        }
        using (var inStream = args.File.OpenReadStream(long.MaxValue))
        {
                var buffer = new byte[TotalBytes];
                await inStream.ReadAsync(buffer, 0, buffer.Length);
                try
                {
                    using (Image image = Image.Load(buffer))
                    {
                        if (image.Width < 1600) ImageWidth = image.Width;                        
                        if (image.Height < 1200) ImageHeight = image.Height;
                        image.Mutate(x => x.Resize(ImageWidth, ImageHeight));
                        image.Save(filename); 
                    }
                }
                catch (Exception ex)
                {
                    string Message = ex.Message.ToString();
                }
                await InvokeAsync(StateHasChanged);
        }
    }

### Steps to Reproduce

Using VS 2022 to create a .Net 6.0 Blazor server application, create a page and copy the code above to this page.
Install Sixlabors.ImagesSharp 2.1.3 by Nuget Package Manager. 
Upload the attached image file, you will get the error; CRC Error. PNG IDAT chunk is corrupt

Change the application from .Net 6.0 to .Net 5.0. it works without any error

### Images

![Chrysanthemum](https://user-images.githubusercontent.com/11756536/189400877-5b0ce293-2d05-4a3d-9293-2074d26358fd.jpg)

**Comment by brianpopow** [comment]
@klou456 Is that Blazor Server code really necessary to trigger the issue? Would just loading the image trigger this? It would be good to have a simpler reproduction, I am not familiar with blazor.

**Comment by brianpopow** [comment]
There is maybe an issue on how you read the data from the stream: 

`await inStream.ReadAsync(buffer, 0, buffer.Length)`

You should check the return value to actually match the number of bytes you want to read. From the documentation:

```
... The result value can be less than the number of bytes allocated in the buffer if that many bytes are not currently available, or it can be 0 (zero) if the end of the stream has been reached.
```

**Comment by JimBobSquarePants** [comment]
That’ll be exactly the issue. Stream reading was changed in .NET in a manner which enforced the need to use the APIs properly. 

Why are you allocating and reading to that intermediate buffer? Use `Image.LoadAsync`

**Comment by klou456** [comment]
Jim, 
what I try to do is uploading image files and resize them if sizes are bigger than 1600 X 1200 (for example) in a Blazor Server .Net 6.0 app. The the same code works on .Net 5.0. 
So what is your suggestion? Is it possible to send me a piece of code you think will resolve my issues? Anything I can change However I have to use  Blazor Server .Net 6.0. Thanks

**Comment by JimBobSquarePants** [comment]
Both the problem and solution have been described above. You’re expecting the stream read to always return the desired length which, as documented in the MS docs is an incorrect assumption.

You can avoid the issue entirely by reading the stream directly using `LoadAsync` instead of reading to the `byte[]` buffer.

**Comment by klou456** [comment]
Thanks Jim, It works!

**Comment by enkodellc** [comment]
I am getting this error with a png on my server side blazor / .net core 6. I tried LoadAsync as well with no luck.
