### ISSUE TITLE
TiffEncoder with TiffCompression throws System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by lennart02** [SixLabors/ImageSharp#2255]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.3

### Other ImageSharp packages and versions

-

### Environment (Operating system, version and so on)

Windows 11 x64

### .NET Framework version

6.0

### Description

I wanted to convert my base64-Image (which is a .png file) to a Tiff Image and use the **CcittGroup3Fax** compression.

```

System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=SixLabors.ImageSharp
  StackTrace:
   at SixLabors.ImageSharp.Formats.Tiff.Compression.Compressors.TiffCcittCompressor.WriteCode(UInt32 codeLength, UInt32 code, Span`1 compressedData) in /_/src/ImageSharp/Formats/Tiff/Compression/Compressors/TiffCcittCompressor.cs:line 492

```

```
This exception was originally thrown at this call stack:
    SixLabors.ImageSharp.Formats.Tiff.Compression.Compressors.TiffCcittCompressor.WriteCode(uint, uint, System.Span<byte>)
    SixLabors.ImageSharp.Formats.Tiff.Compression.Compressors.T4BitCompressor.CompressStrip(System.Span<byte>, int, System.Span<byte>) in T4BitCompressor.cs
    SixLabors.ImageSharp.Formats.Tiff.Compression.Compressors.TiffCcittCompressor.CompressStrip(System.Span<byte>, int) in TiffCcittCompressor.cs
    SixLabors.ImageSharp.Formats.Tiff.Writers.TiffCompositeColorWriter<TPixel>.EncodeStrip(int, int, SixLabors.ImageSharp.Formats.Tiff.Compression.TiffBaseCompressor) in TiffCompositeColorWriter{TPixel}.cs
    SixLabors.ImageSharp.Formats.Tiff.Writers.TiffBaseColorWriter<TPixel>.Write(SixLabors.ImageSharp.Formats.Tiff.Compression.TiffBaseCompressor, int) in TiffBaseColorWriter{TPixel}.cs
    SixLabors.ImageSharp.Formats.Tiff.TiffEncoderCore.WriteFrame<TPixel>(SixLabors.ImageSharp.Formats.Tiff.Writers.TiffStreamWriter, SixLabors.ImageSharp.ImageFrame<TPixel>, SixLabors.ImageSharp.Metadata.ImageMetadata, SixLabors.ImageSharp.Image<TPixel>, long) in TiffEncoderCore.cs
    SixLabors.ImageSharp.Formats.Tiff.TiffEncoderCore.Encode<TPixel>(SixLabors.ImageSharp.Image<TPixel>, System.IO.Stream, System.Threading.CancellationToken) in TiffEncoderCore.cs
    SixLabors.ImageSharp.Formats.ImageEncoderUtilities.Encode<TPixel>(SixLabors.ImageSharp.Formats.IImageEncoderInternals, SixLabors.ImageSharp.Image<TPixel>, System.IO.Stream) in ImageEncoderUtilities.cs
    SixLabors.ImageSharp.Formats.Tiff.TiffEncoder.Encode<TPixel>(SixLabors.ImageSharp.Image<TPixel>, System.IO.Stream) in TiffEncoder.cs
    SixLabors.ImageSharp.Image.EncodeVisitor.Visit<TPixel>(SixLabors.ImageSharp.Image<TPixel>) in Image.cs

```

### Steps to Reproduce

I used this piece of code:

      string base64Input = File.ReadAllText("TestFiles/imageExample_Base64String.txt");
      byte[] byteArr = System.Convert.FromBase64String(base64Input);
      using (MemoryStream msIn = new MemoryStream(byteArr, 0, byteArr.Length))
      {
        SixLabors.ImageSharp.Image img = SixLabors.ImageSharp.Image.Load(msIn);

        SixLabors.ImageSharp.Image<Rgba32> imageWithoutTransparency = new(img.Width, img.Height);

        imageWithoutTransparency.Mutate(x => x.Fill(SixLabors.ImageSharp.Color.White)
                                               .DrawImage(img, 1));
        IImageEncoder tiffEncoder = new SixLabors.ImageSharp.Formats.Tiff.TiffEncoder()
        {
          Compression = SixLabors.ImageSharp.Formats.Tiff.Constants.TiffCompression.CcittGroup3Fax,
          CompressionLevel = SixLabors.ImageSharp.Compression.Zlib.DeflateCompressionLevel.DefaultCompression,

        };

        using (MemoryStream msOut = new MemoryStream())
        {
          imageWithoutTransparency.Save(msOut, tiffEncoder);
          return msOut.ToArray();
        }
      }

You can use this Base64 Test File:

[TestFiles.zip](https://github.com/SixLabors/ImageSharp/files/9722641/TestFiles.zip)

**Comment by brianpopow** [comment]
The problem is that the `BitsPerPixel` is not choosen correctly here. Its not `TiffBitsPerPixel.Bit1`, which it should be for this compression method. 

You can enforce it to be 1 Bit by setting the encoder option `BitsPerPixel = TiffBitsPerPixel.Bit1`, which should fix your issue, but we should change the encoder to choose 1-Bit, when the compression is one of the 1-Bit type.

Also note: `CompressionLevel = SixLabors.ImageSharp.Compression.Zlib.DeflateCompressionLevel.DefaultCompression`, will not have a effect on the 1-Bit compressions.

**Comment by lennart02** [comment]
Thank you, that really helped my problem.
