### ISSUE TITLE
Can't open some TIFs files (System.NotSupportedException: The specified TIFF photometric interpretation is not supported: Separated)

### ISSUE THREAD

**Issue by aistvan** [SixLabors/ImageSharp#2263]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.3

### Other ImageSharp packages and versions

No

### Environment (Operating system, version and so on)

Windows

### .NET Framework version

net6

### Description

I tried this lib at first time, with TIFF's and now, I have no clue, why I get tis exception.

`System.Private.CoreLib: Exception while executing function: ResizeImage. SixLabors.ImageSharp: The specified TIFF photometric interpretation is not supported: Separated.`

Does anyone have any solution for this?

### Steps to Reproduce

```
using (Image<Rgba32> input = Image.Load<Rgba32>(image, out format))
{
   ...
}
```

### Images

I only have copyrighted images unfortunately.

**Comment by brianpopow** [comment]
Closing with #2268 merged

**Comment by aistvan** [comment]
> Are you serious? Have you tried reading the exception? What is unclear in "The specified TIFF photometric interpretation is not supported"?

Yes, I'm serious. I think an image handling lib's one of the most important goal must be to support the image hanling itself.
And yes, I read the exception, but for me, who is not an "imaging" developer, it doesn't say anything.

> It's one of the million different variant's of tiff, someone needs to implement support for this.

Nice. I tried to keep myself away from tiff images, but we have marketing and they used it a lot.
I must support them. If ImageSharp doesn't work for me, I have to look for another lib. I don't want to write a new one.

**Comment by JimBobSquarePants** [comment]
Do you pay for this? Does marketing?

**Comment by aistvan** [comment]
> Do you pay for this? Does marketing?

No. Wife.
