### ISSUE TITLE
PNG can only save as R8 for 1 component formatting but Images only support A8

### ISSUE THREAD

**Issue by Jacbo1** [SixLabors/ImageSharp#2273]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.3

### Other ImageSharp packages and versions

SixLabors.ImageSharp.Drawing 1.0.0-beta15

### Environment (Operating system, version and so on)

Windows 11

### .NET Framework version

.NET 6.0

### Description

The PngEncoder can only save in R8 if you want a 1 component output but images only support 1 component images as A8. If the image tries to convert, it just converts all pixels to byte.MaxValue. This means it's impossible to save and load them without additional color channels.

### Steps to Reproduce

See above

**Comment by JimBobSquarePants** [comment]
We need a lot more information here. I do not understand the issue you have raised.

**Comment by Jacbo1** [comment]
Images only have 1 pixel format that supports a single color component (A8) and PngEncoder also only has one pixel format that supports a single color component which is R8 (named Grayscale). When ImageSharp tries to save A8 as R8, it sets every pixel in the new image to 255 instead of the alpha value. This is true for trying to load an R8 png. It just loads an image of the same resolution with every pixel set to A 255.

**Comment by JimBobSquarePants** [comment]
>Images only have 1 pixel format that supports a single color component (A8) 

Image? What images.

**Comment by Jacbo1** [comment]
The Image class

**Comment by Jacbo1** [comment]
> Image? What images.

The Image class e.g. `Image<A8>`
> The `PngEncoder` supports encoding many different pixel format based on the `PngColorType` value passed to the encoder.

![image](https://user-images.githubusercontent.com/86734639/196847031-c4abd379-eea7-4975-8825-61c982b52ab0.png)
Grayscale is the only one that supports 1 color component and it is incompatible with `Image<A8>`

**Comment by JimBobSquarePants** [comment]
There are currently 3 pixel-formats that hold a single component. 

1. `A8` (Alpha 0-255)
2. `L8` (Luminance 0-255)
3. `L16` (Luminance 0-65535)

Both `L8` and `L16` calculate the luminance based upon the formula defined by ITU-R Recommendation BT.709

There's no such thing as `R8`. Nor does the png specification support such a thing. For bit depths of less than 8 you must use `PngColorType.Palette` which uses the built in quantizer (or one you can pass to the encoder) to create a palette of that bit depth and encode the image accordingly.

**Comment by Jacbo1** [comment]
> There's no such thing as R8. Nor does the png specification support such a thing.

I mean... that's how the png encoder in Unity saves them. And that's how they seem to be stored. ImageSharp certainly isn't loading them properly when stored to A8.

**Comment by JimBobSquarePants** [comment]
If what you are looking for is new pixel formats to represent the separate R, G, and B components then that is a feature request, and you should not have opened an issue.

**Comment by Jacbo1** [comment]
![brush_circle](https://user-images.githubusercontent.com/86734639/196849111-afe10a9c-1e23-4306-8925-4995475b054b.png)

**Comment by Jacbo1** [comment]
Loading this as A8 and drawing to an Image<Argb32> just draws a black square

**Comment by JimBobSquarePants** [comment]
>Loading this as A8 and drawing to an Image<Argb32> just draws a black square

Which is absolutely expected since the alpha component of each pixel in the image at 8 bits is 255 and there is no information for the R-G-B components. 

```
A8        Argb32
==============
A    =>     A
     =>     R
     =>     G
     =>     B
```

I've independently verified our image and it is an 8-bit image encoded with grayscale format. `L8` would be the most appropriate pixel format to use as it was designed specifically for that scenario.  

<img width="528" alt="image" src="https://user-images.githubusercontent.com/385879/196850785-497cf84f-b995-45d3-9d37-9521722ba5fa.png">

**Comment by Jacbo1** [comment]
Alright that works. I had no idea what L8 was and the description made it seem like some advanced format with complicated operations.
