### ISSUE TITLE
IccProfile Comment is Incorrect

### ISSUE THREAD

**Issue by pha3z** [SixLabors/ImageSharp#2287]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.3

### Other ImageSharp packages and versions

none

### Environment (Operating system, version and so on)

Windows 10

### .NET Framework version

.NET 5

### Description

XML Comment for IImageInfo.Metadata.ICCProfile appears to be incorrect.

It says

> Gets or sets the list of ICC profiles.

But it returns a single ICC Profile (as expected).  The comment confused me and made me wonder if there's actually supposed to be a way to get multiple profiles.

Comment should probably read:

> Gets or sets the ICC profile.

### Steps to Reproduce

Create a new project and use ImageSharp to Identify a file:

> var info = SixLabors.ImageSharp.Image.Identify(imgFilepath);
> var icc = info.Metadata.IccProfile;

Highlight over "IccProfile" to see the intellisense XML comment.

**Comment by JimBobSquarePants** [comment]
Thanks for this. Please open a PR.
