### ISSUE TITLE
Gifs sometimes get optimized incorrectly

### ISSUE THREAD

**Issue by SigmundurMorkore** [SixLabors/ImageSharp#2288]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

v2.1.3

### Other ImageSharp packages and versions

ImageSharp.Web 2.0.2

### Environment (Operating system, version and so on)

Linux and Mac

### .NET Framework version

6

### Description

When doing any processing on some gifs, the output isn't correct.

**Example 1**
This is the original gif:
![51819_osvart_orkushow](https://user-images.githubusercontent.com/39065262/199743803-8c77ce68-de3d-457b-8b85-9ff6d338f553.gif)
When sending it through ImageSharp.Web with any query parameters, even inconsequential ones, the output gif is extremely slow (with `rmode=crop`):
![imagesharp-51819_osvart_orkushow](https://user-images.githubusercontent.com/39065262/199744281-efd3090c-5315-405d-8fd1-0263229be47a.gif)

**Example 2**
This is the original gif:
![irishpublysing](https://user-images.githubusercontent.com/39065262/199744718-7989990d-7fb0-4a17-8b8a-20ababc4cac4.gif)
When sending it through ImageSharp.Web with any query parameters, even inconsequential ones, the output gif has the first "V" in the smaller text almost turned into a "M" (with `rmode=crop`):
![imagesharp-irishpublysing](https://user-images.githubusercontent.com/39065262/199744984-a1ea3974-0bed-407f-86c9-af513fa73af1.gif)

### Steps to Reproduce

1. Run a gif through ImageSharp.Web
2. It may or may not have things that are incorrect

### Images

![51819_osvart_orkushow](https://user-images.githubusercontent.com/39065262/199743803-8c77ce68-de3d-457b-8b85-9ff6d338f553.gif)
![imagesharp-51819_osvart_orkushow](https://user-images.githubusercontent.com/39065262/199745525-4c8bed21-0824-4572-82da-0bacfceef4b5.gif)

![irishpublysing](https://user-images.githubusercontent.com/39065262/199744718-7989990d-7fb0-4a17-8b8a-20ababc4cac4.gif)
![imagesharp-irishpublysing](https://user-images.githubusercontent.com/39065262/199745513-c20deb2d-62be-4981-a496-3f3e31d3bf95.gif)

**Comment by JimBobSquarePants** [comment]
I think the issue here is that we always encode the GraphicsControlExtension even though it is optional. I should be able to code up a workaround to prevent this.

**Comment by SigmundurMorkore** [comment]
@JimBobSquarePants awesome :D

Is the weird artifacting (around the "V") in the second example a separate issue?

**Comment by JimBobSquarePants** [comment]
Ah... Didn't spot that. Separate issue. Not sure what the cause is there....Yet

**Comment by JimBobSquarePants** [comment]
OK. The issue there is that the image contains both global and local color tables but we only support one or the other. 

BTW. I wouldn't currently recommend resizing/cropping multi-frame gifs in this manner with ImageSharp. Unfortunately, a current architectural limitation requires that all frames are the same size so each frame is padded if smaller to match. This can lead to multi-frame images being much larger following processing than the input.

**Comment by SigmundurMorkore** [comment]
Aah I see, makes sense 👍 

Is it possible for ImageSharp to implement support for gifs with both kinds of color tables?
I may want to look into a tool that can convert gifs with both global and local color tables to just use one or the other.

Thanks for the info on resizing/cropping!

**Comment by JimBobSquarePants** [comment]
It's absolutely possible. Working on a fix just now. Might take me a few days though.

**Comment by JimBobSquarePants** [comment]
![OptionalExtensionsShouldBeHandledProperly_Rgba32_issue_2288_2](https://user-images.githubusercontent.com/385879/200345287-327698ac-69f2-46b9-9347-3a54e3e985f4.gif)

Got some cleanup and investigation to do but this is major progress

**Comment by SigmundurMorkore** [comment]
That looks perfect! ❤️
