### ISSUE TITLE
VB.NET - Problem with transparent background PNG and ImageSharp quantizer

### ISSUE THREAD

**Issue by wjbode** [SixLabors/ImageSharp#2304]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

v4.0.30319

### Other ImageSharp packages and versions

N/A

### Environment (Operating system, version and so on)

Windows 10 Enterprise 21H2 64 bit

### .NET Framework version

4.7.2

### Description

I am trying to make a WinForms app in VB.NET (Framework 4.7.2) that optimizes an electronic signature using ImageSharp, and I am running into a problem. When I try to use the OctreeQuantizer to decrease the number of colors in the PNG, I get an inverted / negative image if the source has a transparent background. This is a problem since the signature will need to be transparent when it is applied to a document.

See [StackOverflow Question](https://stackoverflow.com/questions/74735320/vb-net-problem-with-transparent-background-png-and-imagesharp-quantizer)

### Steps to Reproduce

Quantize function: 
```
    Public Shared Function QuantizeImageGrayscalePNG(ByVal vstrSource As String, ByVal vintMaxColors As Integer) As Bitmap
        Dim poqQuant As New OctreeQuantizer()
        Dim pencPNG As New PngEncoder() With {.BitDepth = PngBitDepth.Bit8, .ColorType = PngColorType.GrayscaleWithAlpha}

        vintMaxColors = Math.Min(256, vintMaxColors)
        If vstrSource IsNot Nothing AndAlso IO.File.Exists(vstrSource) AndAlso vintMaxColors > 0 Then
            Using piNew As Image = Image.Load(vstrSource),
                  pstOutput As New IO.MemoryStream()

                poqQuant.Options.MaxColors = vintMaxColors

                piNew.Mutate(Sub(x) x.Quantize(poqQuant))
                piNew.Save(pstOutput, pencPNG)

                Return Bitmap.FromStream(pstOutput)
            End Using
        Else
            Return Nothing
        End If
    End Function
```

### Images

Original Image:
![Hancock](https://user-images.githubusercontent.com/60433243/207645114-640c55b7-544c-4c25-8f0e-76390544b4d3.png)

Quantized Image:
![Hancock Quantized](https://user-images.githubusercontent.com/60433243/207646756-f42f4e57-64c2-46c4-9d83-5d8904b57b99.png)

**Comment by JimBobSquarePants** [comment]
Octree only supports a single transparent color . For Png you need to use the Wu quantizer which is the default quantizer.

However, if you are trying to reduce the colors in a png you should be saving it in indexed format by setting the PngColorType in the encoder along with a custom Wu quantizer with your max color count.
