### ISSUE TITLE
SixLabors.ImageSharp.UnknownImageFormatException: 'Image cannot be loaded. 

### ISSUE THREAD

**Issue by xiaoxstz** [SixLabors/ImageSharp#2307]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.3

### Other ImageSharp packages and versions

None

### Environment (Operating system, version and so on)

Windows 10, VS2022

### .NET Framework version

.NET 6

### Description

The code below throw the error.
```CSharp
            byte[] pixelData = new byte[16] { 0, 0 ,0,0,
                                            1,1,1,1,
                                            2,2,2,2,
                                            3,3,3,3};
            Image image = Image<Rgba32>.Load(pixelData);
            image.SaveAsBmp("pixelData.bmp");
```

The error information is
> SixLabors.ImageSharp.UnknownImageFormatException: 'Image cannot be loaded. Available decoders:
> - TGA : TgaDecoder
> - BMP : BmpDecoder
> - PBM : PbmDecoder

#1406 has the same error. But the code is different and it's not helpful.

### Steps to Reproduce

Put the code above in  C# programs. And then run it

**Comment by JimBobSquarePants** [comment]
That data is not an encoded image format. You're using the wrong method.

You want [`Image<TPixel> LoadPixelData<TPixel>(byte[] data, int width, int height)`](https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Image.html#SixLabors_ImageSharp_Image_LoadPixelData__1_System_Byte___System_Int32_System_Int32_)
