### ISSUE TITLE
After adding watermark to an image a shade of red tint color is appearing in the image background, which is affecting the original image used. Please provide a solution to rectify this.

### ISSUE THREAD

**Issue by SureshKumarRamakodirajan** [SixLabors/ImageSharp#2314]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

1.0.0-beta13

### Other ImageSharp packages and versions

SixLabors.ImageSharp(1.0.3),SixLabors.Fonts(1.0.0-beta15)

### Environment (Operating system, version and so on)

Linux

### .NET Framework version

.Net core 5.0

### Description

When adding watermark for an image, the color of the watermark is affecting the image's original color. The original color of the image is Grey, but when adding a red color text watermark to the image, the image background color is slightly varying to red tint color. Please provide a solution to resolve this.

Screenshot showing the variation between images:
![new-metal-auto-parts-grey-background_93675-87569](https://user-images.githubusercontent.com/121957631/210593744-c059a457-7926-4817-bf12-e0637cc6f305.jpg)

### Steps to Reproduce

Select an image and add watermark to it. There will be variation between the original image and the image after watermark is added.

### Images

This is the original image that has been used
![new-metal-auto-parts-grey-background_93675-87569](https://user-images.githubusercontent.com/121957631/210594240-4c4cceef-0c5b-469e-afd6-e356dc2fdf35.jpg)

The below screenshot shows the variation between the images after applying watermark. (Note: The image shown in the right side is the original image, the image in the left is after applying watermark)
![Screenshot 2023-01-04 211833](https://user-images.githubusercontent.com/121957631/210594396-a97251f6-521d-402e-9fbd-8e103aa2bd44.jpg)

**Comment by dlemstra** [comment]
Please provide a code sample that demonstrates this issue.

**Comment by tiesont** [comment]
Also: `1.0.0-beta13` - is that correct? Any particular reason for using a beta from almost three years ago?

**Comment by JimBobSquarePants** [comment]
- [X] I have verified that I am running the latest version of ImageSharp

@SureshKumarRamakodirajan it's very important that you accurately complete this issue template. We do not support prior versions of the library, especially beta versions.

**Comment by JimBobSquarePants** [comment]
I'm closing this due to the long obsolete version number. @SureshKumarRamakodirajan if you still have problems with the latest v3 builds on MyGet feel free to open another issue here.
