### ISSUE TITLE
Exception Input stream does not have enough bytes in version 2.1.1+

### ISSUE THREAD

**Issue by ratapwnz** [SixLabors/ImageSharp#2315]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.1 - 2.1.3

### Other ImageSharp packages and versions

2.1.1 - 2.1.3

### Environment (Operating system, version and so on)

Windows 10

### .NET Framework version

.NET 6

### Description

I found valid (from my point of view) JPG image that fails to load from starting from version 2.1.1.
2.1.0 and lower and also other image processing libs works fine with this image. Image attached.

### Steps to Reproduce

`using var image = Image.Load("image path");`

### Images

![site137](https://user-images.githubusercontent.com/61802814/210805817-989c8b80-1b6a-447e-8ccc-42eaf0bf3e82.jpg)

**Comment by br3aker** [comment]
Most likely fixed here: https://github.com/SixLabors/ImageSharp/pull/2147
Wasn't released but you can try it in the preview version package: https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp

**Comment by JimBobSquarePants** [comment]
@ratapwnz Are you able to confirm?
