### ISSUE TITLE
Webp images are being processed and come out 10x larger

### ISSUE THREAD

**Issue by thomas-gregg-bz-agency** [SixLabors/ImageSharp#2332]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.3

### Other ImageSharp packages and versions

None

### Environment (Operating system, version and so on)

Windows 10 and Windows Server 2022 Std

### .NET Framework version

.NET 6.0

### Description

As per the title when we upload an image in webp format, the resulting image comes out roughly 10 times bigger. We have not seen this for other image formats

### Steps to Reproduce

Checkout another bug report through the Pirhana CMS github - https://github.com/PiranhaCMS/piranha.core/issues/1975

**Comment by JimBobSquarePants** [comment]
Re you sure this isn't related to https://github.com/SixLabors/ImageSharp/issues/2216 ?

You've not really provided enough information to replicate.

**Comment by thomas-gregg-bz-agency** [comment]
Yes it does seem like it is related to this, the developer said to include the following

using (var image = Image.Load(source, out IImageFormat format))
{
    image.Mutate(x => x.AutoOrient());
    image.Save(dest, format);
}

This is where the processing takes place and results in the larger image. I will add the above 2 issues to the issue over at Pirhana to see if this helps. What are your thoughts @JimBobSquarePants

**Comment by JimBobSquarePants** [comment]
That's not enough to replicate without the input image. WebP has multiple encoding configurations, so we need to know the configuration.

I would recommend testing the image against the latest v3 builds. The MyGet feed link is listed in our readme.

**Comment by JimBobSquarePants** [comment]
@thomas-gregg-bz-agency How did you get on with your test?

**Comment by thomas-gregg-bz-agency** [comment]
@JimBobSquarePants I have just tested ina simple console app and it works as expected now with v3. Thanks very much for your help on this.

**Comment by JimBobSquarePants** [comment]
@thomas-gregg-bz-agency Thanks for testing, really appreciate it.
