### ISSUE TITLE
Input stream does not have enough bytes to parse declared contents of the 00 marker.

### ISSUE THREAD

**Issue by ThomasWirz** [SixLabors/ImageSharp#2334]
### Prerequisites

- [X] I have bought a Commercial License
- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.3

### Other ImageSharp packages and versions

2.1.1, 2.1.2

### Environment (Operating system, version and so on)

Windows 10 / Linux

### .NET Framework version

7.0

### Description

When i Load the following images with Image.Load(..) I get the Exception: "Input stream does not have enough bytes to parse declared contents of the 00 marker."

![3e0f1451-09e4-4eb0-96ae-2d7240f516fc](https://user-images.githubusercontent.com/22996632/215701408-8e992b36-8777-4fea-8d03-3db14dceac21.jpg)
![3f95dbb5-b694-42c6-9c52-c8bc7122a7da](https://user-images.githubusercontent.com/22996632/215701412-36268939-0f23-41c2-83af-dcdbe6486bdf.jpg)

### Steps to Reproduce

```
var fileStream = File.OpenRead(file);
using (var memoryStream = new MemoryStream())
{
    await fileStream.CopyToAsync(memoryStream).ConfigureAwait(continueOnCapturedContext: false);
    memoryStream.Seek(0L, SeekOrigin.Begin);
    using (var originalImage = Image.Load(memoryStream, out var imageFormat))
    {
    ...
    }
}
```

### Images

![3f95dbb5-b694-42c6-9c52-c8bc7122a7da](https://user-images.githubusercontent.com/22996632/215702679-aa34ee7b-7163-4d67-9225-87e15bc48ef5.jpg)
![3e0f1451-09e4-4eb0-96ae-2d7240f516fc](https://user-images.githubusercontent.com/22996632/215702681-4a8c6a4f-b1e1-4830-acf7-f31b01a9f7de.jpg)

**Comment by JimBobSquarePants** [comment]
Hi @ThomasWirz thanks for rasing this issue. 

I actually fixed it the other day with #2324. You can get the working package to test with from our MyGet feed listed in the readme.
