### ISSUE TITLE
Transitive dependency Microsoft.NETCore.Platforms 5.0.0 contains vulnerabilities according to Checkmarx

### ISSUE THREAD

**Issue by aybe** [SixLabors/ImageSharp#2336]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.3

### Other ImageSharp packages and versions

none

### Environment (Operating system, version and so on)

Microsoft Windows [Version 10.0.19045.2486]

### .NET Framework version

6.0

### Description

When adding the package to a .NET 6.0 project, one can see a warning about a vulnerability in the .csproj file.

See the image below.

### Steps to Reproduce

Explained in the description.

### Images

![devenv_7d2Fn1IN99](https://user-images.githubusercontent.com/1537591/215749022-f764bcf5-f687-4bc5-821e-d09ee15c58e4.png)

**Comment by JimBobSquarePants** [comment]
The next version of ImageSharp V3 targets .NET 6+ Only. Those depenencies are now gone. You can get the latest builds from our MyGet feed.

**Comment by aybe** [comment]
Amazing, thank you!
