### ISSUE TITLE
Problem converting TIF to grayscale PNG, resulting a negative image

### ISSUE THREAD

**Issue by joaovsoares** [SixLabors/ImageSharp#2358]
### Prerequisites

- [X] I have bought a Commercial License
- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.3

### Other ImageSharp packages and versions

No

### Environment (Operating system, version and so on)

Linux

### .NET Framework version

NET 6

### Description

Hello!

I'm part of a company that purchased the ImageSharp commercial license.
In general, we are satisfied. By the way, congratulations on a job well done.
But we are facing a problem.
Our process involves converting images we receive in TIF format to grayscale PNG. 
It works in most cases. But in certain situations the resulting PNG is a negative image.

I can provide our code (Code.zip) and sample images (Sample.zip).

The goal is to have a small grayscale PNG file.

I don't really know if it's a bug...
Can you help us with this?

### Steps to Reproduce

Load the sample image on a MemoryStream, and call the extension method ConvertToPNG provided on the code below.
Save the provided stream on a file.

[Code.zip](https://github.com/SixLabors/ImageSharp/files/10760585/Code.zip)

### Images

[Sample.zip](https://github.com/SixLabors/ImageSharp/files/10760587/Sample.zip)

**Comment by brianpopow** [comment]
@joaovsoares I have tried your example image with the current main source code and it works correctly. 

![output](https://user-images.githubusercontent.com/38701097/219484281-a92bcdd0-4c17-400b-8000-cff7e42b01c8.png)

I believe it's an issue with `2.1.3` which was already fixed. `3.0.0` will be released soon, but until then you can use our nightly builds from MyGet: [nightly](https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp)

**Comment by joaovsoares** [comment]
@brianpopow , thanks for the answer. 
Do you beleave that I can use the last nightly build on production environment?

**Comment by brianpopow** [comment]
> @brianpopow , thanks for the answer. Do you beleave that I can use the last nightly build on production environment?

I am very confident that you can, but I am also very biased as a maintainer.
We have 36k unit test, which back my opinion and the `3.0.0` version will not differ much from the myget version.

It would be of course better to try it first in a staging/testing environment if you can.

**Comment by JimBobSquarePants** [comment]
We're within weeks of a release. There _should_ be no changes to the public API other than #2357

**Comment by joaovsoares** [comment]
I understood. 
Thanks for the responses and suggestions.

Explaining our situation: My concern about waiting is the fact that we process literally thousands of images a day. So each day with a problem causes a huge amount of inconsistencies.

This conversion issue adds to another issue with TIF oldJpeg, which will also only be resolved in version `3.0.0`.
We're looking forward to version `3.0.0`, but we probably can't wait another few weeks, so I'll need to test the alpha version (`3.0.0-alpha.0.96`).

Again, thanks for the help.

**Comment by JimBobSquarePants** [comment]
I'm closing this, since it's fixed in main. There'll be a final v3 release this week.
