### ISSUE TITLE
Publish step fails with .NET 7.0.200

### ISSUE THREAD

**Issue by brianpopow** [SixLabors/ImageSharp#2361]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

Current main branch

### Other ImageSharp packages and versions

Current main branch

### Environment (Operating system, version and so on)

Ubuntu 22.04.1

### .NET Framework version

.NET 7.0.200

### Description

There seems to be a braking change with the current .NET 7.0 version, which breaks the publish step. See: https://github.com/SixLabors/ImageSharp/actions/runs/4217414560/jobs/7321231893

Error message is:
```
/usr/share/dotnet/sdk/7.0.200/Current/SolutionFile/ImportAfter/Microsoft.NET.Sdk.Solution.targets(36,5): error NETSDK1194: The "--output" option isn't supported when building a solution. 
```

MS build version: 17.5.0-preview-23061-01+040e2a90e

Related issue [dotnet sdk issue](https://github.com/dotnet/sdk/issues/30625)

### Steps to Reproduce

Run: `dotnet pack -c Release --output artifacts`

**Comment by JimBobSquarePants** [comment]
Cripes!

Looks like there's two workarounds.

Use the property.
https://github.com/dotnet/sdk/issues/30624#issuecomment-1432118204

Or specify the project name. 
https://github.com/sebastienros/esprima-dotnet/pull/375/files
