### ISSUE TITLE
BinaryDither and Dither with palette with length 2 sometimes yields incorrect result

### ISSUE THREAD

**Issue by Kizuto3** [SixLabors/ImageSharp#2370]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.13

### Other ImageSharp packages and versions

n/a

### Environment (Operating system, version and so on)

Windows 10

### .NET Framework version

.NET 6.0

### Description

I've found a weird case where Binary dither produces incorrect result. I am loading a jpeg image, applying binary dither to it and saving the image as bmp. I've attached jpeg image below and 1-bit bmp resulting image (in a zip file). Seems like the last bar is just ignored. The same issue is reproducible with regular Dither with palette with length of 2 

### Steps to Reproduce

```
using (var sharpImage = Image.Load<Rgba32>(@"C:\Users\Public\Documents\ext.jpeg"))
{
     image.Mutate(x => x.BackgroundColor(ImageSharp.Color.White).BinaryDither(ErrorDither.FloydSteinberg));

     var encoder = new BmpEncoder()
          {
          BitsPerPixel = BmpBitsPerPixel.Pixel1,
          Quantizer = new OctreeQuantizer(new QuantizerOptions()
               {
                    MaxColors = 2
               })
          };

     sharpImage.SaveAsBmp(@"C:\Users\Public\Documents\ext.bmp", encoder);
}
```

### Images

![ext](https://user-images.githubusercontent.com/38604580/221166806-99092d58-0d3e-4256-9531-f3e4b334fc29.jpeg)
[ext.zip](https://github.com/SixLabors/ImageSharp/files/10823538/ext.zip)

**Comment by JimBobSquarePants** [comment]
I'm sorry. I don't understand the issue here. You've attached the result but no input nor given me an example of what the expected result should be.

**Comment by Kizuto3** [comment]
The input image is the first attached image. Zip archive contains currently produced result. I am expecting the input image and the result image to be identical, containing all the black bars. I can attach the input image in a zip archive if you would like

**Comment by JimBobSquarePants** [comment]
Why would you expect them to be identical?

You should be aware that you are actually applying a double dither here. 

1. When applying `BinaryDither`
2. When you are quantizing the output. `QuantizerOptions.Dither` has a default value of `KnownDitherings.FloydSteinberg`

**Comment by Kizuto3** [comment]
Well, I just thought it's weird that the last bar is not present on the output image, as if it's ignored, and both the input and the output image have the same dimensions . If this is not the case, I will close the issue. Thank you for your response

**Comment by JimBobSquarePants** [comment]
No, you were right to raise this. Error accumulates but not generally this much.

I just did some testing with 3.0.0-alpha.0.102 using the following snippet applying the double dithering.

``` c#
foreach (string jpeg in Directory.EnumerateFiles(rootPath, "*.jpeg"))
{
    using var image = Image.Load(jpeg);
    image.Mutate(x => x.BinaryDither(KnownDitherings.FloydSteinberg));
    var encoder = new BmpEncoder()
    {
        Quantizer = new OctreeQuantizer(new() { MaxColors = 2 })
    };
    image.SaveAsBmp(Path.Combine(rootPath, Path.GetFileNameWithoutExtension(jpeg) + ".bmp"), encoder);
}
```
There is a minor difference between the two at the edge of each banding. 
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/385879/221176887-3ee82ab2-27a0-4af9-a08f-7eb4a53d2223.png">

If you remove the duplicated dithering and rely on the default quantizer dither `(KnownDitherings.FloydSteinberg`) then the output is identical.

``` c#
foreach (string jpeg in Directory.EnumerateFiles(rootPath, "*.jpeg"))
{
    using var image = Image.Load(jpeg);
    var encoder = new BmpEncoder()
    {
        Quantizer = new OctreeQuantizer(new() { MaxColors = 2 })
    };
    image.SaveAsBmp(Path.Combine(rootPath, Path.GetFileNameWithoutExtension(jpeg) + ".bmp"), encoder);
}
```

<img width="726" alt="image" src="https://user-images.githubusercontent.com/385879/221177565-292b9247-07ee-443b-baed-cd0abd33bf98.png">

**Comment by JimBobSquarePants** [comment]
Interestingly this [3rd party website](https://ditherit.com/) introduces exactly the same values as we do for `BinaryDither`.

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/385879/221178363-9be56417-0d46-478f-8fc4-736ec487ce70.png">

I think we can assume everything is working in the v3 code.

**Comment by Kizuto3** [comment]
Oh, so the reason was double dithering, I see. Thank you so much for your response!

**Comment by JimBobSquarePants** [comment]
No, it's not the double dither. Whatever it was though the issue is now fixed in the upcoming v3.
