### ISSUE TITLE
.NET Standard 2.0 support removed?

### ISSUE THREAD

**Issue by mfeingol** [SixLabors/ImageSharp#2387]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0

### Other ImageSharp packages and versions

3.0

### Environment (Operating system, version and so on)

Windows

### .NET Framework version

.NET Standard 2.0

### Description

It appears that .NET Standard 2.0 support has been removed in the latest ImageSharp release (3.0). I presume this is by design, but I wanted to confirm. I use ImageSharp in a UWP app that cannot (yet) be migrated to WinUI 3. Unfortunately, UWP is limited to using .NET Standard 2.0 assemblies.

### Steps to Reproduce

Install ImageSharp 3.0 as dependency to UWP app (or your own .NET Standard 2.0 assembly)

**Comment by dlemstra** [comment]
Already discussed in #2378.

**Comment by JimBobSquarePants** [comment]
This should have been a Q&A discussion.
