### ISSUE TITLE
An exception was encountered when instantiating multiple Image objects from a Stream object

### ISSUE THREAD

**Issue by haphuongle959** [SixLabors/ImageSharp#2423]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.1

### Other ImageSharp packages and versions

3.0.0

### Environment (Operating system, version and so on)

Windows 10, Windows Server 2019

### .NET Framework version

ASP NET Core - .NET 7

### Description

Hello. I'm writing an application that has a photo archive feature.
For each image I create 3 versions with different sizes and store them in S3. So before I archive them, I have to resize the images with your gallery.
In older versions of the library the application works properly.
However in recent versions (v3.0.0, v3.0.1) I get an unexpected error when instantiating multiple Image objects by Loading from the same Stream. Only the first Image.Load works properly, all subsequent Image.Loads throw an exception.

Attempts tried:

> - Changing the input with different images with JPG, PNG format is not possible.

> - Initialize 3 different Streams to create 3 Image from Image.Load => fix the problem, but so our application has to modify as well as not optimize performance

Here is my source code

```
var Content = Convert.FromBase64String(APIRequest.Base64StringFile.Split(',').LastOrDefault());
Stream stream = new MemoryStream(Content);
Image imageOriginSize = await Image.LoadAsync(stream);
Image imageMiddleSize = await Image.LoadAsync(stream);
Image imageSmallSize = await Image.LoadAsync(stream);
```
When the application runs to the third line it will create a normal Image object
But when the application runs to the fourth line it throws an exception as: 
Exception Message
```
Image cannot be loaded. Available decoders:
 - Webp : WebpDecoder
 - TIFF : TiffDecoder
 - PNG : PngDecoder
 - TGA : TgaDecoder
 - PBM : PbmDecoder
 - BMP : BmpDecoder
 - GIF : GifDecoder
 - JPEG : JpegDecoder
```
StackTrace
```
   at SixLabors.ImageSharp.Formats.ImageFormatManager.ThrowInvalidDecoder(ImageFormatManager manager)
   at SixLabors.ImageSharp.Image.InternalDetectFormat(Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Image.DiscoverDecoder(DecoderOptions options, Stream stream)
   at SixLabors.ImageSharp.Image.DecodeAsync(DecoderOptions options, Stream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Image.<>c__DisplayClass82_0.<LoadAsync>b__0(Stream s, CancellationToken ct)
   at SixLabors.ImageSharp.Image.<WithSeekableStreamAsync>d__88`1.MoveNext()
```

Thank you!

### Steps to Reproduce

> - Initialize a Stream object from byte[]

> - Create multiple Image objects using the Image.Load function with the same input as the Stream object initialized above.

> - Run the app

**Comment by JimBobSquarePants** [comment]
Can you share sample images or an encoded string?

**Comment by tocsoft** [comment]
can you try resetting the stream position betwene loads

i.e. 
``` c#
Image imageOriginSize = await Image.LoadAsync(stream);
stream.Postion = 0;
Image imageMiddleSize = await Image.LoadAsync(stream);
stream.Postion = 0;
Image imageSmallSize = await Image.LoadAsync(stream);
```

That code assumes your stream contains a single image you are trying to laod 3 instances of.

does stream contain 3 images worth of data or are you trying to get 3 instances of the same steam?

FYI if its the latter and you are just trying to create 3 instance of the same image to resize loading it 3 times isn't what you want, load it once, then do the resize inside an `using var imageMiddleSize = image.Clone(x=>x.Resize...);` operation you will reduce your memoy consumption and speed up the process as it'll only have 1 copy of the origional image in memory and will no have to run the decode operation multiple times..

i.e.
```c#
using Image imageOriginSize = await Image.LoadAsync(stream);
// cleanup any meta data removal or `AutoOrientation` fixing you need 
// to do once here and then perform the resizes last just before persisting them

using Image imageMiddleSize = imageOriginSize.Clone(x=>x.Resize...);
using Image imageSmallSize = imageOriginSize.Clone(x=>x.Resize...);

// save out the versions as required
```

**Comment by haphuongle959** [comment]
Thank you for suggesting a workaround.
