### ISSUE TITLE
Transparent pixels are not preserved

### ISSUE THREAD

**Issue by mj2015** [SixLabors/ImageSharp#2438]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.1

### Other ImageSharp packages and versions

None

### Environment (Operating system, version and so on)

Windows

### .NET Framework version

.Net 6.0

### Description

The Alpha channel of pixels is not operating properly. My purpose is to mask areas of a bitmap so that I can merge two together. If I start with a transparent bitmap, then apply layers of bitmaps with transparency using Mutate, that is working. However I now have to start with a solid bitmap, so I need to "cut out" areas of another so the first can show through. No matter what I try, I cannot get the transparency to work in the resulting bitmap. I therefore went back to basics in the sample code, and even setting the pixels manually fails to work. Either there is a setting that is not obvious, or there is a bug in the pixel processing somewhere.

I see others have had issues with the transparency/alpha but have not had responses.

A workaround I could go with would be the `ProcessPixelRows` that would accept three images, then I could pick pixels from the two I want, and operate the mask myself. 

I'm hoping that this is a simple thing, but I cannot see a way around what appear to be a simple problem - setting a pixel alpha isn't stored in the resulting image.

### Steps to Reproduce

This is code modified from the tutorial code. The mask image is a simple bitmap with solid shapes and the background is transparent. I've tried setting the pixel.A value and also the RGB too - changing the colour is fine, but it is visible.

```
      private static Image<Rgba32> ApplyMask(Image<Rgba32> sourceImage, Image<Rgba32> maskImage)
      {
          int height = sourceImage.Height;
          Rgba32 transparent = Color.Transparent;
          sourceImage.ProcessPixelRows(maskImage, (sourceAccessor, maskAccessor) =>
          {
              for (int i = 0; i < height; i++)
              {
                  Span<Rgba32> sourceRow = sourceAccessor.GetRowSpan(i);
                  Span<Rgba32> maskRow = maskAccessor.GetRowSpan(i);

                  for (int x = 0; x < sourceRow.Length; x++)
                  {
                      // Get a reference to the pixel at position x
                      ref Rgba32 pixel = ref sourceRow[x];
                      ref Rgba32 maskPixel = ref maskRow[x];
                      if (maskPixel == transparent)
                      {
                          // Overwrite the pixel referenced by 'ref Rgba32 pixel':
                          pixel = transparent;
                      }
                  }
              }
          });
          string partialFile = @$"C:\mask-test.png";
          using (var outputStream = new FileStream(partialFile, FileMode.Create)) 
          {
              sourceImage.Save(outputStream, new PngEncoder() { TransparentColorMode = PngTransparentColorMode.Preserve});
          }

          return sourceImage;
      }
```

**Comment by JimBobSquarePants** [comment]
>I see others have had issues with the transparency/alpha but have not had responses

What other issues?

>However I now have to start with a solid bitmap, so I need to "cut out" areas of another so the first can show through. No matter what I try, I cannot get the transparency to work in the resulting bitmap.

What is the pixel format of the opaque image?

**Comment by mj2015** [comment]
Thank you for responding. The other issues are those in the discussions: [https://github.com/SixLabors/ImageSharp/discussions?discussions_q=transparent](https://github.com/SixLabors/ImageSharp/discussions?discussions_q=transparent)

How can I tell the pixel format? Both are PNG, and the Image says the PixelType is AlphaRepresentation:null, BitsPerPixel: 32.
The mask obviously has transparency as I can detect that in the code, it is just when I set the pixel that it goes to the color I set it, but never transparent. 

The image is loaded using: (with irrelevant code removed, sorry, can't get the markdown to work on multiple lines)
`
                    using (var imageBase = Image.Load<Rgba32>(baseFile))
                    using (var imageOverlay = Image.Load<Rgba32>(maskFile))
                     {
                       ApplyMask( imageBase, imageOverlay);
`

Is there an additional step to make the base image suitable for transparency to work?

**Comment by JimBobSquarePants** [comment]
One of the two questions marked as unanswered actually had an answer explaining everything, but the OP never clicked to accept it. The other was closed by the OP almost immediately after opening.

I've updated your code sample. You can do code blocks using three backtick symbols to mark the start and end of the block.

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

A pixel format is the type used in `Image<TPixel>` 
I suspect that your opaque image is being decoded with a [`PngColorType`](https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Formats.Png.PngColorType.html) of `PngColorType.Rgb` when you want to encode using `PngColorType.RgbWithAlpha`. You can check that in the [`Metadata`](https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Image.html#SixLabors_ImageSharp_Image_Metadata) property.

You can use the extensions methods to that type to get [format specific metadata](https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.MetadataExtensions.html#SixLabors_ImageSharp_MetadataExtensions_GetPngMetadata_SixLabors_ImageSharp_Metadata_ImageMetadata_)

**Comment by mj2015** [comment]
Okay thank you for that. Adding the alpha to the save makes it work. 
`sourceImage.Save(outputStream, new PngEncoder() { TransparentColorMode = PngTransparentColorMode.Preserve, ColorType = PngColorType.RgbWithAlpha });
`
I shall have to see if I can get this to work within my system in memory, but this is a big advance. Thank you.
