### ISSUE TITLE
Feature proposal: interlaced PNG encoding

### ISSUE THREAD

**Issue by atruskie** [SixLabors/ImageSharp#244]
I see in #9 that support was added for decoding interlaced PNG images but that support for encoding interlaced images was not considered because it is an uncommon use case.

My question is: if someone (like myself in a fictional world of plentiful free time) were to implement interlaced PNG encoding, would ImageSharp be interested in adopting that feature?

**Comment by JimBobSquarePants** [comment]
@atruskie If you implemented it we would be more than happy to accept it! 😄 

It's something we would like to have it's just something we have set very low on our priority list.

**Comment by IldarKhayrutdinov** [comment]
@JimBobSquarePants @atruskie if the task Is not assigned, please assign it to me.

**Comment by antonfirsov** [comment]
@IldarKhayrutdinov there's no need for such formalities! :)
Feel free to submit a PR, we will review, and most likely accept it (probably after a few change requests).

**Comment by IldarKhayrutdinov** [comment]
@atruskie Ok ) I did not want a few people to do the same task.

**Comment by IldarKhayrutdinov** [comment]
Hi, I implement interlaced algorithm for pixels, but there are bugs with the writing of chunks. Continue working. Unfortunately, there is little time free from the main work.

**Comment by JimBobSquarePants** [comment]
@IldarKhayrutdinov Thanks! :smile: It's a start which I'm sure we can help with. 

If you can open a Work-In-Progress PR against our repo with the check box checked that allows us to push to your PR we should be able to figure this out together.

**Comment by JimBobSquarePants** [comment]
Fixed with #955
