### ISSUE TITLE
PNG converted to WEBP doesn't work in Chrome and Edge, but it does work in Firefox

### ISSUE THREAD

**Issue by creativesuspects** [SixLabors/ImageSharp#2442]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.3

### Other ImageSharp packages and versions

SixLabors.ImageSharp.Web 2.0.2

### Environment (Operating system, version and so on)

Microsoft Windows 10.0.22621 / Microsoft Windows 10.0.17763

### .NET Framework version

.NET 7.0.5 / .NET 6.0.15

### Description

When converting the attached PNG to WEBP the converted images doesn't load in Chrome and Edge, it does load in Firefox.

### Steps to Reproduce

When converting the attached PNG to WEBP the converted images doesn't load in Chrome and Edge (blank image, it shows as a "broken" image in the console network preview): 

![image](https://user-images.githubusercontent.com/161342/234572699-f9e3bb7d-2a94-4a83-8790-88e8f1794c26.png)

The image works fine in Firefox though.

This PNG image was created as a screenshot on a Mac. When I open the PNG in Photoshop and save a copy of the PNG image, the saved copy converts fine in all browsers. I've also attached the copied version of the PNG to this issue.

These are the Response Headers for the WEBP image in Edge:

accept-ranges: bytes
cache-control: public, must-revalidate, max-age=604800
content-length: 471538
content-type: image/webp
date: Wed, 26 Apr 2023 12:09:54 GMT
etag: "1d97837429e39f2"
last-modified: Wed, 26 Apr 2023 12:04:32 GMT
server: Microsoft-IIS/10.0
vary: Accept
x-powered-by: ASP.NET

Any idea what is wrong with the PNG file and why the converted WEBP image doesn't work in Chrome and Edge?

#### Bad PNG
![bad](https://user-images.githubusercontent.com/161342/234570999-7a45f50a-54cb-4f50-83f6-a3cd5a760389.png)

#### This is the WEBP version of the bad PNG

https://www.dropbox.com/s/71zpabju1zbi60a/bad.webp?dl=0

#### Copy of bad PNG saved using Photoshop
![copy](https://user-images.githubusercontent.com/161342/234571634-4ec7c75c-4890-49f8-a489-ce3a667dce2a.png)

#### This is the WEBP version of the copied PNG

https://www.dropbox.com/s/qt71c9zad09lwin/copy.webp?dl=0

**Comment by JimBobSquarePants** [comment]
We don’t support v2.

**Comment by creativesuspects** [comment]
I'm using ImageSharp on Umbraco 10+. Do you know if I can just upgrade to the latest 3.x version? And are there any license costs involved with 3.x?

**Comment by dlemstra** [comment]
You can find that information in the `LICENSE` of this project.

**Comment by creativesuspects** [comment]
The issue seems to be fixed in 3.x, so that's great.

> You can find that information in the `LICENSE` of this project.

I've read the LICENSE of this project, but I'm still confused. Umbraco version 10 and 11 both reference version 2.x of ImageSharp, so that falls under the transitive package dependency. But what if I would manually upgrade that dependency to ImageSharp 3.x? Does it then still fall under the transitive package dependency?

**Comment by antonfirsov** [comment]
> Does it then still fall under the transitive package dependency?

Yes, however:
3.0 introduced breaking API changes, so I'm not sure if it's possible to upgrade to 3.0 without Umbraco doing it, depends on their API usage. Needs to be tried I guess.

**Comment by JimBobSquarePants** [comment]
>Yes, however:

Actually no. Once you directly update a version of ImageSharp to a version not installed as a transient dependency then you are introducing the library as a direct dependency. 

>Needs to be tried I guess.

Umbraco reference ImageSharp.Web which transiently references ImageSharp so I find it highly unlikely that upgrading to a new major of ImageSharp will work. 

So... either pester Umbraco to update ImageSharp or don't use WebP. Jpeg will give you very similar results as usually a higher quality output than WebP anyway.
