### ISSUE TITLE
Drawing Text Expanded example causes MissingFieldException

### ISSUE THREAD

**Issue by vargonian** [SixLabors/ImageSharp#2444]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.1

### Other ImageSharp packages and versions

SixLabors.Fonts 1.0.0-beta19, SixLabors.ImageSharp.Drawing 1.0.0-beta15

### Environment (Operating system, version and so on)

Windows 10

### .NET Framework version

.NET 6.0

### Description

I attempted to run the expanded Drawing Text example at the bottom of this page: https://docs.sixlabors.com/articles/imagesharp.drawing/gettingstarted.html

The line:
IBrush brush = Brushes.Horizontal(Color.Red, Color.Blue);

results in the unhandled exception: 
System.MissingFieldException: 'Field not found: 'SixLabors.ImageSharp.DenseMatrix`1.Columns'.'

(As an aside, I'm also seeing a TypeLoadException trying to use an ImageBrush but I fell back to a simpler example and got this exception above.)

### Steps to Reproduce

1. Create a new .NET 6.0 console application.
2. Add references to the following Nuget packages: SixLabors.Fonts 1.0.0-beta19, SixLabors.ImageSharp 3.0.1, and SixLabors.ImageSharp.Drawing 1.0.0-beta15.
3. Enter the following line into your console application's Main method (distilled from the full sample at https://docs.sixlabors.com/articles/imagesharp.drawing/gettingstarted.html):
`IBrush brush = Brushes.Horizontal(Color.Red, Color.Blue);`

Result: An exception is thrown: System.MissingFieldException: 'Field not found: 'SixLabors.ImageSharp.DenseMatrix`1.Columns'.'

**Comment by JimBobSquarePants** [comment]
The ImageSharp.Drawing beta is not compatible and should not be used with ImageSharp V3

We're working on a V1 final of ImageSharp.Drawing which will continue to be compatible with ImageShartp V2. After this a V2 will be released with ImageSharp V3 compatibility.

**Comment by vargonian** [comment]
Oh, thank you.  In this case, could you help me with the correct versions of packages I should reference so that I both get the latest-and-greatest that I can while also supporting ImageBrushes?  My main requirement is to draw text with an image as a background.

**Comment by JimBobSquarePants** [comment]
You’ll want ImageSharp 2.1.3 plus the other libraries you’ve already got.

**Comment by vargonian** [comment]
It appears this was user error on my part; I was using an invalid combination of libraries/versions.
