### ISSUE TITLE
Huge tiff image (80+ mb) gets distorted when resized to a smaller jpg - huge memory (700+mb) footprint too.

### ISSUE THREAD

**Issue by shapeh** [SixLabors/ImageSharp#2456]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.1

### Other ImageSharp packages and versions

None

### Environment (Operating system, version and so on)

Windows 11 and Windows Server 2022

### .NET Framework version

.NET 7.0.5

### Description

Large tiff of 81.2mb gets distorted / colors off when resizing to smaller jpg size.
Huge memory consumption (700+mb) as well for  Image.LoadAsync

### Steps to Reproduce

            // retrieving the image from Azure using something like this...
            ...
           //  Image.LoadAsync makes VS studio profiler mem consumption go to 839 mb (program consumes 95 mb normally).
            using var image = await Image.LoadAsync(azureBlobData, token); 
            var typeOfImage = image.Metadata.DecodedImageFormat;

            // resize original image to new width:
            image.Mutate(x =>
                x.AutoOrient()
                .Resize(width, 0)
            ); 

            await image.SaveAsync(memoryStream, new JpegEncoder() { Quality = 85 }, token);
           memoryStream.Position = 0;           

            var resizedImage = await Image.LoadAsync(memoryStream, token);
            await resizedImage.SaveAsync(@$"C:\temp\{Guid.NewGuid()}.jpg", token);

### Images

Hugetif.tif Image here: (too large to upload on Github):
https://1drv.ms/f/s!Aj75-9hUJpB1nZJHAY8Y0a0o46dLQA?e=4HLRVL

Imagesharp result:
![hugetif660](https://github.com/SixLabors/ImageSharp/assets/29387615/e5c6bc21-e5b3-4754-a883-8b57848bd08f)

Photoshop result:
![hugetif660-photoshop](https://github.com/SixLabors/ImageSharp/assets/29387615/dda85d5b-db7e-4893-b43b-685d53b9b704)

**Comment by dlemstra** [comment]
Does it only happen during a resize or also when you just save the image as jpeg?

**Comment by JimBobSquarePants** [comment]
This looks like a color type detection mismatch during decode to me. 

I'd really like to see the output of the memory profile if I can. A decoded image of that size will consume ~114MB without any modification so there's a lot of additional allocations I'd like to identify.

**Comment by brianpopow** [comment]
The is an issue decoding the image. This image uses lzw compression with a horizontal predictor. For CMYK the horizontal predictor is not reverted correctly. This should be an easy fix.

**Comment by shapeh** [comment]
I'll revert tomorrow but I built a simple console app just to test and memory does _not_ go through the roof for some reason. Tried with both Load and LoadAsync directly from file system and memory is okay. 

Minimal API / Azure causes mentioned problems. I'll see if I can do some memory profiling for you (not my specialty...)

**Comment by JimBobSquarePants** [comment]
Thanks for the accurate diagnosis @brianpopow !

@shapeh is what type is your `azureBlobData` variable?

**Comment by shapeh** [comment]
@JimBobSquarePants 
azureBlobData is: 

`System.IO.Stream {Azure.Storage.LazyLoadingReadOnlyStream<Azure.Storage.Blobs.Models.BlobProperties>}`

I will post some code later.

**Comment by shapeh** [comment]
This is my code - memory is OK for all three methods below in a sample Console app. Which is weird! 
In the Minimal API, memory goes high - doing some investigation now...
Colors are still off but it was expected according to the diagnosis by @brianpopow 

```
using Azure.Storage.Blobs;
using SixLabors.ImageSharp.Formats.Jpeg;

void TestLoad()
{
    using (Image image = Image.Load(@"C:\Web\tmp\hugetif.tif"))
    {
        image.Mutate(x => x.AutoOrient().Resize(660, 0));
        image.Save(@$"C:\Web\tmp\image-load-{Guid.NewGuid()}.jpg", new JpegEncoder() { Quality = 85 });
    }
    Console.WriteLine("Done Load.");

}
async Task TestLoadAsync()
{
    using (Image image = await Image.LoadAsync(@"C:\Web\tmp\hugetif.tif"))
    {
        image.Mutate(x => x.AutoOrient().Resize(660, 0));
        await image.SaveAsync(@$"C:\Web\tmp\image-load-async-{Guid.NewGuid()}.jpg", new JpegEncoder() { Quality = 85 });
    }
    Console.WriteLine("Done LoadAsync.");
}

async Task TestAzureLoad(CancellationToken token)
{
    var client = new BlobServiceClient("myconnectionstring");
    var containerClient = client.GetBlobContainerClient("mycontainer");
    var blob = containerClient.GetBlobClient("hugetif.tif");

    var azureBlobData = await blob.OpenReadAsync(null, cancellationToken: token);
    using var image = await Image.LoadAsync(azureBlobData, token);

    image.Mutate(x => x.AutoOrient().Resize(660, 0));

    await image.SaveAsync(@$"C:\Web\tmp\image-azure-{Guid.NewGuid()}.jpg", new JpegEncoder() { Quality = 85 });
    Console.WriteLine("Done Azure.");
}

TestLoad();
await TestLoadAsync();
await TestAzureLoad(CancellationToken.None);
```

**Comment by shapeh** [comment]
**Snapshot from Minimal API**

<img width="842" alt="minapi" src="https://github.com/SixLabors/ImageSharp/assets/29387615/1a5ca297-3f51-4dfe-9ccf-9469ed09c9a8">

Dependencies:
<img width="266" alt="minapi-dep" src="https://github.com/SixLabors/ImageSharp/assets/29387615/dd5f31e4-9d0d-4725-b3c1-b5acd28ff153">


**Snapshot from Console App**

<img width="845" alt="consoleapp" src="https://github.com/SixLabors/ImageSharp/assets/29387615/09aebad5-b1a8-4699-ab6f-ec1ac35c4124">

Dependencies:
<img width="266" alt="consoleapp-dep" src="https://github.com/SixLabors/ImageSharp/assets/29387615/38d8cc43-a509-4885-9efb-53f2632da081">

**Comment by JimBobSquarePants** [comment]
The biggest allocation in the API snapshot is 89MB. 

You’ve got “show dead objects” checked in the first window. As I recall they’re objects that are removed by the next snapshot.

I can see that you’re not disposing of your input stream also.
