### ISSUE TITLE
System.MissingMethodException when using DrawText to apply watermark to the image

### ISSUE THREAD

**Issue by vasylhulpak** [SixLabors/ImageSharp#2458]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.1

### Other ImageSharp packages and versions

ImageSharp.Drawing: 1.0.0-beta13, ImageSharp.Web: 1.0.4

### Environment (Operating system, version and so on)

Windows 10

### .NET Framework version

.Net 7.0

### Description

When using DrawText method to apply watermark text , and System.MissingMethodException is thrown, with message  `Method not found: 'System.Span`1<SixLabors.ImageSharp.PixelFormats.Rgb24> SixLabors.ImageSharp.Memory.Buffer2D`1.GetRowSpan(Int32)`. FYI: for ImageSharp, version: 1.0.4 - it works fine

### Steps to Reproduce

```
using SixLabors.Fonts;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Drawing.Processing;
using SixLabors.ImageSharp.Processing;
	
var file = System.IO.File.OpenRead("c:\test.jpg");
var bytes = await File.ReadAllBytesAsync("c:\test.jpg", httpContext.RequestAborted);

using var memoryStream = new MemoryStream(bytes );
using var image = await Image.LoadAsync(memoryStream );

image.Mutate(x => x.AutoOrient());
image.Metadata.ExifProfile = null;
image.Mutate(x => x.Resize(new ResizeOptions()
{
   Size = new Size(2000, 2000),
   Mode = ResizeMode.Max
}));

var fonts = new FontCollection();
var font = fonts.Install("c:\fonts\roboto-condensed\RobotoCondensed-Regular.ttf", CultureInfo.InvariantCulture);

image.Mutate(x => x.DrawText(
options: new DrawingOptions
  {
          GraphicsOptions = new GraphicsOptions
  {
	  BlendPercentage = 0.15F,
  },
           Transform = Matrix3x2.CreateRotation((float)(-45 * Math.PI) / 180f, new PointF(200, 200))
  },
text: "TEST,
new Font(font, ((image.Height + image.Width) / 4 / 18), FontStyle.Regular),
Color.White,
new PointF("200 / 2,200 - step)));
```

**Comment by antonfirsov** [comment]
ImageSharp.Drawing is not compatible with ImageSharp 3.0+, there are breaking API changes between those versions. Also note that ImageSharp.Drawing: `1.0.0-beta13` is an old version. You need to use:
- ImageSharp: 2.1.*
- ImageSharp.Drawing: beta15
- ImageSharp.Web: 2.0.*

As for the future, ImageSharp.Drawing will come out of beta in two flavors: 1.0.* for compatibility with ImageSharp 2.1.* and 2.0.* for compatibility with ImageSharp 3.*

**Comment by vasylhulpak** [comment]
Thanks. Works fine :)
