### ISSUE TITLE
Creating a new ImageBrush returns the exception of "Could not load type 'SixLabors.ImageSharp.ImageInfoExtensions' from assembly 'SixLabors.ImageSharp'"

### ISSUE THREAD

**Issue by CharlesWalkden** [SixLabors/ImageSharp#2461]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.1

### Other ImageSharp packages and versions

.Fonts: 1.0.0-beta19 and ImageSharp.Drawing: 1.0.0-beta15

### Environment (Operating system, version and so on)

Windows 10 pro version 10.0.19044

### .NET Framework version

.NET 6.0

### Description

I am trying to create a ImageBrush with the image of an discord avatar so that I can use that to fill in an ellipse. It is the creating of this ImageBrush that is throwing the following exception:
"Could not load type 'SixLabors.ImageSharp.ImageInfoExtensions' from assembly 'SixLabors.ImageSharp, Version=3.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13'.":"SixLabors.ImageSharp.ImageInfoExtensions"

### Steps to Reproduce

The code I was using when I found the issue was a simple creation of a new ImageBrush with my avatar image.
```
Image avatar = await FetchImageAsync(user.GetAvatarUrl(size: 2048, format: Discord.ImageFormat.Png) ?? user.GetDefaultAvatarUrl());

if (avatar.Bounds.Width != 256 && avatar.Bounds.Height != 256)
{
    avatar.Mutate(x => x.Resize(new Size(256, 256)));
}
IBrush imageBrush = null;
try
{
    imageBrush = new ImageBrush(avatar);
}
catch(Exception e)
{
    Console.WriteLine(e.Message);
}

```

I tested it using the test from here: https://github.com/SixLabors/ImageSharp.Drawing/blob/main/tests/ImageSharp.Drawing.Tests/Drawing/FillImageBrushTests.cs

```
using (var src = new Image<Rgba32>(5, 5))
{
    var brush = new ImageBrush(src);
    using (var dest = new Image<Rgba32>(10, 10))
    {
        dest.Mutate(c => c.Fill(brush, new Rectangle(0, 0, 10, 10)));
        dest.Mutate(c => c.Fill(brush, new Rectangle(0, 0, 10, 10)));
    } 
}
```

### Images

![image](https://github.com/SixLabors/ImageSharp/assets/37580366/59d65605-6f57-46fb-9700-64d8ebf64983)

![image](https://github.com/SixLabors/ImageSharp/assets/37580366/20ace841-0574-47ca-9b42-ccc96eb2c5aa)

**Comment by tiesont** [comment]
More or a less a dup of #2458 

> ImageSharp.Drawing is not compatible with ImageSharp 3.0+
