### ISSUE TITLE
Ambiguous reference between 'Microsoft.Maui.Graphics.Color' and 'SixLabors.ImageSharp.Color'

### ISSUE THREAD

**Issue by mike-rowley** [SixLabors/ImageSharp#2466]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.1

### Other ImageSharp packages and versions

None

### Environment (Operating system, version and so on)

Windows 10.0.19045 Build 19045, VS 17.6.1 

### .NET Framework version

7 

### Description

Adding SixLabors.ImageSharp to a brand new Maui Project with CommunityToolkit.Maui causes multiple ambiguous reference between 'Microsoft.Maui.Graphics.Color' and 'SixLabors.ImageSharp.Color' errors

### Steps to Reproduce

Create a new Maui Project
Add CommunityToolkit.Maui from nuget
Compile the project successfully
Add SixLabors.ImageSharp
Compile the project fails

### Images

Not Applicable

**Comment by JimBobSquarePants** [comment]
See #2381

**Comment by JimBobSquarePants** [comment]
I'll keep this open as I want to track adding a single key to remove usings and add docs.

**Comment by DavidPressman** [comment]
This error appeared in my Maui solution after updating Stimulsoft Reports, which includes SixLabors.ImageSharp 3.01 as a dependency. A similar error also occurs for Size. Obviously I've had to revert and will notify Stimulsoft.

**Comment by JimBobSquarePants** [comment]
Why revert? Just add the exclusions to your csproj:

**Comment by DavidPressman** [comment]
Actually, in my own code, I added the proper namespace prefixes to my uses of Color and Size. However, I also use the Microsoft's Community Toolkit to generate observable objects in my partial classes. Any code it generates referring to Color now fails with the error. Please rename your conflicting classes to remove such conflicts. Thank you.

David Pressman
________________________________

**Comment by JimBobSquarePants** [comment]
>Please rename your conflicting classes to remove such conflicts. Thank you.
 
 Yeah sure, I'll get right to that.... 🙄
 
Hold tight while I make a massive breaking change to a library with 57 million downloads because you can't make a [5-line change](https://github.com/SixLabors/ImageSharp/discussions/2381#discussioncomment-5188759) to a csproj file.

**Comment by tocsoft** [comment]
> Actually, in my own code, I added the proper namespace prefixes to my uses of Color and Size. However, I also use the Microsoft's Community Toolkit to generate observable objects in my partial classes. Any code it generates referring to Color now fails with the error. Please rename your conflicting classes to remove such conflicts. Thank you. David Pressman

To be fair ImageSharp pre-dates Maui so you could argue that they should renamed thiers.

But on a more helpfull(ish) note I would have to argue that the really issue here seems to stem from the Microsoft's Community  Toolkit being buggy and generating bad/fragile code, auto generated code (in my opinon) should really always be generated referencing types absolutly i.e `global::SixLabors.ImageSharp.Color` etc. That way the generated code can never be ambiguous... yes the generated code is verbose but what does the compiler care.

**Comment by DavidPressman** [comment]
I appreciate that comment much more. You may haver a point the Community Toolkit folks could benefit from.

As to the five lines to add to a .csproj, somehow those did not reach me.
Would you mind, please, repeating them in any further reply and I'll give them a try?
Thank you.

David Pressman
________________________________

**Comment by tocsoft** [comment]
that would be the comment https://github.com/SixLabors/ImageSharp/issues/2466#issuecomment-1563674774 (first comment on the original post), which points to the relevent discussion https://github.com/SixLabors/ImageSharp/discussions/2381 where I added the csproj code needed fro overriding the implicit `using`s

**Comment by DavidPressman** [comment]
Thank you.
DP
________________________________

**Comment by bijington** [comment]
> But on a more helpfull(ish) note I would have to argue that the really issue here seems to stem from the Microsoft's Community  Toolkit being buggy and generating bad/fragile code, auto generated code (in my opinon) should really always be generated referencing types absolutly i.e `global::SixLabors.ImageSharp.Color` etc. That way the generated code can never be ambiguous... yes the generated code is verbose but what does the compiler care.

I would agree that this sounds like the source generator code from the .NET Community Toolkit has a bug in it if it cannot handle conflicting types. Has anyone raised this as an issue with the toolkit?

**Comment by DavidPressman** [comment]
This work-around, found elsewhere in the now closed issue 2381 mentioned above, does work when added into the .csproj file:
<ItemGroup>
    <Using Remove="SixLabors.ImageSharp" />
    <Using Remove="SixLabors.ImageSharp.PixelFormats" />
    <Using Remove="SixLabors.ImageSharp.Processing" />
</ItemGroup>
As to why it is needed, one might read that issue.
The reasons why SixLabors chose to add the cause may be well-justified and fully thought out.

I have received various responses from the SixLabors author about my earlier comments and did appreciate the later ones.
Nonetheless, I, too, respectfully agree with the essence of some comments in that thread that the cause is rather surprising and, for at least some of us, not only counter-intuitive but one I would not wish to see repeated in other nuget packages.

**Comment by JimBobSquarePants** [comment]
From v3.1 onwards the behavior will be reversed and the following will be required to add the usings.

```xml
<UseImageSharp>true</UseImageSharp>
```
