### ISSUE TITLE
BMP with 1 bitcount (B/W) corrupts after save

### ISSUE THREAD

**Issue by synercoder** [SixLabors/ImageSharp#2467]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.1 

### Other ImageSharp packages and versions

>&gt;= 2.0.0 (tested up to 3.0.2-alpha.0.17)

### Environment (Operating system, version and so on)

Ubuntu-latest & Windows-latest

### .NET Framework version

7.0.0

### Description

I have a bmp file that is 10x10 pixels. The bmp file has a bitcount of 1, and thus a color pallet of 2 colors, namely: FFFFFF & 000000.

When loading the bmp, the pixeldata is loaded correctly, but when saving the bmp, the image somehow becomes corrupt.

When you save the image by first copying the pixeldata into a new `Image` object, the resulting image is correct. Indicating that the bug has to do with the original metadata messing somehow with the encoding process.

The error bug occurs since ImageSharp version 2.0.0.

Input image:
![Original image](https://github.com/synercoder/BitmapBug/raw/main/ImageSharp.BmpBug/datamatrix.bmp)
<img width="377" alt="original-large" src="https://github.com/SixLabors/ImageSharp/assets/18616295/bab4f795-d448-4c66-8ad9-1ccfa3102277">

Corrupt image:
![Corrupt image](https://github.com/synercoder/BitmapBug/raw/main/ImageSharp.BmpBug/corrupt-result.bmp)
<img width="377" alt="corrupt-large" src="https://github.com/SixLabors/ImageSharp/assets/18616295/681f9fac-a64f-4491-b0ab-3fcb105a5d48">

Test project: https://github.com/synercoder/BitmapBug/blob/main/ImageSharp.BmpBug/BmpSavedWrong.cs
Test run showing matrix of os, mode & ImageSharp versions: https://github.com/synercoder/BitmapBug/actions/runs/5094509469

### Steps to Reproduce

Use the attached image (`datamatrix.bmp`), and execute the following code:
```
using (var dmImage = Image.Load<Rgb24>("datamatrix.bmp"))
using (var fs = File.OpenWrite("corrupt.bmp")))
{
    dmImage.SaveAsBmp(fs);
}
```

The resulting `corrupt.bmp` is visibly (zoom in, it is 10x10 pixels) different on the right side of the image.

### Images

[datamatrix.zip](https://github.com/SixLabors/ImageSharp/files/11579625/datamatrix.zip)

**Comment by JimBobSquarePants** [comment]
Most likely error diffusion being turned on by default in the encoder. Try creating a new instance of the BmpEncoder using the Octree Quantizer with the dither property set to null and passing it as the second parameter in your save method.

The reason it will work with a new image is that the default metadata will cause the image to be saved with full color

**Comment by synercoder** [comment]
I tried your suggestion as followed:

```
var quantizer = SixLabors.ImageSharp.Processing.KnownQuantizers.Octree;
quantizer.Options.Dither = null;
input.SaveAsBmp(ms, new SixLabors.ImageSharp.Formats.Bmp.BmpEncoder() { Quantizer = quantizer });
```

But the result is the same: https://github.com/synercoder/BitmapBug/actions/runs/5095035910

**Comment by synercoder** [comment]
Also, enjoy the weekend 😉, code is not in critical path, and I do have a workaround for now. 

This is an "FYI bug report", not an "I need it fixed" bug report.

**Comment by synercoder** [comment]
Now it has become an "I have made a fix for this bug" bug report. 😉
