### ISSUE TITLE
Images saved using Pbm Binary Byte format (P4) are corrupted. 

### ISSUE THREAD

**Issue by danzk** [SixLabors/ImageSharp#2477]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.1

### Other ImageSharp packages and versions

3.0.1

### Environment (Operating system, version and so on)

Windows 10

### .NET Framework version

6.0

### Description

Images saved using Pbm Binary Byte format (P4) are corrupted. 
It seems like the file written is too short and if you try to open it in GIMP it will say it's corrupted.
Reloading the saved file and saving to a different format you can see it is visibly corrupted. 
I have tried a few different images and they all have the same issue. 

### Steps to Reproduce

`
var image = Image.Load("input.png");
var encoder = new PbmEncoder()
{
    ColorType = PbmColorType.BlackAndWhite,
    ComponentType = PbmComponentType.Byte,
    Encoding = PbmEncoding.Binary
};
image.Save("output.pbm", encoder);
var output = Image.Load("output.pbm");
output.SaveAsPng("output.png");

`

### Images

![input](https://github.com/SixLabors/ImageSharp/assets/85151246/af28ed4e-8fbd-4883-b602-e21e2c867418)
![output](https://github.com/SixLabors/ImageSharp/assets/85151246/5468af7c-0caf-42c9-bbef-8e26a21716c7)
[output.zip](https://github.com/SixLabors/ImageSharp/files/11785960/output.zip)
[outputImageMagick.zip](https://github.com/SixLabors/ImageSharp/files/11786038/outputImageMagick.zip)

**Comment by ynse01** [comment]
Sure, would love to fix this bug
