### ISSUE TITLE
Async IO methods should use `FileOptions.Asynchronous`

### ISSUE THREAD

**Issue by Neme12** [SixLabors/ImageSharp#2487]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.1

### Environment (Operating system, version and so on)

Windows 11 Version 22H2

### .NET Framework version

.NET 7.0.304

### Description

Async methods that read/write from the file system, such as `Image.LoadAsync` and `Image.SaveAsync`, use async methods on `FileStream` but don't instantiate the `FileStream` with `FileOptions.Asynchronous`, as should be done when using async operations. This means that the implementation isn't actually truly async and instead uses synchronous IO on a new thread, needlessly using more resources.

There is a simple workaround for this by creating the `FileStream` manually and giving ImageSharp the stream as opposed to the file path, e.g.:
```c#
await using (var fileStream = new FileStream(path, new FileStreamOptions
{
    Mode = FileMode.Open,
    Access = FileAccess.Read,
    Share = FileShare.Read,
    Options = FileOptions.Asynchronous,
}))
using (var image = await Image.LoadAsync(fileStream))
{
// ...
}
```
but I feel like this is a bug and should be fixed in ImageSharp itself. The method is misleading, suggesting that it uses async IO while actually doesn't.

**Comment by antonfirsov** [comment]
This makes sense, here is what BCL is doing for `File.ReadAllTextAsync`:

https://github.com/dotnet/runtime/blob/2f208128f257b2390a8edefa0a19e0eaad6bd419/src/libraries/System.Private.CoreLib/src/System/IO/File.cs#L853-L856

I guess `SequentialScan` would make things worse in our case, because `BufferedReadStream` does `Seek` a lot.

@Neme12 interested raising a PR?

**Comment by Neme12** [comment]
Sure, I can give it a try.

**Comment by Neme12** [comment]
I cloned the repo, followed all the instructions, built the solution and ran tests, and there's 1 test failure - `PreferContiguousImageBuffers_LoadImage_BufferIsContiguous(formatOuter: "webp")` . Is this expected?
