### ISSUE TITLE
jpeg Image cannot be loaded 

### ISSUE THREAD

**Issue by michaelakin** [SixLabors/ImageSharp#2494]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.1

### Other ImageSharp packages and versions

n/a

### Environment (Operating system, version and so on)

Windows 11

### .NET Framework version

net6.0

### Description

I have tried to load a file that was transferred from an iPhone, but it will not load into ImageSharp.

Here is my sample app:

```
var files = Directory.GetFiles(@"C:\Users\myuser\Downloads");
var types = new List<string>() { ".jpg", ".jpeg", ".png" };

foreach (var file in files)
{
    var ext = Path.GetExtension(file);
    if (types.Contains(ext))
    {
        Console.WriteLine(file);
        try
        {
            var image = Image.Load(file);
            Console.WriteLine(image.Size.ToString());
        }
        catch (Exception ex)
        {
            Console.WriteLine($"{file} error {ex.Message}");
            //throw;
        }
    }
}
```

### Steps to Reproduce

Run the code above in a new dotnet 6 console app.

### Images

![0929C_bol](https://github.com/SixLabors/ImageSharp/assets/7062652/7e7e8a40-8ed1-4a96-ab53-740e0cc6d7b4)

**Comment by michaelakin** [comment]
Also, when I load the file from windows 11 explorer, it loads fine into the windows image app.

**Comment by JimBobSquarePants** [comment]
The image is HEIC not Jpeg. 

https://stackoverflow.com/a/62462584/427899

<img alt="image" src="https://github.com/SixLabors/ImageSharp/assets/385879/deaeff21-8962-4c2d-b444-2dfbf4b683e5">

There's a 3rd party decoder available for those file types.

https://github.com/hey-red/ImageSharp.Heif

**Comment by michaelakin** [comment]
Thanks for the confirmation.  I will try that.  So far, I am having issues with it but will work with that package to figure it out.
