### ISSUE TITLE
JPEG. SixLabors.ImageSharp.InvalidImageContentException: 'Input stream does not have enough bytes to parse declared contents of the D7 marker.'

### ISSUE THREAD

**Issue by spec1er** [SixLabors/ImageSharp#2517]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.1

### Other ImageSharp packages and versions

2.1.5

### Environment (Operating system, version and so on)

win7, win11

### .NET Framework version

4.8

### Description

Hello!

I found out by experience that since 2.1.1 on one JPEG file, taken from scanner SixLabors.ImageSharp.Image.Load(PATH_TO_JPEG) throw this:

SixLabors.ImageSharp.InvalidImageContentException: 'Input stream does not have enough bytes to parse declared contents of the D7 marker.'

### Steps to Reproduce

`using (var image = SixLabors.ImageSharp.Image.Load("C:\\temp\\Scan762.jpg"))`

### Images

![Scan762](https://github.com/SixLabors/ImageSharp/assets/10131236/7f9349a3-54f9-4ba1-b8d4-2a99a218d6e9)

**Comment by JimBobSquarePants** [comment]
>I have verified that I am running the latest version of ImageSharp

This is very important. We only support the latest major release which in this case is v3.x. Have you verified that the issue exists there?

**Comment by spec1er** [comment]
> > I have verified that I am running the latest version of ImageSharp
> 
> This is very important. We only support the latest major release which in this case is v3.x. Have you verified that the issue exists there?

Sorry, NO. I tried running on last version supported on net48. This feature we need on net48.

**Comment by JimBobSquarePants** [comment]
Note for v3 we should allow skipping D0-D7 in `JpegDecoderCore.LoadTables` when called via `JpegDecoderCore.ParseStream`
