### ISSUE TITLE
DrawImage doesn't overlay the "x" position properly if "x" is < 0

### ISSUE THREAD

**Issue by Spawnkid** [SixLabors/ImageSharp#252]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When using  DrawImage with a negative X position,  it seems that the rightmost part of the image were cropped instead of moving the image to the left (negative position relative to parent image).

### Steps to Reproduce

Just try to set negative location in the X position like below:

                        image
                            .DrawImage(image2, size, new Point(-31, 62), GraphicsOptions.Default)
                            .Save(stream, new PngEncoder()); 

### System Configuration

- ImageSharp version: 1.0.0-alpha9-00140
- Other ImageSharp packages and versions: ImageSharp.Drawing 1.0.0-alpha9-00135
- Environment (Operating system, version and so on):  W10 64bit
- .NET Framework version: WPF .Net 4.6

- Additional information:
![drawimage](https://user-images.githubusercontent.com/28699801/27327251-9297dd7e-55e0-11e7-84cb-00f600747f49.png)

**Comment by JamesMatchett** [comment]
What should the correct behavior be if a negative coordinate is set? @JimBobSquarePants @Spawnkid 

I'm looking to get started in helping in solving issues on GitHub to build my experience but I'm not too sure where to start. Thanks -James

**Comment by tocsoft** [comment]
The correct behaviour would be that the left/top edge should be the one cropped not the right/bottom.

**Comment by JamesMatchett** [comment]
@tocsoft  Thanks for clarifying, sorry for being a bit of a Github amateur, at this stage I can just fork over the repo and make a pull request once I think I've solved what the issue is?

Thanks a bunch, James

**Comment by JimBobSquarePants** [comment]
@JamesMatchett I'd still consider myself an amateur after all these years 😄 

It would be smashing if you could help here, we'd all really appreciate it!
