### ISSUE TITLE
Unable to save images with DPI changes

### ISSUE THREAD

**Issue by trinhpapa** [SixLabors/ImageSharp#2527]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.2

### Other ImageSharp packages and versions

No

### Environment (Operating system, version and so on)

Windows 11 and Linux

### .NET Framework version

.NET 6

### Description

I uploaded the image from the path and saved the image as Jpeg, but it automatic changed the DPI from 300 to 72. I tried changing the DPI to 32 but it still saved the image with 72 DPI default. It doesn't seem to work.

### Steps to Reproduce

        using Image image = Image.Load(imagePath);
        var metaData = image.Metadata;
        var currentDPI = image.Metadata.HorizontalResolution;
        if (currentDPI < 300)
        {
            image.Metadata.VerticalResolution = 300;
            image.Metadata.HorizontalResolution = 300;
        }

        image.SaveAsJpeg("test.jpg", new JpegEncoder { Quality = 100 });

### Images

![code](https://github.com/SixLabors/ImageSharp/assets/23254838/e5cd3e23-5616-4dc6-a54e-aa88ecba059c)
![Aaron_Jay_Young_4N4A3583](https://github.com/SixLabors/ImageSharp/assets/23254838/ef745abe-5dbc-432c-93d2-f2644b2e742f)

**Comment by JimBobSquarePants** [comment]
I don't actually understand your issue. 

You talk about changing the DPI to values other than 300 but your code sample changes the DPI to 300?

I looked at the properties of the second image you uploaded and that also say that the DPI is 300?

<img alt="image" src="https://github.com/SixLabors/ImageSharp/assets/385879/68e4cf8a-ec39-49b6-84fa-51176f9ed316">

**Comment by trinhpapa** [comment]
> 

Yes, that's the example image I'm using for testing. When running that image and saving it to test.jpg, it is only 72dpi

**Comment by trinhpapa** [comment]
> I don't actually understand your issue.
> 
> You talk about changing the DPI to values other than 300 but your code sample changes the DPI to 300?
> 
> I looked at the properties of the second image you uploaded and that also say that the DPI is 300?
> ![image](https://user-images.githubusercontent.com/385879/266496039-68e4cf8a-ec39-49b6-84fa-51176f9ed316.png)
Yes, that's the example image I'm using for testing. When running that image and saving it to test.jpg, it is only 72dpi

**Comment by trinhpapa** [comment]
![image](https://github.com/SixLabors/ImageSharp/assets/23254838/b842e5cb-36db-4456-b3f3-c70412873d5b)

**Comment by trinhpapa** [comment]
![test](https://github.com/SixLabors/ImageSharp/assets/23254838/93ed978f-36ee-4af4-97a5-8e14b4d524ec)
This is image result, even though I tried changing or keeping the DPI the same, it was always 72 DPI

**Comment by JimBobSquarePants** [comment]
OK. 

Please try to supply all the relevant information in one go, otherwise it's just noise.

**Comment by JimBobSquarePants** [comment]
Windows is reading the resolution from the EXIF metadata you need to change it in both places or remove the EXIF resolution metadata

<img  alt="image" src="https://github.com/SixLabors/ImageSharp/assets/385879/6290fbdb-9bcb-485a-9c0c-4cf7394b909a">
