### ISSUE TITLE
transparency issues with some .webp images

### ISSUE THREAD

**Issue by Lovrenc** [SixLabors/ImageSharp#2528]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.2

### Other ImageSharp packages and versions

/

### Environment (Operating system, version and so on)

ubuntu 20.04, win 11, ryzen

### .NET Framework version

7.0

### Description

Most images work fine, but some will replace part of the transparent background with white background (but not all of it, a small rectangle around the image stays transparent).

Here are the results as viewed in an image viewer.
Original:
![image](https://github.com/SixLabors/ImageSharp/assets/2620599/c25ff922-0aa0-4633-a5cd-ee793ec25f7e)

Result:
![image](https://github.com/SixLabors/ImageSharp/assets/2620599/54375e23-53d2-43e0-b0d0-f15f7070e9a0)

### Steps to Reproduce

```

var img = Image.Load("d:\\bugged_image.webp");
var encoder = new WebpEncoder()
{
    TransparentColorMode = WebpTransparentColorMode.Preserve
};
img.Mutate(t => t.Resize(img.Width/2, img.Height/2));
img.Save("d:\\bugged_image_result.webp");
```

### Images

[bugged_image.zip](https://github.com/SixLabors/ImageSharp/files/12570524/bugged_image.zip)

**Comment by brianpopow** [comment]
For some reason the `bugged_image.webp` seems to be encoded as an animated webp with a loop count of 1, which does not make alot sense to me.

```
webpinfo bugged_image.webp
File: bugged_image.webp
RIFF HEADER:
  File size:  60214
Chunk VP8X at offset     12, length     18
  ICCP: 0
  Alpha: 1
  EXIF: 0
  XMP: 0
  Animation: 1
  Canvas size 874 x 874
Chunk ANIM at offset     30, length     14
  Background color:(ARGB) ff ff ff ff
  Loop count      : 1
Chunk ANMF at offset     44, length  60170
  Offset_X: 98
  Offset_Y: 0
  Width: 663
  Height: 869
  Duration: 0
  Dispose: 0
  Blend: 1
Chunk ALPH at offset     68, length  30006
Chunk VP8  at offset  30074, length  30140
  Width: 663
  Height: 869
  Alpha: 0
  Animation: 0
  Format: Lossy (1)
No error detected.
```
If I first convert the image to be a normal lossy webp (not an animated webp), the issue goes away. Unfortunatly my usually approach to compare the decoding result to the reference implementation does not work here, since `dwebp` does not support decoding aniamted webp.

I thing the background color `(ARGB) ff ff ff ff` plays a role in with the issue, but I am not sure about it.

**Comment by brianpopow** [comment]
Most viewers/decoders seem to just ignore the background color. 
- Irfanview shows it as black color
- gimp as transparent color
- xnview also transparent color
- firefox/edge/chrome show it as gray
- even `vwebp` which is the official tool from libwebp to decode and show webp images ignores the background color

I tried changing the color to blue:
[bugged_image_blue_background.zip](https://github.com/SixLabors/ImageSharp/files/12777338/bugged_image_blue_background.zip)

Same result, no decoder cares about it. 
The specification of webp is unclear on how to use the background color. [ANIM spec](https://developers.google.com/speed/webp/docs/riff_container#animation)

```
Viewer applications SHOULD treat the background color value as a hint and are not required to use it.
The canvas is cleared at the start of each loop. The background color **MAY** be used to achieve this.
```

**Comment by JimBobSquarePants** [comment]
Thanks for looking at this @brianpopow 

I would say we are doing the correct thing by honouring the background color encoded in the image then.

**Comment by brianpopow** [comment]
@JimBobSquarePants I would also say we do it right, but it can be irritating for user, that only ImageSharp handles animated webp in that way and other viewers/decoders dont. It's really frustrating that the spec is so vague on this.
What do you think, would a decoder options to ignore the background color make sense?

@Lovrenc how did you create the image? It seems wrong that an animated image would only contain one frame. Also if you want the image background to be transparent, you should choose a transparent color for the background, not opaque white.

**Comment by Lovrenc** [comment]
Hey, 

I did not create the image, I took some random images from random customers to try ImageSharp out. I will track the customer and ask about the method and intentions and come back to you. 

Considering what you wrote though, I expect them to just be used to some method that is at its core wrong (and encodes opaque background into an image) but produces what they want in the viewers they are accustomed to.

**Comment by JimBobSquarePants** [comment]
> Member

We'd have to change `WebPDecoder` to inherit `SpecializedImageDecoder<TOptions>` and introduce a custom `WebPDecoderOptions` type containing a configuration property. I would use an enum. `BackgroundColorHandling` or similar with two options `Standard` and `Ignore`

**Comment by brianpopow** [comment]
@JimBobSquarePants Ok, I will give it a try in the next days

**Comment by Lovrenc** [comment]
> @Lovrenc how did you create the image? It seems wrong that an animated image would only contain one frame. Also if you want the image background to be transparent, you should choose a transparent color for the background, not opaque white.

Got a response:

I took an existing webp file and then ran an ffmpeg command on it to make it square.

`ffmpeg -i ${inputFilePath} -vf pad="max(iw\\,ih):ow:(ow-iw)/2:(oh-ih)/2:black@0.0" ${outputFilePath}`

**Comment by brianpopow** [comment]
@Lovrenc would it be ok, if I use the image you have provided in a unit test?

**Comment by Lovrenc** [comment]
Sorry for the late reply.

I do not object to it, but I do not hold a license to the artwork (though I doubt that could ever be an issue for a unit test).

**Comment by brianpopow** [comment]
with #2547 merged it is now possible to ignore the background color with a webp decoder option. Closing this now

**Comment by Lovrenc** [comment]
@brianpopow This is probably outside of the scope of the ticket. 
Can you guide me a bit please? I can see the flag in `WebpDecoderOptions`, and that works fine, I cannot however find a way to set it as a global/default behavior so it would get picked by `Image.Load` for instance.

What am I blundering?

**Comment by seanhakbb** [comment]
Hello! 
It seems I have a similar issue:
<img width="1584" alt="image" src="https://github.com/SixLabors/ImageSharp/assets/52152340/64bd3137-b4fc-4cb0-93e2-43545dddea67">
From left to right
FILE.png?width=360&height=0&format=png&quality=100
FILE.png?width=360&height=0&format=webp&quality=100
FILE.png

We're using Umbraco.CMS.Imaging.ImageSharp 13.1.1, SixLabors.ImageSharp.Web 3.1.0 & SixLabors.ImageSharp 3.1.3
Attaching original file, togheter with png and webp in zip
[webptests.zip](https://github.com/SixLabors/ImageSharp/files/14585259/webptests.zip)

Maybe I should submit this as a Umbraco ticket?

**Comment by JimBobSquarePants** [comment]
@seanhakbb this looks completely unrelated. I want to show you something weird though....

Here's the image displayed in Edge on my laptop screen.

![image](https://github.com/SixLabors/ImageSharp/assets/385879/5e40ff2a-e288-4a59-a5af-f02c7e11a61a)

And when it's dragged to my external screen.

![image](https://github.com/SixLabors/ImageSharp/assets/385879/8cbee387-870a-4082-b5c8-5e7ec7441cab)

**Comment by seanhakbb** [comment]
> @seanhakbb may be unrelated but I have to check the file. I want to show you something weird though....
> 
> Here's the image displayed in Edge on my laptop screen.
> 
> ![image](https://private-user-images.githubusercontent.com/385879/312411205-5e40ff2a-e288-4a59-a5af-f02c7e11a61a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjU1ODYsIm5iZiI6MTcxMDMyNTI4NiwicGF0aCI6Ii8zODU4NzkvMzEyNDExMjA1LTVlNDBmZjJhLWUyODgtNGE1OS1hNWFmLWYwMmM3ZTExYTYxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxMDIxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZTFlYzkyM2VjMTQ5YjM4MjMxMjMxNzUxMDJiOTU0NjIxNDIwNzYxYTFlZDNlZDYzZjBhZGM1OTk4OGVkZjQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NtSnoVypnRBtq4H-OioiULXW3q0MwcKG5feFlF_5UYc)
> 
> And when it's dragged to my external screen.
> 
> ![image](https://private-user-images.githubusercontent.com/385879/312411535-8cbee387-870a-4082-b5c8-5e7ec7441cab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjU1ODYsIm5iZiI6MTcxMDMyNTI4NiwicGF0aCI6Ii8zODU4NzkvMzEyNDExNTM1LThjYmVlMzg3LTg3MGEtNDA4Mi1iNWM4LTVlN2VjNzQ0MWNhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxMDIxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTQ5MjM1NGE0OGI5OWE5ZmQ4M2MwODcyYTM0ODU5OTRjM2M3NTM1OWViZjQ5MWJkY2I0YzAwZDI3YjhiMmM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LXlY5XMtOwkHMh64zSNoTBtR7_EsHx_8p669I886SxM)

I get the exact same thing, do you think this has something more to do with the original image itself? I have never seen anything like this before

**Comment by JimBobSquarePants** [comment]
I need to investigate the WebP and check what’s going on.
