### ISSUE TITLE
Support for GPSHPositioningError tag?

### ISSUE THREAD

**Issue by prabhavmehra** [SixLabors/ImageSharp#2542]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.2

### Other ImageSharp packages and versions

None

### Environment (Operating system, version and so on)

windows, android, ios

### .NET Framework version

7

### Description

Is Support for GPSHPositioningError tag present? if not, can we include that.

### Steps to Reproduce

Read exif image which has GPSHPositioningError.  unable to read or write the tag.

**Comment by JimBobSquarePants** [comment]
Hi @prabhavmehra  

Just a heads up, feature requests should be made via Discussion channels not raised as issues. 

You're more than welcome to submit a PR if you feel like adding the missing tag. The relevant information about the tags backing structure is here. 

https://exiftool.org/TagNames/GPS.html

**Comment by Cheesebaron** [comment]
I can have a look at adding this one, is it just this one tag that is missing or are there more GPS related tags that should be included?
