### ISSUE TITLE
Bug ERROR Unknown App0 Marker - Expected JFIF ProfileResolver OSQid

### ISSUE THREAD

**Issue by JoseEliasSantos** [SixLabors/ImageSharp#2565]
Working with camera images, I ended up getting the error: System.NotSupportedException: 'Unknown App0 Marker - Expected JFIF.'. Looking at the latest issues I noticed that I was having a similar problem, I verified that the bytes referring to the maker of the file in question are: '\n', '[', 'I', 'D' and ' '. I added the ProfileResolver class to the OSQidMaker property and with that I was successful in loading the image, I also added a test with the image that generated the mentioned error.

_Originally posted by @JoseEliasSantos in https://github.com/SixLabors/ImageSharp/discussions/2564_

**Comment by JoseEliasSantos** [comment]
I can't push with my corrected branch getting the error remote: Permission to SixLabors/ImageSharp.git denied to JoseEliasSantos.

**Comment by JimBobSquarePants** [comment]
You must fork a repository, make the changes in your clone and then open a Pull Request. 

https://docs.github.com/en/get-started/quickstart/fork-a-repo

How did you create this issue without using the predefined template?
