### ISSUE TITLE
Image.Load() throws InvalidImageContentException: CRC Error. PNG IDAT chunk is corrupt!

### ISSUE THREAD

**Issue by oskarlindman** [SixLabors/ImageSharp#2570]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.2

### Other ImageSharp packages and versions

None

### Environment (Operating system, version and so on)

Windows 11 Version 22H2

### .NET Framework version

.net 7

### Description

I have two png images that opens fine with System.Drawing.Common, but that fails to open with ImageSharp, and instead throw an InvalidImageContentException: CRC Error. PNG IDAT chunk is corrupt! Both files can be viewed in windows.

### Steps to Reproduce

Just point to the filePath with Image.Open(filePath) and it should throw the exception when running the code.

```
 at SixLabors.ImageSharp.Formats.Png.PngThrowHelper.ThrowInvalidChunkCrc(String chunkTypeName)
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.ValidateChunk(PngChunk& chunk)
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.TryReadChunk(PngChunk& chunk)
   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.Decode[TPixel](BufferedReadStream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, Func`3 largeImageExceptionFactory, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.Png.PngDecoder.Decode[TPixel](DecoderOptions options, Stream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.Png.PngDecoder.Decode(DecoderOptions options, Stream stream, CancellationToken cancellationToken)
   at SixLabors.ImageSharp.Formats.ImageDecoder.<>c__DisplayClass1_0.<Decode>b__0(Stream s)
   at SixLabors.ImageSharp.Formats.ImageDecoder.<WithSeekableStream>g__PeformActionAndResetPosition|11_0[T](Stream s, Int64 position, <>c__DisplayClass11_0`1& )
   at SixLabors.ImageSharp.Formats.ImageDecoder.WithSeekableStream[T](DecoderOptions options, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Formats.ImageDecoder.Decode(DecoderOptions options, Stream stream)
   at SixLabors.ImageSharp.Image.Decode(DecoderOptions options, Stream stream)
   at SixLabors.ImageSharp.Image.<>c__DisplayClass80_0.<Load>b__0(Stream s)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](DecoderOptions options, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Load(DecoderOptions options, Stream stream)
   at SixLabors.ImageSharp.Image.Load(DecoderOptions options, String path)
   at SixLabors.ImageSharp.Image.Load(String path)
```

### Images

![transparent_png_without_extension_2](https://github.com/SixLabors/ImageSharp/assets/11799525/03878073-3ac0-424a-8f2e-02fffe3faccf)
![transparent_png_without_extension_1](https://github.com/SixLabors/ImageSharp/assets/11799525/e24cc769-3dbd-420b-977f-7f7b6dbec05c)

**Comment by JimBobSquarePants** [comment]
The IDAT is indeed corrupt.

<img  alt="image" src="https://github.com/SixLabors/ImageSharp/assets/385879/70ba308a-de1b-47fd-bf94-6c56db12412e">

We'll need to have a look at libpng to see if they have some special handling of this.

https://www.nayuki.io/page/png-file-chunk-inspector

**Comment by dlemstra** [comment]
Libpng also "throws an exceptions":

```
C:\Users\Dirk\Desktop>magick 277674454-e24cc769-3dbd-420b-977f-7f7b6dbec05c.png info:
magick: Expected 4 bytes; found 0 bytes `277674454-e24cc769-3dbd-420b-977f-7f7b6dbec05c.png' @ warning/png.c/MagickPNGWarningHandler/1526.
magick: Read Exception `277674454-e24cc769-3dbd-420b-977f-7f7b6dbec05c.png' @ error/png.c/MagickPNGErrorHandler/1492.
```

**Comment by svenclaesson** [comment]
![corrupt](https://github.com/SixLabors/ImageSharp/assets/2105609/57c5e277-a472-4f13-98f0-a2a238c0fe28)
This file, and the two above can be partially displayed by chrome, that uses libpng

**Comment by JimBobSquarePants** [comment]
Can they be opened by other imaging libraries? Chrome looks to have turned of the safety checks. (There’s a compiler option in libpng)

**Comment by svenclaesson** [comment]
[MagicScalar](https://github.com/saucecontrol/PhotoSauce) uses libpng and can handle the last image that i posted

**Comment by JimBobSquarePants** [comment]
Ah not a compiler option it seems. Look for `png_set_crc_action`

http://www.libpng.org/pub/png/libpng-manual.txt

**Comment by svenclaesson** [comment]
So [this](https://github.com/saucecontrol/PhotoSauce/blob/f24a07fec7426745a1d3b5e4e39cde51f5460fd1/build/vcpkg/ports/pspng/pspng.c#L60C35-L60C35) explains why it works in MagicScalar then.

Would it be possible to consider this for ImageSharp?

**Comment by svenclaesson** [comment]
After further investigation into MagicScaler, it turns out that using default settings on windows will result in [native WIC codecs](https://learn.microsoft.com/en-us/windows/win32/wic/native-wic-codecs) being used. This png codec is more forgiving.
Instead when libpng is used with "codecs.UseLibpng()" no CRC error is thrown but the resulting image is all black.

Since libpng is [considered the reference implementation](https://github.com/SixLabors/ImageSharp/wiki/Useful-tools-and-links) for ImageSharp, i would think it is reasonable to close this issue as won't do.
Any input?

**Comment by JimBobSquarePants** [comment]
This is precisely the kind of thing I designed [ISpecializedDecoderOptions](https://github.com/SixLabors/ImageSharp/blob/afe21339afb60061de8a942e1262cac230e6b6a2/src/ImageSharp/Formats/ISpecializedDecoderOptions.cs) for. There's no reason we cannot define rules for handling Crc and Adler validation on decode. 

Would you be interested in creating a PR?

**Comment by svenclaesson** [comment]
Tried it a bit but got stuck by the fact that IDAT and IEND is considered critical chunks and found no way of ignoring that fact if the file is truncated, IDAT is cut off and IEND is missing.

Maybe you have some pointers for me [here](https://github.com/svenclaesson/ImageSharp/pull/1/files)
PR not yet posted to here because it is work in progress still.

**Comment by JimBobSquarePants** [comment]
Sorry for the slow reply @svenclaesson I've been off the boil for the last few weeks with sickness. 

If you actually open a PR I can commit directly to your fork to help finish it off.

**Comment by EmilAlipiev** [comment]
What happened with the Image class from 3.0.2 current version? Why was it removed? It is so hard to find exact change set between a lot of commits. Is it not better document this as a big breaking change?

**Comment by Erik-White** [comment]
@JimBobSquarePants What is the easiest way to make use of the new options? Ideally I would like to be able to pass something through via `Image.Identify` or `Image.Load`, but they only take a basic `DecoderOptions`.

Would it be reasonable to add overloads that take `ISpecializedDecoderOptions` since that already contains a `DecoderOptions` property? Or maybe some other concept of aggregated specialized decoder options?

**Comment by JimBobSquarePants** [comment]
> @JimBobSquarePants What is the easiest way to make use of the new options? Ideally I would like to be able to pass something through via `Image.Identify` or `Image.Load`, but they only take a basic `DecoderOptions`.
> 
> Would it be reasonable to add overloads that take `ISpecializedDecoderOptions` since that already contains a `DecoderOptions` property? Or maybe some other concept of aggregated specialized decoder options?

Ideally, we'd add a general equivalent to `DecoderOptions` but we're stuck with the problem of what to choose... The specialized, or general version of the enum. Implementing it would require a breaking change to either remove or make nullable the specialized enum.

**Comment by Erik-White** [comment]
Just so I understand, you would like to add a new property to `DecoderOptions`, a new enum e.g. `CrcChunkHandling`.
This could then be used in place of `PngCrcChunkHandling`, and maybe also in other decoders?

Maybe the new one could be added and mapped to the specialized enum to save a breaking change? If I get time I could make an attempt at that.

**Comment by ADSAU-vestas** [comment]
So this issue is still pending, right? And no workaround in sight?

**Comment by ADSAU-vestas** [comment]
Possibly its not, there is a PR merged for it as I see now. 
I do get the same exception on `.Identify()` not on `.Load()`, guess its fixed on one path only.

**Comment by JimBobSquarePants** [comment]
Feel free to PR a fix for `Identify`

**Comment by ADSAU-vestas** [comment]
Ouch, I am working full time employed plus on 3 Github projects on my "spare" time already. Hard to find time for another one.

**Comment by svenclaesson** [comment]
Then you wait and hope for the best

**Comment by ADSAU-vestas** [comment]
> Possibly its not, there is a PR merged for it as I see now. I do get the same exception on `.Identify()` not on `.Load()`, guess its fixed on one path only.

Done some more investigation here and it seems to be an deeper issue.

The images where we can see the issue are actually saved with ImageSharp as PNG.
We do receive the image, using `var loaded = Image.Load(imageStream).Clone(i => i.AutoOrient());`
Then we determine the format from `var format = loaded.MetaData.DecodedImageFormat`, if it is an acceptable format we then store it into a memory stream from where we save it to cloud storage `loaded.Save(targetStream, format);`

So the issue happens somewhere between those lines. Will have to try and run an `.Identify()` after each step to get to the bottom of it.

**Comment by Erik-White** [comment]
As far as I can see, this is fixed. However it does require passing `SegmentIntegrityHandling.IgnoreImageData`

The default options throws InvalidImageContentException("CRC Error. PNG IDAT chunk is corrupt!"):
```
using var image = Image.Load("Issue_2589.png");
ImageInfo info = Image.Identify("Issue_2589.png");
```

Passing decoder options avoids the throw:
```
DecoderOptions options = new() { SegmentIntegrityHandling = SegmentIntegrityHandling.IgnoreImageData };
using var image = Image.Load(options, "Issue_2589.png");
ImageInfo info = Image.Identify(options, "Issue_2589.png");
```

Output:
<img width="256" height="256" alt="Image" src="https://github.com/user-attachments/assets/8529f400-e76b-427c-8574-2007202e2f96" />

**Comment by ADSAU-vestas** [comment]
I will try that out, but it does not explain how come that the image gets saved by ImageSharp with a corrupt IDAT block. As mentioned -> `Load()->Clone(AutoOrient())->Save`  and the incoming image has no defects.

**Comment by Erik-White** [comment]
Ok, it wasn't clear to me that you were starting with a good image that was maybe getting a corrupt IDAT during the ImageSharp processing.

When exactly do you get the exceptions? Do you do an `Identify()` after `loaded.Save(targetStream, format);`? Is the input image definitely well formed?

**Comment by ADSAU-vestas** [comment]
Yes, input images are definitely good. Created a console app to read a bunch of the ones that are saved with IDAT errors, all fine. 

The Identify() is separate from the load/clone/save cycle, different modules even, same ImageSharp library ( we are still on the latest 3.x version though)

**Comment by JimBobSquarePants** [comment]
>we are still on the latest 3.x version though

Stop wasting everyone’s time then

**Comment by ADSAU-vestas** [comment]
> Stop wasting everyone’s time then

So its already fixed in the 4.x version? Great. Then its just a license question.
