### ISSUE TITLE
JPEG Parse Fails If APP0 doesn't immediately follow SOI

### ISSUE THREAD

**Issue by QuinnDamerell** [SixLabors/ImageSharp#2578]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

v3.0.2

### Other ImageSharp packages and versions

None

### Environment (Operating system, version and so on)

Linux

### .NET Framework version

dotnet core 7.0

### Description

I run a service that processes webcam images from many users. These webcam images come from a variety of webcam servers, some [mjpg-streamer](https://github.com/jacksonliam/mjpg-streamer), webcam streamer, IP cameras, and more. I have recently encountered an issue where one of the webcam servers seems to be using a weird jpeg image format, where the `FF DB` (DQT) comes before the `FF E0` (APP0). Here's a hex dump of the headers from an image:

![image](https://github.com/SixLabors/ImageSharp/assets/7854873/59ba6d15-2c16-4aee-9763-90904dcef582)

The ImageSharp lib seems always to need the ``FF E0` to follow the `FF D8`. The fix would be to allow these header-type byte formats to be consumed in different orders.

### Steps to Reproduce

Produce a JPEG image with at DQT header and move the DQT header before the APP0 header.

**Comment by QuinnDamerell** [comment]
Actually, I was incorrect; the issue seems to be fixed with this fix.

https://github.com/SixLabors/ImageSharp/commit/492507fa2d4bcbd77ca638724db1307da99b5bd5

That change was made on Jun 23 of this year, and the latest release is from Aug 29th, do you have any idea when that change will make it to the release branch?

**Comment by JimBobSquarePants** [comment]
It's going to be part of the [v3.1](https://github.com/SixLabors/ImageSharp/milestone/12) which I've targeted to release at the end of the month. You can use our nightly releases in the interim (see readme) if you need it sooner.
