### ISSUE TITLE
TIF to JPG Color Problem

### ISSUE THREAD

**Issue by FabCodeDE** [SixLabors/ImageSharp#2586]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.02

### Other ImageSharp packages and versions

Web 3.01 & Web.Providers.Azure 3.01

### Environment (Operating system, version and so on)

Windows Server 2022 & Windows 11

### .NET Framework version

.NET Core 7

### Description

When converting a specific tif image from tif to jpg via web the colors are completly wrong and look distorted:
https://picture-media-pool.ap.basf.com/media/dnaahyll/gakago_erygr_2_05-blumeria-graminis-cmyk.tif?format=jpg&width=1920
If you download the image as tif and then view it with the windows image viewer it looks normal. I can also provide multiple examples of that.

### Steps to Reproduce

When converting a specific tif image from tif to jpg via web the colors are completly wrong and look distorted:
https://picture-media-pool.ap.basf.com/media/dnaahyll/gakago_erygr_2_05-blumeria-graminis-cmyk.tif?format=jpg&width=1920
If you download the image as tif and then view it with the windows image viewer it looks normal. I can also provide multiple examples of that.

### Images

![gakago_erygr_2_05-blumeria-graminis-cmyk](https://github.com/SixLabors/ImageSharp/assets/35263046/ca74808b-2f30-45d8-8ee3-e2dccd6a1312)
Can upload the tif here sadly, need to be downloaded via the url

**Comment by JimBobSquarePants** [comment]
The web portion here should be irrelevant. If you add the tiff to a zip file you can upload it.

**Comment by FabCodeDE** [comment]
[gakago_erygr_2_05-blumeria-graminis-cmyk.zip](https://github.com/SixLabors/ImageSharp/files/13459493/gakago_erygr_2_05-blumeria-graminis-cmyk.zip)
here you go

**Comment by brianpopow** [comment]
> [gakago_erygr_2_05-blumeria-graminis-cmyk.zip](https://github.com/SixLabors/ImageSharp/files/13459493/gakago_erygr_2_05-blumeria-graminis-cmyk.zip) here you go

The image looks correct to me with the current main branch when converting to jpg.

**Comment by JimBobSquarePants** [comment]
Closing as fixed in #2459
