### ISSUE TITLE
The number of samples in the TIFF BitsPerSample entry is not supported.

### ISSUE THREAD

**Issue by kandeepandev** [SixLabors/ImageSharp#2587]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.2

### Other ImageSharp packages and versions

3.0.1

### Environment (Operating system, version and so on)

aks and windows 2010

### .NET Framework version

6

### Description

We are using Image sharp to convert the tiff images to png, as part of that process we are using below code but it is throwing the error for for specific tiff files but file looks vaild tiff images only. 

When try to load tiff images using the below code through the error "The number of samples in the TIFF BitsPerSample entry is not supported." 

 using (MemoryStream loadImage = new MemoryStream(byteArray))
            {
                image = Image.Load(loadImage);
            }

So can you suggest the possible fix or work around for this issue.
I am login the issue as behalf of RM and RM have a license for this library. 

### Steps to Reproduce

1. Use the attached sample tiff images.
2. Use the below code to load the  tiff images
 using (MemoryStream loadImage = new MemoryStream(byteArray))
            {
                image = Image.Load(loadImage);
            }

### Images

[SampleTiffs.zip](https://github.com/SixLabors/ImageSharp/files/13449317/SampleTiffs.zip)

**Comment by brianpopow** [comment]
The `Bits/Sample` is missing in these images, it should be 1. 
@JimBobSquarePants How do you think we should handle this? Should we assume `Bits/Sample` is 1, when its missing and compression is `CCITT Group 4`?

tiffinfo:
```
=== TIFF directory 0 ===
TIFF Directory at offset 0x1561c (87580)
  Image Width: 2446 Image Length: 3453
  Resolution: 300, 300 pixels/inch
  Compression Scheme: CCITT Group 4
  Photometric Interpretation: min-is-white
  Rows/Strip: 1716
  Planar Configuration: single image plane
```

**Comment by JimBobSquarePants** [comment]
@brianpopow Yes, I think so. The compression format normally only used on bitonal images so that seems a sensible default.

**Comment by brianpopow** [comment]
@JimBobSquarePants ok, I will prepare a fix for that.

@kandeepandev Do we have the permission to use your sample images for unit tests?

**Comment by kandeepandev** [comment]
Ya, we can use that.

Thanks,
Kandeepan

**Comment by kandeepandev** [comment]
Hi team,
Thank you for the quick fix. When it will be available as release?

Thanks,
Kandeepan

**Comment by JimBobSquarePants** [comment]
The nightlies already are, see the readme for details
