### ISSUE TITLE
Calling `Transform` using a `ProjectiveTransformBuilder` on a 32-bit image leaves black in the background instead of transparency

### ISSUE THREAD

**Issue by aceoft** [SixLabors/ImageSharp#2616]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.1.1

### Other ImageSharp packages and versions

None

### Environment (Operating system, version and so on)

Win10 22H2

### .NET Framework version

7/8

### Description

In 3.0.2, when applying a taper or perspective transform to an `Rgba32` image using the `Transform` method, the areas left behind are transparent. Starting in 3.1.0, they are black instead. Not sure if this can be called a bug, but it is a change in behavior, so I submit this issue for your consideration.

### Steps to Reproduce

```csharp
using var original = Image.Load<Rgb24>("numbered-grid.png");
using var converted = original.CloneAs<Rgba32>();

var inset = 60;
var builder = new ProjectiveTransformBuilder();
builder.AppendTaper(TaperSide.Top, TaperCorner.Both, 1 - (inset * 2 / (float)original.Width));

converted.Mutate(i => i.Transform(builder));
converted.SaveAsPng("v311.png");
```

#### Output in 3.0.2:
- Image has transparent background
- Photoshop says "RGB Color" in Mode

![v302](https://github.com/SixLabors/ImageSharp/assets/3302131/b664277c-d39f-4175-b8bb-463fb4d022d6)

#### Output in 3.1.0, 3.1.1:
- Image has black background
- Photoshop says "Indexed Color" in Mode
 
![v311](https://github.com/SixLabors/ImageSharp/assets/3302131/a56e3b8b-2c40-4a67-9791-3fdea616afc1)

I noticed that loading up the source grid image in Photoshop also says 'Indexed Color' instead of RGB, so I converted it to RGB and tried again. Same black background, but now the output image is nearly 4x the size of the previous output (190KB vs 34KB), and RGB as well instead of indexed.

### Images

Indexed:
![numbered-grid](https://github.com/SixLabors/ImageSharp/assets/3302131/4e11e687-4275-48ef-9031-239ab7c75db0)

RGB:
![numbered-grid-rgb](https://github.com/SixLabors/ImageSharp/assets/3302131/53314e4b-b705-4bd0-a2fe-1fb4e734af65)

**Comment by JimBobSquarePants** [comment]
Delete the palette from the metadata. 

v3.1.0 will attempt to reuse it but you've introduced transparency where there was none previously.

**Comment by aceoft** [comment]
I saw your response and was nearly there after digging through the metadata, but your edit really helped and I have it working again, thank you!

**Comment by JimBobSquarePants** [comment]
No worries. I want to see if I can improve this for V4 so we do the right thing more often.
