### ISSUE TITLE
Add option to GifEncoder to enable dithering for animated gifs

### ISSUE THREAD

**Issue by tocsoft** [SixLabors/ImageSharp#262]
Add option to GifEncoder to enable dithering for animated gifs.

This should just be a flag that can change the default behaviour for animated gifs to allow users to enable dithering if the gif has frames. Leave default as current behaviour where dithering is disabled if frames are detected.

**Comment by JimBobSquarePants** [comment]
Thinking about it we should probably just leave dithering on and people can turn it off if they need to.
