### ISSUE TITLE
SetDrawingTransform doesn't seem to affect all Draw calls

### ISSUE THREAD

**Issue by RobotGizmo** [SixLabors/ImageSharp#2622]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.1.1

### Other ImageSharp packages and versions

Drawing: 2.1.0

### Environment (Operating system, version and so on)

Windows 11

### .NET Framework version

.NET 8

### Description

If I call SetDrawingTransform to set a rotation then call DrawImage the image isn't drawn with any rotation. Should SetDrawingTransform  be affecting all draw calls or is it limited to only some of them?

### Steps to Reproduce

This is basically the code, I just set the rotation on context then call DrawImage.

```
x.SetDrawingTransform(Matrix3x2Extensions.CreateRotationDegrees(60, new PointF(10, 10)));
x.DrawImage(bitmap); 
```

**Comment by RobotGizmo** [comment]
As a follow-up, I'm not sure if DrawImage counts as a shape or not. Sorry if this is a non-issue. If this is a non-issue is there a way to perform actions on an image when using DrawImage? Like can I tint the colour, scale it into a target rect, rotate it... etc without having to clone the original image, modify it, then dispose the clone?

**Comment by JimBobSquarePants** [comment]
`DrawImage` is a member of ImageSharp `SetDrawingTransform`. Is a member of ImageSharp.Drawing. That’s two separate libraries. 

If you want to use the transform use `ImageBrush`. 

This would have been better framed as a question in our Discussions channels.
