### ISSUE TITLE
Load-Save TGA wiping alpha channel

### ISSUE THREAD

**Issue by AN3Orik** [SixLabors/ImageSharp#2629]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.0

### Other ImageSharp packages and versions

3.0.0

### Environment (Operating system, version and so on)

Windows 10

### .NET Framework version

.NET 8

### Description

Loading 32bit RGBA TGA and saving after wiping Alpha channel to white (255) color.

### Steps to Reproduce

```
using (Image<Rgba32> image = Image.Load<Rgba32>("test.tga"))
{
   image.Save("test_output.tga");
}
```

Before:
![image](https://github.com/SixLabors/ImageSharp/assets/6397450/63d5459d-a5c4-4eec-9c57-85a4baa87f64)

After:
![image](https://github.com/SixLabors/ImageSharp/assets/6397450/6ac53422-c3d1-4db9-a695-4c87c80446e5)

### Images

[test.zip](https://github.com/SixLabors/ImageSharp/files/13769125/test.zip)

**Comment by AN3Orik** [comment]
Sorry, library version is 3.1.1

**Comment by brianpopow** [comment]
The image descriptor byte in the file header of the provided image is 0. Usually bits 0-3 indicate designated as alpha channel bits.
Since the descriptor is 0, the decoder assumes there is no alpha channel. 

That is the reason it is lost when decoding and encoding again.

**Comment by brianpopow** [comment]
I still believe the provided image does not follow the spec with omitting the image descriptor, when there is alpha data.
Other decoders have problems with it too, like irfanview:

![test](https://github.com/SixLabors/ImageSharp/assets/38701097/e3d9b101-45e7-45fc-8c27-199405105a26)

I think one solution in handling this is to assume **true color** images with 32 bits per pixel to always have a alpha channel with 8 bit. @JimBobSquarePants What do you think about this? Would anyone write a 32 bits per pixel image without a alpha channel?

**Comment by JimBobSquarePants** [comment]
Yeah @brianpopow good idea! I think that’s a safe assumption and it’s non-destructive. We should add it to the v3.1.x branch and then main.

**Comment by brianpopow** [comment]
@AN3Orik can I use the image you have provided in a unit test?

**Comment by AN3Orik** [comment]
> @AN3Orik can I use the image you have provided in a unit test?

It's a texture from very old game, so i think it's not a problem at all if you care about license or something.

**Comment by brianpopow** [comment]
> We should add it to the v3.1.x branch 

@JimBobSquarePants I have opened a [PR](#2643) for this Issue. I am not sure how the procedure is to add it to the v3.1.x, I think, it would be better if you do that, so I dont break stuff. Also I am not totally sure this should go into a hotfix, since the image is not following the spec correctly and this PR only adds a workaround to deal with those kind of images.

**Comment by JimBobSquarePants** [comment]
I’m happy to skip adding to 3.1.x I’ve only been doing so because v4 is so far away.

**Comment by brianpopow** [comment]
closing this now with #2643 merged
