### ISSUE TITLE
ImageSharp poor performance on Blazor Assembly & MAUI

### ISSUE THREAD

**Issue by 3egirlsdream** [SixLabors/ImageSharp#2631]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.1.1

### Other ImageSharp packages and versions

SixLabors.Fonts2.0.1

### Environment (Operating system, version and so on)

MAUI Android & Blazor Assembly In browser

### .NET Framework version

.net 8

### Description

In Blazor Assembly and MAUI Android every function run slowly dozens of times. I don't know who should pay for it. ms or sb. but SkiaSharp worked well.  that's I want to say.

### Steps to Reproduce

**Image.Load()** U will understand

**Comment by JimBobSquarePants** [comment]
You should raise this with the Maui team. We’re not responsible for the failures of the Xamarin compiler.

**Comment by 3egirlsdream** [comment]
> You should raise this with the Maui team. We’re not responsible for the failures of the Xamarin compiler.
> 
> [dotnet/runtime#71210 (comment)](https://github.com/dotnet/runtime/issues/71210#issuecomment-1193075312)

and Blazor Assembly as well，not Xamarin compiler , if MS should fix it, maybe your team person in charge should ask MS to hurry up fix it?  ur product worked not well, u don't care about it ?

**Comment by sharpwood** [comment]
This is a serious issue: ImageSharp cannot be used at all on MAUI Android.

**Comment by antonfirsov** [comment]
@sharpwood the only way to push this forward is to upvote & comment on https://github.com/dotnet/runtime/issues/71210. There are no reasonable ways to address this from within the library.
