### ISSUE TITLE
Image.Load Error

### ISSUE THREAD

**Issue by TJMicroPower** [SixLabors/ImageSharp#2652]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.1.2

### Other ImageSharp packages and versions

OfficeIMO.Word 0.5.0

### Environment (Operating system, version and so on)

windows server 2019; windows 10

### .NET Framework version

8.0

### Description

dotnet 8.0,OfficeIMO.Word Call paragraph.AddImage(image, 160, 160);Error：Method not found: 'SixLabors.ImageSharp.Image SixLabors.ImageSharp.Image.Load(System.IO.Stream, SixLabors.ImageSharp.Formats.IImageFormat ByRef)'.

### Steps to Reproduce

var image = Path.Combine(imagePaths, imageName.Split('\\')[1]);
paragraph.AddImage(image, 160, 160); paragrapha is OfficeIMO.Word.WordParagraph

### Images

![微信图片_20240130095415](https://github.com/SixLabors/ImageSharp/assets/12667858/e60fa917-cc08-4116-a13f-72f34e1c522e)

**Comment by JimBobSquarePants** [comment]
You're attempting to use a major version of ImageSharp that differs from the version (v2.1.3) bundled with OfficeIMO.Word

https://www.nuget.org/packages/OfficeIMO.Word#dependencies-body-tab
