### ISSUE TITLE
Saving webp to jpg gives strange result

### ISSUE THREAD

**Issue by brianpopow** [SixLabors/ImageSharp#2660]
### Discussed in https://github.com/SixLabors/ImageSharp/discussions/2659

<div type='discussions-op-text'>

<sup>Originally posted by **omuleanu** February  7, 2024</sup>
I tried saving an webp image to jpg using this code:
```
using var fstream = file.OpenReadStream(); // file is IFormFile
var img = Image.Load(fstream);
await img.SaveAsync(filePath, new JpegEncoder { Quality = 50 });
```
and the result is quite strange, here is the result:
![7](https://github.com/SixLabors/ImageSharp/assets/2010805/e9ed9690-dd4c-4823-8b6e-fe48c17b95e8)
the original I've uploaded as zip, because webp is not allowed here
[before.zip](https://github.com/SixLabors/ImageSharp/files/14200293/before.zip)
</div>

**Comment by brianpopow** [comment]
webpinfo:

```
RIFF HEADER:
  File size:  74554
Chunk VP8X at offset     12, length     18
  ICCP: 0
  Alpha: 1
  EXIF: 1
  XMP: 0
  Animation: 0
  Canvas size 480 x 480
Chunk VP8L at offset     30, length  74330
  Width: 480
  Height: 480
  Alpha: 1
  Animation: 0
  Format: Lossless (2)
Chunk EXIF at offset  74360, length    194
No error detected.
```

**Comment by brianpopow** [comment]
@dlemstra yes you are right, it is not actually a bug in the decoder. Using a format which supports transparency or applying `image.Mutate(x => { x.BackgroundColor(Color.White); });` fixes the issue:

![output](https://github.com/SixLabors/ImageSharp/assets/38701097/d670d24a-cfa5-4847-8423-964ae29dc20f)

I was jumping to fast to a conclusion.

**Comment by omuleanu** [comment]
@dlemstra Thank You,
(shouldn't it default to white for transparent pixels ? ; like in mspaint you when save a transparent png as jpg)

**Comment by JimBobSquarePants** [comment]
No. We should never make assumptions that are destructive to incoming data.
