### ISSUE TITLE
Black Background after resizing in the latest version.

### ISSUE THREAD

**Issue by Elinareso** [SixLabors/ImageSharp#2668]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.1.2

### Other ImageSharp packages and versions

3.0.2

### Environment (Operating system, version and so on)

Windows VS 17.8.7

### .NET Framework version

NET7, NET8

### Description

After Resize and image to create a Thumbnail the result image is being created with a black or green or gray background.

```
            using SixLabors.ImageSharp.Image image = SixLabors.ImageSharp.Image.Load(Bytes);

            var imageResized = new MemoryStream();

            image.Mutate(x => x.Resize(dimensions.Width, dimensions.Height));
            image.Save(imageResized, image.Metadata.DecodedImageFormat);
```

### Steps to Reproduce

Using the version 3.0.2 the thumbnail es created at the same of the original png image. After upgrading to 3.1.2 a background is in the result image.

### Images

![Original](https://github.com/SixLabors/ImageSharp/assets/18618697/62a91bff-1705-4227-bddd-821cd17208bd)
![Result](https://github.com/SixLabors/ImageSharp/assets/18618697/07780773-186d-42c5-a1b3-7b47a35c793d)

**Comment by JimBobSquarePants** [comment]
Looks like we're not capturing the correct entry for the alpha palette (or maybe setting it incorrectly).

**Comment by Elinares-82** [comment]
> Looks like we're not capturing the correct entry for the alpha palette (or maybe setting it incorrectly).

Thanks so much for your quick fix. We are waiting the new version to move on this.

**Comment by JimBobSquarePants** [comment]
>Thanks so much for your quick fix. We are waiting the new version to move on this.

No problem. There's be a release out this week. Make sure that your company is working in accordance with the [Six Labors License](https://github.com/SixLabors/ImageSharp/blob/f85500ded85787c2cdbfc84c760039502558ff6b/LICENSE)

**Comment by Elinares-82** [comment]
> > Thanks so much for your quick fix. We are waiting the new version to move on this.
> 
> No problem. There's be a release out this week. Make sure that your company is working in accordance with the [Six Labors License](https://github.com/SixLabors/ImageSharp/blob/f85500ded85787c2cdbfc84c760039502558ff6b/LICENSE)

Yes, we are!  👍
