### ISSUE TITLE
Simple conversion of Tiff file to PNG or JPG generates a strange result, even, at certain times, it is in 3D perspective

### ISSUE THREAD

**Issue by yuridiniz** [SixLabors/ImageSharp#2679]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.1.2

### Other ImageSharp packages and versions

No

### Environment (Operating system, version and so on)

Linux / Windows

### .NET Framework version

.NET 6

### Description

I have attached the images that are generating this behavior

### Steps to Reproduce

O problema ocorreu em uma imagem específica, segue código mínimo para reprodução:

```C#
using (var inImg = File.OpenRead("Image_025.tif"))
using (var outImg = File.Create("Image_025.png"))
using (var imagem = Image.Load(inImg))
{
    imagem?.Save(outImg, new PngEncoder());
}
```

### Images

[Img.zip](https://github.com/SixLabors/ImageSharp/files/14423153/Img.zip)

**Comment by brianpopow** [comment]
The expected decoded image `Image_021.tiff` should look like this:
![expected](https://github.com/SixLabors/ImageSharp/assets/38701097/32e59f4f-88b2-4e9c-8717-ed4623eb3a01)

It actually looks like this from the main branch:
![actual](https://github.com/SixLabors/ImageSharp/assets/38701097/7aa4ff32-fa94-4e1f-b82d-e8d9354ffa80)

The tiffinfo is:
```
TIFFReadDirectory: Warning, Unknown field with tag 347 (0x15b) encountered.
Image_021.tif: JPEG compression support is not configured.
=== TIFF directory 0 ===
TIFF Directory at offset 0x8 (8)
  Image Width: 1666 Image Length: 2359
  Resolution: 200, 200 pixels/inch
  Bits/Sample: 8
  Compression Scheme: JPEG
  Photometric Interpretation: YCbCr
  YCbCr Subsampling: 2, 2
  Samples/Pixel: 3
  Planar Configuration: single image plane
  Reference Black/White:
     0:     0   255
     1:   128   255
     2:   128   255
```

So this is a jpeg compressed tiff image. The image decodes correctly, if we set the ycbcrSubSampling to 1, 1 instead of 2, 2, since this is already handled by the jpeg decoding part.
I am not 100% sure if we always can assume ycbcrSubSampling to 1, 1 with tiff compressed jpeg's. @JimBobSquarePants any thoughts?

**Comment by JimBobSquarePants** [comment]
Does the tag specifically state the subsampling is 2, 2?

https://www.awaresystems.be/imaging/tiff/tifftags/ycbcrsubsampling.html

**Comment by JimBobSquarePants** [comment]
I had another dig through our Tiff code (I really do not enjoy how complicated it is to follow) and it appears to me that our jpeg scan decoder is already handling the deinterleaving so we can treat the subsampling as [1, 1] when using the jpeg decoder.

**Comment by brianpopow** [comment]
> I had another dig through our Tiff code (I really do not enjoy how complicated it is to follow) and it appears to me that our jpeg scan decoder is already handling the deinterleaving so we can treat the subsampling as [1, 1] when using the jpeg decoder.

Ok, thanks for confirming. I think what makes it so complicated is the myriads of possible combinations of compressions, pixelformats  and colorspaces. When ever I think now we finally covered all possible combinations someone comes up with a new tiff variant.

I will try to make a fix for that. @yuridiniz Is it ok, if we use your testimage in a unit-test?

**Comment by brianpopow** [comment]
Since #2789 was merged, I will close this now as completed
