### ISSUE TITLE
Exif rotation and save

### ISSUE THREAD

**Issue by bertasoft** [SixLabors/ImageSharp#2693]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.1.3

### Other ImageSharp packages and versions

no package

### Environment (Operating system, version and so on)

Windows 11

### .NET Framework version

NET 8

### Description

Exif rotation and save

3.1.3

I have some Exif image to adjust but the library don't give the expected result.

Before
![Screenshot 2024-03-09 101858](https://github.com/SixLabors/ImageSharp/assets/926243/d817d34e-da61-4c6d-993c-a881cd8abb1b)

After, the library make the rotation
![Screenshot 2024-03-09 101919](https://github.com/SixLabors/ImageSharp/assets/926243/4e607cdd-9c15-4c0a-b2b2-e1102678ba28)

But it doesn't save correctly
![Screenshot 2024-03-09 101953](https://github.com/SixLabors/ImageSharp/assets/926243/c9ba6d69-dc7f-4b3c-aad2-da15a4c0f9d0)

In the attachment the image that i used

Thanks

### Steps to Reproduce

Look the description

### Images

![original](https://github.com/SixLabors/ImageSharp/assets/926243/b96ee7bd-8448-465d-b16e-cd036b4642d8)

**Comment by JimBobSquarePants** [comment]
I’m not sure what you are expecting here. The image was rotated to match the exif orientation.

**Comment by bertasoft** [comment]
I'm expected that the rotated is like this 

![Rotated](https://github.com/SixLabors/ImageSharp/assets/926243/feac7ac5-34a2-4d4e-8bfa-3400f409b429)

**Comment by JimBobSquarePants** [comment]
That's an incorrect assumption. `AutoOrient` update the orientation of the image to match the EXIF metadata properties and removes those properties from the metadata. 

As you can see on your breakpoints. The input image has physical dimensions of 1536x2048 (portrait) but is displayed rotated 90degrees (landscape). Once processed the image pixels are 2048x1536 which matches the landscape display orientation of the input.

**Comment by bertasoft** [comment]
Ok, how can I have the rotated version of the image like my example? 

Something that follow the exif infos and give me the jpg rotated, any c# code example?

Now i'm using something like this

private const int exifOrientationID = 0x112; //274

public static void ExifRotate(this Image img)
{
    if (!img.PropertyIdList.Contains(exifOrientationID))
        return;

    var prop = img.GetPropertyItem(exifOrientationID);
    int val = BitConverter.ToUInt16(prop.Value, 0);
    var rot = RotateFlipType.RotateNoneFlipNone;

    if (val == 3 || val == 4)
        rot = RotateFlipType.Rotate180FlipNone;
    else if (val == 5 || val == 6)
        rot = RotateFlipType.Rotate90FlipNone;
    else if (val == 7 || val == 8)
        rot = RotateFlipType.Rotate270FlipNone;

    if (val == 2 || val == 4 || val == 5 || val == 7)
        rot |= RotateFlipType.RotateNoneFlipX;

    if (rot != RotateFlipType.RotateNoneFlipNone)
    {
        img.RotateFlip(rot);
        img.RemovePropertyItem(exifOrientationID);
    }
}


Thanks for clarification,
