### ISSUE TITLE
File (detected as bmp) fails to open, consumes a lot of memory

### ISSUE THREAD

**Issue by skanejohan** [SixLabors/ImageSharp#2696]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.1.3

### Other ImageSharp packages and versions

N/A

### Environment (Operating system, version and so on)

Windows 11

### .NET Framework version

.net 8

### Description

The attached (zipped) file, 126 bytes long, gives an out-of-memory error when I try to open it with the following code:

```
using FileStream stream = File.OpenRead("00271-imageworsener-leftshift");
SixLabors.ImageSharp.Image.Load(stream);
```

I believe there is a problem with the image dimensions - BmpDecoderCore.ReadImageHeaders sets this.infoHeader.Width and this.infoHeader.Height to very high values which tries to create a huge image in BmpDecoderCore.Decode().

### Steps to Reproduce

See description.

### Images

[00271-imageworsener-leftshift.zip](https://github.com/SixLabors/ImageSharp/files/14583779/00271-imageworsener-leftshift.zip)

**Comment by JimBobSquarePants** [comment]
Can you please re-upload the zip file. GitHub is showing varnish cache errors when I try to download it.

**Comment by skanejohan** [comment]
[00271-imageworsener-leftshift.zip](https://github.com/SixLabors/ImageSharp/files/14584223/00271-imageworsener-leftshift.zip)

**Comment by skanejohan** [comment]
Our testers reported this, and it turns out the file is from a test set used to test ImageMagick - https://github.com/rip1s/Fuzzing-ImageMagick

**Comment by JimBobSquarePants** [comment]
Thanks, I'll look at this today.
