### ISSUE TITLE
I have encountered a bug with heigh and width of image

### ISSUE THREAD

**Issue by sodiqjonovich** [SixLabors/ImageSharp#2736]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.1.4

### Other ImageSharp packages and versions

3.1.4

### Environment (Operating system, version and so on)

Windows 11, Linux Ubuntu

### .NET Framework version

.net6

### Description

![image](https://github.com/SixLabors/ImageSharp/assets/74007674/cd81ec52-dccd-42e3-858c-4baf21d2fdd8)

This is my picture, in here width = 4282pixels, height = 5712 pixels.
But In ImageSharp showing wrong

![image](https://github.com/SixLabors/ImageSharp/assets/74007674/b84e7be4-a824-436f-bb8f-c43e884fd7bb)

### Steps to Reproduce

using (var imageSharp = SixLabors.ImageSharp.Image.Load<Rgba32>(image.OpenReadStream()))
{
    var width = imageSharp.Width;
    var height = imageSharp.Height;

    // Check image ratio
    double allowedRatio = 0.01;
    var ratio = (double) width / height;
    if (Math.Abs(ratio - ((double)_ratioX / _ratioY)) >= allowedRatio)
    {
        return new ValidationResult($"Image ratio should be {_ratioX}:{_ratioY}");
    }
}

### Images

![image](https://github.com/SixLabors/ImageSharp/assets/74007674/4037afaa-2c9f-4384-ac82-d8e9129cb7d6)
![image](https://github.com/SixLabors/ImageSharp/assets/74007674/42a0aaec-4f5e-4113-a984-5c64108171f8)

**Comment by tocsoft** [comment]
this is most likely due to some metadata tag setting a rotation (EXIF). We don't handle that automagically like windows/viewer software does.

You will want to call the `img.Mutate(p=>p.AutoOrient())` helper to force the pixel into the correct orientation.

**Comment by sodiqjonovich** [comment]
I should only get with and heigh of image, how can i get via this library

**Comment by tiesont** [comment]
Also: #2644

**Comment by JimBobSquarePants** [comment]
> I should only get width and height of image, how can i get via this library

The height and width of the image are the ones reported by the library. This is exactly the same as other libraries. If you want orientation dimensions you will have to check the image metadata.
