### ISSUE TITLE
Missing Separable Blending Modes?

### ISSUE THREAD

**Issue by ShadowsAreBlack** [SixLabors/ImageSharp#2737]
This issue lists Separable blend modes
**color-dodge** blend mode
**color-burn** blend mode
**soft-light** blend mode
**difference** blend mode
and
**exclusion** blend mode

as completed in this issue, however in the current version:
```
Enum PixelColorBlendingMode
Add (Linear Dodge)
Darken
HardLight
Lighten
Multiply
Normal
Overlay
Screen
Subtract
```

The ones I listed are not present, or anywhere in the current documentation

https://www.w3.org/TR/compositing-1/#blending
It would also be nice to have Non-separable blend modes support such as
"**hue**"
"**saturation**"
"**color**"
or "**luminosity**"
for a larger range of compositing options

_Originally posted by @ShadowsAreBlack in https://github.com/SixLabors/ImageSharp/issues/16#issuecomment-2113247151_

**Comment by JimBobSquarePants** [comment]
Please do not raise feature suggestions as issues. We have a documented process.

**Comment by ShadowsAreBlack** [comment]
Sorry I was not Clear, Minus my suggestion at the end.

https://github.com/SixLabors/ImageSharp/issues/16#issue-186120563

Most of these blending modes are not present in the current version of ImageSharp, yet theyre listed as completed almost 10 years ago?
I cannot find any documentation about "Color-Burn" besides that link as I need to use it.
