### ISSUE TITLE
After the jpeg image is loaded, there is a problem with the image color

### ISSUE THREAD

**Issue by anjisZhou** [SixLabors/ImageSharp#2755]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.8

### Other ImageSharp packages and versions

2.1.6

### Environment (Operating system, version and so on)

win11

### .NET Framework version

4.6.2

### Description

I load a jpeg image from a file and save it as a bmp or jpg. When I view it with other image viewers, the image displays strangely. So far, I have only found this one image that has the problem, and it does not appear when I load it with `System.Drawing.Bitmap`.

### Steps to Reproduce

```
using (var image = Image.Load<Bgr24>("./src.jpg"))
{
  image.SaveAsJpeg("111.jpg");
}
```

### Images

![B409A35F-21EF-4696-917A-EFE2B42E9DC6](https://github.com/SixLabors/ImageSharp/assets/25604955/8b8ccef2-1762-49da-9d5c-88181ffec306)
Original file

![1111](https://github.com/SixLabors/ImageSharp/assets/25604955/fea6473e-6145-4e8b-a13d-2c1e65d68a92)
Re-saved file

**Comment by JimBobSquarePants** [comment]
Hi @anjisZhou 

It's really important that when you complete this issue template you do so accurately. 

 - [X] I have verified that I am running the latest version of ImageSharp
 
 The version you have specified is version 2.1.8. As of this point in time the latest version is 3.1.4
 
 We do not support issues raised against anything other than the latest version and as such I will close this. If you still have the same issue with 3.1.4, please feel free to reopen the issue.
