### ISSUE TITLE
Image.Load() with ''CRC Error. PNG Image chunk is corrupt"

### ISSUE THREAD

**Issue by xakep139** [SixLabors/ImageSharp#276]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I try to load PNG image that displays normally. It also loads normally with .NET Framework's `System.Drawing.Image.FromFile()`.
There was similar issue that has been closed: #127 

### Steps to Reproduce

Simple code:
```
Image.Load("banner.png");
```
With image [banner.zip](https://github.com/SixLabors/ImageSharp/files/1144422/banner.zip) cause an `ImageSharp.ImageFormatException` with stacktrace:

```
   at ImageSharp.Formats.PngDecoderCore.ReadChunkCrc(PngChunk chunk)
   at ImageSharp.Formats.PngDecoderCore.ReadChunk()
   at ImageSharp.Formats.PngDecoderCore.Decode[TPixel](Stream stream)
   at ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)
   at ImageSharp.Image.WithSeekableStream[T](Stream stream, Func`2 action)
   at ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)
   at ImageSharp.Image.Load[TPixel](Configuration config, String path)
   at ImageSharp.Image.Load(String path)
   at ImageSharpTest.Program.Main(String[] args) in c:\users\user
\documents\visual studio 2017\Projects\ImageSharpTest\Program.cs:line 12
```

### System Configuration

- ImageSharp version: 1.0.0-alpha9-00171
- Environment: Windows 10 Enterprise Version 1703 Build 15063.483
- Visual Studio Professional 2017 Version 15.2 (26430.15)
- `dotnet --info` output:
```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
```

**Comment by dlemstra** [comment]
Just did a quick test to see if the image was actually corrupt. ImageMagick can read it without any issues and ImageMagick normally is very strict about errors inside an image. Means this is most likely an issue inside the decoder.

**Comment by xakep139** [comment]
Any updates on this?

**Comment by JimBobSquarePants** [comment]
None yet I'm afraid, we've not had the opportunity (sickness, time constraints etc). You'll see something here as soon as we do.

**Comment by funkyOne** [comment]
![zincartabstract_smallbar](https://user-images.githubusercontent.com/2235489/28774041-865a9536-75f4-11e7-98e0-d30703bb76e7.png)

**Comment by JimBobSquarePants** [comment]
Thanks. Yeah images that break our decoder are always useful. I'll get stuck in asap. Stuck doing stuff for my day job just now.

**Comment by JimBobSquarePants** [comment]
I've checked everything and the new fix works. Enjoy!
