### ISSUE TITLE
Missing CurrentImageFormat

### ISSUE THREAD

**Issue by MaklaCof** [SixLabors/ImageSharp#279]
### Description
Before upgrading to version 1.0.0-alpha9-00173 I was using the following code to get extension:

```
    public static string GetImageExt(Stream image)
    {
      using (var img = ImageSharp.Image.Load(image))
      {
        return img.CurrentImageFormat.Extension;
      }
    }
```

but now CurrentImageFormat does not exists. How can I get image extension from Stream?

**Comment by dlemstra** [comment]
You will need to use the overload that has an `IImageFormat` as an out argument.

**Comment by MaklaCof** [comment]
What is the method name and in which namespace it is?

**Comment by tocsoft** [comment]
its an out param overload on the standard `Image.Load`
you do it like this
````
IImageFormat format;
using(var img = ImageSharp.Image.Load(image, out format)){
  // .. do your thing
}
````
