### ISSUE TITLE
BmpEncoder does not respect QuantizerOptions.Dither when BitsPerPixel is 1, 2 or 4

### ISSUE THREAD

**Issue by mistoll** [SixLabors/ImageSharp#2817]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.1.5

### Other ImageSharp packages and versions

None

### Environment (Operating system, version and so on)

Win 11

### .NET Framework version

.net 8

### Description

When writing 1-bit (or 2, 4) files using BmpEncoder, the dither settings are not respected.

That is, because in https://github.com/SixLabors/ImageSharp/blob/5c2812901488bc7e97512e97b8a4aa2629c29185/src/ImageSharp/Formats/Bmp/BmpEncoderCore.cs#L681-L684

the QuantizerOptions is replaced with new QuanitzerOptions, which does not include the inital Dither values. Similar code is in Write2BitPixelData and Write4BitPixelData.

I'd write a pull request, but I don't know how you want to handle that. Like modify the original options, create a full clone opt the original options, remove the new options completely, or whatever you come up with.

### Steps to Reproduce

```
var image = // Load any image
var palette =new Color[] { Color.Black, Color.White };
var quantizerOptions = new QuantizerOptions() { MaxColors = 2, Dither = **null** };
var quantizer = new PaletteQuantizer(palette, quantizerOptions);
var encoder = new BmpEncoder { BitsPerPixel = BmpBitsPerPixel.Pixel1, Quantizer = quantizer };
image.SaveAsync(anyFile, encoder);
```

The result is a image with dithering (example created from car.bmp from test images)
![grafik](https://github.com/user-attachments/assets/de3eb985-f189-4766-bd2a-f96748f2b0dc)

**Comment by JimBobSquarePants** [comment]
Thanks for the detail here and analysis. It's very much appreciated!

The correct approach would be to do the following all places where we require new options. 

```c#
using IQuantizer<TPixel> frameQuantizer = this.quantizer.CreatePixelSpecificQuantizer<TPixel>(configuration, new QuantizerOptions()
{
    MaxColors = 2, // Use correct value for each method
    Dither = this.quantizer.Options.Dither,
    DitherScale = this.quantizer.Options.DitherScale
});

If you could submit a PR that would be really great.
```
