### ISSUE TITLE
Make ComparableExtensions public 

### ISSUE THREAD

**Issue by Inumedia** [SixLabors/ImageSharp#282]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
In order to implement custom PixelFormats, being able to use ComparableExtensions helps as that's used in some of the existing PixelFormats.

### Steps to Reproduce
* Try to make an Rgb565 PixelFormat outside of the ImageSharp repository based off of `src/ImageSharp/PixelFormats/Bgr565.cs`
* Notice that x.Clamp in the Pack method does not resolve.

### System Configuration
All.

- ImageSharp version: 1.0.0-alpha9-00173
- Other ImageSharp packages and versions: "ImageSharp.Drawing" Version="1.0.0-alpha9-00168"
- Environment (Operating system, version and so on): Ubuntu 16.10
- .NET Framework version: NetCore 1.1
- Additional information: Pls.

**Comment by JimBobSquarePants** [comment]
I have no issue making them public. @antonfirsov @tocsoft @dlemstra thoughts?

**Comment by tocsoft** [comment]
I'm not convinced we should... they are just internal helpers really not something  we should be exposing on our public API. If we expose it we have to support it and supporting clamping functions isn't what this library is for.

**Comment by Inumedia** [comment]
I strongly disagree with that sentiment. Exposing something publicly does not necessarily imply supporting that functionality, but rather that you're trying to make use of the primary functionality easier and more convenient. 

Not to drive too far into that but even if you exposed it publicly and later took it back, the clamp function isn't hard to reproduce. It should really just be exposed publicly as a convenience.

**Comment by antonfirsov** [comment]
I don't think the library should expose internals outside of the scope of it's main purpose. The thinner the API, the easier to maintain.

Closing as part of a general issue cleanup, if someone disagrees - feel free to reopen.
