### ISSUE TITLE
Imagesharp's alpha blending doesn't result in standard sRGB values

### ISSUE THREAD

**Issue by jez9999** [SixLabors/ImageSharp#2839]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.1.5

### Other ImageSharp packages and versions

SixLabors.ImageSharp.Drawing 2.1.4

### Environment (Operating system, version and so on)

Windows 10

### .NET Framework version

.NET 8

### Description

Given the two files included below (a white background and a foreground mask with some black pixels at 50% alpha), when both are loaded in and the mask is drawn onto the background, it should result in pixels where the black pixels are on the mask being 188,188,188; this is the color perceptually half-as-dark as black.  In GIMP, this is what you get.  However in ImageSharp you get pixels with RGB 128,128,128.  This seems to not be how the pixels should be blended in sRGB.

GIMP result:
![GIMP result](https://github.com/user-attachments/assets/e96abd07-58b8-4ae5-be00-e545b8b782d6)

ImageSharp result:
![ImageSharp result](https://github.com/user-attachments/assets/f8b55777-f007-4b9a-934b-c6d6181481a3)

### Steps to Reproduce

```
Image imgTestBg = await Image.LoadAsync("white-bg.png");
Image imgTestMask = await Image.LoadAsync("black-mask.png");

imgTestBg.Mutate(x =>
    x.DrawImage(imgTestMask, 1)
);

await imgTestBg.SaveAsPngAsync(@"combined-output.png");
```

### Images

![white-bg](https://github.com/user-attachments/assets/d7319a90-a160-4dd9-ab64-b394867981eb)

![black-mask](https://github.com/user-attachments/assets/5eb0f87a-3d4c-4f5b-b0d8-74db878a7753)

**Comment by JimBobSquarePants** [comment]
I'm not convinced GIMP is doing the correct thing (_and this has nothing to do with sRGB_). Pixel Composition requires alpha premultiplication and it does not appear to me that GIMP is performing that premultiplication.

Here's the CSS take on this, which in my opinion is absolutely correct and matches the ImageSharp output. 

https://jsfiddle.net/w5sx9mfq/

**Comment by JimBobSquarePants** [comment]
Closing this as I think the ImageSharp implementation is correct.
