### ISSUE TITLE
Allow encoding directly from frames

### ISSUE THREAD

**Issue by PazerOP** [SixLabors/ImageSharp#284]
It'd be nice to have `IImageEncoder` also have the overload
```C# 
void Encode<TPixel>(ImageBase<TPixel> imageBase, Stream stream) where TPixel : struct, IPixel<TPixel>
```

That way, you can directly save frames of an image as separate images without having to clone them as you have to now:

```C#
var img = Image.Load(source);

foreach (var frame in img.Frames.Select((f, i) => (f, i)))
{
	var frameImg = new Image<Rgba32>(frame.Item1);

	var outputFile = File.Create($"frames/{frame.Item2}.png");
	frameImg.SaveAsPng(outputFile);
}
```

**Comment by JimBobSquarePants** [comment]
Your wish is granted! :smile:

The latest builds on MyGet now allow exporting of frames 

``` c#
using( var img = Image.Load(source))
{
    foreach (var frame in img.Frames.Select((f, i) => (f, i)))
    {
        using (Image<TPixel> cloned = img.Frames.ExportFrame(i))
        {
         // Save cloned frame
        }
    }
}
```

**Comment by antonfirsov** [comment]
@JimBobSquarePants what does `.Select((f, i) => (f, i))` do in your sample code? Or is it just a typo?

**Comment by JimBobSquarePants** [comment]
I just copy/pasted the surrounding code above to be honest. It doesn't do anything now I look at it.
