### ISSUE TITLE
Losing quality on loading 48/64 bpp PNG

### ISSUE THREAD

**Issue by xakep139** [SixLabors/ImageSharp#285]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Loading 48/64 bpp PNG lose quality even if using `Rgba64` as `TPixel`. This is due to compressing 16 bits of bit depth in 8 bits in `ImageSharp.Formats.PngDecoderCore.ProcessDefilteredScanline()` and in `ImageSharp.Formats.PngDecoderCore.ProcessInterlacedDefilteredScanline()`

### Steps to Reproduce

Simple image loading with
```
var image = Image.Load<Rgba64>("some64bpp.png");
```

### System Configuration

- ImageSharp version: 1.0.0-alpha9-00175
- Environment: Windows 10 Enterprise Version 1703 Build 15063.483
- Visual Studio Professional 2017 Version 15.2 (26430.16)
- `dotnet --info` output:
```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
```

**Comment by JimBobSquarePants** [comment]
Thanks @xakep139 for raising this. 

@dlemstra and I actually discussed this last night. We should make sure we preserve the information by moving any compression logic where is is required. 

To properly fix the issue we're going to have to introduce encoding support for those pixel depths also.

**Comment by JimBobSquarePants** [comment]
Just realised this was still open. Fixed it 6 months ago! 😆
