### ISSUE TITLE
Off-color pixels in WuQuantizer output

### ISSUE THREAD

**Issue by funkyOne** [SixLabors/ImageSharp#286]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
For large sprite image input WuQuantizer outputs some off-color pixels. 
Red pixels everywhere:
![issue1](https://user-images.githubusercontent.com/2235489/28815182-2a6caea2-76a9-11e7-9a21-80b74e53755c.PNG)
Weird grain, original is subtle gradient:
![issue2](https://user-images.githubusercontent.com/2235489/28815185-2ea48ca6-76a9-11e7-917b-7df571f1011d.PNG)
Green pixels:
![issue3](https://user-images.githubusercontent.com/2235489/28815189-31c174f8-76a9-11e7-842b-3a3bab7e5e37.PNG)

Feels like the reason may be in the last steps when quantizer chooses which color from palette to use for a pixel. Just a speculation, but, perhaps it selects mathematically closest, when should also take human perception into account? 

I've run the same image through pnguant and nQuant both output cleaner results. All result images are in the attachment.
[quantization-issue.zip](https://github.com/SixLabors/ImageSharp/files/1189895/quantization-issue.zip)

### Steps to Reproduce
        void Test4()
        {
            var path = @"sample.png";

            using (var img = Image.Load(path))
            {                                   
                img.Quantize(Quantization.Wu);
                var encoder = new ImageSharp.Formats.PngEncoder() { PaletteSize = 256 };
                img.Save("sample-ImageSharp.png", encoder);
            }
        }

### System Configuration
- ImageSharp version: 1.0.0-alpha9-00175
- Environment: Windows 10
- .NET Framework version: 2.0.0-preview2-006497

**Comment by JimBobSquarePants** [comment]
Hi @funkyOne 

This should really be a question not an issue. The grain is due to the chosen error ditherer and will differ from image to image. 

NQuant uses a Wu Quantizer but doesn't support error dithering (I had a quick look at the code and saw no trace of one), that works well for some images but terribly for others. PngQuant uses a Median Cut Quantizer with a Floyd Steinburg ditherer with extra tweaks to limit the color range of chosen colors. We use a Sierra Lite ditherer without the tweaks as it's much faster. 

Note: PngQuant is specifically designed with for only one task so can afford to tweak it's ditherer to customise the equation, we have to keep it mathematically pure.

All this is configurable though (Look for the Dither property on the quantizer) I would experiment and see what gives you the best output. You might even be better off using the Octree Quantizer in your case, you never know. We actually support all the dithering and diffusion algorithms on this page. http://www.tannerhelland.com/4660/dithering-eleven-algorithms-source-code/

Hope that helps

Cheers

James

**Comment by funkyOne** [comment]
Hi James,
Sorry for this. Great thanks for the info. I finally start to grasp something about the images. Octree was even worse and I tried all dithering algos with Wu and the best result I got was with dithering off. 

It gives almost as good (for my image) result as nQuant. Still some slight issues.

Still nQuant result is visually more suitable in my case. Having the same quantizer algorithm and dithering off I wonder what else could contribute to this difference?

**Comment by JimBobSquarePants** [comment]
@funkyOne No worries... I'm actually curious to see what is causing the difference now. I'll have to download the nQuant source to see what is going on. The original images you uploaded contain much less colors in the ImageSharp palette than the nQuant one.

**Comment by funkyOne** [comment]
Ah, great I still got your interest!

The samples are from a large image bundle. For original question I tried to localize issue as much as possible, I cropped off a part of the bundle and tested with it. The latter one I snipped from whole bundle processed. 

Just found a more more severe visual issue:
Original
![orig](https://user-images.githubusercontent.com/2235489/28867317-550a1d90-777e-11e7-803b-2187e3e57e45.PNG)
nQuant
![nquant](https://user-images.githubusercontent.com/2235489/28867321-5baf4526-777e-11e7-9bb9-653e74a99f68.PNG)
ImageSharp(Wu, no dithering)
![imagesharp](https://user-images.githubusercontent.com/2235489/28867329-64cf0d26-777e-11e7-8eab-a837850e0447.PNG)

I know it's kind of an edge case, quantizing such a big (30meg) image and expecting an ideal result. I think about improvement to our bundling process - group the images by similar palette and produce multiple bundles for optimal quantization. Which is another big challenge for me! 

But still, even with current input nQuant produces more or less acceptable image. Would be really great to understand what's the deal here. If it's due to some tweaks to Wu quantizer in nQuant, we could probably post these as a separate recipe or a configuration point to the quantizer? So that mathematical pureness of the original implementation is still preserved.

Let me know if you want the original source bundle image. I'll send you the link.

Also let me know if i can help with anything else.

Cheers

**Comment by funkyOne** [comment]
I wonder if this is related to 2nd caveat from this link https://github.com/leeoniya/RgbQuant.js/tree/master#caveats--tips

The author also suggests a solution for this. I will try to test that lib later today, and let you know what I get.

**Comment by JimBobSquarePants** [comment]
That second example looks like a bug to me. I'm gonna re open this.

**Comment by funkyOne** [comment]
@JimBobSquarePants, I've sent you the source image via WeTransfer

**Comment by JimBobSquarePants** [comment]
@funkyOne I don't have the second image anymore to accurately test against but I retested our current output from dev branch [1.0.0-dev002212](https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp/1.0.0-dev002212) against your original image. 

Our new output is on the left, as you can see it's far superior. We've changed a couple of things.

- We now assign the same number of bits available for each color component for comparison when reducing the color palette as NQuant does.
- We introduce less error into the image when dithering to ensure blocks of color do not have unnecessary error introduced.

![image](https://user-images.githubusercontent.com/385879/48962465-42c32780-ef78-11e8-81c2-6417aed62da8.png)

I'm going to close this now but if you have any further issues let me know.
