### ISSUE TITLE
"CRC Error. PNG Image chunk is corrupt!" when loading certain image

### ISSUE THREAD

**Issue by devedse** [SixLabors/ImageSharp#290]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When loading the image below I run into an issue that ImageSharp says that the PNG Image chunk is corrupt.

[versioning-1_1.zip](https://github.com/SixLabors/ImageSharp/files/1211765/versioning-1_1.zip)
![versioning-1_1](https://user-images.githubusercontent.com/2350015/29127321-0b054e56-7d21-11e7-9689-63032d4086be.png)

### Steps to Reproduce

Simply load it using Image.Load();
```
// Loads the image
Image.Load(imagePath);
```

### System Configuration

- ImageSharp version: 1.0.0-alpha9-00176
- Other ImageSharp packages and versions: -
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: .NET Core
- Additional information: -

**Comment by dlemstra** [comment]
I get the following error with ImageMagick:

`identify: zTXt: CRC error `versioning-1_1.png' @ warning/png.c/MagickPNGWarningHandler/1709.`

Maybe this will help someone solve the issue. It looks like the image chunk is not corrupt.

**Comment by JimBobSquarePants** [comment]
What's that error telling me?

**Comment by dlemstra** [comment]
In ImageMagick we just report a warning when the `CRC` of the `zTXt` is incorrect. I just did a quick check of our decoder and we report `corrupt Image Chunk` for every chunk. I thought this was an exception for an invalid `IDAT` chunk. I wonder if we should only throw an exception when the `CRC` of a [critical chunk](http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html) are invalid?

**Comment by xakep139** [comment]
Is this issue related to #276?

**Comment by JimBobSquarePants** [comment]
Most likely. We should double check the PR against all given images in both issues

**Comment by devedse** [comment]
Thanks for fixing all these issues so quickly guys :smile:
