### ISSUE TITLE
Saving png image as jpg loses characteristics

### ISSUE THREAD

**Issue by spyker0** [SixLabors/ImageSharp#293]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When an image in png format with transparency is saved as jpg, it loses characteristics.
Example:
![sancris-portugues-horizontal](https://user-images.githubusercontent.com/26263503/29171753-f4f258d2-7db3-11e7-8a74-6ec9d53c3b81.png)

Becomes:
![5a12f01c8f80b06bd282cbf2c0f7a62c](https://user-images.githubusercontent.com/26263503/29171819-2df0e34c-7db4-11e7-8850-319a4e441d3e.jpg)

### Steps to Reproduce
```c#
        public static string GravaImagem(IFormFile imagem, IFileProvider fileProvider)
        {
            if (imagem.Length > 0)
            {
                var image = Image.Load(imagem.OpenReadStream());

                var imageName = Md5Image.GeraMd5(image);

                var path = ReplaceExtension($@"/images/{imageName.Substring(0, 3)}/{imageName}");

                var fileinfo = fileProvider.GetFileInfo(path);

                Directory.CreateDirectory(Path.GetDirectoryName(fileinfo.PhysicalPath));

                if (!fileinfo.Exists)
                {
                    using (var outputStream = new FileStream(fileinfo.PhysicalPath, FileMode.CreateNew))
                    {
                        image.SaveAsJpeg(outputStream);
                    }
                }
                return path;

            }
            return "";
        }

        private static string ReplaceExtension(string wwwRelativePath)
        {
            return Path.Combine(
                Path.GetDirectoryName(wwwRelativePath),
                Path.GetFileNameWithoutExtension(wwwRelativePath)) + ".jpg";
        }

```

### System Configuration

- ImageSharp version: ImageSharp.1.0.0-alpha9-00176
- Other ImageSharp packages and versions: -
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: .NET Core
- Additional information: -

**Comment by tocsoft** [comment]
This defiantly feels like a bug... its will be happening because your source image will actually be using transparent green and when we save it the png we just blindly remove the transparancy.

As a work around if you use `image.Background(Rgba32.White)` before saving you should get the effect your after. However we should probably do an equivalent processing pass on all pixels with transparency whenever we save to a format that doesn't support transparency.

**Comment by dlemstra** [comment]
We should not touch the transparent pixels. When the image is saved in a format that does not support transparency it is the user their responsibility to change the transparent pixels. If we change them to another color this might cause unwanted behavior. Calling `image.Background(Rgba32.White)` is not a work around but something that should/can be done by the user.

**Comment by spyker0** [comment]
I understand, this solves my problem, thank you!
