### ISSUE TITLE
Strange description of nuget package.

### ISSUE THREAD

**Issue by hardhub** [SixLabors/ImageSharp#295]
PLACEHOLDER - DO NOT DOWNLOAD. 

A cross-platform library for the processing of image files; written in C#.

Version: 0.0.0

![image](https://user-images.githubusercontent.com/4306334/29254015-58b3f6a4-8094-11e7-9fdf-daf9d92cbc17.png)

**Comment by JimBobSquarePants** [comment]
Hi @hardhub 

You're looking at the Nuget package description instead of the MyGet one which you would have installed. The Nuget hosted package is a placeholder just now. 

Cheers

James

**Comment by hardhub** [comment]
I have installed it with:

`Install-Package ImageSharp -Version 1.0.0-alpha9-00182 -Source https://www.myget.org/F/imagesharp/api/v3/index.json`

After that I opened VS dependencies and it shows me above info for your package.  
So it is at least very confusing...

**Comment by JimBobSquarePants** [comment]
That's a VS issue then. The MyGet repo contains none of those description comments.
