### ISSUE TITLE
Implement new Vector methods correctly to take advantage of performance improvements

### ISSUE THREAD

**Issue by JimBobSquarePants** [SixLabors/ImageSharp#3]
_From @JimBobSquarePants on December 1, 2015 12:23_

The new `System.Numerics.Vectors` contains several new types that take advantage of SIMD processors and are specifically designed graphics programming. I have little-to-no knowledge of those types and will need assistance integration the various methods they offer in order to utilize them properly.

_Copied from original issue: JimBobSquarePants/ImageProcessor#259_

**Comment by JimBobSquarePants** [comment]
_From @voidstar69 on January 23, 2016 14:27_

@JimBobSquarePants is this the sort of change that you are looking for?

Changing Color.Lerp from this:

        public static Color Lerp(Color from, Color to, float amount)
        {
            amount = amount.Clamp(0f, 1f);

            if (Math.Abs(from.A - 1) < Epsilon && Math.Abs(to.A - 1) < Epsilon)
            {
                return from + (to - from) * amount;
            }

            // Premultiplied.
            return from * (1 - amount) + to;
        }

to this:

        public static Color Lerp(Color from, Color to, float amount)
        {
            amount = amount.Clamp(0f, 1f);

            if (Math.Abs(from.A - 1) < Epsilon && Math.Abs(to.A - 1) < Epsilon)
            {
                return Vector4.Lerp(from, to, amount);
            }

            // Premultiplied.
            // TODO: not sure how to use Vector4.Lerp here
            return from * (1 - amount) + to;
        }

*might* improve performance by making use of the Vector4.Lerp method (need to measure performance to be certain).

**Comment by JimBobSquarePants** [comment]
You're absolutely correct. I can use the built in `Vector4.Lerp` in that situation. The `Color` minus operator utilizes the backing vector but we might as well cut out the middle man.

The code, I believe, would be: 

    return Vector4.Lerp(from.backingVector, to.backingVector, amount);

For premultiplied alpha we'd probably have to fall back to the non SIMD approach. 

I'd imagine it would be a very tiny performance improvement but every little most certainly helps.

**Comment by olivif** [comment]
I'll try to read a bit on this, see how far I get.

**Comment by olivif** [comment]
I see usage of `Vector4` in a bunch of places now, are there any remaining areas which we need to convert? 😄

**Comment by JimBobSquarePants** [comment]
I think it might be possible to vectorize bits and bobs throughout, maybe in colorspace conversions or running through lists. I know the subsampling scaling in jpeg decoder is vectorised in libjpeg turbo also. 

I just don't know the Numerics API's well enough though to figure out what could benefit.

**Comment by antonfirsov** [comment]
Subsampling is not an issue, the only test input where it goes over 1% is the cmyk watch:
![jpegcmykwatchprofile](https://cloud.githubusercontent.com/assets/6835152/21474436/505e5e98-cb1f-11e6-97ac-65371e60e335.png)

**Comment by JimBobSquarePants** [comment]
Closing this. @antonfirsov has done incredible work to implement vectorization throughout the library.
