### ISSUE TITLE
ErrorDiffusionDitherProcessor bug when constrained with a `Rectangle`

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#300]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The rectangle constraints are not well managed, this should start at (10,10):
![image](https://user-images.githubusercontent.com/6835152/29488187-02142672-8506-11e7-8c3a-90161b2dbf96.png)

### Steps to Reproduce
On `beta-1` branch: Re enable, and run the `ApplyDiffusionFilterInBox()` test case.

**Comment by JimBobSquarePants** [comment]
Fixed in #299
