### ISSUE TITLE
PNG decoder result is incorrect for certain images

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#301]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The decoder result has incorrect pixels with:
- [ ] Interlaced images (`TestImages.Png.Interlaced`)
- [ ] Certain other images from #296, like (`TestImages.Png.SnakeGame`)

### Steps to Reproduce
Uncomment commented test images, and unskip skipped tests in `PngDecoderTests` on the `beta-1` branch.

**Comment by JimBobSquarePants** [comment]
Fix for snakegame in beta-1, other fixes in master
