### ISSUE TITLE
NotSupportedException: Specified method is not supported

### ISSUE THREAD

**Issue by TJK2017** [SixLabors/ImageSharp#303]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Essentially when i use the  `.Save(output, ImageFormats.Jpeg); ` i get a 
`NotSupportedException: Specified method is not supported error`. 
I have opened a question on Stackoverflow [here](https://stackoverflow.com/questions/45815741/imagesharp-specified-method-is-not-supported/45816238#45816238).  `output.Position = 0;` is never reached when i use .Save

### Steps to Reproduce

  
            input.Seek(0, SeekOrigin.Begin);
            using (Image<Rgba32> image = Image.Load<Rgba32>(input))
            {

                if (image.Width >= image.Height)    //landscape
                {
                    ratio = image.Height / defaultWidth;                  
                }
                else //portrait
                {
                    ratio = image.Width / defaultHeight;                   
                }

                image.Resize(image.Width / ratio, image.Height / ratio)
                   .Crop(defaultWidth, defaultHeight)               
                    .Save(output, ImageFormats.Jpeg);
            }
            // upload the resized and cropped file
            output.Position = 0;
            await source.UploadFromStreamAsync(output);

### System Configuration
- ImageSharp version: 1.0.0-alpha9-00182
- Environment: Windows 10
- Visual Studio Communtiy 2017 Version 15.3.0
- dotnet  --info

```
.NET Command Line Tools (1.1.0)

Product Information:
 Version:            1.1.0
 Commit SHA-1 hash:  d6f4336106

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.1.0

```

**Comment by JimBobSquarePants** [comment]
Hi @TJK2017

You forgot to put the relevant stacktrace here but thankfully it was on the Stackoverflow question.

The answer was given there also. The error is thrown not by us but by the underlying stream you are attempting to write to.

`Microsoft.AspNetCore.Http.Internal.ReferenceReadStream.Write(byte[] buffer, int offset, int count)`

Don't try to write to that stream (e.g. a MemoryStream) and you will be fine. 

Hope that makes sense

**Comment by TJK2017** [comment]
@JimBobSquarePants  thanks for that, writing to another MemoryStream worked. Apologizes for creating what turns out to be a non-issue.

**Comment by JimBobSquarePants** [comment]
No worries, every day is an opportunity to learn something new. :smile:
