### ISSUE TITLE
Libraries are not signed!

### ISSUE THREAD

**Issue by fahadabdulaziz** [SixLabors/ImageSharp#308]
### Prerequisites

- [ * ] I have written a descriptive issue title
- [ * ] I have verified that I am running the latest version of ImageSharp
- [ * ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ * ] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
ImageSharp libraries are not signed which cause a problem when using them on signed libs.

### Steps to Reproduce
* Create a new library (I used WinForms targeting .NET 4.7)
* Sign it with a certificate or snk file
* Run it and it throw exception

### System Configuration

- ImageSharp version: Latest on MyGet
- Other ImageSharp packages and versions: Latest on MyGet
- Environment (Operating system, version and so on): Win10
- .NET Framework version: 4.7
- Additional information:

Thank you

**Comment by M-Zuber** [comment]
https://github.com/dsplaisted/strongnamer is what you need.
Enjoy!

**Comment by fahadabdulaziz** [comment]
Thank you @M-Zuber .. :-)
