### ISSUE TITLE
Need help building and running on MacOS in PowerShell

### ISSUE THREAD

**Issue by larssb** [SixLabors/ImageSharp#311]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [-] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Help needed. I'm trying to build this in VS Code, C# and .net core has been installed and VS Code closed and opened to make sure it can read the install.

### Steps to Reproduce

- Hit ctrl-shift-b to run the build job from the tasks.json file in the .vscode folder in the project.
-- it builds and builds but.....
>> I'm unsure of how-to:
- load the Imagesharp assembly with PowerShell in the correct way, if it is actually supported Usually .NET componets are supported to be loaded in PowerShell. 
I have tried to list the available assemblies on the system and Imagesharp does not seem to be there. So could be it, but I have done the built.
- How to properly built Imagesharp. I tried following the somewhat scarse notes via: https://github.com/SixLabors/ImageSharp#manual-build but I'm unsure that the result is as it should be.

Could you please guide me in the right direction.

### System Configuration
- ImageSharp version: 1.0.0-alpha9-00187
- Other ImageSharp packages and versions: 
- Environment (Operating system, version and so on): MacOS sierra v10.12.6
- .NET Framework version: .net core dotnet-sdk-2.0.0-osx-gs-x64.pkg installed
- Additional information:
-- VS Code v1.15.1
-- C# VS Code extension v1.12.1

-----

**Thank you very much.**

**Comment by larssb** [comment]
I also get this error when building:

> /usr/local/share/dotnet/sdk/2.0.0/Microsoft.Common.CurrentVersion.targets(1122,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/gitRepos/ImageSharp/tests/ImageSharp.Sandbox46/ImageSharp.Sandbox46.csproj]

**Comment by antonfirsov** [comment]
@larssb I think it's the Sandbox46 project. It's a special profiling project, you don't need it to produce a build.
Does remove it from the solution help?

**Comment by larssb** [comment]
Hi @antonfirsov ,

Thank you very much for replying. It is highly appreciated. That helped me built the thing. However, because of lack of documentation and my competencies reading through C# code I'm having a hard time actually using the dll's in a PowerShell session.
This is as far I get:
- I can build the ImageSharp project in MacOS now.
- I can load the assembly in a PowerShell session with >> `add-type -path /PATH/ImageSharp.dll`

But that is pretty much it. How do I find out what methods and so forth is available on the loaded assembly?

Thank you.

**Comment by larssb** [comment]
Okay so I got a little further....by "eye" parsing the code 👍 .... 

So:
- `add-type -path /PATH/ImageSharp.dll`
- Then I can do `[ImageSharp.Image]::Load("/Users/JohnDoe/Downloads/myPicture.jpg") << however that one throws this error == 

> The following exception occurred while retrieving member "Load": "Could not load file or assembly 'System.Memory, Version=4.0.0.0, Cultu
re=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
"
At line:1 char:1
+ $maaske = [ImageSharp.Image]::Load("/Users/JohnDoe/Downloads/myPic ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ExtendedTypeSystemException
    + FullyQualifiedErrorId : CatchFromBaseGetMember

Shouldn't it be possible to use the overloads on the Load function? So that I can read a file directly with [ImageSharp.Image]::Load("pathToImage) ??? 

**Also, notice that I'm using PowerShell v6 beta 6 on MacOs sierra** << so it is in there I'm trying to use ImageSharp as shown in the example above.

Thank you :-D

**Comment by JimBobSquarePants** [comment]
Hi @larssb .

I've never tried to run the code via Powershell, let alone on MacOs (I'm utterly useless with a Mac, they make me feel like an idiot) so I'm not much help I'm afraid. 

It might be better if you ask these questions in our Gitter forum though. There's more eyes there and definitely more Cross Os experience. I'm sure there'll be someone lurking who can help you.

Cheers

James

**Comment by larssb** [comment]
Hi @JimBobSquarePants ,

Thank you very much.....I myself am on a learning curve in regards to using a Mac. I'll try over in your Gitter forum.

Thank you....

PS: @antonfirsov if you by any chance have an idea I would be happy to know.

**Comment by larssb** [comment]
Finally did it. My process for others landing here:

1) Build CoreFX Microsoft repo. Make sure to do the 'release' version.
2) Build the SixLabors.Core repo (https://github.com/SixLabors/Core).
3) Copied the System.Memory.dll and the System.Runtime.CompilerServices.Unsafe.dll plus the SixLabors.Core.dll as well as the ImageSharp.dll to the **same folder** under my PowerShell project.
4) 
- `Add-Type -Path "Path to the imagesharp.dll"`
- `Add-Type -Path "Path to the SixLabors.Core.dll"`
- `$myImage = [ImageSharp.Image]::Load('/pathToTheImage.JPG')`
Then you can do `$myImage.MetaData.ExifProfile.Values` <-- **IF** the picture has any EXIF data.

I will go ahead and close this issue. Thank you for the help to those that got in on the case.

**Comment by JimBobSquarePants** [comment]
Nice work! I'm glad you figured it out. 👍

**Comment by dlemstra** [comment]
And thanks for letting us know how you solved it.
