### ISSUE TITLE
Use primitives from System.Drawing

### ISSUE THREAD

**Issue by fahadabdulaziz** [SixLabors/ImageSharp#312]
Hello,

Why not use System.Drawing.Primitives classes like Size, Rectangle.

**OR**

At least add implicit converter like this:

```csharp
        public static implicit operator System.Drawing.Size(Size size)
        {
            return new System.Drawing.Size(size.Width, size.Height);
        }

        public static implicit operator Size(System.Drawing.Size size)
        {
            return new Size(size.Width, size.Height);
        }
 ```

Thanks

**Comment by JimBobSquarePants** [comment]
Because we are trying to design better primitives with which we can provide a more usable, faster API. 

Why did you delete the issue template? Did you not read our contribution guidelines?

**Comment by fahadabdulaziz** [comment]
> Because we are trying to design better primitives with which we can provide a more usable, faster API.

Ok, then why not add implicit convert or maybe a wrapper class with extensions to convert these primitives.
It would be more compatible with the .NET classes, I have some projects still using System.Drawing and some projects converted to .NET standard and started using ImageSharp but I had to convert these primitives between them.

> Why did you delete the issue template? Did you not read our contribution guidelines?

Sorry I deleted the template because it not an issue. and no, I did not.

**Comment by fahadabdulaziz** [comment]
I just revised the Size types between the core and .net core, I don't see differences between them ?!

**Comment by JimBobSquarePants** [comment]
Here's the thing... System.Drawing is dead. Sure they're building a shim just now but it's gonna be poor performing, buggy, and will only serve large organisation temporarily who lack the ability to migrate large quantities of code. There's zero incentive for me to build implicit operators (btw they shouldn't be implicit) for obsolete technology. 

>I just revised the Size types between the core and .net core, I don't see differences between them ?!

You'll have missed the inlining instructions, hashcode generation code and operators between our primitives and vector types then.

If you had read the contribution guidelines as you were prompted to when raising this question you would have known that questions belong in our Gitter channel. It's. A much better place for questions where we can discuss such subjects in depth.

**Comment by fahadabdulaziz** [comment]
I think System.Drawing is not completely dead yet.

Thank you for your time, I'll just create my wrapper then.. 

I just read the contribution guidelines, and I just discovered Gitter!! 

Thanks
