### ISSUE TITLE
Is it possible to conert Image<Rgba32> to array of bytes?

### ISSUE THREAD

**Issue by ChristopherRobinSuperStar** [SixLabors/ImageSharp#321]
I think it is possible through base64, but is it possible by more simple way?
Thanks!

### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/JimBobSquarePants/ImageSharp/issuess) and [closed](https://github.com/JimBobSquarePants/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### System Configuration

- ImageSharp version:
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by dlemstra** [comment]
What do you want in the byte array?

**Comment by ChristopherRobinSuperStar** [comment]
I want to compress image to webp by this https://github.com/JosePineiro/WebP-wrapper
after ImageSharp Resizing.

**Comment by JimBobSquarePants** [comment]
I wouldn't bother with WebP it's a dead end. You'd be much better off using MozJpeg.

Quickest way would probably be the following though.

```
image.Pixels.NonPortableCast<Rgb32, byte>().ToArray()
```

**Comment by fahadabdulaziz** [comment]
Why not add a method to get bytes array directly, calling NonPortableCast requires referencing System.Memory which a little headache add references in many project just to convert image to bytes.

I used this workaround for to convert Image<> to byte[]
```csharp
MemoryStream memoryStream = new MemoryStream();
image.SaveAsPng(memoryStream);
```

**Comment by JimBobSquarePants** [comment]
@fahadabdulaziz Because that's an entirely different thing?!

You're saving the compressed image in png format to a stream. My sample is converting the raw pixels from `Span<Rgba32>` to `byte[]`.

**Comment by fahadabdulaziz** [comment]
My method is wrong because it will convert all images to PNG.
Using NonPortableCast requires referencing System.Memory in every project we use this method.
Adding method in the middle like GetBytes() will nor require System.Memory and will keep the format as is.

**Comment by JimBobSquarePants** [comment]
@fahadabdulaziz 

Can you please not spam our issue tracker. If you want a `GetBytes()` method please follow the instructions in the [Contribution Guidelines](https://github.com/SixLabors/ImageSharp/blob/68e6897c155a8668bb9da2a73670bc2d2df8e6f2/.github/CONTRIBUTING.md#do-you-intend-to-add-a-new-feature-or-change-an-existing-one) and start a conversation on Gitter. We can then move on to raising an issue and subsequent PR from there.

Thanks

**Comment by fahadabdulaziz** [comment]
@JimBobSquarePants I didn't spam your tracker I'm not the issue creator ?!

**Comment by JimBobSquarePants** [comment]
@fahadabdulaziz You interrupted an open issue with incorrect information and then requested a feature. It's considered poor etiquette to do so.  

And yes, the original issue should have been raised as a question on [Gitter](https://gitter.im/ImageSharp/General) (@ChristopherRobinSuperStar please take note of that in future)

I'm not trying to come across as harsh, it's just I (and the rest of the team) get several alerts on many devices every time a comment is made here. 

If our processes are followed we can keep on top of our workload and deliver the library to the public, If they are not then we waste time sifting through content to identify real issues and our library is delayed.

**Comment by ChristopherRobinSuperStar** [comment]
Oh, thank you! But why WebP it's a dead end?

**Comment by ChristopherRobinSuperStar** [comment]
Oh, thank you! But why WebP it's a dead end?

**Comment by JimBobSquarePants** [comment]
@ChristopherRobinSuperStar There's multiple issue with the format. They're described by a chap on Hacker News who is known as an authority on image compression. 

https://news.ycombinator.com/item?id=13021845
