### ISSUE TITLE
BMP with 8-bit pixel depth and RLE won't load

### ISSUE THREAD

**Issue by devedse** [SixLabors/ImageSharp#323]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Doing Image.Load() on the following file fails:

[TestImageBMP.zip](https://github.com/SixLabors/ImageSharp/files/1272446/TestImageBMP.zip)

### Steps to Reproduce

Do Image.Load on the included image.

### System Configuration

- ImageSharp version: 00191 and 00194
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version: .NET Core 1.1
- Additional information:

**Comment by dlemstra** [comment]
Your bitmap is compressed with RLE and we don't support that at the moment. That is why you got the NotSupportedException.

**Comment by georgexcollins** [comment]
I have added this, pull request will be coming. I'm not a Git user though so we'll see how that goes.

**Comment by JimBobSquarePants** [comment]
@georgexcollins Ace! My advice, use Github Desktop, takes the complexity away

**Comment by devedse** [comment]
Ah that's nice, I'll rerun my tests after to verify if this solves the problems I had for this image.
