### ISSUE TITLE
async await with ImageSharp

### ISSUE THREAD

**Issue by ChristopherRobinSuperStar** [SixLabors/ImageSharp#324]
Will there be async await support?
And second question: what is a the simplest way to convert Image<Rgba32> to System.Drawing.Bitmap?

### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### System Configuration

- ImageSharp version:
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by tocsoft** [comment]
@ChristopherRobinSuperStar please direct questions to https://gitter.im/ImageSharp/General the issue tracker is for issues only.
