### ISSUE TITLE
ImageSharp buffers take up too much memory space

### ISSUE THREAD

**Issue by HasanAyan** [SixLabors/ImageSharp#325]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I am only resizing and placing single rectangle to a PNG image (725kb). I checked my code and I dispose eveything related to ImageSharp after I am done. Still, I see (dotMemory) that ImageSharp use using a lot of memory

![dotMemory ss](https://i.imgur.com/7FGdlHB.png)

The first time I run my application, I get 5 of these objects and each time I run the application again it adds new one.

Not sure if there is a problem here or not but I would like to know if I am doing something wrong.

### System Configuration

- ImageSharp version: 1.0.0-alpha9-00194
- Other ImageSharp packages and versions: ImageSharp.Drawing 1.0.0-alpha9-00194
- Environment (Operating system, version and so on): windows 10 creators update
- .NET Framework version: .netcore 2.0
- Additional information:

**Comment by JimBobSquarePants** [comment]
Can you supply a code sample please so we can replicate?

**Comment by HasanAyan** [comment]
Sure. 

I need to correct something; it doesn't add a new buffer object each time. It creates 5 when I run it first, adds another one on the second run and it seems to preserve the count for the continuing runs (I tested 4 consequetive runs)

This is the first part of my code, where I basically change the size and try to minimize the size. In my test 
I run this for two different images (~720kb each)

```


public static byte[] OptimizeImage(MemoryStream rawImage)
        {

            rawImage.Position = 0;
            Image.Load(rawImage).To<Rgb24>().Resize(new ResizeOptions()
            {
                Mode = ResizeMode.Max,
                Size = new Size(750, 400),

            }).Save(rawImage, new PngEncoder()
            {
                CompressionLevel = 9,
                PngColorType = PngColorType.Rgb,
                IgnoreMetadata = true,
            }).Dispose();


            return rawImage.ToArray();
        }

```

The second part is where I use copy of one of the two images I optimized before and add a filled rectangle at some coordinates (between 1 and 4, but 90% of times only one rectangle). I call this function around 140 times.

I


```
public static byte[] CreateMinimap(byte[] minimap,  IEnumerable<Point3D> coordinates)
        {
          
            var image = Image.Load(minimap);

            var brush = Brushes.Solid(Rgba32.Red);
            coordinates.ForEach(x =>
            {
                var rectangle = new Rectangle(x.X - 5, x.Y - 5, 10, 10);
                image.Fill(brush, rectangle);
            });

            using (var stream = new MemoryStream())
            {
                image.SaveAsPng(stream, new PngEncoder()
                {
                    PngColorType = PngColorType.Rgb,
                    IgnoreMetadata = true,
                }).Dispose();

                return stream.ToArray();
            }

        }
```

**Comment by antonfirsov** [comment]
@hasanayan this is default `ArrayPool` behaviour. The pools are retaining the arrays for future reuse. This will actually result in more optimal memory usage and better performance. We had several discussions on the pros and contras regarding this topic (see #123 #151 #224). If this is really an issue for you, #225 should provide a solution.
