### ISSUE TITLE
Question: Why use SpanHelper.Copy instead of Slice and CopyTo on Span?

### ISSUE THREAD

**Issue by ahsonkhan** [SixLabors/ImageSharp#327]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I am curios to know, what is the reason for using `SpanHelper.Copy(Span<T> source, Span<T> destination, int count)` instead of `Span.Slice()` and `Span.CopyTo()`?
https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Memory/SpanHelper.cs#L37
https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/Span.cs#L272

For example, the following can be changed from:
https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/PixelFormats/RgbaVector.PixelOperations.cs#L25
```C#
 SpanHelper.Copy(sourceColors.NonPortableCast<RgbaVector, Vector4>(), destVectors, count);
```
To:
```C#
 sourceColors.NonPortableCast<RgbaVector, Vector4>().Slice(0, count).CopyTo(destVectors);
```

**Comment by antonfirsov** [comment]
@ahsonkhan the main reason is that the copy implementation of slow span [did not look optimized](https://github.com/AtsushiKan/corefx/blob/d551c71f9f79bb59a0c699968caf322945b443c5/src/System.Memory/src/System/Span.cs#L261) when we added it to the library. However, [it looks promising now](https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/SpanHelpers.cs#L62), so we may revise this, but it means we need to invest time into doing benchmarks.

One thing is sure: `Buffer.MemoryCopy()`, which drives our current copy implementation is really fast for large buffers.

**Comment by antonfirsov** [comment]
TBH - after having a second look - I think even the current (slow) `Span<T>.CopyTo()` implementation won't outperform `Buffer.MemoryCopy()`.

**Comment by ahsonkhan** [comment]
I see, that makes sense. Thanks!
I wanted to make sure it wasn't an API related workaround (i.e. a need for a Copy method that must take count).

**Regarding optimization/performance:**
The fast Span seems to be just as good since it too uses Buffer.MemoryCopy (well, Memmove, which MemoryCopy uses as well). https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Span.NonGeneric.cs#L150

Slow Span uses Unsafe.CopyBlock which I also see in the SpanHelper.Copy impl for NETSTANDARD1_1
And for slow span, only for structs containing reference types, like string (or if they overlap), is there a noticeable performance impact.

![image](https://user-images.githubusercontent.com/6527137/30505276-888b7480-9a28-11e7-832f-2f114bd34104.png)

![image](https://user-images.githubusercontent.com/6527137/30505294-9a3fe904-9a28-11e7-8696-27cb461b3315.png)

![image](https://user-images.githubusercontent.com/6527137/30505282-8d8b0982-9a28-11e7-8328-c4bc301f2db7.png)



cc @jkotas, @krzysztofcwalina

**Comment by antonfirsov** [comment]
@ahsonkhan great benchmarks! 👍 And thanks for taking the time for reviewing our stuff! 😄

I believe a cross platform library should be fast on old platforms as well, so I think we should not depend on Fast Span only perf features. This makes `SpanHelper.Copy` stay for a while, because it's still faster for small to mid sizes.

Re additional `count` argument: it's just an occasional result of our `PixelOperations` design, there's no need for that argument in a generic copy method.

**Comment by ahsonkhan** [comment]
> I believe a cross platform library should be fast on old platforms as well, so I think we should not depend on Fast Span only perf features.

The CopyTo API is just as fast for your scenarios for both slow and fast span (structs without reference types and primitive type spans).

How would you deal with overlapping spans?

**Regarding the use of Unsafe.CopyBlock:**
Unsafe.CopyBlock is a thin wrapper around cpblk IL instruction. The spec for cpblk IL instruction explicitly says “The behavior of cpblk is unspecified if the source and destination areas overlap.”
See: http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-335.pdf  Page 355.

**Comment by JimBobSquarePants** [comment]
@antonfirsov is this still relevant?

**Comment by JimBobSquarePants** [comment]
Closing since we now just use `Slice`.
