### ISSUE TITLE
Was it okay to delete old versions from MyGet?

### ISSUE THREAD

**Issue by AlexByte** [SixLabors/ImageSharp#332]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of ImageSharp
- [x]  I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

In projects using deleted versions, there are errors from switching to new versions.

**Comment by JimBobSquarePants** [comment]
Hi @AlexByte 

Please use Gitter for questions. The issue tracker is for issues only.

Cheers

James
