### ISSUE TITLE
StreamExtensions.Skip may skip less bytes than specified

### ISSUE THREAD

**Issue by AndreasTruetschel** [SixLabors/ImageSharp#338]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The method `static void Skip(this Stream stream, int count)` in the `StreamExtension` class may skip less bytes than specified by count if the following conditions met:
1. The specified stream can not seek
2. The number of bytes read by `stream.Read(foo, 0, count);` in line 36 reads less bytes than specified by `count` as documented [here](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.read?view=netstandard-1.3#System_IO_Stream_Read_System_Byte___System_Int32_System_Int32_)

The documentation states: 

> Returns
> Int32
> 
> The total number of bytes read into the buffer. **This can be less than the number of bytes requested if that many bytes are not currently available**, or zero (0) if the end of the stream has been reached.

I propose to introduce an extension method that reads the exact numbers of bytes specified, like I did in [my own project](https://github.com/AndreasTruetschel/AI4E/blob/master/src/AI4E.Modularity/StreamExtension.cs) and substitute the call on line 36 to `stream.Read(...)` with `stream.ReadExact(...)`.

**Comment by tocsoft** [comment]
the stream by that point can always be seeked. Thus in our current code path should always skip the correct amount.

but we should fix it incase we ever make changes that makes seeking not required.
