### ISSUE TITLE
Clone/Extract frames from image

### ISSUE THREAD

**Issue by tocsoft** [SixLabors/ImageSharp#340]
Provide 2 new public methods on `Image<TPixel>` called `CloneFrame` and `ExtractFrame`.

### Methods signature
`public Image<T> CloneFrame(int frameIndex);`
### Expected behavior
A new `Image<TPixel>` instance is created with a clone of the frame at index `frameIndex` as its `RootFrame`.
Throws `IndexOutOfRangeException` if `frameIndex` >= `ImageFrameCollection.Count` or `frameIndex` < `0`
The cloned `Image<TPixel>` should have the same metadata as the source image

### Methods signature
`public Image<T> ExtractFrame(int frameIndex);`
### Expected behavior
A new `Image<TPixel>` instance is created with the actual frame at index `frameIndex` as its `RootFrame`. _this is an instance move not a clone operation._
The frame from the source image will be removed from the source images `ImageFrameCollection`
Throws `IndexOutOfRangeException` if `frameIndex` >=` ImageFrameCollection.Count` or `frameIndex` < `0`
Throws `InvalidOperationException` if the user is trying to extract the last frame from the collection.
The cloned `Image<TPixel>` should have the same metadata as the source image.

**Comment by tocsoft** [comment]
_updated name ExportFrame -> CloneFrame_

**Comment by tocsoft** [comment]
this will enable scenarios where a user want to save and individual from from an animated gif

An example of the desired api would be 

```c#
for(var i = 0; i<sourceimage.Frames.Count; i++){
    using(var frameImage = sourceimage.CloneFrame(i) ){
        frameImage.Save("path.here");// we include all metadata from the original image;
    }
}
```
or if we don't mind a destructive operation where the source image will be left empty of all but one frame.
```c#
// skip last frame as it will throw removing the last frame
for(var i = 0; i<sourceimage.Frames.Count-1; i++){
    using(var frameImage = sourceimage.ExtractFrame(i) ){
        frameImage.Save("path.here");// we include all metadata from the original image;
    }
}
sourceimage.Save("lastFrame.path.here");
```


https://gitter.im/ImageSharp/General?at=59c0c18cc101bc4e3ae484be

**Comment by tocsoft** [comment]
@SixLabors/core 
should we instead of calling the clone method `CloneFrame` instead add on overload to our current clone APIs that accept a `frameIndex` to clone from?

👎  so instead of  : 
`image.Clone()` => returns clone of image and all frames
`image.CloneAs<TPixel2>()` => returns clone of image and all frames and converts pixel type
`image.CloneFrame(int frameIndex)` => returns clone of image and a single frame

👍  we should have 
`image.Clone()` => returns clone of image and all frames
`image.CloneAs<TPixel2>()` => returns clone of image and all frames and converts pixel type
`image.Clone(int frameIndex)` => returns clone of image and a single frame
`image.CloneAs<TPixel2>(int frameIndex)` => returns clone of image and a single frame and converts pixel type


if we're going with `Clone(...)` instead of `CloneFrame(...)` we should probably name the other method `Extract(...)`

**Comment by antonfirsov** [comment]
Like the API-s and the naming!

**Comment by devedse** [comment]
I personally wouldn't add the "ExtractFrame" method. I'd rather add a seperate function to remove frames in the image.Mutate(t => t.RemoveFrame(i)) or something.

**Comment by tocsoft** [comment]
To just remove a frame you can currently just call `image.Frames.RemoveAt(index)` 

The reason to have an extract call as well is to prevent unwanted pixel buffers being created.. basically calling extract should be significantly faster that clone frame because it doesn't need to create a second buffer and copy all the pixel data over to it.

**Comment by tocsoft** [comment]
now I think about it we could do with rethinking the whole API around imageframes. At the moment it's very easy to remove frames and it not be obvious that you need to dispose of them. we also have a second issue where it's difficult to mutate individual frames thus making it difficult to interact with them that way.

**Comment by devedse** [comment]
But why should "Extract" have the side effect to also remove it from the original then?

**Comment by tocsoft** [comment]
because that's what extract means? to extract something from something else is to pluck/take/remove it.

What I'm currently thinking is we rework the the api surface of `ImageFrameCollection` into this:

|Member|Return Type| Description|
|---|---|---|
|`CloneFrame(int index)`| `Image<TPixel>`|creates an image<t> with a copy of the pixel data from that frame on it|
|`RemoveFrame(int index)`| `Image<TPixel>`| creates an image<T> with only the indexed frame on it and removes that frame from the original image.|
|`DeleteFrame(int index)`|`void`| just removes the frame for the collection and disposes of the pixel data without returning anything|
|`AddFrame(ImageFrame<T> source)`  |`ImageFrame<T>`| clones the new frame and adds it the the collection. (returns ImageFrame)`
|`AddFrame(TPixel[] data)`  |`ImageFrame<T>`| creates a new frame from the raw pixel data and adds it the the collection.|
|`InsertFrame(ImageFrame<T> source, int index)`  |`ImageFrame<T>`| clones the new frame and adds it the the collection.|
|`this[int index] {get;}`  |`ImageFrame<T>`| get just returns frame at index|
|`MoveFrame(int sourceIndex, int destIndex)` |`void`| moves a frame from sourceindex so that after the operation it ends up at destIndex|
|`IndexOf(ImageFrame needle)`|`int`| find the index of a frame|
|`Contains(ImageFrame needle)`|'bool`| as it looks, does the frame existing in the collection|
|`Count {get;}` | `int`frame count|
|`RootFrame {get;}` | `ImageFrame<T>` |returns the frame at index `0` this is the frame used for pixel operations performed directly on `Image<t>`|

This ensures that `ImageFrame`s can never be disconnected from an `Image<T>` if you try and disconnect on then you will end up with a clone of the original image with only that frame on it, thus we can remove `IDisposable` from `ImageFrame`s and make it obvious that you should only be disposing on Image<T> and you can't easily corrupt an `Image<T>`s internal state

My reasoning for having this API on `ImageFrameCollection` instead of `Image<T>` is so that it hides away the frame based APIs into a property on the image for all those people who couldn't care less about frames and want to process the image as a simple single frames picture, they won't see any of this APIs cluttering up intellisense except the root Frames property itself.

**Comment by JimBobSquarePants** [comment]
I like this. @tocsoft . Only a few changes.

I would:

- Reverse the order of the parameters in a few operations e.g. `InsertFrame(int index, ImageFrame<T> source)` to put it more inline with things like `List<T>`. 
- Rename `RemoveFrame(int index)` to `ExportFrame(int index)`.
- Rename `DeleteFrame(int index)` to `RemoveFrame(int index)`
- Change the `AddFrame` variants and `InsertFrame` to be simply `void` without a return type.
- Add a `CreateFrame` method that creates and appends the frame to the end of the collection. We could control the entire lifecycle then. 

I don't think we should remove`IDisposable`. In fact, I think we should make `ImageFrameCollection` implement `IDisposable` since its lifecycle is so tightly coupled to that of the `ImageFrameCollection`.

**Comment by tocsoft** [comment]
The reason I think we want to remove IDisposable is to prevent users disposing of the frame or the collection without disposing of the image basically the lifetime of the pixel data withing the frames should be controlled by the lifetime of the image not when someone sees `Dispose()` on the collection and tries to Dispose of it early.

**Comment by JimBobSquarePants** [comment]
True that, good point.
