### ISSUE TITLE
Converting Png to Jpg give a color background and not white (Asp.Net Core)

### ISSUE THREAD

**Issue by FelixLeChat** [SixLabors/ImageSharp#355]
### Description
My goal is to generate renditions (thumbnail, and other size of the image) from an uploaded image (IFormFile, png or jpg).

When uploading a .png with transparency, the resulting image has a background of a color in the image and not a default white one. 

### Steps to Reproduce
```
        public static Stream GenerateCompressedOriginal(IFormFile file)
        {
            Stream outputStream = new MemoryStream();

            using (Image<Rgba32> image = Image.Load(file.OpenReadStream()))
            {
                image.SaveAsJpeg(outputStream, new JpegEncoder() { Quality = 80 });
            }

            return outputStream;
        }
```
From :
![2553905512_listing_logo](https://user-images.githubusercontent.com/8709465/31017762-a7ddefdc-a4f7-11e7-9a18-20aed2765bca.png)

To :
![2553905512_preview](https://user-images.githubusercontent.com/8709465/31017773-b1b7670e-a4f7-11e7-9979-ae30b5e3b569.jpg)

if i save the outputstream as a jpg. the error occur. The image variable has also this background in color and not white. 

### System Configuration

- ImageSharp version: 1.0.0-alpha9-00194
- Environment (Operating system, version and so on): windows 10
- .NET Framework version: .Net Standard 1.6

**Comment by JimBobSquarePants** [comment]
Hi @FelixLeChat ,

The transparent sections of the image are not actually fully transparent, rather only the alpha component of the pixels is set to zero.

You'll need to manually set the background color.

``` csharp
    public static Stream GenerateCompressedOriginal(IFormFile file)
        {
            Stream outputStream = new MemoryStream();

            using (Image<Rgba32> image = Image.Load(file.OpenReadStream()))
            {
                image.Mutate(x => x.BackgroundColor(Rgba32.White));
                image.SaveAsJpeg(outputStream, new JpegEncoder() { Quality = 80 });
            }

            return outputStream;
        }
```

Cheers

James

**Comment by tocsoft** [comment]
I feel we should be doing this by default when encoding into formats that don't support alpha channels.

I think we should add a `NormalizeBackground` property onto `JpegEncoder`  that, if enabled (defaulted to `true`), will do the background color fixes as it encodes each pixel.

**Comment by JimBobSquarePants** [comment]
I disagree. The encoding overheads in my opinion are too high and it's technically incorrect. 
Adding the method to the consumers pipeline code is trivial. Consumers should know what they are operating on.
