### ISSUE TITLE
PNG decoder allocates a lot of memory on corrupted chunk

### ISSUE THREAD

**Issue by xakep139** [SixLabors/ImageSharp#358]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I try to load PNG image that displays normally and loads normally with .NET Framework's `System.Drawing.Image.FromFile()`. But it allocates approximately 1.4 Gb and it takes 4-5 seconds with ImageSharp.
One of chunks is corrupted and has length 1.474.938.428, but image size is 9.195 bytes.
Maybe it's better to skip memory allocation if some chunk has incorrect length (more than image size minus current stream position).

### Steps to Reproduce

Simple code:
```
using (Image.Load("big-corrupted-chunk.png")) { }
```
with image [big-corrupted-chunk.zip](https://github.com/SixLabors/ImageSharp/files/1358721/big-corrupted-chunk.zip)

### System Configuration

- ImageSharp version: 1.0.0-beta0001
- Environment (Operating system, version and so on): Windows 10 Enterprise Version 1703 Build 15063.540
- Visual Studio Professional 2017 Version 15.3.5
- `dotnet --info` output:
```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by JimBobSquarePants** [comment]
@xakep139 Thanks for raising this with hall the info.  👍 

You were pretty close with the fix. We just had to handle negative numbers also and reverse the stream so we can handle corruption in between chunks anywhere in the image.

**Comment by xakep139** [comment]
@JimBobSquarePants thanks for this quick fix!

**Comment by JimBobSquarePants** [comment]
@xakep139 No worries 😄
