### ISSUE TITLE
Question: Any plans HEIC support?

### ISSUE THREAD

**Issue by cecilphillip** [SixLabors/ImageSharp#371]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Are there any plans to support HEIF/HEIC file formats? I was looking into creating a quick converter

**Comment by tocsoft** [comment]
We don't currently have any plans but if someone was to send in a pull request we probably wouldn't turn it down.

**Comment by tocsoft** [comment]
Actually, after having done some research on this format, I doubt we would ever add support for this to the core ImageSharp product. 

The reason being is that the codec that HEIC uses (HEVC) is covered by patents that would require licensing thus we probably wouldn't be able to ship this as a core software component. Me might be able to be work something out to be able to provided as an add-on package but that would depend on how the licencing for the codec would work out.

**Comment by cecilphillip** [comment]
Thanks for the response.

**Comment by flemingm** [comment]
ON iOS and macOS HEIC reading is supported natively and some version of Windows 10 (not all version) have support.

https://developer.apple.com/documentation/avfoundation/avfiletype/2873439-heif

Also :
https://github.com/nokiatech/heif (requires license for commercial use)

HEIF is a media container format. It is not an image or video encoder per se. Hence, the quality of the visual media depends highly on the proper usage of visual media encoder (e.g. HEVC). Current standard allows containing HEVC/AVC/JPEG encoded bitstreams.

**Comment by jonasnordlund** [comment]
HEIC support already ought to be available from the Windows Imaging Component (WIC) framework and in .NET via the `Windows.Graphics.Imaging` namespace in case Microsoft's HEIF Image Extensions is installed. I'm not sure if ImageSharp supports automatically gathering encoding and decoding support from this API but I think it would be pretty nice and sensible if it did. This would both allow ImageSharp to stay clear of licensing issues as well as not having to implement several modern formats. The next-generation AV1 is also already supported in Windows 10 this way.

**Comment by JimBobSquarePants** [comment]
That’s too Windows centric a solution.

**Comment by rickbrew** [comment]
Implementing HEIC in managed code on your own will be quite the uphill battle.

Paint.NET relies on the built-in Windows 10 codec for reading, and a $1 codec you have to buy from the Store. I can't provide writing for free because it requires royalty payments.

There is a plugin for the app, HeicFileTypePlus by @0xC0000054 (aka null54), https://github.com/0xC0000054/pdn-heicfiletype-plus, that provides read/write for free but it uses native libs w/ GPL licensing. The plugin is Windows-centric because the app is Windows-only, but it could probably be adapted into something that works with ImageSharp.

**Comment by JimBobSquarePants** [comment]
Yeah. I can't honestly see us implementing this now, especially with AVIF available.

**Comment by onyxmaster** [comment]
Not that I'm a big fan of Apple "pick some quite obscure tech and force it upon users" tech radar, but not supporting the primary image format for one of two mobile platforms in existence looks strange. I really wanted to use ImageSharp instead of ImageMagick wrapper, but, well, not this time.

**Comment by JimBobSquarePants** [comment]
Write it then.

**Comment by 0xC0000054** [comment]
In addition to the Paint.NET plugin I also wrote a .NET Standard wrapper for [libheif](https://github.com/strukturag/libheif) (a cross-platform native library that implements HEIF/AVIF image support).
The decoder and encoder sample projects in the [libheif-sharp-samples](https://github.com/0xC0000054/libheif-sharp-samples) use ImageSharp for loading and saving images.

**Comment by JimBobSquarePants** [comment]
Love it @0xC0000054 Thanks!
