### ISSUE TITLE
Remove stylecop.json from SixLabors.ImageSharp.Drawing NuGet package 

### ISSUE THREAD

**Issue by johannesegger** [SixLabors/ImageSharp#374]
I guess you mistakenly added it anyway. The core package SixLabors.ImageSharp doesn't have it.

![image](https://user-images.githubusercontent.com/237707/31908695-0178a78c-b838-11e7-87b4-b2dad25a21c0.png)

**Comment by JimBobSquarePants** [comment]
Thanks, @johannesegger, appreciate it!

We'll get that updated. In the future can you please raise issues using the issue template we provide. It just makes things a little easier for us to keep track of. 

Cheers

James
