### ISSUE TITLE
Wrapped text should not include space at start of new line

### ISSUE THREAD

**Issue by CDDelta** [SixLabors/ImageSharp#375]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When wrapping text with spaces to a new line DrawText() starts the next line with a space.

### Steps to Reproduce
1. Draw text (eg. "TEST TEST TEST TEST") that includes spaces and enable wrapping.
2. Output and view it.

Here is an example I made.
![output_512x512](https://user-images.githubusercontent.com/14818946/32054458-2aba9c08-baaa-11e7-8c15-2c89420aefa7.jpeg)

### System Configuration
- ImageSharp version:
- Other ImageSharp packages and versions: SixLabors.ImageSharp.Drawing 1.0.0-beta0001
- Environment (Operating system, version and so on):
- .NET Framework version: .NET Core 2.0
- Additional information:

**Comment by tocsoft** [comment]
moved to SixLabors/Fonts#47 as this is a bug/issue with the layout engine built into SixLabors.Fonts

**Comment by tocsoft** [comment]
thanks for reporting this, I've 'moved' this over to the other repository as its specifically an issue in that component.

**Comment by CDDelta** [comment]
Thanks for the swift reply!

**Comment by naveedahmed1** [comment]
@tocsoft can you please guide where can I find documentation of this plugin. I want to add some text on an image, but couldn't find any documentation or tutorial.

**Comment by tocsoft** [comment]
@naveedahmed1 as linked from our readme our [samples repository](https://github.com/SixLabors/Samples/tree/master/ImageSharp) has 2 different examples of drawing text on images. The [Draw watermark on image](https://github.com/SixLabors/Samples/blob/master/ImageSharp/DrawWaterMarkOnImage/Program.cs) and [Draw text along a path](https://github.com/SixLabors/Samples/blob/master/ImageSharp/DrawingTextAlongAPath/Program.css) both do this.

**Comment by naveedahmed1** [comment]
Thank you so much @tocsoft :)

**Comment by naveedahmed1** [comment]
I am using the latest version but its not recognizing `SixLabors.Fonts`

**Comment by tocsoft** [comment]
@naveedahmed1 make sure you have a dependency on `SixLabors.ImageSharp.Drawing` this is the package that enables drawing onto images.

**Comment by naveedahmed1** [comment]
@tocsoft can you please guide whats wrong with below code:

```

public async Task<FileResult> Test()
        {
            using (var img = Image.Load("fb.jpg"))
            {
                using (System.IO.Stream outputImageStream = new MemoryStream())
                {
                    Font font = SystemFonts.CreateFont("Arial", 10); // for scaling water mark size is largly ignored.

                    string text = "Hello world!";
                    float padding = 5;

                    img.Mutate(ctx => ctx.Apply(image =>
                     {
                         float targetWidth = image.Width - (padding * 2);
                         float targetHeight = image.Height - (padding * 2);

                         // measure the text size
                         SizeF size = TextMeasurer.Measure(text, new RendererOptions(font));

                         //find out how much we need to scale the text to fill the space (up or down)
                         float scalingFactor = Math.Min(image.Width / size.Width, image.Height / size.Height);

                         //create a new font 
                         Font scaledFont = new Font(font, scalingFactor * font.Size);

                         var center = new PointF(image.Width / 2, image.Height / 2);

                         image.Mutate(i => i.DrawText(text, scaledFont, Rgba32.HotPink, center, new TextGraphicsOptions(true)
                         {
                             HorizontalAlignment = HorizontalAlignment.Center,
                             VerticalAlignment = VerticalAlignment.Center
                         }));


                         JpegEncoder encoder = new JpegEncoder()
                         {
                             Quality = 100
                         };

                         img.SaveAsJpeg(outputImageStream, encoder);

                     }));

                    outputImageStream.Position = 0;
                    return new FileStreamResult(outputImageStream, "image/png");
                }

            }
        }
```

I am receiving below error:

```
An unhandled exception occurred while processing the request.

ObjectDisposedException: Cannot access a closed Stream.
System.IO.__Error.StreamIsClosed()
```

**Comment by dlemstra** [comment]
You should not `Dispose` the `outputImageStream` passed to the `FileStreamResult` object. That class becomes the owner and will release it themselves.

**Comment by naveedahmed1** [comment]
Thank you so much @dlemstra it was really helpful :)
