### ISSUE TITLE
Incorrect nuget dependencies for SixLabors.ImageSharp.Web package

### ISSUE THREAD

**Issue by sla1k** [SixLabors/ImageSharp#378]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
In dependencies for SixLabors.ImageSharp.Web nuget package you have conditions for Microsoft.AspNetCore.* packages with more than 1.1.2 version, but after installing we have Microsoft.AspNetCore.* packages with version 2.0.0 and they are not incompatible with 1.1.2 version.

Example:
ctor of EntityTagHeaderValue does't have argument like string (public EntityTagHeaderValue(StringSegment tag))
`
System.MissingMethodException: Method not found: 'Void Microsoft.Net.Http.Headers.EntityTagHeaderValue..ctor(System.String)'.
   at SixLabors.ImageSharp.Web.Middleware.ImageContext.ComputeLastModified()
   at SixLabors.ImageSharp.Web.Middleware.ImageContext.ComprehendRequestHeaders(DateTimeOffset lastModified, Int64 length)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.<SendResponse>d__10.MoveNext()
`
### Steps to Reproduce
Install SixLabors.ImageSharp.Web  for asp core 2.0 app
Try get an image

### System Configuration

- ImageSharp version:
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by tocsoft** [comment]
this should have been posted at 
https://github.com/SixLabors/ImageSharp.Web/issues as ImageSharp.Web has its own repositroy.

FYI we have already fixed this in source and will be resolved when we push out a beta2.
