### ISSUE TITLE
Failing installation of SixLabors.ImageSharp in NuGet VS 15.4.2

### ISSUE THREAD

**Issue by krystyna93** [SixLabors/ImageSharp#380]
I have been having issues with the installation of this package.
I have updated to Visual Studio 15.4.2, but I am still getting the same error below in the error list as well as in my previous version of VS 15.4.0. I have also uninstalled and reinstalled numerous time, but to no avail.

Error		Package restore failed. Rolling back package changes for 'myprojectname'.

I am also receiving the following error in my output:

Restoring packages for C:\Users\Me\Source\Repos\project\src\project\project.csproj...
Package SixLabors.ImageSharp 1.0.0-beta0001 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package SixLabors.ImageSharp 1.0.0-beta0001 supports:
  - netstandard1.1 (.NETStandard,Version=v1.1)
  - netstandard1.3 (.NETStandard,Version=v1.3)
Package restore failed. Rolling back package changes for 'project'.
Time Elapsed: 00:00:01.1947210
========== Finished ==========

I dont know what could be the issue, am I missing some library for it?
Can someone please enlighten me, I cant seem to find a solution to this issue, which has been bugging me all day

Cheers

**Comment by JimBobSquarePants** [comment]
Hi @krystyna93 The error message is telling exactly what the problem is.

You are trying to install the library into an unsupported environment (NETCore 2.0)

You need to target a .NETStandard target.

See the chart here

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

Cheers

James
