### ISSUE TITLE
Make ColorSpaces and conversion public

### ISSUE THREAD

**Issue by irium** [SixLabors/ImageSharp#381]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Currently all members of `SixLabors.ImageSharp.ColorSpaces` namespace are internal and there is no way to use it.

**Comment by JimBobSquarePants** [comment]
Hi @irium 

They're internal at the moment for precisely that reason. We want to do some API and optimization work first to ensure that what we release is both usable and performant. As soon as we're happy we'll make the namespace public.

Cheers

James

**Comment by JimBobSquarePants** [comment]
Forgot to close this. They're all public now in the nightlies.
