### ISSUE TITLE
Behavior of DrawText unclear

### ISSUE THREAD

**Issue by kentcb** [SixLabors/ImageSharp#389]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I'm trying to figure out the exact logic to render some text vertically centered with respect to a horizontal line, like this:

![image](https://user-images.githubusercontent.com/1901832/33473037-b68f4db0-d6c4-11e7-9bfc-d8853e6a76f6.png)

My thinking was that this code should work:
```C#
using (var image = new Image<Rgba32>(400, 100))
{
    image.Mutate(
        context =>
        {
            context.Fill(Rgba32.Black);

            var text = "Greetings, world!";
            var font = SystemFonts.CreateFont("Arial", 26);
            var rendererOptions = new RendererOptions(font);
            var textSize = TextMeasurer.Measure(text, rendererOptions);

            context.DrawLines(
                Rgba32.White,
                1,
                new[]
                {
                    new PointF(0, 20),
                    new Point(100, 20)
                });
            context.DrawText(
                text,
                font,
                Rgba32.White,
                new PointF(20, 20),
                new TextGraphicsOptions(true)
                {
                    VerticalAlignment = VerticalAlignment.Center
                });

    image.Save("Test.png");
}
```

However, it produces this result:

![image](https://user-images.githubusercontent.com/1901832/33473103-071d687a-d6c5-11e7-8b17-a93ac8446c2b.png)

In an effort to understand this, I tried this code:
```C#
using (var image = new Image<Rgba32>(400, 100))
{
    image.Mutate(
        context =>
        {
            context.Fill(Rgba32.Black);

            var text = "Greetings, world!";
            var font = SystemFonts.CreateFont("Arial", 26);
            var rendererOptions = new RendererOptions(font);
            var textSize = TextMeasurer.Measure(text, rendererOptions);

            context.DrawText(
                text,
                font,
                Rgba32.White,
                new PointF(20, 20));
            context.Draw(
                Rgba32.Red,
                1,
                new RectangleF(
                    new PointF(20, 20),
                    textSize));
        });

    image.Save("Test.png");
}
```
Which looks like this:
![image](https://user-images.githubusercontent.com/1901832/33473183-505e59ae-d6c5-11e7-982a-e29aa8d73ca5.png)

It looks to me like the measurement might have too much height and the `DrawText` method is rendering the text too low (perhaps using the bottom of the bounds to dictate the baseline?)

I guess I'm just confused about how the text rendering works and how I can accurately position my text per my original example.

### Steps to Reproduce

See code above.

### System Configuration

- ImageSharp version: `1.0.0-beta0002`
- Other ImageSharp packages and versions: `SixLabors.ImageSharp.Drawing 1.0.0-beta0002`
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: .NET Core2.1.1-preview-007118
- Additional information: I love this project! 🎉

**Comment by JimBobSquarePants** [comment]
I believe this is related to #470 and as such should be fixed in beta4. @kentcb would you be able to confirm?

**Comment by jtorjo** [comment]
Note that I've ran into this issue myself. My workaround was to create a Windows font of the same size, and measure with it :D 
@JimBobSquarePants I'm photawe on twitter :) - we've implemented writing text on top of photos, and it's pretty accurate. 
Glad to know this is fixed, will certainly give it a whirl ;)
