### ISSUE TITLE
GIF Artifacts

### ISSUE THREAD

**Issue by TodesBrot** [SixLabors/ImageSharp#390]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
This specific GIF:
![kumin](https://user-images.githubusercontent.com/8228822/33489514-58e607ae-d6b4-11e7-93eb-e16713585e8b.gif)

shows artifacts when loaded using ImageSharp. When loading the GIF using ImageSharp and saving it again, the resulting file looks like this:
![test](https://user-images.githubusercontent.com/8228822/33489449-384e8b92-d6b4-11e7-9422-5710868798b0.gif)

### Steps to Reproduce
Load the GIF with ImageSharp.

### System Configuration

- ImageSharp version: beta 2
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: 4.5.2
- Additional information:

**Comment by TodesBrot** [comment]
I just noticed the second GIF file also appears to be faster than the first one.

**Comment by JimBobSquarePants** [comment]
@TodesBrot I can't replicate this in the current master. Here's the output from there.

![giphy](https://user-images.githubusercontent.com/385879/33550063-b61fbcba-d940-11e7-8a2f-38c7a2909087.gif)

**Comment by TodesBrot** [comment]
@JimBobSquarePants I have noticed some weird behavior. When I create a new project and load the image, it loads just fine, but in my old project it has the buggy output. However, if I move the line that loads and saves the file to the beginning of the project, it works fine. It seems like something in my project changes something somewhere that causes the bug to occur. I'll have to do some more investigating.

**Comment by JimBobSquarePants** [comment]
Thanks, let us know how you get on.

**Comment by TodesBrot** [comment]
@JimBobSquarePants Okay, now this is a weird one. Loading this specific image:
![icon](https://user-images.githubusercontent.com/8228822/33552173-410fe630-d8f4-11e7-8b12-f4f195fc8e3d.png)
and saving it again before loading the GIF leads to the corruption shown above. Additionally, loading it and not saving it beforehand leads to a different corruption.

Code example: (The GIF is called "Kumin.gif" here, and the image above is called "Icon.png")
```
Image.Load("Kumin.gif").Save("Kumin ImageSharp 1.gif");

Image<Rgba32> icon = Image.Load("Icon.png");

Image.Load("Kumin.gif").Save("Kumin ImageSharp 2.gif");

icon.SaveAsPng(new MemoryStream());

Image.Load("Kumin.gif").Save("Kumin ImageSharp 3.gif");
```
Kumin ImageSharp 1.gif looks just fine:
![kumin imagesharp 1](https://user-images.githubusercontent.com/8228822/33552354-f3535480-d8f4-11e7-97d9-0b9674b56a19.gif)
Kumin ImageSharp 2.gif has purple corruptions:
![kumin imagesharp 2](https://user-images.githubusercontent.com/8228822/33552385-024687d2-d8f5-11e7-8146-899c45a378d2.gif)
Kumin ImageSharp 3.gif has the blue corruptions from my first post:
![kumin imagesharp 3](https://user-images.githubusercontent.com/8228822/33552400-0df9f9b0-d8f5-11e7-9e41-f8071580db6b.gif)

Note: The GIF file has to be loaded again each time, as the corruptions occur during the decoding, not the encoding.

**Comment by TodesBrot** [comment]
It seems like loading and saving any 256x256 image causes this bug. I created one with only blue and green stripes in it, and it caused blue and green stripes to appear.

**Comment by JimBobSquarePants** [comment]
I think this might be an array pooling thing as the LZW decoder doesn't use clean arrays to read from.

Would you be able to alter the code locally in [GifDecoderCore](https://github.com/SixLabors/ImageSharp/blob/7bd6225366b586007954a81b092f20a7527e14e5/src/ImageSharp/Formats/Gif/GifDecoderCore.cs#L324) to clear the array before decoding? Also the global color table?

**Comment by antonfirsov** [comment]
@JimBobSquarePants I had the same idea

**Comment by JimBobSquarePants** [comment]
@TodesBrot I've actually just pushed a [branch](https://github.com/SixLabors/ImageSharp/compare/js/fix-390) that should fix this for you, could you please dl, build it and test against it?

**Comment by JimBobSquarePants** [comment]
@TodesBrot Version has gone out of whack for our CI server so SixLabors.ImageSharp.1.0.0-ci0030 will contain the fix.
