### ISSUE TITLE
Ambiguous ImageExtensions reference

### ISSUE THREAD

**Issue by Spawnkid** [SixLabors/ImageSharp#391]
### Prerequisites

- [x ] I have written a descriptive issue title
- [x ] I have verified that I am running the latest version of ImageSharp
- [x ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
![2017-12-05 2](https://user-images.githubusercontent.com/28699801/33589384-1ed463ec-d9b3-11e7-938c-5cf41d2bcc2e.png)

### Steps to Reproduce
Add SixLabors.ImageSharp and SixLabors.ImageSharp.Drawing

### System Configuration
VS 2017
.Net Standard 2.0
WPF
W10 Enterprise

- ImageSharp version:
1.0.0-beta0002 for both SixLabors.ImageSharp and SixLabors.ImageSharp.Drawing 
0.16.4-beta ZXing.Net.Bindings.ImageSharp

**Comment by JimBobSquarePants** [comment]
Hi @Spawnkid 

We probably should reorganize the namespaces for the two libraries but I'm a little confused by the approach you're taking.

Extension methods (hence the namespace) are most commonly used as extensions to method instance and are not called via static invocation.

e.g. 

``` c#
img.SaveAsPng(stream)
```
You'll get no ambiguity doing it properly like that.

Hope that makes sense.

Cheers

James

**Comment by Spawnkid** [comment]
Hi, Thanks for the suggestion.

It's because I need to save the Rgba64 from ZXing.ImageSharp.BarcodeWriter to a stream that I passed. Here is the method:
`   private static void ApplyBarcode(Stream img, BarcodeFormat barcodeFormat, string value, int width, int height)
        {
            var bcWriter = new ZXing.ImageSharp.BarcodeWriter<SixLabors.ImageSharp.PixelFormats.Rgba64>
            {
                Format = barcodeFormat,
                Options = new EncodingOptions { Height = height, Width = width, PureBarcode = true }
            };

            SixLabors.ImageSharp.ImageExtensions.SaveAsPng(bcWriter.Write(value), img).Dispose();
        }`
 So what this extension does (in my app) is to save the barcodewriter output to a stream and eventually will be loaded back to the caller for further post processing.

**Comment by Spawnkid** [comment]
Nevermind, I think I found an solution.

`   bcWriter.WriteAsImageSharp<SixLabors.ImageSharp.PixelFormats.Rgba64>(value).SaveAsPng(img);`

Thanks!

**Comment by JimBobSquarePants** [comment]
Glad you found an answer.  I think perhaps you should have raised this on the issue tracker for ZXing.

Anyway...  In regards to your question.

`bcWriter.Write(value)` is of type `Image<Rgba64>` yeah?

If so.... Why not?

``` c#
Image<Rgba64> output = bcWriter.Write(value);
output.SaveAsPng(img); // btw img is not a good parameter name for a stream.
output.Dispose();
```

Btw, there's no reason to use `Rgba64` as your pixel format type. The png encoder will convert that to `Rgba32`.

**Comment by Spawnkid** [comment]
bcWriter.Write(value) is of type Image<Rgba64> yeah? -> Yes. I also changed the param name (Thank you for the free code review 👍  )

Anyway, I will let ZXing know about the issue. Thank You for your help and very quick response Jim!

**Comment by JimBobSquarePants** [comment]
Happy to help, any other issues please let me know 😄
