### ISSUE TITLE
ImageFormatException: 'Bad Th value' on jpeg image

### ISSUE THREAD

**Issue by J0nKn1ght** [SixLabors/ImageSharp#394]
Hi,

I have a problem loading a specific jpeg image using ImageSharp.  The code is in an ASP.Net MVC Core application, and is loading the image data from an IFormFile stream.
The image is available at the following url:

[http://www.edenamps.com/images/eden_terra_nova_10-crop-u182927.jpg](http://www.edenamps.com/images/eden_terra_nova_10-crop-u182927.jpg)

Are you able to see if there's any way to get this to work?
We're loading the image to get the dimensions, and then creating a thumbnail from it.  If we load, then resave the image in Paint.Net, it works fine, but we'd like to know if there is a way to process the original image, in case we find more with the same encoding issue.

Thanks,

Jon

- ImageSharp version:  v1.0.0-beta0002
- Environment:  Windows 10 Pro (running under IISExpress)
- .NET Framework version: .Net Core v2.0.3

**Comment by dlemstra** [comment]
Could you add a small code sample so we can easily reproduce your issue?

**Comment by J0nKn1ght** [comment]
Sure. Just download the file in my original post locally, and then pass the path to the following .Net Core 2 console app:

```csharp
using SixLabors.ImageSharp;
using System;

namespace ImageSharpTest
{
    class Program
    {
        static void Main(string[] args)
        {
            string filename = args[0];
            try
            {
                using (var image = Image.Load(filename))
                {
                    Console.WriteLine($"Image is {image.Width} wide by {image.Height} high");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Exception: {ex.Message}");
            }
        }
    }
}
```

**Comment by JimBobSquarePants** [comment]
I know what's causing this and it's an easy fix.

We're incorrectly limiting the possible huffman table count to 2 for non-progressive jpegs. It's actually ok to have up to 4 dc and 4 ac tables.

https://github.com/SixLabors/ImageSharp/blob/f49bd9bec547dbdb4ab5fd581a47f8cd428683c0/src/ImageSharp/Formats/Jpeg/GolangPort/OrigJpegDecoderCore.cs#L691

Deleting the conditional after the logical OR operator on this line will fix it. I would do it now but it's already 1:37am here.
