### ISSUE TITLE
Artifacts after resizing

### ISSUE THREAD

**Issue by 777olexandr** [SixLabors/ImageSharp#396]
### Description
Image resizing works worse than when done with imagemagick php library and generally cannot be moved to production with that quality. 

### Steps to Reproduce
I'v used three mods: pad, boxpad and max. Passed only width so to save original aspect ration.

See links of original and resized images:

Original: https://ibb.co/npKCFG
Resized to 350px: https://ibb.co/doeCFG

### System Configuration
Using asp.net core 2.0 with .net core 2.0 on Windows in Debug mode(will be published later on Linux). ImageSharp version - v1.0.0-beta0002.

I hope this issue can be fixed within few months? Thanks.

**Comment by JimBobSquarePants** [comment]
Hey @777olexandr 

There's nothing wrong with our resampling algorithms, what your are seeing is the result of the default jpeg encoding quality options. If you change them, then the artifacts will go away.

We've chosen those options as default as they work well for photos (which is what jpeg is designed for) you'd be much better off saving an image with crisp lines like that as a 24 bit png, it's likely to be a smaller file also. 

Hope that makes sense.

Cheers

James

**Comment by 777olexandr** [comment]
@JimBobSquarePants I'm grateful for your fast reply. Could you please clarify what code should I use? Currently I have such method:

`public Stream Get()
        {
            Stream stream = new MemoryStream();
            IImageEncoder encoder = null;
            
            switch (_extension)
            {
                case ImageExtension.JPEG:
                    encoder = new SixLabors.ImageSharp.Formats.Jpeg.JpegEncoder();
                    break;
                case ImageExtension.PNG:
                    encoder = new SixLabors.ImageSharp.Formats.Png.PngEncoder();
                    break;
                case ImageExtension.GIF:
                    encoder = new SixLabors.ImageSharp.Formats.Gif.GifEncoder();
                    break;
            }
            
            _object.Save(stream, encoder);

            return stream;
        }`

That saves into stream with choosing correct encoder based on extension enum. Maybe it's redundant and library can take from image header, but that way I feel more safer. So here is no quality argument in Save method. Only JpegEncoder has quality property or method(don't remember), but with interface I can't use that. How would you rewrite this code so it keeps general in creating encoder through interface type and applies quality on jpeg format?

Also I have another issue which I can't solve - when creating second instance with same stream through Image.Load it returns null. I'v checked and stream and decoder both are set.

**Comment by 777olexandr** [comment]
Tried another code and the same - the Load method returns null when passing same stream second time =( Maybe I do something wrong, I'm newbie in c# but cloning the stream didn't help.

**Comment by JimBobSquarePants** [comment]
@777olexandr 

No worries, happy to help. 😄 

I would never rely on the image extension over the file headers to determine the format. The header will return the correct value and it's all too easy for someone to save a file with the wrong extension.

Here's a bulletproof way if saving the files with the correct format.

``` c#
// Create a new config based on the default.
var config = Configuration.CreateDefaultInstance();
JpegEncoder jpegFormat = config.ImageEncoders.Where(e => e.Value is JpegEncoder)
                                .Select(x => x.Value)
                                .Cast<JpegEncoder>()
                                .First();

// Alter the jpeg encoder values
jpegFormat.Subsample = JpegSubsample.Ratio444; // This is automatically set if the quality is over 90
jpegFormat.Quality = 90; // This should be a good value.


using (var instream = // Your input stream)
using (var outStream = // I'm assuming a FileStream))
using (var image = Image.Load(config, instream, out IImageFormat format))
{
    // Edit the image

    image.Save(outStream, format);
}
``` 

Regarding your second issue I imagine it is because you haven't reset the input stream to the original  position. (normally `0`) you need to do that as we cannot assume developers actually want us to.

Does all this make sense?

**Comment by 777olexandr** [comment]
This line

var config = Configuration.CreateDefaultInstance();

Creates an error "..does not contain a defination for CreateDefaultInstance". It finds the Configuration class but no such method. 

Also in my code the Load method is used in constructor and Save in a method "Get" because I'v wrapped it in a class that has multiple methods with chain like functionality. So the Get method is last point where caller can get the resulting Stream. Probably there is a bad thing about releasing resources but I'v found your method "Dispose" and will put it in Get method, is this ok? How do I get format out of Load method? Or this is impossible and then I'll just add private field with it to my class.

**Comment by 777olexandr** [comment]
Figured out with format and now my method became 3x time slimmer by removing the switch. Nice! But still can't solve config problem. And is it possible to set up quality in Save method?

**Comment by JimBobSquarePants** [comment]
@777olexandr Sorry, I forgot that method was internal, I've updated the sample for you and that should now work. 

Doing it on save won't work unless you used a switch again which is what we want to avoid.

**Comment by tocsoft** [comment]
@777olexandr 
The easiest way to configure the default encoder options  is to do it like this:
https://github.com/SixLabors/Samples/blob/d8959156c24b671be13cd345ac50d3dbe967dd7d/ImageSharp/ChangeDefaultEncoderOptions/Program.cs#L14-L20

That way you shouldn't need to fight with creating a custom configuration and will be the version thats automatically used when using the named formats.

@JimBobSquarePants we shouldn't be encouraging users to have to cast encoders from config and instead be telling them to replace the encoder with one configured to their liking, that's exactly what the  `SetEncoder` api is for.

**Comment by JimBobSquarePants** [comment]
@tocsoft I completely forgot about that API! 

Yeah, that's definitely the best way to go.

**Comment by 777olexandr** [comment]
Excellent! Thank you guys!
