### ISSUE TITLE
Remove EXIF from image

### ISSUE THREAD

**Issue by mgrishkov** [SixLabors/ImageSharp#400]
Dear team, can you please describe how can I remove EXIF information from image or rotate it based on EXIF data?

**Comment by JimBobSquarePants** [comment]
Hi @mgrishkov 

Normally we use this issue tracker for issues (bugs) only and our [Gitter](https://gitter.im/ImageSharp/General) chatroom for questions but I'll answer here for brevity.

If you want to auto rotate an image based on its EXIF metadata you can use the `AutoOrient` method

e.g. 

``` c#
image.Mutate( x => x.AutoOrient());
```
To alter or remove EXIF data (if it exists) is a case of setting either the `image.MetaData.ExifProfile` property to `null`  or removing the individual tag `image.MetaData.ExifProfile.RemoveValue(ExifTag.Orientation)`

Hope that makes sense.

Cheers,

James

**Comment by ArrowRaider** [comment]
Will AutoOrient() remove the EXIF value or should I do that after calling AutoOrient?

**Comment by JimBobSquarePants** [comment]
Use the source Luke 😉

https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Processing/Processors/Transforms/Linear/AutoOrientProcessor%7BTPixel%7D.cs
