### ISSUE TITLE
Create API Documentation

### ISSUE THREAD

**Issue by JimBobSquarePants** [SixLabors/ImageSharp#402]
### The Problem

Currently we have no API documentation. This harms library adoption and testing and also limits our visibility of the project. 

Initially we planned to add the API documentation directly to the [SixLabors](https://sixlabors.com/) site but I now believe that proposal is now too complicated and will not only cause further delay but prevent the community from giving documentation assistance.

### The Solution

For each project in the ImageSharp repository (and others) I propose we create a separate documentation repo. e.g **SixLabors.ApiDocs.ImageSharp**

We can utilize DocFX (via chocolatey) and Git Submodules to point at our individual projects to produce the API documentation. Sharing themes could also be done via Git Submodules if we see fit to do so.

An example of using Git Submodules for this task can be found here.
https://github.com/mellinoe/veldrid-docs/tree/master/ext  

I believe by serving the API docs via Github Pages in this manner we can increase automation, reduce complexity, and also free up time to focus on creating real developer friendly sample documentation on the SixLabors main site.

#### Notes
We need to do #401 first before we can publish the documentation but there is no reason why we couldn't immediately create the repositories and start working on supplementary content.

**Comment by antonfirsov** [comment]
@JimBobSquarePants for me it feels much simpler to maintain a single repo for all the docs.

I think we should host manual and generated documentations on the same site. ([Just as Velrid docs do.](https://mellinoe.github.io/veldrid-docs/))

**Comment by JimBobSquarePants** [comment]
I'm up for that also if that's easier. We can keep the Six Labors site more marketing based.

**Comment by JimBobSquarePants** [comment]
Closing for now as we have the basics in place and we have #411.
