### ISSUE TITLE
IndexOutOfRangeException in ReadFrameColors when processing Gif

### ISSUE THREAD

**Issue by iamcarbon** [SixLabors/ImageSharp#403]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] Only tested in RELEASE mode (Linux + Windows)
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When loading the following GIF with ImageSharp:

http://carbonmade-media.accelerator.net/35483286

an IndexOutOfRangeException is thrown in the following method:

SixLabors.ImageSharp.Formats.Gif.GifDecoderCore`1.ReadFrameColors(Byte[] indices, Byte[] colorTable, GifImageDescriptor descriptor)

### System Configuration

- ImageSharp version: 1.0.0-Beta2 running on .netcore2.0

Same error on Windows & Linux.

**Comment by JimBobSquarePants** [comment]
@iamcarbon I'll have a look at this with our latest build, I just did some work on the gif decoder. Hopefully it's simple enough to fix.

**Comment by JimBobSquarePants** [comment]
@iamcarbon Turns out this one has a left offset + width for the ImageDescriptor on frame 1 that is greater than the actual image width. Easy fix again thankfully 😄 

BTW this tool is super useful for looking at individual frames.

https://github.com/ata4/gifiddle
