### ISSUE TITLE
SVG encoding?

### ISSUE THREAD

**Issue by asterixorobelix** [SixLabors/ImageSharp#417]
### Description
Thanks for the great package!
Encoding and decoding of images in the SVG format?

**Comment by JimBobSquarePants** [comment]
Hi @asterixorobelix 

I'm very glad you like the package. 

We don't support non-raster image formats like SVG and it's unlikely that we will add the format to the core library.

It's more likely that someone would use ImageSharp as a basis for rendering SVG, in fact, someone has already suggested doing such with a popular library.  https://github.com/vvvv/SVG/issues/346

Cheers

James
