### ISSUE TITLE
SaveAsBmp doesn't write correct BPP into the Header

### ISSUE THREAD

**Issue by feliwir** [SixLabors/ImageSharp#420]
### Description
When having image data with an alpha channel (for example Rgba32 or Argb32) the Bmp Header produced by SaveAsBmp does specify 24bpp. This results in the alpha value being ignored by image viewers

### Steps to Reproduce
```csharp
public static byte[] PrependBmpHeader(byte[] rgbaData, int width, int height)
        {
            using (var outputStream = new MemoryStream())
            {
                var image = Image.LoadPixelData<Rgba32>(rgbaData, width, height);
                image.SaveAsBmp(outputStream);

                return outputStream.ToArray();
            }
        }
```

Looking at the image data now shows that the Bmp Header is incorrect. Instead of the expected 32bpp the header does contain 32bpp.

Thanks and with best regards

**Comment by JimBobSquarePants** [comment]
Hi @feliwir 

What you are seeing is actually correct behaviour. ImageSharp supports about 20 different pixel formats and as such the encoders and decoders are format agnostic. 

What you need to do is to pass a new instance of the `BmpEncoder` class as the second parameter when saving the image with the `BmpBitsPerPixel` property set to `BmpBitsPerPixel.Pixel32`.

Hope that makes sense

Cheers

James
