### ISSUE TITLE
Inconsistent behaviour between TextMeasurer and the result text size when DPI is specified

### ISSUE THREAD

**Issue by TheBlueSky** [SixLabors/ImageSharp#421]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I'm trying to draw a text on an image where its size is determined from the size of the text plus some margin.

For this, I'm using `TextMeasurer.Measure(Font font, float dpi)` to measure the text size then create the image as shown in the following code:

```csharp
private static void Main(string[] args)
{
    var rawImg72 = WriteTextToImage(72);
    System.IO.File.WriteAllBytesAsync(@".\output\img72.png", rawImg72).Wait();

    var rawImg96 = WriteTextToImage(96);
    System.IO.File.WriteAllBytesAsync(@".\output\img96.png", rawImg96).Wait();
}

private static byte[] WriteTextToImage(int dpi)
{
    var text = "SixLabors.ImageSharp";
    var font = SystemFonts.CreateFont("Arial", 16);
    var sizeF = TextMeasurer.Measure(text, new RendererOptions(font, dpi));
    var textSize = new Size(Convert.ToInt32(sizeF.Width), Convert.ToInt32(sizeF.Height));
    var margin = 4 * 2;
    var imageSize = new Size(textSize.Width + margin, textSize.Height + margin);
    var textPosition = new PointF(
        (imageSize.Width - textSize.Width) / 2,
        (imageSize.Height - textSize.Height) / 2);

    using (var img = new Image<Rgba32>(imageSize.Width, imageSize.Height))
    {
        // not sure these are needed or doing anything; the result with or without them is the same
        img.MetaData.HorizontalResolution = dpi;
        img.MetaData.VerticalResolution = dpi;

        img.Mutate(operation => operation
            .Fill(Rgba32.WhiteSmoke)
            .DrawText(text, font, Rgba32.Black, textPosition));

        using (var stream = new System.IO.MemoryStream())
        {
            img.Save(stream, ImageFormats.Png);

            return stream.ToArray();
        }
    }
}
```

The result of this code is the following images:

**72 DPI**
![img72](https://user-images.githubusercontent.com/807685/34463763-b9db6f26-ee7f-11e7-9995-1973b6db867e.png)

**96 DPI**
![img96](https://user-images.githubusercontent.com/807685/34463764-ba07edf8-ee7f-11e7-9feb-0c0c60bab099.png)

Note the following:

- The first image (72 DPI): the size is perfect and the image is horizontally centred, but the vertically is off.
- The second image (96 DPI): the image is vertically centred, but the size is incorrect and the text isn't horizontally centred (or maybe it is because it thinks the image size is the same as with 72 DPI).

### Steps to Reproduce
See Description section.

### System Configuration

- ImageSharp version: 1.0.0-beta0002 (from NuGet)
- Environment (Operating system, version and so on): Windows 10 Pro [Version 10.0.16299.125]
- .NET Framework version: .NET Core 2.0

**Comment by tocsoft** [comment]
The `DrawText` command currently always draws at 72 dpi ignoring the images configured dpi so that it will consistently produce a well know pixel height based for a specific point size, as this produces a more consistent output for most users.

If you want to measure the text for drawing always use 72 when measuring or just skip the dpi as it will default to 72dpi when omitted.

**Comment by TheBlueSky** [comment]
Thanks for clarifying.
2 questions:

- By "currently", do you mean that there is a plan to change this behaviour so that `DrawText` to respect the image DPI? If not, then what would be the situation where I want to measure the text in certain DPI but draw it in 72 DPI anyway?
- Maybe unrelated to this issue, but the drawn text (72 DPI) is not correctly centred vertically... I hope it isn't my eyes or my math 😄.

**Comment by JimBobSquarePants** [comment]
@tocsoft Just saw this related issue in the OxyPlot repo

https://github.com/oxyplot/oxyplot/issues/1188
