### ISSUE TITLE
"Value should be an unsigned short" exception on image with EXIF rotate.

### ISSUE THREAD

**Issue by musukvl** [SixLabors/ImageSharp#423]
### Description
The image I want to resize has EXIF and ImageSharp tries to update it with new Width/Height values on rotating.
I have "Value should be an unsigned short" on following code:
```
var input = @"G:\temp\temp-img\1.jpg";
using (var image = SixLabors.ImageSharp.Image.Load(input))
{
       image.Mutate(x => x
            .Rotate((float)90.0)); // Exception goes here
       image.Save(input); 
}
```
![1](https://user-images.githubusercontent.com/3954761/34471309-d6e17a3e-ef56-11e7-8ff1-135a3961998a.jpg)

### Analytics
Looks like problem in RotateProcessor
```
 profile.SetValue(ExifTag.PixelXDimension, source.Width);
```
It expects source.Width as `ushort`, but Image.Width defined as `int`:  
`public int Width => this.frames.RootFrame.Width;`

![image](https://user-images.githubusercontent.com/3954761/34471342-fd01a832-ef57-11e7-93bf-cc2c4613755d.png)

![image](https://user-images.githubusercontent.com/3954761/34471386-24a760a6-ef59-11e7-9d20-57409b920c13.png)

My suggestion is to cast PixelXDimension from int to ushort. It fixes problem but I'm not sure it is the best solution.

### Steps to Reproduce

Use 1.jpg attached and try to rotate it.

### System Configuration

- ImageSharp version: 1.0.0-dev000621   1.0.0-beta0002   
- Other ImageSharp packages and versions: master(6f438dac852c5d7408161e1afa034984671257f4)
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: 2.0
- Additional information:

### Exception: 

```
System.ArgumentException occurred
  HResult=0x80070057
  Message=Value should be an unsigned short.
Parameter name: value
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at SixLabors.ImageSharp.Guard.IsTrue(Boolean target, String parameterName, String message) in G:\ext\xxxxx\ImageSharp\src\ImageSharp\Common\Helpers\Guard.cs:line 212
```

**Comment by jsmarcus** [comment]
I'm also having this problem.
