### ISSUE TITLE
Errors on Setting up a ImageCore file for a Discord Bot

### ISSUE THREAD

**Issue by Badflar** [SixLabors/ImageSharp#425]
### Prerequisites

- [X ] I have written a descriptive issue title
- [X ] I have verified that I am running the latest version of ImageSharp
- [X ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X ] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I'm trying to setup a Discord bot to be able to manipulate images when inputted. The website that shows how to set it up says to have an ImageCore file that looks like the one below. The problem is, some of the code gets errors even though it is exactly the same as the website.

Errors on:
"StartStreamAsync" Line: 26
"<Rgba32>" Line: 30 - The type 'SixLabors.ImageSharp.Rgba32' cannot be used as a perameter for '
                                     'TColor' in general type or method of 'Image<'TColor'>. 
"Load<Rgba32>" Lines: 43, 50, 56 - 'image' does not contain the definition of 'load'
"SaveAsPng" Line 76 - Does not contain extention. 

### Steps to Reproduce
`using Discord;
using Discord.Commands;
using Discord.WebSocket;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using System.Net.Http;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Drawing.Pens;
using SixLabors.ImageSharp.Drawing.Brushes;
using SixLabors.ImageSharp.Processing;
using SixLabors.ImageSharp.Drawing;
using SixLabors.Fonts;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.Primitives;
using SixLabors.Shapes;
using SixLabors.ImageSharp.Formats.Png;

namespace Foxley_2
{
    public class ImageCore
    {
        private string randomString = ""; /*Creates a empty string*/

        public async Task<ImageSharp.Image<Rgba32>> StartStreamAsync(IUser user = null, string url = null, string path = null) /*Creates a async Task that returns a ImageSharp image with a user and url param*/
        {
            HttpClient httpClient = new HttpClient(); /*Creates a new HttpClient*/
            HttpResponseMessage response = null;
            ImageSharp.Image<Rgba32> image = null; /*Creates a null ImageSharp image*/

            if (user != null) /*Checks if the url is null aka the default value*/
            {
                try
                {/*try to get users avatar*/
                    response = await httpClient.GetAsync(user.GetAvatarUrl()); /*sets the response to the users avatar*/
                }
                catch
                {/*If they didnt set one, get a default one*/
                    response = await httpClient.GetAsync("https://discordapp.com/assets/1cbd08c76f8af6dddce02c5138971129.png"); /*sets the response to the url*/
                }
                Stream inputStream = await response.Content.ReadAsStreamAsync(); /*creates a inputStream variable and reads the url*/
                image = ImageSharp.Image.Load<Rgba32>(inputStream); /*Loads the image to the ImageSharp image we created earlier*/
                inputStream.Dispose();
            }
            if (url != null)/*Do this if a URL is given*/
            {
                response = await httpClient.GetAsync(url); /*sets the response to the url*/
                Stream inputStream = await response.Content.ReadAsStreamAsync(); /*creates a inputStream variable and reads the url*/
                image = ImageSharp.Image.Load<Rgba32>(inputStream); /*Loads the image to the ImageSharp image we created earlier*/
                inputStream.Dispose();
            }
            if (path != null)/*Do this is a path is given*/
            {
                Stream inputStream = File.Open(path, FileMode.Open);
                image = ImageSharp.Image.Load<Rgba32>(inputStream);
                inputStream.Dispose();
            }
            return image; /*returns the image*/

        }

        public async Task StopStreamAsync(IUserMessage msg, ImageSharp.Image<Rgba32> image) /*Creates an async task with UserMessage as a paramater */
        {
            string input = "abcdefghijklmnopqrstuvwxyz0123456789"; /*alphabet abcdefghijklmaopqrstuvwxy and z! now I know my abc's!*/
            char ch;
            Random rand = new Random();
            for (int i = 0; i < 8; i++)/*loops through the alphabet and creates a random string with 8 random characters */
            {
                ch = input[rand.Next(0, input.Length)];
                randomString += ch;
            }
            if (image != null) /*Checks if the image we created is not null if it is then this part won't run*/
            {
                Stream outputStream = new MemoryStream();
                image.SaveAsPng(outputStream); /*saves the image as a jpg you can of course change this*/
                outputStream.Position = 0;
                var file = File.Create($"images/{randomString}.png"); /*creates a file with the random string as the name*/
                await outputStream.CopyToAsync(file);
                file.Dispose();
                await msg.Channel.SendFileAsync($"images/{randomString}.png"); /*sends the image we just created*/
                File.Delete($"images/{randomString}.png"); /*deletes the image after sending*/
            }
        }
    }
}
`

### System Configuration
Making a cs file for a Discord bot for other cs files to reference. 

- ImageSharp version: 1.0.0-beta0002
- Other ImageSharp packages and versions: RevStackCore-ImageSharp (0.9.0-Alpha), SixLabors.ImageSharp (1.0.0-beta0002)
- Environment (Operating system, version and so on): Windows 10 
- .NET Framework version: 2.0
- Additional information: Here is the website I am getting the code from. https://forum.codingwithstorm.com/index.php?topic=128.0

**Comment by JimBobSquarePants** [comment]
It's that RevStackCore ImageSharp library that is the problem. It's a copy of an early alpha of the library that some prat decided to publish without our permission and have refused to remove. Nuget have also been utterly useless so far in removing it for us. 

Delete that junk and you'll be fine.

**Comment by Badflar** [comment]
Thanks JimBobSquarePants,

That did the trick. Sorry to hear that. That is dickish to have that when it even breaks the SixLabors nuget too.

**Comment by JimBobSquarePants** [comment]
Yeah, frustrating 😦
