### ISSUE TITLE
Feature proposal: handling tileable images

### ISSUE THREAD

**Issue by vpenades** [SixLabors/ImageSharp#427]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I was wondering if there's any provision for handling tileable images... I know that brushes are tileable by default, but in most processors, image tiling/wrapping is simply not supported.

For example, let's say I have an image (texture) I know it's tileable, and I want to apply a gaussian blur with radius 5. The current behavior is that processed pixels close to a boundary would not take in account the pixels of the opposite boundary. The resulting image, when tiled, would show a noticeable sharp seam between tile limits.

Tipically when texture/tiling has an enumeration like this:

WrapModes:

- None
- WrapX
- WrapY
- MirrorX
- MirrorY

**Comment by antonfirsov** [comment]
@vpenades interesting proposal, but really not easy to implement because of the cross-library architectural impact it brings. Might be a candidate feature for 2.0, but with our current focus, I'm afraid it's a bit off the radar, unless someone from the community takes care of it.

But we really want to hear the voice of the users, so anyone else having interest in this, please vote/leave your comments! :)

**Comment by JimBobSquarePants** [comment]
I'd say it only affects only the convolution based processors so theoretically shouldn't be too big a deal. That said a PR would be most welcome.

**Comment by antonfirsov** [comment]
It probably also affects drawing.

**Comment by JimBobSquarePants** [comment]
You reckon? I don't think any of the drawing stuff really cares about edge pixels. I could be wrong though, it's not an area I've looked at in a while.

**Comment by tocsoft** [comment]
Only thing that could be effected in drawing is the `ImageBrush` and that already tiles the fill image.

**Comment by antonfirsov** [comment]
Supporting tiling would mean to me that we need to support "cross boundary" drawing in a way like this:
![image](https://user-images.githubusercontent.com/6835152/34841984-60d8a46e-f70a-11e7-92d7-87005ca0816c.png)

Black lines represent image boundary, the green hearth represents the shape drawn by `ImageSharp.Drawing`.

**Comment by tocsoft** [comment]
no don't think we would need/should to support that scenario. It would be trivial to just draw the shape yourself with applying a transform the make it offset to each side.

**Comment by JimBobSquarePants** [comment]
Fixed with #2060
