### ISSUE TITLE
Anything similar to ColorTranslator.FromHtml for colors?

### ISSUE THREAD

**Issue by Gillardo** [SixLabors/ImageSharp#437]
I have searched the repo and cannot seem to find anything, but i need something like `ColorTranslator` from `System.Drawing` to convert a HTML colour into a Color, then lighten the color and convert that into a html string.  As long as i can start with a string and end with a string, i dont mind how it is done.

Is there anything like this within this project to do this??

**Comment by tocsoft** [comment]
Please note the issue tracker is for reporting issues only, not for general questions. If you had read our contribution guidelines (linked from the 'new issue' screen) or attempted to fill out our issue template then you would have noticed that. In future please direct questions like this to our [gitter channel](https://gitter.im/ImageSharp/General). 

For brevity the API you are looking for is `ColorBuilder<TPixel>.FromHex(string hex)` (it supports hex strings but not color names)
