### ISSUE TITLE
resize an image from byte[] to byte[] may lose pixels

### ISSUE THREAD

**Issue by endink** [SixLabors/ImageSharp#444]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Resize an image will lost some pixel.

### Steps to Reproduce

btw: _imageData is an image byte array.
```csharp
public override byte[] Scale(double scaleFactor, String format)
{
    this.ThrowIfDisposed();
    if (scaleFactor <= 0)
    {
        throw new ArgumentException("scalefactor must be greate than 0", nameof(scaleFactor));
    }
    try
    {
        int width = (int)(this.Profile.PixelWidth * scaleFactor);
        int height = (int)(this.Profile.PixelHeight * scaleFactor);
        using (Image<Rgba32> bitmap = Image.Load(_imageData, out IImageFormat imageFormat))
        {
            bitmap.Mutate(x => x.Resize(width, height));
            IImageFormat f = String.IsNullOrWhiteSpace(format) ? imageFormat : GetImageFormat(format);
            using (MemoryStream stream = new MemoryStream())
            {
                bitmap.Save(stream, f);
                        
                stream.Position = 0;
                return stream.ToArray();
            }
        }
    }
    catch (Exception ex)
    {
        throw new ImagingException("scale error.", ex);
    }
}


private IImageFormat GetImageFormat(string format)
{
    IImageFormat imageFormat = SixLabors.ImageSharp.Configuration.Default.FindFormatByFileExtension(format);
    if (imageFormat == null)
    {
        throw new ImagingException($"unsupported format：{format}。");
    }
    return imageFormat;
}
```

original Image

![gounda_takeshi](https://user-images.githubusercontent.com/240164/35182159-12383016-fe0a-11e7-8355-3d681455777d.png)

## got result:

resize to 150px:
![avatar_150](https://user-images.githubusercontent.com/240164/35182152-0a4f8066-fe0a-11e7-83ab-97d14732f105.png)

resize to 80px
![avatar_80](https://user-images.githubusercontent.com/240164/35182151-0a148c68-fe0a-11e7-8d49-a5e1e5df922b.png)

resize to 30px
![avatar_30](https://user-images.githubusercontent.com/240164/35182153-0a86724c-fe0a-11e7-970c-c4714c480560.png)

### System Configuration
Visual studio 2017
```
 <TargetFramework>netstandard1.6</TargetFramework>
```

- ImageSharp version: 1.0.0-beta0002
- Environment (Operating system, version and so on): Windows 10 x64
- .NET Framework version: netstandard1.6
- Additional information:

**Comment by JimBobSquarePants** [comment]
Hi @endink 

I'm able to resize and save the image to 150 x150 without issue. Are you sure all your variables are correct?
 
![splash](https://user-images.githubusercontent.com/385879/35182471-f1714dd4-fe29-11e7-9fd1-42cf35b4fcb7.png)

**Comment by endink** [comment]
@JimBobSquarePants well, I'll check my code again, and if possible, I'll extract my main code and package it up and upload it.

**Comment by endink** [comment]
@JimBobSquarePants sorry, it works well now, my code writes less bytes when I write a byte array to a file

**Comment by JimBobSquarePants** [comment]
No worries, glad you found a solution. 👍
