### ISSUE TITLE
ImageSharp can't handle InputStreamInvoker with Android.OS.ParcelFileDescriptor.AutoCloseInputStream (Xamarin.Android)

### ISSUE THREAD

**Issue by mfe-** [SixLabors/ImageSharp#451]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Calling `SixLabors.ImageSharp.Image.Load(stream))` with a stream of type `Android.Runtime.InputStreamInvoker` and BaseInputStream of the type `Android.OS.ParcelFileDescriptor.AutoCloseInputStream` results in an instant crashing app. The output:

```
01-30 19:57:49.328 W/Mono    ( 4359): The request to load the assembly System.Numerics.Vectors v4.1.3.0 was remapped to v2.0.5.0
01-30 19:57:49.328 D/Mono    ( 4359): Assembly Ref addref System.Memory[0xaed932c0] -> System.Numerics.Vectors[0xaeea1a00]: 3
01-30 19:57:49.328 D/Mono    ( 4359): Assembly Ref addref System.Numerics.Vectors[0xaeea1a00] -> mscorlib[0xaed92ae0]: 16
01-30 19:57:49.350 D/Mono    ( 4359): Image addref System.Resources.ResourceManager[0xb4099ba0] -> System.Resources.ResourceManager.dll[0x9f661900]: 2
01-30 19:57:49.350 D/Mono    ( 4359): Prepared to set up assembly 'System.Resources.ResourceManager' (System.Resources.ResourceManager.dll)
01-30 19:57:49.350 D/Mono    ( 4359): Assembly System.Resources.ResourceManager[0xb4099ba0] added to domain RootDomain, ref_count=1
01-30 19:57:49.351 D/Mono    ( 4359): AOT: image 'System.Resources.ResourceManager.dll.so' not found: dlopen failed: library "/data/app/App1Android.App1Android-1/lib/x86/libaot-System.Resources.ResourceManager.dll.so" not found
01-30 19:57:49.351 D/Mono    ( 4359): AOT: image '/usr/local/lib/mono/aot-cache/x86/System.Resources.ResourceManager.dll.so' not found: dlopen failed: library "/data/app/App1Android.App1Android-1/lib/x86/libaot-System.Resources.ResourceManager.dll.so" not found
01-30 19:57:49.351 D/Mono    ( 4359): Config attempting to parse: 'System.Resources.ResourceManager.dll.config'.Loaded assembly: System.Resources.ResourceManager.dll [External]

01-30 19:57:49.351 D/Mono    ( 4359): Config attempting to parse: '/usr/local/etc/mono/assemblies/System.Resources.ResourceManager/System.Resources.ResourceManager.config'.
01-30 19:57:49.351 D/Mono    ( 4359): Assembly Ref addref SixLabors.Core[0xaed92f00] -> System.Resources.ResourceManager[0xb4099ba0]: 2
01-30 19:57:49.351 D/Mono    ( 4359): Assembly Ref addref System.Resources.ResourceManager[0xb4099ba0] -> mscorlib[0xaed92ae0]: 17
01-30 19:57:49.363 W/Mono    ( 4359): The request to load the assembly System.Numerics.Vectors v4.1.3.0 was remapped to v2.0.5.0
01-30 19:57:49.363 D/Mono    ( 4359): Assembly Ref addref SixLabors.Core[0xaed92f00] -> System.Numerics.Vectors[0xaeea1a00]: 4
01-30 19:57:49.363 F/        ( 4359): * Assertion at /Users/builder/jenkins/workspace/xamarin-android-d15-5/xamarin-android/external/mono/mono/mini/mini-codegen.c:1265, condition `reginfo [sreg].born_in > 0' not met
01-30 19:57:49.363 F/libc    ( 4359): Fatal signal 6 (SIGABRT), code -6 in tid 4359 (oid.App1Android)
```
First it seems to me that, in general all `InputStreamInvoker ` aren't working with `ImageSharp.Load`
While investigating this issue I found in #223 that `Android.Runtime.InputStreamInvoker` works for loaded images resources:
```
Stream src = this.Resources.OpenRawResource(Resource.Drawable.tree); //BaseInputStream of type Android.Content.Res.AssetManager.AssetInputStream
Image<Rgba32> image = Image.Load(src); //works
```
Looking closer to the Android.Runtime.InputStreamInvoker (which crashes the app) I noticed a different BaseInputStream of the type `Android.OS.ParcelFileDescriptor.AutoCloseInputStream`. I'm not 100% sure if this error is related to ImageSharp or whether it's related to Mono.

### Steps to Reproduce
Create an [image filepicker](https://developer.xamarin.com/recipes/android/other_ux/pick_image/) and pass the stream into `ImageSharp.Load`.
```
Stream stream = ContentResolver.OpenInputStream(uri);
Image<Rgba32> image = Image.Load(src); //crashes the app
```
I created a [repository](https://github.com/mfe-/App1Android/blob/master/App1Android/MainActivity.cs#L53) which reproduces the crash. I will reproduce the issue on a real phone on Thursday.

### System Configuration
The bug occurs on my Visual Studio Emulator 5" Marshmallow (6.0.0) XHDPI Phone API Level 23). The app was created using Xamarin.Android, compiled using Android 6.0 with the minimum target version 5.0.

- ImageSharp version: 1.0.0-beta0002
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): Windows 10 1709
- .NET Framework version: Xamarin.Android (Mono)
- Additional information: Building the Project in Release Mode didn't worked for the Emulator.

**Comment by JimBobSquarePants** [comment]
Hi @mfe- 

That looks like a Mono issue to me. We don't and shouldn't need to do anything special since we are building to the .NET Standard. 

Perhaps @TodesBrot can shed some light on the difference between the two stream types? I have never used Xamarin.

**Comment by mfe-** [comment]
Hi @JimBobSquarePants,

I just tested the linked [repository](https://github.com/mfe-/App1Android/blob/master/App1Android/MainActivity.cs) on a Samsung Galaxy A3 with an Image of size {Image<Rgba32>: 4128x3096}.

Loading the Image took about 3 Minutes. Maybe the crash was related to the emulator.

**Comment by antonfirsov** [comment]
> Loading the Image took about 3 Minutes. [4128x3096]

Unfortuanately Xamarin runtime lacks SIMD support + has poor Generics implementation at the moment. ImageSharp performance relies heavily on these fetures. Hope they gonna improve this in the future.

**Comment by JimBobSquarePants** [comment]
>Loading the Image took about 3 Minutes

Ouch!

**Comment by JimBobSquarePants** [comment]
I'm closing this as it really boils down to SIMD support on ARM chips which should be coming. 

https://github.com/dotnet/corefx/issues/22940

However we could be limited to netcore only?

https://github.com/dotnet/corefx/issues/24346
