### ISSUE TITLE
Crash when resizing an image

### ISSUE THREAD

**Issue by vpenades** [SixLabors/ImageSharp#453]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I've got a crash when resizing the image below.

### Steps to Reproduce
Try to resize [this](https://github.com/ianare/exif-samples/blob/master/jpg/Konica_Minolta_DiMAGE_Z3.jpg) image.

Crash report shows something related to EXIF.

Btw, the whole repository that contains that image has some intersting test images for EXIF

### System Configuration
Latest Alpha.

- ImageSharp version:
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by JoshaMunnik** [comment]
I had the same problem. The bug is caused because ExifValue.CheckValue expects an uint for the Exif Long type when ResizeProcesser.AfterImageApply stores the dimensions. However Image uses int for Width and Height. 

I'll try to do a pull/push.

**Comment by vpenades** [comment]
@dlemstra @JimBobSquarePants Additionally, if EXIF metadata is going to be affected by resizes, crops and other transformations, I would request as a feature, to also handle `SubjectPosition ` and `SubjectArea` tags , since they also contain pixel based, positional information within the image.

This is obvious from the [image ](https://github.com/ianare/exif-samples/blob/master/jpg/Konica_Minolta_DiMAGE_Z3.jpg) I linked before. It has SubjectArea located outside the image bounds, because the image was resized, but the resizing image didn't change the SubjectArea.

**Comment by JimBobSquarePants** [comment]
@vpenades Good catch

We should strip out the following tags on all transforms
- SubjectLocation
- SubjectArea

And possibly strip out the following on scale/crop (not sure about these)
- SubjectDistance
- SubjectDistanceRange

**Comment by vpenades** [comment]
@JimBobSquarePants SubjectDistanceRange is an Enum, and my guess SubjectDistance is the depth from the camera in metres , so they should not be affected by transforms (unless we're talking about 3D transforms...)

By strip the tags, you mean remove them? or adjust the values? I have some utilities to easily access the Subject information [here ](https://github.com/vpenades/UberFactory/blob/master/src/Epsylon.ImageSharp.Procedural/SubjectInfo.cs).

**Comment by JimBobSquarePants** [comment]
Yeah, you're right, we don't need to touch SubjectDistance and SubjectDistanceRange.

>By strip the tags, you mean remove them? or adjust the values? 

I meant remove them as I don't know how feasible it would be to recalculate them based on the transform. We're gonna have unlimited composable affine transforms in the next beta. Happy to take suggestions though if you can think of something better?

That's some great code you have there btw, stuff we should probably have in core. It seems a lot of work based on our current API/capabilites for you to get the information you need in a usable form.

**Comment by JimBobSquarePants** [comment]
@vpenades You and I need to chat about those [suggestions](https://github.com/vpenades/UberFactory/blob/acd15cb792fcd590fdaa3636740ad9df075b85b5/src/Epsylon.ImageSharp.Procedural/Readme.txt) in your repo btw, would love your help implementing some of the changes. We need people like you writing code based on our work to help us make sure it does what you need/expect it to do. 👍

**Comment by JimBobSquarePants** [comment]
@vpenades I've pushed a quick fix for your resize issue to the nightlies. If you can open a new issue regarding `SubjectDistance` and friends we can have a separate discussion there and hopefully incorporate some of your work.
