### ISSUE TITLE
Allow decoders to load metadata only

### ISSUE THREAD

**Issue by vpenades** [SixLabors/ImageSharp#460]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
In some scenarios, it could be interesting to load the MetaData information of an image, without loading the bitmap data.

The advantage is to be able to load the metadata of thousands of images much faster, and with less memory consumption.

The implementation would be done in the image decoders, with a `LoadMetadata `method or something like that.

As a bonus, it could be great to be able to modify the metadata of an image file, without modifying the actual compressed image.

**Comment by antonfirsov** [comment]
@vpenades we have `Image.Identify()` for this since the merging of #292. Do you lack some other functionality here, or just missed it? :)

**Comment by antonfirsov** [comment]
@vpenades see [this spontaneous design discussion](https://github.com/SixLabors/ImageSharp/pull/292/files/9f719d5b9423083c112a69144e98a15bbb8c9409#diff-70bebbed1a8bf52bdf94497d7856525eR14) to see API choices we made.

**Comment by vpenades** [comment]
@antonfirsov ahhh, I didn't know about that one!

**Comment by JimBobSquarePants** [comment]
>As a bonus, it could be great to be able to modify the metadata of an image file, without modifying the actual compressed image.

That would be a very nice bonus. Probably for V2, Lets close this issue and open another for that specific functionality.
