### ISSUE TITLE
Read keyword metadata

### ISSUE THREAD

**Issue by wozzo** [SixLabors/ImageSharp#468]
### Description
I've been through every bit of Metadata I can see on an Image, but am unable to find the keywords I know to be stored on the image. Is it possible to add the list of keywords as a property on Metadata? Or is there an alternative means of accessing the keywords I've missed?

**Comment by JimBobSquarePants** [comment]
Hi @wozzo 

At present we do not support reading/writing either IPTC or XMP metadata which both support keywords. EXIF does not have such a tag. 

We're always looking for contributions though to add those metadata specifications. 

Hope that clears it up.

Cheers

James
