### ISSUE TITLE
Vertical Central Text Alignment - Text is cut off or too low

### ISSUE THREAD

**Issue by benwilliamson** [SixLabors/ImageSharp#470]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I'm trying to centralize text both horizontally and vertically but it's just not aligning correctly. It's so bad that the text is being cut off at the bottom when using larger fonts, even though the text should fit at this size. (e.g)
![front2](https://user-images.githubusercontent.com/6832680/36439865-04db8566-1666-11e8-971e-7fdc6e2f7909.png)

Smaller fonts won't be cut off, but still aren't exactly central. Am I doing something wrong, or is there some padding built into DrawText that pushes the text down?

### Steps to Reproduce
```
public static void createText(string savePath, string text, string fontFileName, RectangleF rectText)
        {            
            var fontSize = 250;            
            FontCollection fonts = new FontCollection();
            FontFamily fontFamily = fonts.Install(fontStore + fontFileName);
            
var rendererOptions = new RendererOptions(fontFamily.CreateFont(fontSize, FontStyle.Regular), 72);                       
                        
            var textColor = Rgba32.Black;
            
            using (Image<Rgba32> img = new Image<Rgba32>((int)rectText.Width, (int)rectText.Height))
            {                
                float textMaxWidth = img.Width;

                Vector2 pos = new Vector2(0, img.Height / 2);                

                img.Mutate(x => x.Fill(Rgba32.Transparent));                
                img.Mutate(x => x.Draw(Rgba32.Red, 1, rectText));

                img.Mutate(ctx => ctx
                    .DrawText(text, fontFamily.CreateFont(fontSize, FontStyle.Regular), textColor, pos, new TextGraphicsOptions(true)
                    {
                        Antialias = true,
                        ApplyKerning = true,
                        VerticalAlignment = VerticalAlignment.Center,
                        HorizontalAlignment = HorizontalAlignment.Center,
                        WrapTextWidth = img.Width
                    }));

                SixLabors.ImageSharp.Formats.Png.PngEncoder pngEncoder = new SixLabors.ImageSharp.Formats.Png.PngEncoder();
                pngEncoder.CompressionLevel = 0;                

                FileStream fileStream = new FileStream(savePath, FileMode.OpenOrCreate);
                img.SaveAsPng(fileStream, pngEncoder);
            }            
        }

```

### System Configuration
VS2017, Windows 10, .NET Core, 2.0

- ImageSharp version: 1.0 beta 2
- Other ImageSharp packages and versions: core, fonts, drawing, shapes
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: NET Core 2.0
- Additional information:

**Comment by JimBobSquarePants** [comment]
@tocsoft What's your thoughts on this? I've seen it pop up a few times now. Where should I be looking to investigate?

**Comment by tocsoft** [comment]
It will be an issue inside `SixLabors.Fonts` if its anywhere.
This method is the layout engine bit that decides exactly where text is placed.. https://github.com/SixLabors/Fonts/blob/master/src/SixLabors.Fonts/TextLayout.cs#L27

Thing to note about this is I'm pretty sure its setup to render glyphs in relation to their internal default line height not the actual vectors used to draw the glyph (basically layout relies on the metadata about the glyphs in the font not the actual vectors themselves.)

**Comment by JimBobSquarePants** [comment]
I think we need to create reference implementations to compare against. I have no real idea what the correct behavior should be.

**Comment by woutware** [comment]
In method `SixLabors.Fonts.TextLayout.GenerateLayout()`:

There was a gap between the top of the line and the top of the glyphs of the first line that the vertical alignment didn't take into account. Also there was a minor bug in calculating the line height itself that possibly happened when there were glyphs of varying line heights in the line.

**Comment by woutware** [comment]
https://github.com/SixLabors/Fonts/pull/67

**Comment by JimBobSquarePants** [comment]
I believe this has now been fixed in beta4. Will close for now. @benwilliamson please reopen if you continue to have the issue.
