### ISSUE TITLE
Bad RST marker For Mobile Jpeg Images

### ISSUE THREAD

**Issue by KANekT** [SixLabors/ImageSharp#481]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

```
            using (var file = new MemoryStream(data))
            {
                using (var image = SixLabors.ImageSharp.Image.Load<Rgba32>(file))
                {
                    using (var outputStream = new MemoryStream())
                    {}
}
}
```

### Steps to Reproduce
load 
![photo_00104](https://user-images.githubusercontent.com/580273/36789014-3216e048-1ca1-11e8-955c-a3424d3001a9.jpg)
![photo_00102](https://user-images.githubusercontent.com/580273/36789016-3254ae14-1ca1-11e8-9bed-90063c66e040.jpg)
![photo_00103](https://user-images.githubusercontent.com/580273/36789017-32728dee-1ca1-11e8-9ca5-8c8b005c78e5.jpg)

### System Configuration

- ImageSharp.Drawing version: 1.0.0 beta2 / 1.0.0-dev000807
- Environment (Operating system, version and so on): Win 10
- .NET Framework version: net core 2.0
- Additional information: https://github.com/SixLabors/ImageSharp/issues/416

**Comment by JimBobSquarePants** [comment]
@antonfirsov 

I checked the first image and we're throwing because when we check for the first expected RST marker we get 255,255 instead of 255,208. 

https://github.com/SixLabors/ImageSharp/blob/bc65aead9b04bb911236f3b1fc67bd08773c8c2b/src/ImageSharp/Formats/Jpeg/GolangPort/Components/Decoder/OrigJpegScanDecoder.cs#L207

What I don't know is what we should do here. Do we rewind and continue? Should we expect the next marker?

**Comment by KANekT** [comment]
more foto/images: https://yadi.sk/d/dQ0zVKFu3StT7w

**Comment by antonfirsov** [comment]
@JimBobSquarePants Depends on what RST marker is. Wish I knew, need to check it 😃

**Comment by JimBobSquarePants** [comment]
RST markers are used to resync decoding of scan data when the image is corrupt. 

They're distributed at an interval defined in the DRI (Define Restart Interval) marker. This means that every n MCU blocks a RSTn marker can be found. The first marker will be RST0, then RST1 etc, after RST7 repeating from RST0.

How you actually use them do do so is a mystery to me. I think however I've found the logic used in libjpeg turbo. https://github.com/libjpeg-turbo/libjpeg-turbo/blob/077e5bb4e0f6761c034e7c1f7e7a4120f580f1a0/jdmarker.c#L1209

**Comment by antonfirsov** [comment]
What happens if we ignore the verification?

**Comment by JimBobSquarePants** [comment]
You get a partially decoded image. Same as PdfJs version.

**Comment by KANekT** [comment]
My i use it in Nightly ? And since Version ?

**Comment by JimBobSquarePants** [comment]
No worries.

Yeah, just grab the latest from here.

https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp
