### ISSUE TITLE
How Add WaterMark

### ISSUE THREAD

**Issue by KANekT** [SixLabors/ImageSharp#484]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Steps to Reproduce
I create WaterMark class 
```
    public static class WaterMark {
        public static IImageProcessingContext<TPixel> ApplyScalingWaterMark<TPixel>(
            this IImageProcessingContext<TPixel> processingContext, string cacheFolder)
            where TPixel : struct, IPixel<TPixel> {
            return processingContext.Apply(image => {
                var path = Path.Combine(cacheFolder, "logo.png");
                if (!File.Exists(path))
                    return;
                var logo = SixLabors.ImageSharp.Image.Load<TPixel>(path);
                var worh = image.Width > image.Height;

                var coff = worh ? image.Width * 0.1 / Math.Min(logo.Width, logo.Height) : image.Height * 0.1 / Math.Max(logo.Width, logo.Height);

                var size = new Size((int)(logo.Width * coff), (int)(logo.Height * coff));
                var location = new Point(image.Width - size.Width - 5, image.Height - size.Height - 5);
                image.Mutate(i => {
                    i.DrawImage(logo, PixelBlenderMode.Normal, 0.5f, size, location);
                });
            });
        }
    }
```

and use it 

```
            using (var image = SixLabors.ImageSharp.Image.Load<Rgba32>(file))
            {
                using (var outputStream = new MemoryStream())
                {
                    if (modelImage.UseResize)
                    {
                        image.Mutate(x => x.Resize(modelImage.Width, modelImage.Height));
                    }

                    image.Mutate(x => x.ApplyScalingWaterMark(_rootFolder));

                    image.Save(modelImage.Path);
                    image.Save(outputStream, new JpegEncoder
                    {
                        Quality = _options.Quality,
                        IgnoreMetadata = true
                    });

                    return outputStream.ToArray();
                }
            }

```
It worked in 1.0.0 beta2

After update to 1.0.0-dev000873
size has removed in public static class ImageExtensions

and i use 
`i.DrawImage(logo, PixelBlenderMode.Normal, 0.5f, location);`
But in result image I'm not view watermark :(

### System Configuration

- ImageSharp version: 1.0.0-dev000873
- Other ImageSharp packages and versions: 1.0.0-dev000873
- Environment (Operating system, version and so on): VS 2017 (15.6) win 10
- .NET Framework version: net core 2.0
- Additional information:

**Comment by JimBobSquarePants** [comment]
Hi @KANekT 

The issue tracker should only be used for issues, not questions (please read the contribution guidelines).
I'll answer though since it's your first offence 😝 

We removed the size parameter from `DrawImage` because the internal clone required used too much memory. 

See https://github.com/SixLabors/ImageSharp/pull/471

Instead you now have to resize the image before passing it to the other `DrawImage` method.

```
public static class WaterMark
{
    public static IImageProcessingContext<TPixel> ApplyScalingWaterMark<TPixel>(
        this IImageProcessingContext<TPixel> processingContext,
        string cacheFolder)
        where TPixel : struct, IPixel<TPixel>
    {
        return processingContext.Apply(
            image =>
            {
                string path = Path.Combine(cacheFolder, "logo.png");

                if (!File.Exists(path))
                {
                    return;
                }

                // Dispose of logo once used.
                using (var logo = Image.Load<TPixel>(path))
                {
                    bool worh = image.Width > image.Height;
                    double coff = worh
                                ? image.Width * 0.1 / Math.Min(logo.Width, logo.Height)
                                : image.Height * 0.1 / Math.Max(logo.Width, logo.Height);

                    var size = new Size((int)(logo.Width * coff), (int)(logo.Height * coff));
                    var location = new Point(image.Width - size.Width - 5, image.Height - size.Height - 5);

                    // Resize the logo
                    logo.Mutate(i => i.Resize(size));

                    image.Mutate(i => i.DrawImage(logo, PixelBlenderMode.Normal, 0.5f, location));
                }
            });
    }
}
```

P.S You were't disposing of your logo after use. `Image<TPixel>` implements `IDisposable` and should always be disposed of once used.

**Comment by LeslieMurphy** [comment]
Is there a full working example of how to use DrawImage?  I am wanting to embed one image into another, and also overlay some text onto the image.  Part of the code shown in this thread wuuld not compile for me 

`                    image.Mutate(i => i.DrawImage(logo, PixelBlenderMode.Normal, 0.5f, location));
`

My signatures for DrawImage (1.0.0 Beta0003) are:

```
Image<Rgba32> image, float percent, Size size, Point location
Image<Rgba32> image,  Size size, Point location, GraphicOptions options
Image<Rgba32> image, PixelBlenderMode blender, float percent, Size size, Point location
```

The following worked fine for me - but I am hoping there is a full example so I can make sure I am doing everything correctly:

`image1.Mutate(ctx => ctx.DrawImage(image2, PixelBlenderMode.Normal, 0.5f, size, location));
`

Where / how do you wish to get these sorts of issues in the future?  As  a new SO post?

Thanks!

**Comment by JimBobSquarePants** [comment]
@LeslieMurphy Are you sure you definitely have beta3. We removed the size parameter before then. 

Gitter is probably best for questions just now.
