### ISSUE TITLE
İmage file size problem after image.save(...)  is this problem coming from OS or do we need to change something in the code..?

### ISSUE THREAD

**Issue by cemalpolat** [SixLabors/ImageSharp#485]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### System Configuration

- ImageSharp version:
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by tocsoft** [comment]
please direct questions to our gitter channel as it says in our readme

**Comment by cemalpolat** [comment]
Thank you,  Scott, for the answer so quick.  I am very new to using this channel. Please accept my excuse.:)
So the question for me was .. when I save the image, the size of a saved image is not the correct size.
I think this problem probably comes from my OS(Windows 10).  I wanted to know if is there another way to save the image in your library. Thank you very much.

**Comment by cemalpolat** [comment]
This problem I have faced before. When I tried to save image as an object directly, no matter bitmap or image object in windows forms by c#, I had the problem.  The size of the saved image was always wrong. I do not remember but I think I have solved by using file stream class.. It may give a clue. I will try to find a way base on this experience.  Not sure If I can.

**Comment by antonfirsov** [comment]
@cemalpolat can you be more specific? We hardly understand your issue. 
When getting incorrect results: Are you trying to resize + save your image with `System.Drawing`? Or are you trying ImageSharp? (We do not depend on OS services at all btw.)
If you are looking for basic ImageSharp resize examples, just go through [our main README](https://github.com/SixLabors/ImageSharp#api).

**Comment by cemalpolat** [comment]
The image uploaded is 4.30 MB .the Image saved by the code below is always as less than 1 MB.

                    using (var memoryStream = new MemoryStream())
                    {
                        fl.CopyTo(memoryStream);
                        using (Image<Rgba32> image = Image.Load<Rgba32>(memoryStream.ToArray()))
                        {

                            //with encoder it changes but still wrong
                            //without encoder it allways wrong size for saved image
                            IImageEncoder imageEncoder = new JpegEncoder()
                            {
                                Quality = 90,
                                Subsample = JpegSubsample.Ratio444
                            };
                            

                            image.Mutate(x =>
                            {
                                x.AutoOrient();
                                //x.Resize(image.Width / 2, image.Height / 2);
                                image.Save<Rgba32>(fileSaveUrl, imageEncoder);
                                x.Grayscale();
                                image.Save(fileSaveGrayUrl, imageEncoder);
                                x.BlackWhite();
                                image.Save<Rgba32>(fileSaveBWUrl, imageEncoder);
                                x.Lomograph(new SixLabors.Primitives.Rectangle(5, 5, 300, 400));
                                image.Save<Rgba32>(fileSaveLMUrl, imageEncoder);
                            });

                           
                        }
                    }

**Comment by antonfirsov** [comment]
So you mean file size. It wasn't clear from your original post, "image size" usually means image dimensions. 

By applying filters like blackwite or grayscale, you are loosing information, and jpeg is a compressed format, so it works as expected.

Do you also get a 4x smaller file size after applying AutoOrient (without doing a resize)? Can you share a sample image reproducing the issue?
Can you also explain why is this an issue in your application? Is the image quality insufficient?

**Comment by cemalpolat** [comment]
sure

**Comment by cemalpolat** [comment]
on min, please I am installing visual studio preview.  Later on, I will send you both the source image and the output image.

**Comment by tocsoft** [comment]
You seem to keep describing what your seeing not what the problem is.. basically we need to know why a 1mb file is wrong. 

As far as I can see you are taking an image, resizing it so that it 4 times less the number of pixels and are confused about the fact you are getting an image out that's 4 times smaller, personally that's an outcome I would be hoping for.

**Comment by cemalpolat** [comment]
I guess you need to deal with it. As I have mentioned before. When somehow an image is resized by c# in windows machine I mean visual studio and when we did a save this resized Image directly, Like img.Save(....) , this problems comes out. So it was a long time ago, as I remember, my solution was, to read and write with byte arrays using filestream objects. So my opinion, the problem is not coming from your code but you need to handle this problem. I will share with you the details.

**Comment by JimBobSquarePants** [comment]
We need to deal with nothing. Our operations work well. You STILL haven't described why 1mb is wrong.

**Comment by cemalpolat** [comment]
Because I did not resize . ıt should be the same size 
//x.Resize(image.Width / 2, image.Height / 2);  it is only comment

**Comment by cemalpolat** [comment]
4.30 MB the source the destination is less than 1mb without resizing

**Comment by tocsoft** [comment]
All that means is you have likely used a better/higher compression ratio than the original source image. Unless the output actually looks wrong to a human eye then it's doing exactly the right thing.

**Comment by cemalpolat** [comment]
the output looks exactly like the source. Only the source is 4.30 MB output is something like 800kb
The properties of output are similar to the source but the size is different. In 10 min I can share proper code and related images . Give me time please I will be more clear.

**Comment by tocsoft** [comment]
Then well done you have successfully used imagesharp, and we have saved you alot of space. Your welcome.

That's exactly the output imagesharp is trying to accomplish.

**Comment by cemalpolat** [comment]
👍 :)

**Comment by cemalpolat** [comment]
public IActionResult OnPost()
        {
            if (MyFiles.Count > 0)
            {
                foreach (IFormFile fl in MyFiles)
                {
                    FileInfo flInfo = new FileInfo(fl.FileName);
                    string getExt = flInfo.Extension.ToLower();
                    string newFileName = RandomString(5) + getExt;
                    string fileSaveUrl = Path.Combine(TempUploadFolderPath, newFileName);

                    using (var memoryStream = new MemoryStream())
                    {
                        fl.CopyTo(memoryStream);
                        using (Image<Rgba32> image = Image.Load<Rgba32>(memoryStream.ToArray()))
                        {
                            image.Mutate(x =>
                            {
                                image.Save<Rgba32>(fileSaveUrl);
                            });
                        }
                    }

                }

                return null;
            }
            else
            {
                Message = "File not selected";
            }
            return null;
        }

**Comment by cemalpolat** [comment]
source image is 2.24 MB
otput image is  474KB

**Comment by cemalpolat** [comment]
If I use  IImageEncoder like

                            IImageEncoder imageEncoder = new JpegEncoder()
                            {
                                Quality = 90,
                                Subsample = JpegSubsample.Ratio444
                            };

                            image.Mutate(x =>
                            {
                                image.Save<Rgba32>(fileSaveUrl, imageEncoder);
                            });

**Comment by antonfirsov** [comment]
1. Images please.
2. Explain please: why is this behavior wrong for you? It's a good thing to have smaller files.

**Comment by cemalpolat** [comment]
source still the same 2.24MB  
the output image is 1.06MB     better but not similar. I can understand because it passes through jpeg compression but still the difference is big. Still, I think this is the windows issue.  Would be nice to handle.
Thank you very much for your patience. I continue to follow you. Have fun

**Comment by cemalpolat** [comment]
Consider I bought 1 kg apple in the market at home it becomes 300 gr .:) or reverse it at home you produce 1Kg apple when you arrived at the market you have 250 gr to sell... It is ok not much important.  Only sounds a bit not natural. :)

**Comment by JimBobSquarePants** [comment]
The difference is staring you in the face. You've clearly demonstrated what affects the output size.

Your input images are probably saved at 100 quality, you're saving at 75 and then 90. This changes the way the quantizer within jpeg uses colors and sampling and can cause a massive drop in image size with very little difference in quality. Something you could have easily researched. It's all on Wikipedia for example. 

Now....

I need you to stop posting here. This is an issue tracker, for real issues not a forum for you to discuss your fantastical ideas. We have clear guidelines which you obviously ignored. If you continue to waste our time you will be blocked. Do you understand?

**Comment by cemalpolat** [comment]
I did s simply a joke base on  your answer(--Explain please: why is this behavior wrong for you? It's a good thing to have smaller files.) 
But still the question is there (--Your input images are probably saved at 100 quality, you're saving at 75 and then 90. This changes the way the quantizer ....)
In the code, I have an example which saves the image without defining the quality and in another example with defining the quality. The output is not similar but in both, the output is not the correct size.
My purpose is trying to understand your library and use it. Because I have found it brilliant. Also, I have shared the issue  I have faced.  For the purpose to help for improving.  Sorry for the joke.
The issue is still there...

**Comment by tocsoft** [comment]
@cemalpolat what we are trying to tell you is there is no issue... the library is working as designed you feed it an image (that may or may not have been previously saved in a optimised fashion) you then save it and we do all the optermisation on the image we can to reduce file size (thus we actually reduce the size significantly), unless there is actual issue with the visual output of the image then we have done our jobs very well and there is no issue/bug.

As ee are getting no where repeating the fact that saving a file and reducing the size with out effecting the visual quality is a good thing i'm locking this thread.
