### ISSUE TITLE
Image.Load(Span<byte> data) overload please!

### ISSUE THREAD

**Issue by jherby2k** [SixLabors/ImageSharp#489]
Simple feature request... since you guys are using System.Memory extensively, how about supporting it from the API? I'd really like to be able to pass in a Span of bytes directly to Image.Load without having to allocate an array.

**Comment by JimBobSquarePants** [comment]
Hi @jherby2k 

We can probably do that yes but please in future use the Gitter channel to discuss feature request as described in the contribution guidelines.

**Comment by jherby2k** [comment]
Thanks and sorry about that!

**Comment by JimBobSquarePants** [comment]
No worries, it's just I get the fear every time someone opens up an issue 😨

**Comment by antonfirsov** [comment]
@jherby2k we got it in with #567. Check out beta4!

For future planes see #565.
