### ISSUE TITLE
image.MetaData.HorizontalResolution is not correct, returns 1, and file properties shows 96

### ISSUE THREAD

**Issue by steven-gong** [SixLabors/ImageSharp#490]
### Prerequisites
- [v] I have written a descriptive issue title
- [v] I have verified that I am running the latest version of ImageSharp
- [v] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [v] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I'm using the imagesharp to load a test image, and validate its resolution, however the tested image got both vertical and horizontal resolutions are 96, but the loaded image MetaData resolutions by ImageSharp are 1, which is expected to be 96.

### Steps to Reproduce
var fileStream = new FileStream("96Resolution.jpg", FileMode.Open);
IImageFormat format;
var image = Image.Load(fileStream, out format);
if (image.MetaData.HorizontalResolution < 72){ .... }

Here image.MetaData.HorizontalResolution = 1
Just attached my test image. 
![invalidresolution](https://user-images.githubusercontent.com/21999878/37504072-fe3368b2-2940-11e8-9873-71025abdc168.jpg)

### System Configuration
- ImageSharp version: 1.0.0-beta0002
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): Windows10, Visual Studio 2017
- .NET Framework version: .NetCore 2.0
- Additional information:

**Comment by JimBobSquarePants** [comment]
Hi @steven-gong 

Can you please try this again using the issue template. We cannot accept issues without them

**Comment by JimBobSquarePants** [comment]
Thanks, that's much better!

Can you test the image against the latest build. I'm fairly certain we fixed this since beta 2

Cheers

James

**Comment by NickyM** [comment]
This bug is present in both beta 3 and beta 4.

Using this image:
![aa834718-85e0-43e8-91d3-fc3722f6c7b8](https://user-images.githubusercontent.com/1043625/41484793-73b0a4c6-70de-11e8-9d3b-bcf712603453.jpg)

And this code:
```
using (var image = Image.Load(filePath))
{
    var size = image.Size();
    toReturn.Image_Height = size.Height;
    toReturn.Image_Width = size.Width;

    toReturn.Image_HorizontalResolution = image.MetaData.HorizontalResolution;
    toReturn.Image_VerticalResolution = image.MetaData.VerticalResolution;
}
```

**Comment by JimBobSquarePants** [comment]
Hey @steven-gong @NickyM 

I've introduced #649 to improve resolution handling within the library. Once merged you'll also know what unit of measurement is used when querying resolution metadata. 

Explorer is talking absolute nonsense for both the images in this issue.
