### ISSUE TITLE
Converting png to jpeg produces poor image

### ISSUE THREAD

**Issue by MartinDawson** [SixLabors/ImageSharp#502]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

Their are relevant issues regarding this but it seems not to have fixed my issue. I.E issue [355](https://github.com/SixLabors/ImageSharp/issues/355)

### Description
When converting an image from png to jpeg it produces a weird/broken looking image. jpeg to jpeg works fine.

### Steps to Reproduce
```
public Stream ResizeImage(Stream stream, Size size)
{
    var image = Image.Load(stream);
    var resizeOptions = new ResizeOptions { Size = size, Mode = ResizeMode.Stretch };
    var resizedImage = image.Clone(x => x.Resize(resizeOptions).BackgroundColor(Rgba32.White));
    var newStream = new MemoryStream();

    resizedImage.SaveAsJpeg(newStream);

    newStream.Position = 0;

    return newStream;
}
```

### System Configuration
- ImageSharp version: 1.0.0-beta0002
- Other ImageSharp packages and versions: N/A
- Environment (Operating system, version and so on): windows 7
- .NET Framework version: ASP.net core version 2
- Additional information: This is happening for all of the pngs.

Original png and the resized jpeg:

<a href="https://imgbb.com/"><img src="https://image.ibb.co/j96bkS/original_f12d7ce0_2455_4613_9e9b_725935ca88b5.png" alt="original_f12d7ce0_2455_4613_9e9b_725935ca88b5" border="0"></a>
<a href="https://imgbb.com/"><img src="https://image.ibb.co/eF7hQS/original_f12d7ce0_2455_4613_9e9b_725935ca88b5_310x200.jpg" alt="original_f12d7ce0_2455_4613_9e9b_725935ca88b5_310x200" border="0"></a>

**Comment by antonfirsov** [comment]
The default jpeg quality is 75:
/SixLabors/ImageSharp/blob/master/src/ImageSharp/Formats/Jpeg/JpegEncoder.cs

You can change it to 100 on a new `JpegEncoder` instance and passing it to `image.Save()`. Does this help? (Remember: jpeg is a lossy format!)

**Comment by antonfirsov** [comment]
Also:
`image.Mutate(x => x.BackgroundColor(Rgba32.White));`
doesnt this eliminate the backround artifact?

**Comment by MartinDawson** [comment]
@antonfirsov `Mutate` instead of Clone worked. Thanks.

**Comment by antonfirsov** [comment]
@MartinDawson sorry, I missed that you actually called `.BackgroundColor()`. Also remember to dispose your images!

@JimBobSquarePants there might be an actual `.Clone()` bug lurk in there, we should probably investigate this further.

**Comment by JimBobSquarePants** [comment]
What about the nightlies? We can't really investigate anything from the old beta until we know it's also broken in the nightlies.
