### ISSUE TITLE
DDS/DXT/BC support?

### ISSUE THREAD

**Issue by Krakean** [SixLabors/ImageSharp#503]
Is there any plans to add support for DDS/DXT1-3-5/BC6-7?

**Comment by JimBobSquarePants** [comment]
Check out the pixel formats. Off the top of my head Alpha8 and Rgb565 cover some of that. https://github.com/SixLabors/ImageSharp/tree/master/src/ImageSharp/PixelFormats

P.S please don’t use the issue tracker for questions. We have a Gitter channel for that.

**Comment by dlemstra** [comment]
If you need support for those formats at the moment you might want to take a look at my project: https://github.com/dlemstra/Magick.NET.
