### ISSUE TITLE
DrawText is broken in last version (1.0.0-beta0003)

### ISSUE THREAD

**Issue by lukapor** [SixLabors/ImageSharp#508]
I using DrawText for avatar image. With new version i can not get initials on avatar image

I downloaded latest source code. And run DrawAB() test. Produced image was not expected see attachment file
![ab](https://user-images.githubusercontent.com/3388840/38016374-147db9d8-326f-11e8-9119-fc2052509f4c.png)

**Comment by JimBobSquarePants** [comment]
Please use the issue template
