### ISSUE TITLE
Compiling against net451 has multiple errors that are not there for netstandard2.0

### ISSUE THREAD

**Issue by stevehipwell** [SixLabors/ImageSharp#513]
### Description
When compiling against net451 I get multiple errors that are no present when compiling against netstandard2.0.

### Steps to Reproduce
The following line will error when compiling against net451.
```
var image = Image.Load(filePath);
```

### System Configuration

- ImageSharp version: 1.0.0-beta0003
- Other ImageSharp packages and versions: n/a
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: All
- Additional information: n/a

**Comment by iamcarbon** [comment]
The .NETStandard 1.1 target utilized for NET451 is missing some file APIs that you are trying to use.

Are you able to target .NET461?

**Comment by JimBobSquarePants** [comment]
Yeah, that’s not a bug. We also even show in the example code in the readme that the File API overload requires netstandard 1.3+

**Comment by stevehipwell** [comment]
Can you explain why you can't target net451? Usually any code that compiles for netstandard2.0 will also compile against net451!

**Comment by iamcarbon** [comment]
.NET 4.5.1 was released in 2013 and is no longer supported by Microsoft.  Is there a reason you are unable to target a higher framework version?

**Comment by JimBobSquarePants** [comment]
![net standard](https://files.gitter.im/ImageSharp/General/vrhC/Screen-Shot-2018-03-28-at-2.38.02-PM.png)

**Comment by antonfirsov** [comment]
@stevehipwell just take a stream using `File.OpenRead()` and pass it to `Image.Load(...)`.

@JimBobSquarePants on one hand, I really really want to get rid of NET Standard 1.1, but on the other hand there are so many large enterprises having stupid IT limitations keeping them in the stone age. I really wish we knew how many users do we have amongst such companies. @stevehipwell is this your case? 😄

**Comment by stevehipwell** [comment]
@JimBobSquarePants - The reason a lot of projects target net451 as well as netstandard2.0 is that although you need net461 for netstandard2.0 the API surface for net451 is almost identical to netstandard2.0 and in most cases you will be able to target net451 without any code changes. 

@antonfirsov - For me the two required targets would be net451 and netstandard2.0. The net451 target would allow us to keep supporting customers on Windows Server 2008 with extended maintenance. The netstandard2.0 target would be for for new development.

@both - My personal opinion is that .NET Standard versions earlier than 2.0 are at best confusing. Based on the above grid, my suggestion would be to target netstandard2.0, netstandard1.2 and net451. This would not only give multiple targets but the available methods would be based on capability and not the arbitrary .NET Standard versions.

**Comment by JimBobSquarePants** [comment]
@stevehipwell You do understand with an explicit `451` target you're asking us to target a brand new library against an obsolete framework with no security updates available?

**Comment by stevehipwell** [comment]
@JimBobSquarePants - Targeting net451 will allow better support for .NET 4.5.1, .NET 4.6, Mono 4.6 to 5.2. If you can target net451 I don't see the problem in doing so as the framework choice is down to the package consumers who might have a valid reason for requiring net451 (e.g. Windows Server 2008).

**Comment by JimBobSquarePants** [comment]
@stevehipwell 

>Targeting net451 will allow better support for .NET 4.5.1, .NET 4.6, Mono 4.6 to 5.2. 

All of those frameworks are supported by Net Standard 1.1 

I think you are failing to understand exactly what a standard is. I suggest you look again at the picture I posted above.

>I don't see the problem in doing so as the framework choice is down to the package consumers who might have a valid reason for requiring net451 (e.g. Windows Server 2008).

You might not see a problem but I most definitely do. 

Targeting .NET 4.5.1:
- Adds complexity to the build
- Can severely limit future development
- Means that I am now referencing unsupported binaries that may well contain security issues.

And for what? So you can avoid using a FileStream in your consuming code and support an operating system that has another 1 1/2 years of support?

There's a sense of entitlement here I am detecting that I find deeply unpleasant. You are asking me to do what a soon to be trillion dollar company will not and cannot do. 

I'm going to lock this issue now and I suggest you have a good think about your attitude towards open source.
