### ISSUE TITLE
Reached end of stream before proceeding EOI marker!

### ISSUE THREAD

**Issue by mabead** [SixLabors/ImageSharp#517]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Calling Image.Load results in exception.

### Steps to Reproduce

With 1.0.0-beta0003, calling Image.Load on the attached file throws the following exception:

```
SixLabors.ImageSharp.Formats.Jpeg.GolangPort.Components.Decoder.EOFException
  HResult=0x80131500
  Message=Reached end of stream before proceeding EOI marker!
  Source=SixLabors.ImageSharp
```

[REPRO copy.zip](https://github.com/SixLabors/ImageSharp/files/1892442/REPRO.copy.zip)

### System Configuration

- ImageSharp version: 1.0.0-beta0003
- Environment: Windows
- .NET Framework version: dotnet core 2.0.5

**Comment by JimBobSquarePants** [comment]
Hey @mabead can you please use the issue template for opening issues. Thanks!
