### ISSUE TITLE
Bad RST marker

### ISSUE THREAD

**Issue by mabead** [SixLabors/ImageSharp#518]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Loading image throws exception.

### Steps to Reproduce
With 1.0.0-beta0003, calling Image.Load on the attached file throws the following exception:

```
SixLabors.ImageSharp.ImageFormatException
  HResult=0x80131500
  Message=Bad RST marker
  Source=SixLabors.ImageSharp
```

[25.zip](https://github.com/SixLabors/ImageSharp/files/1892447/25.zip)

### System Configuration

- ImageSharp version: 1.0.0-beta0003
- Environment: Windows
- .NET Framework version: dotnet core 2.0.5

**Comment by JimBobSquarePants** [comment]
Fixed with #571

**Comment by softsprocket** [comment]
Do you have an idea when the nuget will be updated? Thanks.

**Comment by JimBobSquarePants** [comment]
Last week

**Comment by softsprocket** [comment]
Ah right. I had to check 'Include prerelease' to see the update. Sorry (and thanks).

**Comment by JimBobSquarePants** [comment]
No worries, hopefully not too long before we can do a release proper.
