### ISSUE TITLE
Unable to cast object of type 'System.Int16[]' to type 'System.Int16'

### ISSUE THREAD

**Issue by mabead** [SixLabors/ImageSharp#520]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description 
Loading image and then trying to resize it and saving as jpeg throws exception.

### Steps to Reproduce
With 1.0.0-beta0003, calling the following code:

```
            using (var image = Image.Load(sourceStream))
            using (var outputFile = File.OpenWrite(target))
            {
                image.Mutate(ctx => ctx.Resize(newWidth, newHeight));
                image.SaveAsJpeg(outputFile);
            }
```
on this image [mag.zip](https://github.com/SixLabors/ImageSharp/files/1892472/mag.zip) results in this exception:

```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'System.Int16[]' to type 'System.Int16'.
  Source=SixLabors.ImageSharp
  StackTrace:
   at SixLabors.ImageSharp.MetaData.Profiles.Exif.ExifWriter.WriteValue(ExifDataType dataType, Object value, Byte[] destination, Int32 offset)
   at SixLabors.ImageSharp.MetaData.Profiles.Exif.ExifWriter.WriteHeaders(Collection`1 indexes, Byte[] destination, Int32 offset)
   at SixLabors.ImageSharp.MetaData.Profiles.Exif.ExifWriter.GetData()
   at SixLabors.ImageSharp.Formats.Jpeg.GolangPort.JpegEncoderCore.WriteExifProfile(ExifProfile exifProfile)
   at SixLabors.ImageSharp.Formats.Jpeg.GolangPort.JpegEncoderCore.WriteProfiles[TPixel](Image`1 image)
   at SixLabors.ImageSharp.Formats.Jpeg.GolangPort.JpegEncoderCore.Encode[TPixel](Image`1 image, Stream stream)
```

### System Configuration

- ImageSharp version: 1.0.0-beta0003
- Environment: Windows
- .NET Framework version: dotnet core 2.0.5

**Comment by mabead** [comment]
@JimBobSquarePants I am really sorry, I am currently fixing the 4 issues that I have opened.

**Comment by mabead** [comment]
@JimBobSquarePants I have just the 5 issues that I just opened. Sorry again, there's no good excuse for what I just did. 

If I can try to be positive after my mistake, note that I processed 49024 files today with ImageSharp and only these 5 issues poped-up on about 50 files out of this big lot.

**Comment by JimBobSquarePants** [comment]
@mabead Thanks for fixing the issues, I appreciate it! 👍 

That's not a bad stat! Hopefully we can figure out what causes the issues quite swiftly and get a fix. The jpeg decoding one's will probably be the most difficult. EXIF, I'm sure we can handle easily enough.

**Comment by dlemstra** [comment]
@JimBobSquarePants This is now also "fixed" because we swapped the JPG decoder.
