### ISSUE TITLE
Unable to cast object of type 'System.UInt32' to type 'SixLabors.ImageSharp.Primitives.Rational'

### ISSUE THREAD

**Issue by mabead** [SixLabors/ImageSharp#521]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description 
Loading image throws exception.

### Description
With 1.0.0-beta0003, calling Image.Load on the attached file throws the following exception:

```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'System.UInt32' to type 'SixLabors.ImageSharp.Primitives.Rational'.
  Source=SixLabors.ImageSharp
  StackTrace:
   at SixLabors.ImageSharp.Formats.Jpeg.GolangPort.OrigJpegDecoderCore.InitDerivedMetaDataProperties()
   at SixLabors.ImageSharp.Formats.Jpeg.GolangPort.OrigJpegDecoderCore.ParseStream(Stream stream, Boolean metadataOnly)
   at SixLabors.ImageSharp.Formats.Jpeg.JpegDecoder.Decode[TPixel](Configuration configuration, Stream stream)
   at SixLabors.ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration config, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load(Stream stream)
```
[7696FE96-7ED0-4D97-B98A-411BC881F9B3.zip](https://github.com/SixLabors/ImageSharp/files/1892486/7696FE96-7ED0-4D97-B98A-411BC881F9B3.zip)

### System Configuration

- ImageSharp version: 1.0.0-beta0003
- Environment: Windows
- .NET Framework version: dotnet core 2.0.5

**Comment by mabead** [comment]
All the attached files also show the problem:
[527588FB-492F-4ED7-ACC9-3C3CA00D409E.zip](https://github.com/SixLabors/ImageSharp/files/1892491/527588FB-492F-4ED7-ACC9-3C3CA00D409E.zip)
[cover.zip](https://github.com/SixLabors/ImageSharp/files/1892492/cover.zip)
[Existence album art.zip](https://github.com/SixLabors/ImageSharp/files/1892493/Existence.album.art.zip)
[IMG_9697_polarr 2.zip](https://github.com/SixLabors/ImageSharp/files/1892494/IMG_9697_polarr.2.zip)
[Jordan_ProdbyKetch 4.0.jpg.zip](https://github.com/SixLabors/ImageSharp/files/1892495/Jordan_ProdbyKetch.4.0.jpg.zip)
[Landr-My Post (20).zip](https://github.com/SixLabors/ImageSharp/files/1892496/Landr-My.Post.20.zip)
[organica.zip](https://github.com/SixLabors/ImageSharp/files/1892497/organica.zip)
[remix singular c.zip](https://github.com/SixLabors/ImageSharp/files/1892498/remix.singular.c.zip)
[StrangerThings_KetchDaKid_4 2.zip](https://github.com/SixLabors/ImageSharp/files/1892499/StrangerThings_KetchDaKid_4.2.zip)
[The Day's Eye.zip](https://github.com/SixLabors/ImageSharp/files/1892500/The.Day.s.Eye.zip)
[visue 031.zip](https://github.com/SixLabors/ImageSharp/files/1892501/visue.031.zip)

**Comment by dlemstra** [comment]
@JimBobSquarePants I looks like this is issues is gone now we swapped the JPEG decoder.

**Comment by JimBobSquarePants** [comment]
@dlemstra  Yeah? I'll run some local tests to double check but that's great news. Thanks for checking.

**Comment by mabead** [comment]
@JimBobSquarePants @dlemstra is this bug really fixed? I just tried beta005 and I still have the issue with several images (ex: StrangerThings_KetchDaKid_4 2.zip).

**Comment by JimBobSquarePants** [comment]
I’ll have another look. The decoder itself is super solid now so it’ll be an issue with the EXIF parsing

**Comment by mabead** [comment]
I have tested ImageSharp with about 70k images submitted by our users and 18 images have this problem. Some of these images were already attached.

**Comment by JimBobSquarePants** [comment]
Should be fixed properly now. Other EXIF fixes will be in as soon as the CI build finishes.
