### ISSUE TITLE
Feature Request: Allow Argb32 as input for IPixel.From*.

### ISSUE THREAD

**Issue by woutware** [SixLabors/ImageSharp#532]
Currently there is an IPixel.FromRGBA(byte red, byte green, byte blue, byte alpha) method. The request is to add an FromARGB(uint argb) as well to be symmetric to the method above. This avoids overhead converting uint argb values to their 4 color components first.

Also: is it an idea to add a FromRGBA(uint rgba)? This would make RGBA -> RGBA very efficient rather than needing to decompose/compose the color components.

I've briefly talked it through with @JimBobSquarePants today.

I will implement the FromARGB(uint argb) myself shortly.

**Comment by JimBobSquarePants** [comment]
As discussed. We need to add the following to `IPixel`

```
PackFromArgb32(Argb32 source)

ToArgb32 (ref Argb32 dest) 
```

We also need to add the following to `PixelOperations<TPixel>`

```
PackFromArgb32(ReadOnlySpan<Argb32> source, Span<TPixel> destPixels, int count)

PackFromArgb32Bytes(ReadOnlySpan<byte> sourceBytes, Span<TPixel> destPixels, int count)

ToArgb32(ReadOnlySpan<TPixel> sourcePixels, Span<Argb32> dest, int count)

ToArgb32Bytes(ReadOnlySpan<TPixel> sourceColors, Span<byte> destBytes, int count)
```

**Comment by woutware** [comment]
Created pull request: https://github.com/SixLabors/ImageSharp/pull/540.

**Comment by woutware** [comment]
Alright, @mellinoe set me straight about the color component order: the color components are ordered from left to right -> least significant to most significant. For example Rgba will be stored with R as least significant byte and A as most significant, following the convention that DirectX does (which apparently is opposite to for example in System.Drawing.Color and CSS RGBA, from where my confusion about which order SixLabors is using stemmed).

So I'll just need conversion methods for Bgra32, which corresponds to the System.Drawing.Color Argb format.

**Comment by woutware** [comment]
I've added IPixel.PackFromBgra32 (corresponds to the System.Drawing.Color Argb format). Updated the .tt file as well and added a bit of textual clarification about the pixel format naming convention for pixel formats.

**Comment by JimBobSquarePants** [comment]
Closing this as it's now in the nightlies.
