### ISSUE TITLE
Porter-Duff enumaration split in two

### ISSUE THREAD

**Issue by vpenades** [SixLabors/ImageSharp#535]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Right now, the Porter-Duff blend modes enumeration is a plain list of modes, but I noticed that some of the enumerated values are in fact a combination of two effects.

I think the enumeration could be split in two enumerations:

```c#
enum ColorBlendMode
{
    Source,
    Destination,
    Multiply,
    Add,
    Substract,
    Screen,
    Darken,
    Lighten,
    Overlay,
    HardLight,
}
```
and
```c#
enum AlphaBlendMode
{
    Clear,
    Atop,
    Over,
    In,
    Out,
    Xor
}
```

This would cover all current blending options, plus new ones currently unavailable.

This would allow having blend modes like `Multiply + In` and `Multiply + Out` that are very useful for dropping inner/outer shadows and other kind of effects.

Normal blend mode would be `Source + Over`

### System Configuration

- ImageSharp version: Beta 3
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by JimBobSquarePants** [comment]
@vpenades  You definitely know a lot more about this than I do. Fancy giving a PR a go?

**Comment by vpenades** [comment]
@JimBobSquarePants Right now my hands are full at work and on another side project... maybe I could try to do something in two weeks if nobody else picks the task.

Just did a fast overview of the code, and it implies changing the T4 template generators so they can produce more pixel blender combinations.

**Comment by JimBobSquarePants** [comment]
Leave as much detail as you can here describing the required changes and we'll see what we can do.

A bit rushed myself just now so completely understand.

**Comment by vpenades** [comment]
@dlemstra I had to undo some of your changes in order to easily allow all combinations; right now I'm looking only for something that works, I'm open to improvements and optimizations.

@JimBobSquarePants @tocsoft let me know if you see something fishy; I know this part of the code is quite critical.
