### ISSUE TITLE
ImageFrameCollection.MoveFrame uses pre-removal index for insertion

### ISSUE THREAD

**Issue by Jjagg** [SixLabors/ImageSharp#538]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

[`ImageFrameCollection.MoveFrame`](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/ImageFrameCollection.cs#L111-L121) removes the frame at `sourceIndex`, then inserts that frame at `destIndex`. If `sourceIndex` comes before `destIndex`, the `destIndex` is a frame past what `destIndex` denoted before the removal. It seems more intuitive to me to have `destIndex` mean the index at the time of calling the function.

**Comment by Jjagg** [comment]
Just to help think about if the behavior I suggest is preferable, here's a small example.

If we assign letters to each frame - A for index 0, B for index 1... - we get
`A B C D E F` for an image with 6 frames before the move.

If we do `MoveFrame(2, 1)` we get `A C B D E F`.
If we do `MoveFrame(2, 4)` we get `A B D E C F`. Here C is inserted at what was originally index 5. I vouch for `A B D C E F` instead.

**Comment by JimBobSquarePants** [comment]
@dlemstra @antonfirsov @tocsoft Thoughts on this?

**Comment by tocsoft** [comment]
I think its right as it is. I would expect after calling `image.Frames.MoveFrame(2, 4)` to then be able to take a reference to that frame by calling `image.Frames[4]`. Basically the Api should do as I've told it make sure what ever is currently in frame position 2 make sure its in frame position 4. This works consistently then no mater weather the source frame is before or after to target location after the operation is complete is should be in the index I said and in a different one.

**Comment by dlemstra** [comment]
I have to agree with @tocsoft. If we tell it to move frame 2 to index 4 it should got to index 4 and not index 3.

**Comment by Jjagg** [comment]
No worries! Thanks for reviewing! :)
