### ISSUE TITLE
Avoid blending in FillProcessor and FillRegionProcessor when SolidBrush is used and add Image constructor that takes clear color parameter.

### ISSUE THREAD

**Issue by woutware** [SixLabors/ImageSharp#551]
From profiling in VS about 20-25% of cpu is spent in the FillRegionProcessor.OnFrameApply.

For SolidBrush and options.BlendPercentage == 1 (and brush alpha of 1?) it should avoid the expensive blending code path.

For the FillProcessor I was able to change OnFrameApply, for the FillRegionProcessor I'm going to need some help as there's too much there that I'm not familiar with.

```
Function Name	Total CPU [ms, %]	Self CPU [ms, %]	Module
| - SixLabors.Shapes.InternalPath::FindIntersections	81 (11,34%)	43 (6,02%)	SixLabors.Shapes.dll
| - SixLabors.ImageSharp.Processing.Drawing.Processors.FillRegionProcessor`1[SixLabors.ImageSharp.PixelFormats.Bgra32]::OnFrameApply	165 (23,11%)	21 (2,94%)	SixLabors.ImageSharp.Drawing.dll
| - SixLabors.Shapes.InternalPath::FindIntersection	13 (1,82%)	13 (1,82%)	SixLabors.Shapes.dll
```

Also it's good to have an image constructor that takes a clear color as parameter so clearing the buffer with zeroes can be avoided.

**Comment by JimBobSquarePants** [comment]
Merged so closing this. Thanks for the PR! 👍
