### ISSUE TITLE
JpgExport -> System.ArgumentOutOfRangeException: Index and count must refer to a location within the buffer. Parameter name: bytes

### ISSUE THREAD

**Issue by alex-birch** [SixLabors/ImageSharp#562]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Similar to [this](https://github.com/SixLabors/ImageSharp/issues/559) issue I raised yesterday but with a different stack trace (thanks for looking at it so quickly!). I'm using ImageSharp to open all these images from [mscoco](http://cocodataset.org/) - there are thousands of images and it's doing well on most of them.

Loading and export this image as a Jpg ByteArray causes the following stack trace (again, PNG works okay):

### Steps to Reproduce
![coco_val2014_000000260238](https://user-images.githubusercontent.com/4734530/39756400-cfdb786a-530c-11e8-9fb8-296a7f2429da.jpg)

`Unhandled Exception: System.ArgumentOutOfRangeException: Index and count must refer to a location within the buffer.
Parameter name: bytes
   at System.Text.UnicodeEncoding.GetString(Byte[] bytes, Int32 index, Int32 count)
   at SixLabors.ImageSharp.MetaData.Profiles.Icc.IccDataReader.ReadTextDescriptionTagDataEntry()
   at SixLabors.ImageSharp.MetaData.Profiles.Icc.IccDataReader.ReadTagDataEntry(IccTagTableEntry info)
   at SixLabors.ImageSharp.MetaData.Profiles.Icc.IccReader.ReadTagData(IccDataReader reader)
   at SixLabors.ImageSharp.MetaData.Profiles.Icc.IccProfile.InitializeEntries()
   at SixLabors.ImageSharp.MetaData.Profiles.Icc.IccWriter.Write(IccProfile profile)
   at SixLabors.ImageSharp.Formats.Jpeg.GolangPort.JpegEncoderCore.WriteIccProfile(IccProfile iccProfile)
   at SixLabors.ImageSharp.Formats.Jpeg.GolangPort.JpegEncoderCore.Encode[TPixel](Image`1 image, Stream stream)
   at WebApplicationBasic.Program.Main(String[] args) in Program.cs:line 17
`

I loaded the image and exported to JPG like so:
`            var img = SixLabors.ImageSharp.Image.Load<Rgba32>(args[0]);
            img.ToByteArray(new JpegEncoder());`

### System Configuration

- ImageSharp version:
SixLabors.ImageSharp 1.0.0-beta0003
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on):
MacOS High Sierra
- .NET Framework version:
Dotnet 2.1.3
- Additional information:

**Comment by JBildstein** [comment]
It's another invalid ICC profile. This time it's only one tag tough. The text description tag consists of three differently encoded texts. ASCII, Unicode and ScriptCode. In this case the ASCII part reports a string length of 33 while it's actually 43. Then the it tries to read the Unicode length which should be zero, but actually reads part of the previous text and returns a huge number.

I think I can add a safeguard around invalid tags like this by checking lengths against the tag size. If it's too big it'll stop trying to read the tag and report it as invalid or simply discard it.

**Comment by JimBobSquarePants** [comment]
@JBildstein If you were able to PR something that would be really useful. I still don't know the inner workings of ICC profiles yet to do a good job.

**Comment by JBildstein** [comment]
@JimBobSquarePants, sure, I'll try to implement both fixes this week.

**Comment by JimBobSquarePants** [comment]
You rock! 🤘
