### ISSUE TITLE
how to distort image with Four-Point

### ISSUE THREAD

**Issue by badmonkeyemail** [SixLabors/ImageSharp#564]
I have a rectangle picture(like 100*100),
I get 4 point, like (5,0), (80,10), (90, 88), (15, 75),
how to distort picture with imagesharp?

**Comment by JimBobSquarePants** [comment]
Hi @badmonkeyemail ,

Please use the gitter channel or stackoverflow for questions. The issue tracker is for issues only.

When asking a question can you please also provide enough information to answer. I have no idea what your expected result should be.

Cheers

James
