### ISSUE TITLE
Guy I want to combine two png images

### ISSUE THREAD

**Issue by diegogarciaa** [SixLabors/ImageSharp#566]
Guys I cannot find any example on how to combine two images.

I don't even know how to start.

**Comment by JimBobSquarePants** [comment]
Did you read the readme? The documentation linked from the repository root?

https://sixlabors.github.io/docs/articles/ImageSharp/GettingStarted.html

As written in the readme 

>- Do you have questions? We are happy to help! Please [join our gitter channel](https://gitter.im/ImageSharp/General), or ask them on [stackoverflow](https://stackoverflow.com) using the `ImageSharp` tag. **Do not** open issues for questions!
>- Please read our [Contribution Guide](https://github.com/SixLabors/ImageSharp/blob/master/.github/CONTRIBUTING.md) before opening issues or pull requests!

https://github.com/SixLabors/ImageSharp#questions
