### ISSUE TITLE
How to read/inspect pixel as CMYK?

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [SixLabors/ImageSharp#575]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I have a CMYK file that i would like to open and inspect it's pixels. Particularly i would like to calculate the sum of each part of the CMYK. So far, i've only able to read a pixel as RGBA... how can I load and read the pixels as CMYK?

PS: the original image has been created and save as CMYK

- ImageSharp version: LATEST
- Other ImageSharp packages and versions: LATEST
- Environment (Operating system, version and so on): MAC OS X / .NET CORE
- .NET Framework version: .NET CORE 2.1
- Additional information:

**Comment by antonfirsov** [comment]
@Leonardo-Ferreira unfortunately, there is no built-in way for this at the moment. We should provide a new [IPixel](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/PixelFormats/IPixel.cs) implemntation.

It's very easy to do a [RGB -> CMYK conversion](http://www.ginifab.com/feeds/pms/cmyk_to_rgb.php) in your application code however as a workaround.

**Comment by JimBobSquarePants** [comment]
@Leonardo-Ferreira @antonfirsov 

I do have a plan I want to enact which would allow loading a hole suite of new pixel formats. It might not make v1 though.

**Comment by JimBobSquarePants** [comment]
Ok.. With any of the latest [dev builds](https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp)  you can use the `SixLabors.ImageSharp.ColorSpaces.Conversion.ColorSpaceConverter` to bulk convert a span of `Rgba32` or `Rgb24` to `Cmyk` and back again.
