### ISSUE TITLE
BMP has alpha 0 instead of 255

### ISSUE THREAD

**Issue by tzachshabtay** [SixLabors/ImageSharp#581]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Same as this bug: https://github.com/SixLabors/ImageSharp/issues/369
(When opening a BMP image all pixels have an alpha value of 0 instead of 255 as with other BMP images.)
Looks like not all scenarios have been fixed for this?

### Steps to Reproduce

Load this image:
[eye.bmp.zip](https://github.com/SixLabors/ImageSharp/files/2018356/eye.bmp.zip)

### System Configuration

- ImageSharp version: 1.0.0-beta003
- Environment (Operating system, version and so on): Ubuntu 16.04 LTS 64bit
- .NET Framework version: Mono 5.10.1.20

**Comment by JimBobSquarePants** [comment]
I've checked this with beta 5 exporting at both 24 and 32 bit and the output is as expected with the correct alpha.

![bmp-compare](https://user-images.githubusercontent.com/385879/44027730-711b21b6-9eef-11e8-9fb1-cd87ace38644.JPG)
