### ISSUE TITLE
Brightness / Contrast 1.00001 too bright

### ISSUE THREAD

**Issue by jtorjo** [SixLabors/ImageSharp#586]
### Prerequisites

- [x] I have written a descriptive issue title (I hope :))
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I believe Brightness and Contrast - initial >1 values produce a too bright/contrast photo.

I'm not sure if this is the default behavior - I was just assuming linear values > 1 should generate slightly more bright/contrast . But from the original image (brightnes/contrast=1), just making that 1.00001 will generate a highly different photo.

I've also tried to use another pixel format (Arg32, Rgba64, Rgb24), but the same result happened.

### Steps to Reproduce

``` c#
Image<Rgba32> src_image;
using (FileStream stream = File.OpenRead(src_file_name))
    src_image = SixLabors.ImageSharp.Image.Load(stream);
src_image.Mutate( x => x.Brightness( 1.00001));
using (FileStream output = File.OpenWrite(dest_file_name_))
    dest_image.Save(output, new JpegEncoder()); 
```

### System Configuration

- ImageSharp version: 1.0.0.beta00003
- Other ImageSharp packages and versions: core 1.0.0-beta0005, Drawing: 1.0.0-beta0003
- Environment (Operating system, version and so on): Win10, Visual Studio 2017, v15.6.6
- .NET Framework version: 4.5.2
- Additional information:

**Comment by JimBobSquarePants** [comment]
Hi @jtorjo 

Could you please add an example of your expected output vs the actual?

**Comment by jtorjo** [comment]
@JimBobSquarePants 
http://phot-awe.com/test/
There are 3 files: the original, the one where you apply brightness 1.00001, the expected.
Thanks!
Best,
John

**Comment by JimBobSquarePants** [comment]
That's very odd. I'm not able to replicate the issue.

**Before**

![testeffects jpg medium](https://user-images.githubusercontent.com/385879/40354876-4b152864-5df8-11e8-8ce9-819f82dfe001.jpg)

**After**

![testeffects jpg medium](https://user-images.githubusercontent.com/385879/40354884-5062388e-5df8-11e8-96ec-6717ab0636b7.jpg)

**Comment by jtorjo** [comment]
@JimBobSquarePants Turns out I was an idiot again, sorry. Let me dig into this just a tad more

**Comment by jtorjo** [comment]
@JimBobSquarePants Embarassed, was a bug in my code. Sorry.

**Comment by JimBobSquarePants** [comment]
@jtorjo No worries, it happens. I'm just relieved! 😄
