### ISSUE TITLE
How to control the work-spacing when drawing text on a new image?

### ISSUE THREAD

**Issue by willhuo** [SixLabors/ImageSharp#592]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed]

### Description
I want to generate a captcha with imagesharp.
I use 4 characters to fill a black image(100*60).
I do not find some option to set the letter spacing

![hello](https://user-images.githubusercontent.com/15681218/40426165-f41b7cc2-5ecc-11e8-889a-3315f183772d.png)

**Comment by Gyroscope07** [comment]
I would also like to modify the character spacing, is this a current feature? or something that would need to be created?

**Comment by becket1337** [comment]
Any ideas on captcha, want to know also about it
