### ISSUE TITLE
How to draw another picture on a picture？

### ISSUE THREAD

**Issue by Antecer** [SixLabors/ImageSharp#602]
Hello, I just started to use this code base.
I can't use `image.Drawing()` , VS2017 tell me it is undefined.
So, how can i draw the picture on another picture?
I hope to get a sample code, thanks!

**Comment by antonfirsov** [comment]
@Antecer start here:
https://sixlabors.github.io/docs/articles/intro.html

You need the `.DrawImage()` extension method from the [Sixlabors.ImageSharp.Drawing](https://www.nuget.org/packages/SixLabors.ImageSharp.Drawing/1.0.0-beta0004) package.

Have a look at our ["draw a watermark on image" example](https://github.com/SixLabors/Samples/tree/master/ImageSharp).

Also:
ask questions [on our gitter channel](https://gitter.im/ImageSharp/General), our issue tracker is for issues only!
