### ISSUE TITLE
Equivalent to Bitmap.LockBits()

### ISSUE THREAD

**Issue by marcpabst** [SixLabors/ImageSharp#606]
I'm trying to replace System.Drawing in a project where I use LockBits():
````csharp
var data = bitmap.LockBits(
     new Rectangle(0, 0, clipWidth, clipHeight), 
     ImageLockMode.ReadWrite, 
     bitmap.PixelFormat);
````

Then I write to that bitmap using a native library. Is there any way to achive this with ImageSharp?

**Comment by antonfirsov** [comment]
@marcpabst  We plan to expose safe, and low level pixel manipulation API-s based on [`System.Memory` types `Span<T>` and `Memory<T>`](https://msdn.microsoft.com/en-us/magazine/mt814808.aspx?f=255&MSPPError=-2147217396), enabling interop scenarios like yours. See #565 for details.

Meanwhile you can use a temporary API for your own risk. *I'm about to deprecate it* as soon as the `Span<T>` / `Memory<T>` stuff get's into the final code:
```C#
using SixLabors.ImageSharp.Advanced;

using (Image<Rgba32> image = LoadMyImage())
{
    fixed (Rgba32* pixelPtr = &image.DangerousGetPinnableReferenceToPixelBuffer())
    {
        // interop code
    }
}
```

**Note 1:** this code is utilizing [`ref` locals](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/ref-returns)!

**Note 2:** The final `System.Memory` based version would look like this:
```C#
fixed (Rgba32* pixelPtr =&MemoryMarshal.GetReference(image.PixelMemory))
{
    // interop code
}
```

**Comment by JimBobSquarePants** [comment]
Hey @marcpabst 

Glad we were able to help you. Just a note to say would you please use the Gitter channel for future questions? We're trying to stay on top of the issue tracker here and limiting it to issues only. 😉 

Thanks!

**Comment by marcpabst** [comment]
Thanks for your help! I will absolutly use the Gitter channel in the future!
