### ISSUE TITLE
PNG loaded from PixelData is encoded incorrectly on beta0004

### ISSUE THREAD

**Issue by Inumedia** [SixLabors/ImageSharp#608]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Images loaded with `LoadPixelData<Argb32>` seem to get encoded incorrectly to PNG

### Steps to Reproduce
Use [test.bin](https://filebin.net/v0gfj2b0va5045f1/test.bin?t=hqsp12xj) as provided and execute code:
```
            byte[] pixels = File.ReadAllBytes("test.bin");
            int width = 875;
            int height = 888;

            using (Image<Argb32> img = Image.LoadPixelData<Argb32>(pixels, width, height))
            using (FileStream output = File.OpenWrite("test.png"))
                img.SaveAsPng(output);
```

Plain-text link for test.bin: `https://filebin.net/v0gfj2b0va5045f1/test.bin?t=hqsp12xj`

### System Configuration
Windows 10, .NET Standard 2.0

- ImageSharp version: v1.0.0-beta0004 (NuGet)
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: .NET Standard 2.0
- Additional information:

### Result
![result](https://user-images.githubusercontent.com/856822/41198374-d38ee76c-6c3e-11e8-8ad1-c01f8c1b928d.png)

### Expected
![expected](https://user-images.githubusercontent.com/856822/41198375-d3b498ae-6c3e-11e8-9176-5bad4e86c537.png)

**Comment by JimBobSquarePants** [comment]
I wonder... would creating a raw 1x1px Argb image and saving it do the same thing? Will help us rule out the load method then.

**Comment by Inumedia** [comment]
Closed as seems to be misunderstanding with DDS header of original file
