### ISSUE TITLE
Chamfering background image to match overlay

### ISSUE THREAD

**Issue by Hawxy** [SixLabors/ImageSharp#609]
### Description
So, I have two images,
[Base](https://i.imgur.com/bPVyXbh.png)
[Overlay](https://cdn.discordapp.com/attachments/421688545854619658/455032270957314049/ZDEF.png)

You can see on the overlay that the bottom left corner is chamfered, I'd like to apply the same chamfering to the base image so the image doesn't [bleed through in the corner.](https://i.imgur.com/FMdDTtk.png)

[Expected example output with a different overlay](https://cdn.discordapp.com/attachments/421688545854619658/455016916826849290/avatar.png)

I've taken a look at the examples and can see a way to make round corners, but am unsure how to create a straight cut. 

- ImageSharp version: 1.0.0-beta004
- Environment (Operating system, version and so on): .NET Core 2.1, Windows 10

**Comment by jongleur1983** [comment]
If you take the example with the Round Corners (see https://github.com/SixLabors/Samples/blob/master/ImageSharp/AvatarWithRoundedCorner/Program.cs ), all that should be necesssary is to change the IPathCollection created by "BuildCorners()"

If you read the BuildCorners method in there, you'd see that it returns a PathCollection of 4 paths.
In your case you'd need only one.

Each of those four paths's describes a rectangle "minus" an ellipse.
In your case you need only one single triangle, so BuildCorners would return a PathCollection containing a single Path that is a Triangle with the corners (0, height-triangleSize), (width, height), (triangleSize, height).
the mutation code applied in ApplyRoundedCorners stays the same.

**Comment by Hawxy** [comment]
Cheers! That's exactly the answer I was looking for.
