### ISSUE TITLE
Feature Request: Support for 16 Bit Greyscale PNG's 

### ISSUE THREAD

**Issue by bpopow** [SixLabors/ImageSharp#610]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Decoding 16-Bit Greyscale PNG's currently is not possible with imagesharp. This would be nice to have.

### Steps to Reproduce

Load an 16 Bit greyscale PNG, like the attached image:
![bit-depth-not-supported](https://user-images.githubusercontent.com/39404531/41235721-a7571640-6d8f-11e8-805b-ca023aab6334.png)

### System Configuration

- ImageSharp version: beta4
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): windows 10
- .NET Framework version:  does not matter
- Additional information:

image properties:
```
Properties:
    date:create: 2018-06-11T14:00:27+02:00
    date:modify: 2018-06-11T14:00:27+02:00
    png:IHDR.bit-depth-orig: 16
    png:IHDR.bit_depth: 16
    png:IHDR.color-type-orig: 0
    png:IHDR.color_type: 0 (Grayscale)
    png:IHDR.interlace_method: 0 (Not interlaced)
    png:IHDR.width,height: 772, 579
```

**Comment by JimBobSquarePants** [comment]
Hi @bpopow 

Thanks for this; yeah great suggestion! 

We should support these bit depths. We'll have to do some work first though. 

Currently we can decode 16 bit Rgb and Rgba pngs but we actually cheat when we do so and reduce the pixel data into an 8 bit equivalent. 

https://github.com/SixLabors/ImageSharp/blob/cdc63adb9469d4bc654601fe16398138c4c6ca50/src/ImageSharp/Formats/Png/PngDecoderCore.cs#L733

To do this properly we should probably add the API to convert to/from `Rgba64` and map these values. We'll eventually have to add write support also as there's no point having readonly data if we can't preserve it.

Will need some help doing this though, I'm a bit swamped with infrastructural work at the moment.

**Notes:** 
`Rgba64` conversion methods should be added to `IPixel`, the scaled vector methods should help us here with conversion.

Cheers

James
