### ISSUE TITLE
Fill processor- add a fast overload for clearing a bitmap

### ISSUE THREAD

**Issue by tzachshabtay** [SixLabors/ImageSharp#612]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

As discussed on the gitter channel, I would like to have an overload for the fill processor that clears a bitmap to a specific color (without region scanning and blending etc) -> i.e simply an overload which directly calls this: https://github.com/SixLabors/ImageSharp/blob/cdc63adb9469d4bc654601fe16398138c4c6ca50/src/ImageSharp/ImageFrame%7BTPixel%7D.cs#L306

### Steps to Reproduce

Current way to clear a bitmap:

```csharp

image.Mutate(x => x.Fill(new GraphicsOptions { BlenderMode = PixelBlenderMode.Src }, Brushes.Solid(color)));

```

This calls ShapeRegion.Scan which makes things slower than they can be.

**Comment by tocsoft** [comment]
That method doesn't call ShapeRegion at all. ShapeRegion will only be called if you pass in a Path to fill and that uses a different processor under the hood

**Comment by antonfirsov** [comment]
Double checked, `image.Mutate(c => c.Fill(color))` will call into the optimized path @JimBobSquarePants mentioned. @tzachshabtay I'm quite sure it must have been some other draw call in your benchmark reporting `ShapeRegion.Scan`.

I think we should close this issue.

**Comment by tocsoft** [comment]
@antonfirsov i'm pretty sure (from a gitter chat) it was a call to draw text that was the the reason for the scan calls, but they will soon be greatly reduced by the work in #614.
