### ISSUE TITLE
Use shared projects instead of the current setup

### ISSUE THREAD

**Issue by ststeiger** [SixLabors/ImageSharp#615]
A "feature" request: 
Would it be possible to use shared projects instead of the current projects ? 

So instead of
```
ImageSharp.Core
ImageSharp.Drawing
ImageSharp.Fonts
ImageSharp.Shapes
ImageSharp
```

```
ImageSharp.Core
 - References ImageSharp.Core.Shared 
ImageSharp.Drawing
- References ImageSharp.Drawing.Shared
ImageSharp.Fonts
- References ImageSharp.Fonts.Shared 
ImageSharp.Shapes
- References ImageSharp.Shapes.Shared 
ImageSharp
- References ImageSharp.Shared 
```
So we can create 
```
ImageSharp.AllInOne
- References ImageSharp.Core.Shared 
- References ImageSharp.Drawing.Shared
- References ImageSharp.Fonts.Shared 
- References ImageSharp.Shapes.Shared 
- References ImageSharp.Shared 
```

Also, that would make it possible to create projects for different framework versions without getting a very convoluted solution file. 
Also, this would allow for "static linking" of ImageSharp. 

Example of what I mean: 
[https://github.com/ststeiger/BlueMine](https://github.com/ststeiger/BlueMine)
(ImageSharpPacked subproject)

**Comment by tocsoft** [comment]
Hi @ststeiger thanks for the suggestion but this is not something we have any plans on doing.

We don't don't want the extra maintenance involved in this as its not a code sharing scenario we would ever recommend and instead recommend consuming our project via nuget. (thus no having any problems with convoluted solutions at all). If you are trying to do it to produce a single exe output there are other methods to do this, IL merge, etc.
