### ISSUE TITLE
Histogram Equalization

### ISSUE THREAD

**Issue by peter-bozovic** [SixLabors/ImageSharp#622]
### Description
I'm looking into how to enhance my images by using "Histogram Equalization".
ex: https://hypjudy.github.io/2017/03/19/dip-histogram-equalization/

Already using ImageSharp, but couldn't find any similar Filter.
Does something similar already exists but maybe called differently ?
And if not, are there any plans for this kind of filter to be implemented in ImageSharp in the future?

**Comment by JimBobSquarePants** [comment]
Hi @peter-bozovic 

There's nothing implemented just now, who knows in the future?

Please don't use the issue tracker for questions. We have a Gitter channel for such.

https://github.com/SixLabors/ImageSharp#questions

Cheers

James

**Comment by peter-bozovic** [comment]
Thanks for the reply,
Sorry about missing the gitter channel for questions ... Now I know.

**Comment by JimBobSquarePants** [comment]
@peter-bozovic It's been a long time but we now have several different histogram equalization options available withing the library. Check out the dev builds!
