### ISSUE TITLE
Remove Image<TPixel>.SavePixelData() api in favour of using Span<T>apis

### ISSUE THREAD

**Issue by tocsoft** [SixLabors/ImageSharp#623]
We should remove our  `Image<TPixel>.SavePixelData()` API and instead point the few people that would want access to the raw pixel data as a set of bytes over to using our Advanced apis and getting the pixel data as a byte array by calling

```c#
using SixLabors.ImageShape.Advanced

Image<Rgba32> image = ...;
byte[] byteArray = image.GetPixelSpan().ToArray();
```

I feel `Image<TPixel>.SavePixelData()` was more of a stop-gap until we where comfortable exposing the Span<T> apis.

**Comment by tocsoft** [comment]
@antonfirsov @JimBobSquarePants @dlemstra do you guys agree?

**Comment by JimBobSquarePants** [comment]
That works for me. We don’t want to be encouraging allocations by making it easy

**Comment by antonfirsov** [comment]
Makes sense, but we should be aware that we would be responsible supporting our users with all span-related stuff then.

Still unsure whether it's good or not. Definitely wouldn't do it without adding more explanatory docs on the pixel manipulation. We are [still lagging behind](https://sixlabors.github.io/docs/articles/ImageSharp/PixelManipulation.html) with that topic.
