### ISSUE TITLE
.Net 4.6.1 / .Net 4 Could not load file or assembly 'System.ValueTuple', Version=0.0.0.0

### ISSUE THREAD

**Issue by jeffreyleblanc225** [SixLabors/ImageSharp#626]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Request to add bindings for .Net framework 4.6.1 or .Net framework 4 (I'm targeting 4.6.1, running on 4)

I get this error:
  message: 'Could not load file or assembly \'System.ValueTuple, Version=0.0.0.0
, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51\' or one of its dependencies.
 The system cannot find the file specified.',
  name: 'System.IO.FileNotFoundException' }

### Steps to Reproduce

N/A

### System Configuration

Runtime machine: Windows Server 2012, .Net 4. On compiling machine: targeting 4.6.1
- ImageSharp version: Beta 4
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): Windows Server 2012
- .NET Framework version:, .Net 4.
- Additional information: Targeting 4.6.1, running on 4.

**Comment by antonfirsov** [comment]
@jeffreyleblanc225 we are supporting .NET 4.6.1 indirectly [by supporting .NET Standard 2.0](https://docs.microsoft.com/en-us/dotnet/standard/net-standard). In most cases this should work without any issues.

If you could investigate & post your NuGet dependencies + stack trace to this exception, maybe we can help tracing the root cause.

**Comment by antonfirsov** [comment]
> I'm targeting 4.6.1, running on 4

I missed this point in my previous reply. Does this mean is this mean that only 4.0 framework is installed on the target environment? Executing on a lower framework version is an unsupported scenario in .NET.

**Comment by mariansam** [comment]
If it doesn't find the System.ValueTuple assembly, try installing the [System.ValueTuple Nuget package](https://www.nuget.org/packages/System.ValueTuple/).

**Comment by JimBobSquarePants** [comment]
@mariansam That should be unnecessary.

@jeffreyleblanc225 Can you confirm that you are not trying to execute on a lower framework version than the target environment? I.E. Does it only have .NET 4.0 installed?
