### ISSUE TITLE
Support loading TGA format?

### ISSUE THREAD

**Issue by SamVanheer** [SixLabors/ImageSharp#629]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Would it be possible to add support for loading TGA files? I couldn't find any prior discussion about this so maybe it hasn't been discussed yet.

### System Configuration

- ImageSharp version: 1.0.0-dev001535
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): Windows 8.1 64 bit, running program as 32 bit
- .NET Framework version: Core 2.1
- Additional information:

**Comment by JimBobSquarePants** [comment]
Hi @SamVanheer 

No plans as yet, we're concentrating on common formats System.Drawing can open. Maybe post V1.

Cheers

James


P.S. Question on the Gitter channel please.

**Comment by brianpopow** [comment]
I would like to add support for TGA. Seems pretty similar to bitmap. I already have a branch where decoding for most of the TGA variations works with imagesharp. It just needs some refinement and unittests.

**Comment by brianpopow** [comment]
@JimBobSquarePants i think this can be closed now.

**Comment by Solokiller-GH** [comment]
I assume this is in reference to #1026? I can close it for you if you want.

**Comment by SamVanheer** [comment]
I assume this is in reference to #1026? I can close it for you if you want.

**Comment by brianpopow** [comment]
@SamVanheer yes that's what im referring to.

**Comment by SamVanheer** [comment]
Alright, closing this issue.
