### ISSUE TITLE
QuantizeProcessor does not use sourceRectangle

### ISSUE THREAD

**Issue by Jjagg** [SixLabors/ImageSharp#633]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Title says it all. The `OnFrameApply` method in [QuantizeProcessor](https://github.com/SixLabors/ImageSharp/blob/700548882f6656813a2b84df78bcd842025e14ae/src/ImageSharp/Processing/Quantization/Processors/QuantizeProcessor.cs#L36-L57) does not use the `sourceRectangle` it gets.

To resolve this the following methods need to support a `sourceRectangle`:
- `IFrameQuantizer<TPixel>.QuantizeFrame`
- `FrameQuantizerBase<TPixel>.FirstPass` and `SecondPass`

### System Configuration

- ImageSharp version: 0d179d624201d37d5b32d592eeda831bc12f01f3

**Comment by JimBobSquarePants** [comment]
I forgot we'd added this functionality. Closing now.
