### ISSUE TITLE
Optimize memory consumption of ResizeProcessor

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#642]
Currently we are using `O(NewWidth * SourceHeight)` memory for doing resize operations, however it's possible to do it consuming only `O(NewWidth * KernelDiameter)` memory, without significant negative effect on speed.

We need to implement a "sliding window" algorithm for this.

It will most likely fix issues like #597.

**UPDATE**
~The issue is now part of the epic #733.~

**UPDATE 2**
The ideas in #733 are abandoned now, we need to implement this with the current architecture.

**Comment by JimBobSquarePants** [comment]
@antonfirsov I'm assigning this one to you for now since you're more likely to get it right than me. Hoping someone from the community will step up though and give us a breather.
