### ISSUE TITLE
Allow passing custom Configuration instances to processors

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#650]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Problem
At the moment it's not possible to pass `Configuration` instances to image processors. We can't do this without changing the public API which means we need to act before RC1 is out. 

### Suggestion:
- `IImageProcessor<T>.Apply()` needs a `Configuration` argument
- `IImageProcessingContext<TPixel>` should hold a `Configuration` instead of `MemoryAllocator`
- We need overloads for `Mutate()` and `Clone()` taking a `Configuration`

**Comment by funcylambda** [comment]
@antonfirsov - Do you mind if I take this one to get my feet wet with ImageSharp? :)

**Comment by antonfirsov** [comment]
@funcylambda thanks volunteering, and sorry for the late reaction!

Actually, I received some critical voices on this proposal from @JimBobSquarePants  and @tocsoft, because it's possible to control the `Configuration` instances with the current API by binding them to `Image<T>` instances at initalization.

Their opinion is that it should be good enough for 1.0, mine is that we can add more flexibility with this feature. (`IImageProcessingContext<T>.Configuration` > `Image<T>.Configuration` > `Configuration.Default`)

I think a community PR won't do any harm here, because it won't distract the core team from our main priorities. @JimBobSquarePants @tocsoft thoughts?

**Comment by funcylambda** [comment]
@antonfirsov 

Cool, and no worries! I'm probably going to be refactoring some imaging code from an old C# library to ImageSharp at work (you have some good publicity going around thanks to a few bloggers!), so I thought it'd be good to give back as it were, and also learn a bit more about the library. If this isn't a good task, I do have some spare time this weekend so feel free to point me in the direction of another one :)

**Comment by funcylambda** [comment]
@JimBobSquarePants - Cool, I'll send a PR when it's done/message if I have any problems. Probably towards the end of Sunday.
