### ISSUE TITLE
Updating solution to dotnet core 2.1 is causing run-time issues with ImageSharp 

### ISSUE THREAD

**Issue by Felixking** [SixLabors/ImageSharp#653]
When loading an Image, I get the following exception:

```
Method not found: '!0 System.ReadOnlySpan`1.get_Item(Int32)'.","StackTrace":"   at SixLabors.ImageSharp.Formats.Bmp.BmpImageFormatDetector.IsSupportedFileFormat(ReadOnlySpan`1 header)\r\n   at SixLabors.ImageSharp.Formats.Bmp.BmpImageFormatDetector.DetectFormat(ReadOnlySpan`1 header)\r\n   at SixLabors.ImageSharp.Image.<>c__DisplayClass0_0.<InternalDetectFormat>b__0(IImageFormatDetector x)\r\n   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()\r\n   at System.Linq.Enumerable.TryGetLast[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)\r\n   at SixLabors.ImageSharp.Image.InternalDetectFormat(Stream stream, Configuration config)\r\n   at SixLabors.ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)\r\n   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Stream stream, Func`2 action)\r\n   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)\r\n   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Byte[] data)\r\n   at InMotion.ImageSharp.Service.ImageService.Resize(Byte[] data, Int32 width, Nullable`1 height, ThumbnailFormatTypes thumbnailFormatType)
```

What's strange is last week a colleague of mine ran into the same problem when adding a dependency to `System.Runtimg.Caching`. We ended up using a different library anyways and avoid that entirely. But now I'm upgrading our entire solution to dotnet core 2.1 and now this is back even without that dependency.

I am running `1.0.0-beta0001`. I tried upgrading to latest version `beta0004` to see if that resolves anything, but ran into problems where `Mutate` doesn't seem to exist as a method on the Image object and rolled back because there doesn't seem to be an alternative.

**Comment by antonfirsov** [comment]
@Felixking this is solved in beta4, and won't work with earlier versions because of API changes in `System.Memory`.

If you need help upgrading, please join [our gitter channel](https://gitter.im/ImageSharp/General) and ask your questions here! `Mutate()` is member of the `SixLabors.ImageSharp.Processing` namespace. Check out our [API docs](https://sixlabors.github.io/docs/api/index.html) for other specific processing extension methods.

**Comment by Felixking** [comment]
`beta0004` does the trick!
And resolved the Mutate issue by adding usings to the extension namespace. #LifeWithoutResharper

**Comment by antonfirsov** [comment]
@Felixking the library is quite stable for most cases, but there is still a lot to do before we can leave the pre-release state: https://github.com/SixLabors/ImageSharp/milestones

Eg. API changes, like simplification of namespeces to improve API discoverability for users without ReSharper :smile: (This is expected for beta5)
