### ISSUE TITLE
Hi guys. Is it possible to get frame of video with ImageSharp?

### ISSUE THREAD

**Issue by AwanesowArtem** [SixLabors/ImageSharp#658]
Hi guys. Is it possible to get frame of video with ImageSharp?

**Comment by tocsoft** [comment]
Questions should be directed to our gitter channel.

But to answer your question, No we don't support vide formats at all, the only file formats we support are JPEG, Bmp, Giff and Bmp.

**Comment by hey-red** [comment]
Maybe it will be interesting for people who came from search.
https://github.com/hey-red/ImageSharp.AVCodecFormats
But I didn't make any leaks test, use with careful.

**Comment by JimBobSquarePants** [comment]
@hey-red Nice!
