### ISSUE TITLE
How to set ETag or Last-Modified to Images that ImageSharp generates?

### ISSUE THREAD

**Issue by A-Programmer** [SixLabors/ImageSharp#659]
I am using ImageSharp for crop and resize on the fly in ASP.NET Core.
I have an API :
`[HttpGet("/image/{width:int:min(0)}/{height:int:min(0)}/{*url}")]
        public async Task<IActionResult> ResizeImage(string url, int width, int height)
        {
            if (width < 0 || height < 0 ) { return BadRequest(); }
            if (width == 0 && height == 0) { return BadRequest(); }

            var key = $"/{width}/{height}/{url}";
            var data = await _cache.GetAsync(key);
            if (data == null)
            {
                var imagePath = PathString.FromUriComponent("/" + url);  
                var fileInfo = _fileProvider.GetFileInfo(imagePath);  
                if (!fileInfo.Exists) { return NotFound(); }

                data = ips.CropResize(fileInfo,height,width);

                const int durationInSeconds = 60 * 60 * 24 * 7;
                ctx.HttpContext.Response.Headers[HeaderNames.CacheControl] =
                "public,max-age=" + durationInSeconds;
                var cacheEntryOptions = new DistributedCacheEntryOptions()
                .SetSlidingExpiration(TimeSpan.FromHours(7));
                await _cache.SetAsync(key, data,cacheEntryOptions); 
            }`
and i have a CropResiz method :
`public byte[] CropResize(IFileInfo fileInfo,int height,int width)
        {
            using (var outputStream = new MemoryStream())  
            {
                using (var inputStream = fileInfo.CreateReadStream())
                {
                    using (var image = Image.Load(inputStream))
                    {
                        var currentW = image.Width;
                        var currentH = image.Height;
                        if(currentW > currentH)
                        {
                            
                            image
                            .Resize(0,height);
                            var resizedW = image.Width;
                            var cropX = (resizedW / 2) - (width / 2);
                            var resizedH = image.Height;
                            var cropY = (resizedH / 2) - (height / 2);

                            image
                            .Crop(new Rectangle(cropX, cropY, width, height))
                            .SaveAsJpeg(outputStream,new JpegEncoder(){Quality = 80});
                        }
                        else
                        {
                            
                            image
                            .Resize(width,0);

                            var resizedW = image.Width;
                            var cropX = (resizedW / 2) - (width / 2);
                            var resizedH = image.Height;
                            var cropY = (resizedH / 2) - (height / 2);

                            image
                            .Crop(new Rectangle(cropX, cropY, width, height))
                            .SaveAsJpeg(outputStream,new JpegEncoder(){Quality = 80});
                        }
                    }
                }

                return outputStream.ToArray();
            }
        }`
Now it works fine, but the problem is when i check my website in GTmetrix.com i get Specify a cache validator error for this images.

Exactly images that i request by ImageSharp api.

Anybody can help me to know how can i specify cache validator to this images?

**Comment by JimBobSquarePants** [comment]
Please do not use the issue tracker for questions. We state very clearly in our readme that you should use the Gitter channel. 

I cannot even read your code properly as you haven’t bothered to format it but from what I can see your caching issue has nothing to do with the library!

Why are you reinventing the wheel anyway? We have provided a library for the web ImageSharp.Web. I suggest you use that.
