### ISSUE TITLE
[[Method not found: '!0 System.ReadOnlySpan`1.get_Item(Int32)'.]]:    at ImageSharp.Formats.BmpImageFormatDetector.IsSupportedFileFormat(ReadOnlySpan`1 header)

### ISSUE THREAD

**Issue by eat-sleep-code** [SixLabors/ImageSharp#663]
### Prerequisites

- [ X ] I have written a descriptive issue title
- [ X ] I have verified that I am running the latest version of ImageSharp
- [ X ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ X ] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The following error is suddenly being thrown using the latest version of ImageSharp as available in your nuget repository:

> [[Method not found: '!0 System.ReadOnlySpan`1.get_Item(Int32)'.]]:    at ImageSharp.Formats.BmpImageFormatDetector.IsSupportedFileFormat(ReadOnlySpan`1 header)
>    at ImageSharp.Formats.BmpImageFormatDetector.DetectFormat(ReadOnlySpan`1 header)
>    at ImageSharp.Image.<>c__DisplayClass0_0.<InternalDetectFormat>b__0(IImageFormatDetector x)
>    at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
>    at System.Linq.Enumerable.TryGetLast[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
>    at ImageSharp.Image.InternalDetectFormat(Stream stream, Configuration config)
>    at ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)
>    at ImageSharp.Image.WithSeekableStream[T](Stream stream, Func`2 action)
>    at ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)
>    at Brand.Extensions.ImageExtensions.ResampleImage(Stream sourceStream, String contentType, Double targetDPI) in C:\SRC\Main\Brand\Extensions\ImageExtensions.cs:line 42

### Steps to Reproduce
This is the offending code:

```
public byte[] ResampleImage(Stream sourceStream, string contentType, double targetDPI = 72)
		{
			MemoryStream outputStream = new MemoryStream();
			try
			{
				using (sourceStream)
				{
					Image<Rgba32> image = Image.Load(sourceStream);
					double currentDPI = image.MetaData.HorizontalResolution;
					double resizeRatio = targetDPI / currentDPI;
					int targetWidth = (int)Math.Round((image.Width * resizeRatio)); 
					int targetHeight = (int)Math.Round((image.Height * resizeRatio));
					image.MetaData.HorizontalResolution = targetDPI;
					image.MetaData.VerticalResolution = targetDPI;
					BicubicResampler resampler = new BicubicResampler();
					switch (contentType)
					{
						case "image/gif":
							GifEncoder gifEncoder = new GifEncoder();
							image.Resize(targetWidth, targetHeight, resampler, false).Save(outputStream, gifEncoder);
							image.SaveAsGif(outputStream);
							break;
						case "image/jpeg":
							JpegEncoder jpegEncoder = new JpegEncoder();
							image.Resize(targetWidth, targetHeight, resampler, false).Save(outputStream, jpegEncoder);
							image.SaveAsJpeg(outputStream);
							break;
						default:
							PngEncoder pngEncoder = new PngEncoder();
							image.Resize(targetWidth, targetHeight, resampler, false).Save(outputStream, pngEncoder);
							image.SaveAsPng(outputStream);
							break;
					}
				}
			}
			catch (Exception ex)
			{
				new LoggerExtensions().LogException(ex, "Image Extensions");
				return new byte[0];
			}
			return outputStream.ToArray();
		}
```

### System Configuration

- ImageSharp version: v1.0.0-alpha9-00194
- Other ImageSharp packages and versions: ImageSharp.Drawing v1.0.0-alpha9-00189
- Environment (Operating system, version and so on): Windows Server 2012 R2
- .NET Framework version: .NET Core 2.1.2
- Additional information:

**Comment by JimBobSquarePants** [comment]
> - [X] I have verified that I am running the latest version of ImageSharp

ImageSharp version: v1.0.0-alpha9-00194 is not the latest version by a long way. In fact, we never released any alphas on Nuget so the version you are using is not supported by us..

The latest release on Nuget is [beta4](https://www.nuget.org/packages/SixLabors.ImageSharp/1.0.0-beta0004
). Update to that version and your issue will go away.

**Comment by tocsoft** [comment]
also please ensure you do actually search issues because this same issue with System.Memory version miss matching has come up a few times now and the answer was to make sure your on the latest beta version where its already been resolved.

**Comment by eat-sleep-code** [comment]
Ok, did the Nuget repository move then?  Because the one I have been using shows no new versions.

**Comment by JimBobSquarePants** [comment]
You mean the MyGet repository for developmental build? That changed when the repository moved to the SixLabors organization. It's linked from the readme.

https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp

**Comment by antonfirsov** [comment]
@eat-sleep-code  please check our intro docs about our packages:
https://sixlabors.github.io/docs/articles/intro.html
