### ISSUE TITLE
nuget packages not found

### ISSUE THREAD

**Issue by seanrockster** [SixLabors/ImageSharp#669]
trying to add the nuget packages however SixLabors.ImageSharp is not found.

**Comment by tocsoft** [comment]
make sure your searching with "Include prerelease" checked as we are still in beta and have yet to release our first version.

**Comment by antonfirsov** [comment]
Related piece of docs:
https://sixlabors.github.io/docs/articles/intro.html

**Comment by JimBobSquarePants** [comment]
Always be using the issue template. Questions on Gitter please.
