### ISSUE TITLE
Question: Outer glow over text effect

### ISSUE THREAD

**Issue by nathan130200** [SixLabors/ImageSharp#670]
In ImageSharp can be possible DrawText and add outer glow/inner glow effect like in photoshop, and/or stroke effect? I don't found in docs and examples.

Edit1: I found how to create a stroke/outline, but nothing about glow.

**Comment by JimBobSquarePants** [comment]
Questions on the Gitter channel please. It’s clearly noted in the readme. Hint. If you’re deleting an issue template, you’re doing something wrong.
