### ISSUE TITLE
beta 5 converts 24-bit BMP to 32-bit PNG by default

### ISSUE THREAD

**Issue by jherby2k** [SixLabors/ImageSharp#672]
### Description
Since upgrading my project from beta4 to beta5, I've noticed that a 24-bit bitmap test image is now being saved to a 32-bit PNG. Its also bigger, as you'd expect. Previously it was saved as 24-bit. Saving to JPEG seems to work as before (though the file hash has changed somewhat).

### Steps to Reproduce
` using (var image = Image.Load(bmpStream))
     image.SaveAsPng(pngStream);`

### System Configuration
Windows 10 64-bit, .net core 2.1

**Comment by JimBobSquarePants** [comment]
This is by design and hasn’t changed.

The default png color mode has always been 32bit to support the alpha channel. If you want to save it as 24 bit you have to explicitly do so.

Jpeg doesn’t have an alpha channel so will always be 24 bit.

**Comment by antonfirsov** [comment]
@jherby2k in our current design `Image<T>` does not preserve the bit rate / color model of the original encoded data.

**Comment by jherby2k** [comment]
Thanks, my mistake on thinking this cropped up in beta 5… its clearly there in beta 4 as well.

Sent from Mail for Windows 10
