### ISSUE TITLE
In the SixLabors.ImageSharp.Web 1.0.0-beta0003 version bug

### ISSUE THREAD

**Issue by MonkSoul** [SixLabors/ImageSharp#674]
A change in the SixLabors.ImageSharp 1.0.0-beta0005 version

```
using S̶i̶x̶L̶a̶b̶o̶r̶s̶.̶I̶m̶a̶g̶e̶S̶h̶a̶r̶p̶.̶P̶r̶o̶c̶e̶s̶s̶i̶n̶g̶.̶T̶r̶a̶n̶s̶f̶o̶r̶m̶s̶; -> using SixLabors.ImageSharp.Processing;
```

but  the SixLabors.ImageSharp.Web 1.0.0-beta0003 version is not change

**Comment by JimBobSquarePants** [comment]
https://github.com/SixLabors/ImageSharp/releases/tag/v1.0.0-beta5

**Comment by antonfirsov** [comment]
The new ImageSharp.Web beta package will be released in the next few days.
