### ISSUE TITLE
Can't load bmp image with bit depth 1

### ISSUE THREAD

**Issue by KozakSergii** [SixLabors/ImageSharp#675]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I'm trying to load simple test image in bmp format with bit depth 1 and get following exception:

Unhandled Exception: SixLabors.ImageSharp.ImageFormatException: Bitmap does not have a valid format. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SixLabors.ImageSharp.Formats.Bmp.BmpDecoderCore.ReadRgbPalette[TPixel](Buffer2D`1 pixels, Byte[] colors, Int32 width, Int32 height, Int32 bits, Boolean inverted)
   at SixLabors.ImageSharp.Formats.Bmp.BmpDecoderCore.Decode[TPixel](Stream stream)
   --- End of inner exception stack trace ---

Image is loaded and processed with system.drawing without any problem

### Steps to Reproduce
using (var file = new FileStream("Black_125x125.bmp", FileMode.Open))
            using (var image = Image.Load(file))
            {
                Console.WriteLine(image.Height);
            }

### System Configuration

- ImageSharp version: 1.0.0-beta0005
- Environment (Operating system, version and so on): Windows 10
- .NET Core: 2.1

[Black_125x125.zip](https://github.com/SixLabors/ImageSharp/files/2274026/Black_125x125.zip)

**Comment by JimBobSquarePants** [comment]
We should check our implementation against the two decoders in Firefox and Chrome. I could do with help here as my C++ is not great.

https://chromium.googlesource.com/chromium/blink.git/+/master/Source/platform/image-decoders/bmp/BMPImageReader.cpp

https://dxr.mozilla.org/mozilla-central/source/image/decoders/nsBMPDecoder.cpp
