### ISSUE TITLE
Resize animated GIF ends up with larger file size

### ISSUE THREAD

**Issue by rayrfan** [SixLabors/ImageSharp#690]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I'm resizing an animated GIF shown below, the resized file ends up with larger file size. 

Original file: dimension: 500 x 225, file size: 443KB
Resized file: dimension: 400 x 180, file size: 539KB

Here is the gif I'm using

![leo](https://user-images.githubusercontent.com/633119/44940844-d0f88a80-ad48-11e8-985b-dff47aa5347d.gif)

### Steps to Reproduce

Here is my code

```c#
    using (var image = Image.Load(@"C:\leo.gif"))
    {
        image.Mutate(i => i.Resize(400, 0).Quantize());
        image.Save(@"C:\leo_resized.gif");
    }
```

One possibility is that when the image gets resized the number of colors in the image becomes higher, and when you quantize each individual frame you can reduce the number of colors.  Could someone help point out how to do that or what I'm missing please?  Thank you!

### System Configuration

- ImageSharp version: 1.0.0-beta0005
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): Windows 10, VS 2017 15.8.2
- .NET Framework version: netcoreapp2.1
- Additional information:

**Comment by JimBobSquarePants** [comment]
I see you didn’t try using a single palette. What is the output size when you use a new `GifEncoder` instance with `GifColorTableMode` set to `Global`?

**Comment by FanrayMedia** [comment]
@JimBobSquarePants Thank you so much.  In this case you gave 64 as the palette color and increasing or decreasing it will affect output file size, so generally speaking what is a good average value to give it here?

**Comment by JimBobSquarePants** [comment]
I chose 64 because that was the length of the input palette, most likely since the image is grayscale. We’ve chosen 255+transparency as the default because that covers most gifs.

**Comment by FanrayMedia** [comment]
@JimBobSquarePants Is there a way to find out the image input palette with code?  So that say in this case I get 64 returned so then I can give it to OctreeQuantizer constructor.
