### ISSUE TITLE
Option to only read metadata to get basic image information

### ISSUE THREAD

**Issue by Exocomp** [SixLabors/ImageSharp#703]
Is there an option to only read the image metadata (not the pixel data) to get basic image information? Obviously to improve performance when only basic info is needed.

**Comment by JimBobSquarePants** [comment]
Hi @Exocomp 

Yes, It's in the API docs linked from the readme. 

``` c#
var info = Image.Identify(Stream stream);
```

https://docs.sixlabors.com/api/ImageSharp/SixLabors.ImageSharp.Image.html#SixLabors_ImageSharp_Image_Identify_Stream_

There's additional format specific information available in the latest nightlies now too.

``` c#
var gifInfo = Image.Identify(Stream stream).MetaData.GetFormatMetaData(GifFormat.Instance);
var pngInfo = Image.Identify(Stream stream).MetaData.GetFormatMetaData(PngFormat.Instance);
var jpegInfo = Image.Identify(Stream stream).MetaData.GetFormatMetaData(JpegFormat.Instance);
var bmpInfo = Image.Identify(Stream stream).MetaData.GetFormatMetaData(BmpFormat.Instance);
```
Cheers

James

P.S Please do not use this issue tracker for questions; we need to keep it for issues only. There's a Gitter channel where you'll get plenty of help.

**Comment by Exocomp** [comment]
Excellent, thanks!  Whenever you guys get to it, I recommend including an example in the how to you guys have, it might be a common thing others might find helpful and easily find. Thanks again.
