### ISSUE TITLE
Loading and Writing this image as PNG results in some pixels not being equal

### ISSUE THREAD

**Issue by devedse** [SixLabors/ImageSharp#704]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When I Load and Save the attached Image some pixels get corrupted. This issue does not occur on version v1.0.0-dev001866, but it does occur on v1.0.0-dev001874:

![image](https://user-images.githubusercontent.com/2350015/45601933-27d2b500-ba15-11e8-956a-665987127bec.png)

![image](https://user-images.githubusercontent.com/2350015/45601935-2b663c00-ba15-11e8-92b1-db3d09f76f72.png)

Source image used for testing:
[versioning-1_2.zip](https://github.com/SixLabors/ImageSharp/files/2387091/versioning-1_2.zip)

### Steps to Reproduce

I used this unit test to test this code:
https://github.com/devedse/DeveImageOptimizer/blob/master/DeveImageOptimizer.Tests/VariousTests/OtherRandomFacts.cs#L87

### System Configuration

Fails on my local machine but also on my build server:
https://ci.appveyor.com/project/devedse/deveimageoptimizer/build/tests

- ImageSharp version: 1.0.0-dev001874
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): Win10
- .NET Framework version: .NET Core 2.0
- Additional information:

P.s. next to this test failing there's about 6 tests that previously worked that are now also failing. So it might be good to look into those as well.

**Comment by JimBobSquarePants** [comment]
I had a look at the tests and the image you supplied does not actually meet the png specification.

Here's what PNG Analyzer makes of your image:

![Invalid png with 573 colors in palette](https://user-images.githubusercontent.com/385879/45613110-1c0ae100-ba5d-11e8-8992-801f0d3cd344.png)

As you can see the image is an indexed image with 573 colors in the palette. I've highlighted below where it violates the specification.

>The PLTE chunk contains from **1 to 256** palette entries, each a three-byte series of the form:
>
> Red | 1 byte
> -- | --
> Green | 1 byte
> Blue | 1 byte
>
>The number of entries is determined from the chunk length. A chunk length not divisible by 3 is an error.
>
>This chunk shall appear for colour type 3, and may appear for colour types 2 and 6; it shall not appear for colour types 0 and 4. There shall not be more than one PLTE chunk.
>
>For colour type 3 (indexed-colour), the PLTE chunk is required. The first entry in PLTE is referenced by pixel value 0, the second by pixel value 1, etc. **The number of palette entries shall not exceed the range that can be represented in the image bit depth (for example, 24 = 16 for a bit depth of 4)**. It is permissible to have fewer entries than the bit depth would allow. **In that case, any out-of-range pixel value found in the image data is an error**.

https://www.w3.org/TR/2003/REC-PNG-20031110/#11PLTE

So... To explain why your images passed the test before. 

In **v1.0.0-dev001866**, when using the png encoder with no instruction as you do in your test.

```c#
img.SaveAsPng(fs)
```

We would have blindly encoded the image as 32bit true color. This would have preserved the invalid colors in your palette but you would no longer have had an indexed png and we would likely have created a larger image than required.

With **1.0.0-dev001874** that behaviour has changed as we can now track whether the image was decoded from an indexed png and use that information to ensure that we encode the image in the same color type. In this case we encode the image in conformance to the specification and max out at 256 colors. 

I believe that this is the correct thing to do. We preserve the integrity of spec compliant images and ensure we do not increase the size of the output compared to the input. We also supply the tools via the metadata information to allow you to make smart encoding decisions.

**Comment by devedse** [comment]
@JimBobSquarePants , I looked at this again and think you've overlooked one thing:

> As you can see the image is an indexed image with 573 colors in the palette. I've highlighted below where it violates the specification.

573 is actually divisible by 3. Which makes it 191 actual colors.

Can I re-open this issue?
