### ISSUE TITLE
ResizeProcessor crash on downsizing height on narrow image when trying to keep aspect ratio, provide safe way to downsize image when keeping ratio?

### ISSUE THREAD

**Issue by Davidsv** [SixLabors/ImageSharp#711]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When using image.Mutate(c => c.Resize(width, height)), the intention is that if either width or height is 0, the aspect ration will be kept. Inside ResizeProcessor constructor I see there is a condition if(width ==0 && height > 0) which then calculates a new width based on the aspect ratio by using this formula:

width = (int) MathF.Round((float) (sourceSize.Width * height) / (float) sourceSize.Height);

This works most of the time, however when downsizing very narrow images this formula will sometimes produce 0, and the next step in the constructor is a guard against 0 so it will throw ArgumentOutOfRangeException that width must be greater than 0.

### Steps to Reproduce
Take an image width 10 height 100.
call Image.Mutate(c => c.Resize(0, 5)) to try to change height to 5 while keep ratio.
Ratio will now be too small to keep so new width will be calculated to 0 and it will crash.
I think the generated width in this case should be always minimum 1 to avoid crash.
Technically it will not keep the aspect ratio but I think there should exist a safe way to downsize an image if the aspect ratio becomes impossible to keep. I was about to write bug report but I understand that this exception might be intended.

**Comment by JimBobSquarePants** [comment]
Hi @Davidsv 

I think this is a reasonable request. Aspect ratio, or closest possible to. Fancy creating a PR?

Cheers

James

**Comment by Davidsv** [comment]
@JimBobSquarePants I could. Should it be an option or always work like this when passing 0 to either dimension?

**Comment by JimBobSquarePants** [comment]
Always work like this I think. A simple `Math.Max(1, dimension)`.
