### ISSUE TITLE
ImageSharp "Does not support this kind of bitmap files"

### ISSUE THREAD

**Issue by wc-matteo** [SixLabors/ImageSharp#735]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Trying to open a specific bitmap file created with `Magick.NET` fails with an exception. Other files created in the same way don't.

Selecting `ImageMagick.MagickFormat.Bmp2` or `ImageMagick.MagickFormat.Bmp3` resolves the issue. The issue is with `ImageMagick.MagickFormat.Bmp` specifically, which uses, according to the docs, version 4 of the format.

The image in question _does_ open without issues in other Windows programs (Paint, Photos, Photoshop) and Dropbox.

### Steps to Reproduce
Download the [file](https://www.dropbox.com/s/i3git6ovot9mp3a/bitmap.bmp?dl=0).

Try to open it:

```csharp
using (var image = Image.Load("bitmap.bmp"))
{}
```

generates

```
Exception has occurred: CLR/System.NotSupportedException
An unhandled exception of type 'System.NotSupportedException' occurred in SixLabors.ImageSharp.dll: 'Does not support this kind of bitmap files.'
   at SixLabors.ImageSharp.Formats.Bmp.BmpDecoderCore.Decode[TPixel](Stream stream)
   at SixLabors.ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)
   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration config, Stream stream, Func`2 action)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, String path)
```

### System Configuration

- ImageSharp version: 1.0.0-beta0005
- Environment (Operating system, version and so on): Windows 10 x64 1803
- .NET Framework version: 4.7.2 / .NET Core 2.1.4

**Comment by dlemstra** [comment]
I think we should be able to add support for this. And the file `coders/bmp.c` could give some insight on how this is done in ImageMagick.

**Comment by JimBobSquarePants** [comment]
If we update the support listed in #320 we can fix this

**Comment by brianpopow** [comment]
@wc-matteo: would you mind sharing the image here again? The drop box link does not work anymore. Just attaching it to this ticket would be helpful to reproduce it.

**Comment by wc-matteo** [comment]
@brianpopow fixed the link. Don't know what happened there.
