### ISSUE TITLE
Image composition SrcIn doesn't work

### ISSUE THREAD

**Issue by MaklaCof** [SixLabors/ImageSharp#739]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Image composition doesn't work.

### Steps to Reproduce
Create empty new .NET Core project and paste this code:
```
        static void Main(string[] args)
        {
            Console.WriteLine($"Current dir {Directory.GetCurrentDirectory()}");

            var location = new DirectoryInfo(Directory.GetCurrentDirectory());
            location = location.Parent.Parent.Parent;  //Move outside bin.
            using (var img = Image.Load(location.FullName + "/Original.png"))
            {
                img.Mutate(imgMaskIn =>
                {
                    using (var mask = Image.Load(location.FullName + "/MaskTransparent.png"))
                    {
                        imgMaskIn.DrawImage(mask, new GraphicsOptions {AlphaCompositionMode = PixelAlphaCompositionMode.SrcIn });
                    }
                });
                img.Save(location.FullName + "/Destination.png");
            }

            Console.WriteLine("Done.");

            Console.ReadKey();
        }
```
Copy attached images to location of the `Program.cs` source file.
![original](https://user-images.githubusercontent.com/1589573/47161491-6f897c80-d2f2-11e8-9781-57d46030250f.png)
![masktransparent](https://user-images.githubusercontent.com/1589573/47161492-6f897c80-d2f2-11e8-95a0-974f219f0aca.png)

### System Configuration
Windows10-64 bit, .NET Core 2.1.

- ImageSharp version: `1.0.0-dev002024`
- Other ImageSharp packages and versions:
```
    <PackageReference Include="SixLabors.ImageSharp" Version="1.0.0-dev002024" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-dev002024" />
```
- Environment (Operating system, version and so on): `Windows10-64 bit`
- .NET Framework version: `.NET Core 2.1.`

### Additional
Also open [SO question](https://stackoverflow.com/questions/52875516/how-to-compose-two-images-using-source-in-composition?noredirect=1#comment92665602_52875516) because I was not sure if I am using library correctly.

**Comment by JimBobSquarePants** [comment]
It looks like there's actually an issue with how we're either decoding the mask png. 

It's a 1bit grayscale png with a transparency marker and somehow we are not picking up on that marker.

If you make your mask a 32bit image it will work fine.

![destination](https://user-images.githubusercontent.com/385879/47164479-07d23200-d2f0-11e8-8b1b-fcba17eea948.png)

**Comment by MaklaCof** [comment]
Works great.
