### ISSUE TITLE
Cross target .NET Framework 4.7.2

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#743]
We should enable optimizations provided by newest runtime & BCL  (eg. #742 #604) under .NET Framework 4.7.2 as well. For this, we need to cross-target that framework.

Checklist:
- [ ] Add build targets for 4.7.2
- [ ] Ensure new NuGet package is also being generated
- [ ] Define a new compilation symbol (eg. `FANCY_MODRN_DOTNET`) which is enabled when targeting .NET Core 2.1 or .NET Framework 4.7.2
- [ ] Replace all `#if NETCOREAPP2_1` conditions with `#if FANCY_MODRN_DOTNET`
- [ ] Define a new CI test target under AppVeyor

**Comment by iamcarbon** [comment]
Implemented in https://github.com/SixLabors/ImageSharp/pull/746

**Comment by JimBobSquarePants** [comment]
@iamcarbon You're the man!
