### ISSUE TITLE
ImageFormatException: 'Bad Huffman code.'

### ISSUE THREAD

**Issue by rmarskell** [SixLabors/ImageSharp#749]
I'm trying to open a jpeg from Wikipedia with ImageSharp (v1.0.0-beta0005) and am getting this exception: `ImageFormatException: 'Bad Huffman code.'`

It seems to be happening in `Image.Load` on this line:
`using ( var image = Image.Load( originalImageStream, out IImageFormat format ) ) {`

This image loads in browsers and image viewers so I'm not sure if this is just a bug in ImageSharp, or perhaps something that can be ignored instead of throwing an exception.

The image I'm using is:
https://upload.wikimedia.org/wikipedia/commons/b/b2/Centre_Block_-_Parliament_Hill.jpg

**Comment by JimBobSquarePants** [comment]
Have you tried the latest version. I.E the nightlies?

**Comment by JimBobSquarePants** [comment]
There's a good chance the issue is related to https://github.com/SixLabors/ImageSharp/issues/723 which I fixed a few weeks back

**Comment by JimBobSquarePants** [comment]
Just tested against [1.0.0-dev002072](https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp/1.0.0-dev002072). Confirmed to be fixed.
