### ISSUE TITLE
JIT exception thrown when creating animated gif on iOS

### ISSUE THREAD

**Issue by dmanning23** [SixLabors/ImageSharp#762]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When creating animated gifs on iOS devices, a JIT exception is thrown by the quantizer and the operation fails:

```
Attempting to JIT compile method 'SixLabors.ImageSharp.Processing.Processors.Quantization.OctreeFrameQuantizer`1/Octree/OctreeNode<SixLabors.ImageSharp.PixelFormats.Rgba32>:ConstructPalette (SixLabors.ImageSharp.PixelFormats.Rgba32[],int&)' while running in aot-only mode. See https://developer.xamarin.com/guides/ios/advanced_topics/limitations/ for more information.
```

The WuQuantizer throws a similar exception:
```
Attempting to JIT compile method 'SixLabors.ImageSharp.Processing.Processors.Quantization.WuFrameQuantizer`1<SixLabors.ImageSharp.PixelFormats.Rgba32>:GetPalette ()' while running in aot-only mode. See https://developer.xamarin.com/guides/ios/advanced_topics/limitations/ for more information.
```

The Xamarin link in the exception message mentions decorating the method with the UnmanagedFunctionPointerAttribute to fix the problem.
https://docs.microsoft.com/en-us/xamarin/ios/internals/limitations#no-dynamic-code-generation

### Steps to Reproduce
I see this error everytime I try to create an animated gif on iOS.
I have a sample project here that demonstrates the problem:
https://github.com/dmanning23/MonogameScreenToolsExample
https://github.com/dmanning23/MonogameScreenTools

### System Configuration
I'm seeing this issue on an iPhone 5S running iOS 12.0.1

- ImageSharp version: I am using the "dev" package from the ImageSharp nightly myget stream.

**Comment by JimBobSquarePants** [comment]
@dmanning23  What do the linked guidelines from your error say?

https://developer.xamarin.com/guides/ios/advanced_topics/limitations/

I have no experience with mobile development so hopefully someone reads this and has a clue.

**Comment by dmanning23** [comment]
The guidelines mention an attribute that can be used to decorate the problem method. There are a few examples out there showing how to use it, I was going to fart around with it later this afternoon and see if I can get it working.

**Comment by antonfirsov** [comment]
It seems to me that you are facing [this specific limiatation](https://www.mono-project.com/docs/advanced/aot/#limitation-generic-interface-instantiation).

@dmanning23 can you try a little experiment for us?
1. Create an application referencing the dev/MyGet version of ImageSharp and [System.Memory](https://www.nuget.org/packages/System.Memory/4.5.1), that does nothing else but
2. `PixelOperations<Bgra32> operations = PixelOperations<Bgra32>.Instance`
3. Invoke something like [this method](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/PixelFormats/PixelOperations%7BTPixel%7D.cs#L31) on the instance created in (2.), using reflection. 
Notes: 
    - reflection is needed because the method is internal
    - to get an instance to `Span<T>` you can use the extension method `array.AsSpan()`
    - `Span<T>` is implictily convertible to `ReadOnlySpan<T>`)

**Comment by antonfirsov** [comment]
I have a few more ideas to try, if it's possible for you to use a manually built version of ImageSharp.

**Comment by dmanning23** [comment]
Ok, I've made a bit of headway on this issue... If I explicitly build one of those objects (with the correct generic type) and call the `ConstructPalette` method BEFORE calling `SaveAsGif(...)`:
```
var test = new OctreeFrameQuantizer<Rgba32>(new OctreeQuantizer(false));
test.AotGetPalette(); //stubbed out method that just calls empty ConstructPalette
```
Now when it hits that bit of code when calling SaveAsGif, it has already seen it ahead-of-time and doesn't need to spin up the JIT compiler. I can't think of a very elegant way to fix it though... The easiest thing I can think of is adding a few `AotCompile` methods that are similar to above, that the user can call at init on iOS.
kind gross, but it would work :)

**Comment by dlemstra** [comment]
Have you tried any of the workarounds mentioned here: https://support.frozenmountain.com/hc/en-us/articles/115000767214-Known-Issue-with-Xamarin-iOS-10-10.

**Comment by dmanning23** [comment]
Looks like those workarounds are if this issue pops up from calling p/invoke, I don't think any of those would work because I'm hitting it here due to the heavy generic usage in ImageSharp. I have a PR open that adds a few methods that can be used to pre-seed the AoT compiler on iOS. I've been able to generate animated gifs on iOS using this technique :)
