### ISSUE TITLE
Uploading images with transparent background

### ISSUE THREAD

**Issue by mjshero** [SixLabors/ImageSharp#766]
I am trying to upload png's and jpeg's and I want to change their background to transparent, but the "a" value being 0 turns it black.

**Comment by JimBobSquarePants** [comment]
Hi @mjshero

A transparent pixel, correctly, by default is an empty one containing 0 for all component values. What you want is the equivalent off the CSS “transparent” color. You can use the `BackgroundColor` method with `Rgba32.Transparent` to set this.

Hope that makes sense

P.S please use Gitter for questions in the future and do not delete the issue template.

**Comment by mjshero** [comment]
That makes sense, thank you.

Mike Shero

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
