### ISSUE TITLE
Nuget Feed does not exist

### ISSUE THREAD

**Issue by SenanuFC** [SixLabors/ImageSharp#777]
Get this when trying to build a project. Any alternative:
```[ImageSharp Nightly] Unable to load the service index for source https://www.myget.org/F/imagesharp/api/v3/index.json.
  Response status code does not indicate success: 404 (Feed does not exist.).

**Comment by tocsoft** [comment]
please ensure you are using the correct nuget feed. 

https://www.myget.org/F/sixlabors/api/v3/index.json

**Comment by SenanuFC** [comment]
Was using https://www.myget.org/F/imagesharp/api/v3/index.json

**Comment by JimBobSquarePants** [comment]
Which is not the one listed in the readme.
