### ISSUE TITLE
ImageSharp disappeared from myget

### ISSUE THREAD

**Issue by johnnyoshika** [SixLabors/ImageSharp#778]
It seems that ImageSharp disappear from myget.

This is gone: https://www.myget.org/gallery/imagesharp

...and so is this: https://www.myget.org/F/imagesharp/api/v3/index.json

Can this be restored please?

**Comment by antonfirsov** [comment]
@johnnyoshika in our readme or in our [docs](https://docs.sixlabors.com/articles/intro.html) you can read about accessing our official myget/nuget feeds.

The links above contained versions, which were outdated a long time ago, those versions are not supported in any form in the past 1.5-2 years, it was time to delete the feeds.

**Comment by johnnyoshika** [comment]
@antonfirsov Thank you. That deprecated feed is still referenced in ImageSharp.Web's README.md: https://github.com/SixLabors/ImageSharp.Web/blob/master/README.md

**Comment by antonfirsov** [comment]
@johnnyoshika our apologies, thank you for informing us!
