### ISSUE TITLE
Endless loop / DoS with invalid GIF-image

### ISSUE THREAD

**Issue by DennisGlindhart** [SixLabors/ImageSharp#779]
### Description
When loading attached (probably) invalid GIF-image the CPU-usage gets to 100% and app does not respond - Seems like a endless loop (Same symptoms as #281).

### Steps to Reproduce
With the image:
![image](https://github.com/DennisGlindhart/issuefiles/raw/master/0777979102164.gif)

```
using (var originalImage = Image.Load(binary, out SixLabors.ImageSharp.Formats.IImageFormat format))
{
  //Do something
}
```

### System Configuration
- ImageSharp version: 1.0.0-beta0005
- Environment (Operating system, version and so on): Linux / Fedora 29
- .NET Framework version: .NET Core (netcoreapp2.1)

**Comment by JimBobSquarePants** [comment]
Have you tried the nightlies? This should be fixed with #770

**Comment by DennisGlindhart** [comment]
@JimBobSquarePants Nope - Nightlies work. Only searched in issues, not merge requests. Sorry

Thanks

**Comment by JimBobSquarePants** [comment]
That’s great to hear! No worries, GitHub search has a long way to go before it’s useful.
