### ISSUE TITLE
Gaussian Blur is not actually Gaussian

### ISSUE THREAD

**Issue by Poyo-SSB** [SixLabors/ImageSharp#786]
```csharp
using (var image = new Image<Rgba32>(128, 128))
{
	image.Mutate(ctx => ctx
		.Fill(Rgba32.Black)
		.Fill(Rgba32.White, new EllipsePolygon(64, 64, 64, 64)));

	image.Mutate(ctx => ctx.GaussianBlur(12));

	using (var stream = new FileStream("image.png", FileMode.Create))
	{
		image.SaveAsPng(stream);
	}
}
```

Mutating an image with a Gaussian blur yields a blur that isn't quite Gaussian, much more closely resembling a box blur. I implemented a mathematically accurate Gaussian blur that factors in every pixel in the image (obviously overkill and inefficient in a 0-255 color space, but completely correct), and the results are as follows:

![image](https://user-images.githubusercontent.com/1782081/49705997-adf73580-fbd7-11e8-8b87-e9f67182b4ba.png)

Note the similarity between ImageSharp's Gaussian blur and its box blur.

I would fix this myself and submit a PR but I genuinely have no clue why this happens. All of the processing regarding the generation of the kernel and the underlying Gaussian function seems to be correct and yields the same values as my own implementation.

Notes: Using ImageSharp v1.0.0-beta0005 on .NET Framework 4.7.1 on a Windows 10 64-bit OS.

**Comment by JimBobSquarePants** [comment]
Hi there, 

Can you do me a favour and compare against the latest dev build? We’ve updated the convolution code there so it would be good to see if anything has changed. 

Cheers!

**Comment by Poyo-SSB** [comment]
Unfortunately, results seem to be identical in v1.0.0-dev002237.

**Comment by JimBobSquarePants** [comment]
Would it be possible to share your code?

**Comment by Poyo-SSB** [comment]
Certainly, but it's messy and doesn't use any of ImageSharp's DenseMatrix or convolution features.

```csharp
internal class MathematicalGaussianBlurProcessor : IImageProcessor<Rgba32>
{
    public float Sigma { get; }

    public MathematicalGaussianBlurProcessor(float sigma) => this.Sigma = sigma;

    /// <summary>A function in the form ae^(-(x - b)² / 2c²).</summary>
    /// <param name="a">The height of the curve's peak.</param>
    /// <param name="b">The position of the center of the curve's peak (or the mean in a normal distribution).</param>
    /// <param name="c">The standard deviation of the curve, affecting the width of the curve.</param>
    private double GaussianFunction(double x, double a, double b, double c)
        => a * Math.Exp(-(x - b) * (x - b) / (2 * c * c));

    public void Apply(Image<Rgba32> source, Rectangle sourceRectangle)
    {
        // Generate a table for the sake of speed.
        // The table will only need to be as large as the largest dimension of the image because the Gaussian function is symmetrical.
        double[] gaussianTable = new double[Math.Max(source.Width, source.Height)];

        for (int i = 0; i < gaussianTable.Length; i++)
        {
            // a is 1 because the weights will be normalized to sum to 1 when convoluting anyway.
            // The normalization will differ depending on the actual values so pre-calculating it is useless.
            gaussianTable[i] = this.GaussianFunction(i, 1, 0, this.Sigma);
        }

        // Clone the source for read-only access to the original pixels.
        Image<Rgba32> input = source.Clone();
        Process(input, source, gaussianTable, false);

        // Apply the convolution again in the horizontal direction.
        // This is possible because the Gaussian function is directionally seperable.
        input = source.Clone();
        Process(input, source, gaussianTable, true);
    }

    private void Process(Image<Rgba32> input, Image<Rgba32> output, double[] gaussianTable, bool horizontal)
    {
        int iSize = horizontal ? input.Height : input.Width;
        int jSize = horizontal ? input.Width : input.Height;

        for (int i = 0; i < iSize; i++)
        {
            for (int j = 0; j < jSize; j++)
            {
                // Doubles are used instead of floats for accuracy.

                double weightSum = 0;

                double r = 0;
                double g = 0;
                double b = 0;
                double a = 0;

                for (int k = 0; k < jSize; k++)
                {
                    // Reflect k along i.
                    double weight = gaussianTable[Math.Abs(j - k)];

                    weightSum += weight;

                    Rgba32 pixel;
                    if (horizontal)
                    {
                        pixel = input[k, i];
                    }
                    else
                    {
                        pixel = input[i, k];
                    }

                    r += weight * pixel.R;
                    g += weight * pixel.G;
                    b += weight * pixel.B;
                    a += weight * pixel.A;
                }

                // Make sure to round, otherwise there will be intense noise from floating point rounding errors.
                // Normalize all weights such that they sum to 1, ergo the channel value is normalized to 255.
                output[i, j] = new Rgba32(
                    (byte)Math.Round(r / weightSum),
                    (byte)Math.Round(g / weightSum),
                    (byte)Math.Round(b / weightSum),
                    (byte)Math.Round(a / weightSum));
            }
        }
    }
}
```

Again, this doesn't use a kernel, instead factoring every relevant pixel.

Also note that the Gaussian function in my implementation is different than that of ImageSharp's. Compare the two:

![mine](https://user-images.githubusercontent.com/1782081/49750287-53a1b780-fc5f-11e8-9360-b4ebb7e0ce98.png)

vs.

![ImageSharp](https://user-images.githubusercontent.com/1782081/49750313-66b48780-fc5f-11e8-86b8-93b70c0246b0.png)

ImageSharp's special `a` calculation yields a probability density function which has an area of 1, but this is negated in this particular use of the Gaussian function thanks to the normalization [(see here for comparison)](https://www.desmos.com/calculator/pytmt4zwyh).

**Comment by JimBobSquarePants** [comment]
Thanks for that, appreciate it.. 

Reading through your code it looks to me that the difference is simply the sampling radius. You sample the entire image while we sample (2 * sigma) + 1

**Comment by JimBobSquarePants** [comment]
CSS makes an absolute meal of it oversampling edge pixels but produces a similar blur.

<img width="200" src ="https://user-images.githubusercontent.com/385879/49845834-81802b00-fe1c-11e8-9677-f6a43069d2bb.png"/>

**Comment by Poyo-SSB** [comment]
I do sample the entire image, but that's not what yields the difference in output—using the Gaussian blur function in an application like Photoshop or Paint.NET yields a similar result to mine. It appears that the shape of the actual kernel is different despite what the code seems to output.

**Comment by JimBobSquarePants** [comment]
> It appears that the shape of the actual kernel is different despite what the code seems to output.

I think you're correct. The calculated kernel dimensions are too small. I rewrote the kernel generation code based on the guide here http://chemaguerra.com/gaussian-filter-radius/ to preserve a minimum kernel radius of `Ceiling(sigma * 3)` and here is the result.

![imageshouldapplygaussianblur_rgba32_solid128x128_ 0 0 0 255](https://user-images.githubusercontent.com/385879/49848543-9d3dfe00-fe29-11e8-85c0-4c22a2394279.png)

**Comment by JimBobSquarePants** [comment]
I’ll create a PR shortly

**Comment by Alerinos** [comment]
@JimBobSquarePants I have a similar problem, the blur in the browser looks completely different.

```
image.Image.Mutate(x => x.GaussianBlur(20));
```
![image](https://user-images.githubusercontent.com/42449535/218257195-8bb03499-32d5-4c9c-97a5-30e23ace9bac.png)
css ``filter: blur(20px);``
![image](https://user-images.githubusercontent.com/42449535/218257230-4211291b-45c9-4046-b8bb-47fe00fd6ca0.png)

In the browser, the effect looks smoother.
I have the latest version, is there any solution for this?
