### ISSUE TITLE
Image width and image height are getting mixed up

### ISSUE THREAD

**Issue by roelgeusens** [SixLabors/ImageSharp#790]
I'm using SixLabors.ImageSharp.Drawing (1.0.0-beta0005) using ASP .NET core MVC 2.1 on Windows 10.

![20180908_101410](https://user-images.githubusercontent.com/20394757/50042648-22155b80-0066-11e9-81f9-82ee6232d6e2.jpg)

I'm uploading the attached image using a IFormFile. Loading the image to ImageSharp using:

Image<Rgba32> _image = Image.Load(file.OpenReadStream());

The image width and height are mixed up (see screenshot). Tis happens with all portrait pictures taken with my Nikon D90 SLR camera.
![2018-12-15 12_40_58-cnock debugging - microsoft visual studio](https://user-images.githubusercontent.com/20394757/50042692-b8498180-0066-11e9-8e6e-6039c874eb83.png)

**Comment by brianpopow** [comment]
@roelgeusens: The picture has actually a width of 4032 and a height of 3024, so imagesharp shows it correctly to you. The image also contains EXIF informations which hold the orientation information. Most Image viewing programs automatically rotate the image by the EXIF information. 

If you want to auto rotate the image by EXIF information with ImageSharp, use the follwoing: 

``` image.Mutate(img => img.AutoOrient()); ```

**Comment by antonfirsov** [comment]
Please remind me that I should add this to our FAQ TODO list in #411.
