### ISSUE TITLE
Valid PNG - ImageFormatException: PNG Image does not contain a data chunk

### ISSUE THREAD

**Issue by dkershner6** [SixLabors/ImageSharp#793]
### Description
When loading some valid PNG images, there is an intermittent error.  If no decoder is specified, the generic decoder exception is thrown.  If PNG decoder is specified, the exception changes to ImageFormatException: PNG Image does not contain a data chunk.  It does not happen 100% of the time, for whatever reason, but on the below images it happens about 98% of the time.  While erroring, the image will load just fine in a browser, though.

### Steps to Reproduce
Example Images: https://cdn.shopify.com/s/files/1/0018/3379/5673/products/lumiworld-product-image-pet-owl-04.png?v=1544223157
https://cdn.shopify.com/s/files/1/0018/3379/5673/products/Owl-info.jpg?v=1544223157

Code:
```
public static async Task<Image<Rgba32>> GetImageFromUrlAsync(HttpClient httpClient, string url)
        {
            HttpResponseMessage response = await httpClient.GetAsync(url);
            using (Stream inputStream = await response.Content.ReadAsStreamAsync())
            {
                return Image.Load(inputStream, new SixLabors.ImageSharp.Formats.Png.PngDecoder());
            }
        }
```

### System Configuration
This happens in production, which is Azure Functions v2, running in consumption (Windows).  This means .net Core 2.1.  I can also recreate this in a simple console app (.Net Core 2.1 on Windows 10).

- ImageSharp version: 1.0.0-beta0005 (also tried in 0004)
- Other ImageSharp packages and versions: None
- Environment (Operating system, version and so on): Windows 10 and Server 2016
- .NET Framework version: .Net Core 2.1

**Comment by dkershner6** [comment]
I believe this is a permissions issue, not image one.  Closing.

**Comment by nominator** [comment]
@dkershner6 how did you resolve this? I am facing same issue when downloading image from blob storage inside an Azure function.

**Comment by mchmielewski1** [comment]
Exactly the same situation I encountered, downloading png image from blob in Azure Function

**Comment by SpicySyntax** [comment]
I am having the exact same issue. It downloads an image from blob storage in an Azure Function. It only fails when the blob is a PNG.

**Comment by JimBobSquarePants** [comment]
@SpicySyntax It's an environmental problem not a code one so I'm inclined not to reopen the issue, plus we don't know what @dkershner6  did to resolve the issue. 

I would report something to the Azure Functions team.

**Comment by SpicySyntax** [comment]
@JimBobSquarePants That makes sense, thanks.
@dkershner6 how did you resolve this issue?
Is it something with the way the pngs are persisted in blob storage or problem with the download and processing?

**Comment by JimBobSquarePants** [comment]
I wonder if any of the function code uses the same pinnings as [DownloadToStreamAsync](https://github.com/Azure/azure-storage-net/issues/470)

**Comment by tomuxx** [comment]
I just ran into this myself with Azure Functions. Had to reset stream position back to 0 and it worked with both PNG and JPEG files.

```
CloudBlockBlob image = container.GetBlockBlobReference(filePath);

System.IO.Stream imageStream = new System.IO.MemoryStream();

await image.DownloadToStreamAsync(imageStream).ConfigureAwait(false);

imageStream.Position = 0;

IImageDecoder imageDecoder = new SixLabors.ImageSharp.Formats.Jpeg.JpegDecoder();
// OR:
// IImageDecoder imageDecoder = new SixLabors.ImageSharp.Formats.Png.PngDecoder();

using (Image img = Image.Load(imageStream, imageDecoder))
{ ... }
```

Maybe reset passed stream to zero automatically inside Load() method?

**Comment by JimBobSquarePants** [comment]
There’s already an overload that allows you to choose that behaviour. It’s not the default for good reason as we cannot predict the position of an image in a stream.
