### ISSUE TITLE
Image.Load throws NullReferenceException

### ISSUE THREAD

**Issue by Metalnem** [SixLabors/ImageSharp#797]
**Image.Load** throws a **NullReferenceException** when loading the image from the [attached archive]. You can run the following code to reproduce it (the **path** variable should contain the path to the extracted file):

```csharp
Image.Load(path);
```

Found via [SharpFuzz].

[attached archive]: https://github.com/SixLabors/ImageSharp/files/2707118/NullReferenceException.zip
[SharpFuzz]: https://github.com/Metalnem/sharpfuzz

**Comment by jongleur1983** [comment]
@Metalnem Just to confirm I understand it right: The image in fact is invalid, right?

According to the file header it's a JPEG (Jfif) file, and I can reproduce the bug, but the image can't be opened by the windows 10 image viewer, paint, paint.net or Gimp.

So we're going to throw an ImageFormatException stating that there is no readable SOF0 marker in this case.

PR incoming in a few minutes...

**Comment by Metalnem** [comment]
That's right, the image is invalid!
