### ISSUE TITLE
Image.Load terminates the process with AccessViolationException

### ISSUE THREAD

**Issue by Metalnem** [SixLabors/ImageSharp#798]
**Image.Load** terminates the process by throwing an **AccessViolationException** when loading the image from the [attached archive]. You can run the following code to reproduce it (the **path** variable should contain the path to the extracted file):

```csharp
Image.Load(path);
```

Found via [SharpFuzz].

[attached archive]: https://github.com/SixLabors/ImageSharp/files/2707127/AccessViolationException.zip
[SharpFuzz]: https://github.com/Metalnem/sharpfuzz

**Comment by deslee** [comment]
I am also experiencing this on Windows

**Comment by JimBobSquarePants** [comment]
We have a template. It's incredibly frustrating that you have chosen not to use it.
