### ISSUE TITLE
PNG Corruption when loading

### ISSUE THREAD

**Issue by equinox2k** [SixLabors/ImageSharp#799]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Using a .netstandard 2.0 project loading a png becomes corrupted in memory (looks not fully loaded into memory)

### Steps to Reproduce
Example project to demonstrate corruption...
https://www.dropbox.com/s/u7ly5uj7nfh2q59/TestPng.zip?dl=0

### System Configuration
Mac OS Mojave 10.14 running latest stable Visual Studio for Mac

- ImageSharp version: 1.0.0-beta0005
- Other ImageSharp packages and versions: Image Sharp core 1.0.0-beta0006
- Environment (Operating system, version and so on): as above
- .NET Framework version: Xamarin Mac Modern

Before loading...

![brdf](https://user-images.githubusercontent.com/655939/50402886-fc1b4580-074e-11e9-8038-c2340319e319.png)

After Saving...

![test](https://user-images.githubusercontent.com/655939/50402879-f45ba100-074e-11e9-8f4d-4ca26b955fe0.png)

**Comment by JimBobSquarePants** [comment]
Can you give the latest dev build a try and make sure you’re using the latest Mono. I think we’ve solved this. (Funkiness in Xamarin’s deflatestream implementation)

**Comment by equinox2k** [comment]
@JimBobSquarePants ok so first of all I tried updating mono + vs to very latest, but made no difference.

I then grabbed a copy of this repo and built the sixlabors.imagesharp.dll and updated reference. I ran and it worked ! :)

Would it be possible to do a new beta build and deploy to Nuget?

**Comment by JimBobSquarePants** [comment]
We’ve got a MyGet feed (link in readme) where you can get the latest build. Was gonna hold out for an RC release but am beginning to think a beta6 might be wise to give us some breathing room. I’ll get one on Nuget after Christmas. (It’s Christmas Day already here in Sydney)

**Comment by equinox2k** [comment]
@JimBobSquarePants ah great thanks, didn't see you had a MyGet feed, yeah would be nice to have a beta 6 on Nuget. Have a Merry Xmas from Vancouver :)

**Comment by equinox2k** [comment]
@JimBobSquarePants any chance of getting beta6 on nuget yet?

Thanks

**Comment by JimBobSquarePants** [comment]
Not yet, actually chatting to our lawyer this evening so RC might move forward. Will have to plan timescales with the other chaps.

**Comment by equinox2k** [comment]
@JimBobSquarePants RC sounds cool :)
