### ISSUE TITLE
HueProcessor doesn't behave as expected

### ISSUE THREAD

**Issue by Nacimota** [SixLabors/ImageSharp#802]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When using `HueExtensions.Hue()`, the resulting image does not look the way I would expect it to, based on my understanding of what hue is.

Given this example:

![example](https://user-images.githubusercontent.com/651955/50741780-baf65b80-124d-11e9-9165-1347654ab386.png)

I would expect a hue shift of 180 degrees to produce something like this:

![example-photoshop-180](https://user-images.githubusercontent.com/651955/50741787-e6794600-124d-11e9-93fc-2e8e470464d3.png)

However, ImageSharp produces this:

![example-180](https://user-images.githubusercontent.com/651955/50741789-f729bc00-124d-11e9-8e46-4f4d741017dd.png)

Have I misunderstood what this method is supposed to do? Basically I'm expecting it to behave like the Hue/Saturation dialog in Photoshop does, when you change the hue and `Colorize` is unchecked.

### Steps to Reproduce
1. Download and save the first image from above as `example.png`.
2. Run this code:

```csharp
using (var img = Image.Load("example.png"))
{
    img.Mutate(c => c.Hue(180));

    using (var stream = File.Create("example-180.png"))
    {
        img.SaveAsPng(stream);
    }
}
```

### System Configuration

- ImageSharp version: `1.0.0-beta0005`
- Other ImageSharp packages and versions: `none`
- Environment (Operating system, version and so on): 
  - `Windows 10 Pro 1809 x64 v10.0.17763.194`
  - `Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-43-generic x86_64)`
- .NET Framework version: `.NET Core 2.1`

**Comment by Nacimota** [comment]
Okay I think I understand what's going on here. I had a dig around in the source and it pretty explicitly states that lum is preserved in the filter:

https://github.com/SixLabors/ImageSharp/blob/441942b771232f3b1f4c4a54bdf79f48bc1ca6bc/src/ImageSharp/Processing/KnownFilterMatrices.cs#L329

I guess my question then becomes: should it, though? It doesn't seem intuitive to me, at least not as a default. Maybe we could get a filter that ignores luminosity? I don't have much experience with graphics programming so I'll have to do a lot of thought/research if I'm to create one myself.

**Comment by JimBobSquarePants** [comment]
Hi @Nacimota 

This is one of those situations where what Photoshop does I'd describe as wonky. Here's a fiddle demonstrating what CSS does. As you can see the output matches the behaviour there exactly which is what I would expect.

https://jsfiddle.net/37dyftxz/

![CSS Hue rotated image](https://user-images.githubusercontent.com/385879/50742617-f864e400-1261-11e9-905d-39a0b90f1340.png)

I don't plan on adding a filter that replicates the unorthodox behaviour but if you wanted to the maths is demonstrated here.
http://graficaobscura.com/matrix/index.html 

Hope that makes sense.

Cheers

James

**Comment by Nacimota** [comment]
Hi, @JimBobSquarePants 

Thanks for your quick reply. I think I'm just not understanding this stuff properly. One of my main issues with this hue function is that it seems to colourize grey parts of an image under certain conditions. 

So for example when I take this image:
![grey](https://user-images.githubusercontent.com/651955/50742849-07489800-125c-11e9-993a-1e57d66002d5.png)

And run it through ImageSharp with a rotation of 90 degrees, I get this:
![grey-90](https://user-images.githubusercontent.com/651955/50742877-58f12280-125c-11e9-86de-1618947e5689.png)

When I use the same image and 90 degree shift in your CSS example, the image stays grey as I would expect it to. Surely if you shift the hue of a pixel with no saturation, it should remain unchanged?

**Comment by Nacimota** [comment]
After discussing this in gitter, I've been encouraged to post a couple of extra examples for clarity. Both of these comparison pictures use a 90 degree shift as well. It seems like the further you are from 180 or 0 degrees, the more incorrect the result becomes:

![rainbow-comp](https://user-images.githubusercontent.com/651955/50858972-c4163280-13dd-11e9-9872-822fc12b8c0e.png)

![mixed](https://user-images.githubusercontent.com/651955/50858984-c8425000-13dd-11e9-9d36-07c5623256eb.png)

The middle image on the bottom there is my attempt at implementing the "simple" (non-luminance-preserving) filter described on the graficaobscura page linked above.

**Comment by jsheely** [comment]
Did anyone figure out how to do it so it works like how Photoshop does hue processing. I'm not getting any yellow. 

I'm not sure I understand how to use the Fix Colors Filters PR if that is a fix or not

**Comment by jsheely** [comment]
@Nacimota Would you be able to post a function that handles the filter processing you were able to come up with?

**Comment by JimBobSquarePants** [comment]
Hey @jsheely can you please stop spamming closed issues. If you have a problem report it properly like a professional
