### ISSUE TITLE
System.NotSupportedException: 'Image cannot be loaded.' for JPEGs

### ISSUE THREAD

**Issue by IvanJosipovic** [SixLabors/ImageSharp#803]
### Description
Unable to load JPEG images from two online stores.
GearBest.com and ALIExpress.com

### Steps to Reproduce
Download:
https://ae01.alicdn.com/kf/HTB1aXCLXFzsK1Rjy1Xbq6xOaFXaH/QCY-qs1-TWS-5-0-Bluetooth-headphone-3D-stereo-wireless-earphone-with-dual-microphone.jpg
https://gloimg.gbtcdn.com/gb/pdm-product-pic/Electronic/2016/07/27/source-img/20160727175032_35397.jpg

Attempt to load image using 
```
var image1 = Image.Load("QCY-qs1-TWS-5-0-Bluetooth-headphone-3D-stereo-wireless-earphone-with-dual-microphone.jpg");
var image2 = Image.Load("20160727175032_35397.jpg");
```

Throws Exception:
```
Image cannot be loaded. Available decoders:
 - GIF : GifDecoder
 - PNG : PngDecoder
 - JPEG : JpegDecoder
 - BMP : BmpDecoder
```

### System Configuration
- ImageSharp version: 1.0.0-dev002315
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: .Net Core 2.2.101
- Additional information:

**Comment by IvanJosipovic** [comment]
Yes, I tried to simplify the repro as much as possible.
The repro is using load from path option, `public static Image<Rgba32> Load(string path);`

**Comment by JimBobSquarePants** [comment]
Here's your problem. They're not Jpeg's, they're WebP images. See #121 for the story there. Hoping for community help to get started supporting that image format.

![Not jpegs](https://user-images.githubusercontent.com/385879/50803601-7a2a3f80-133e-11e9-94be-5fcd7bef4ac7.png)
