### ISSUE TITLE
Feature request: allow Color Space choices in JpegEncoder

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#808]
This is a useful image size optimization for users dealing with grayscale images. (See #807) 

Additional colorspace encoders to implement:
- [x] Grayscale (actually important)
- [ ] Ycck (nice to have)
- [ ] Cmyk (nice to have)
- [x] RGB (nice to have)

**Comment by brianpopow** [comment]
@antonfirsov with #1734 merged, encoding with RGB colorspace is now possible.

**Comment by antonfirsov** [comment]
@brianpopow nice!  Only two more left.

**Comment by JimBobSquarePants** [comment]
Fixed via #2120
