### ISSUE TITLE
Feature request: Add Median filter

### ISSUE THREAD

**Issue by dejanberic** [SixLabors/ImageSharp#814]
This is a simple filter which can be used to filter out noise.

Here is one paper on fast Median and Bilateral filtering:
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.93.1608&rep=rep1&type=pdf

**Comment by michasacuer** [comment]
Hi, can i take and try to make this feature with Parallel tasks and Interop services? @JimBobSquarePants

**Comment by michasacuer** [comment]
Referring to gitter talk witn @antonfirsov i take that issue. I will start implementing it in february

**Comment by antonfirsov** [comment]
@michasacuer great news! Thanks! 👍

**Comment by Jarak-Jakar** [comment]
Just in case it helps (probably not, but I don't think it can hurt to mention it) I was recently working on basic median filtering, i.e. simply taking the median of a square window.  You can see the most up-to-date version of the fastest program I came up with [here](https://github.com/Jarak-Jakar/ivcnz2018/blob/master/naive/Program.fs) - feel free to look at everything else in the repo, but I think that'll be by far the most useful part of it.  It is written in F# though, so might not be of as much use to you.  Moreover, I have undoubtedly done something silly, or somehow not used ImageSharp effectively.  I also didn't get around to implementing more interesting types of median filters.

Based on some quick profiling of my program, it appears to spend about 60% of its time in the `Array.sort` function.  I tried implementing some alternatives like Insertion Sort and Shell Sort (I did think about Radix sort, but I can't remember actually testing it), but nothing came close to being as fast as the built-in .NET sort once the arrays got bigger than about 10 elements.  Someone suggested that I move from sorting the array to using a selection algorithm like QuickSelect, but I never got around to implementing it/trying it out.

I hope that this helps 😃

**Comment by michasacuer** [comment]
Thanks for help! I will start to implementing this after my exams (i think it will be int the next one, two weeks)

**Comment by FransBouma** [comment]
Isn't this a 9 tap tent filter, as described by Smith? https://pdfs.semanticscholar.org/cdf7/1f6ea2178cfa210a30c5870c235f3acdc42a.pdf

**Comment by JimBobSquarePants** [comment]
Fixed via #2219 !
