### ISSUE TITLE
Clarify difference between TextMeasurer.Measure() and TextMeasurer.MeasureBounds()

### ISSUE THREAD

**Issue by mogikanin** [SixLabors/ImageSharp#815]
Could someone clarify exact difference between these two methods? Documentation says they both ```Measures the text.```,  but in fact they return different result for same text.

**Comment by JimBobSquarePants** [comment]
Hi @mogikanin

One returns a RectangleF one returns a SizeF. 

https://docs.sixlabors.com/api/Fonts/SixLabors.Fonts.TextMeasurer.html


In future could you please ask questions in the Gitter channel. It makes life a little easier for us. Thanks!
