### ISSUE TITLE
Specific jpeg images result in very strange saved images (corrupted?)

### ISSUE THREAD

**Issue by LarsWesselius** [SixLabors/ImageSharp#817]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When loading an image using `Image.Load` and saving it again, using `image.Save()`. the resulting image is very different from the original, loaded image without doing any mutations.

### Steps to Reproduce
.NET Core 2.1 Console app. Use
`
using (Image<Rgba32> image = Image.Load("8.jpg"))
{
    image.Save("8-saved.jpg");
}
`
As the only code in Main and run with 8.jpg in your working directory (see attached).

This is the image being loaded (8.jpg):
![8](https://user-images.githubusercontent.com/24613528/51745605-aa464200-20a3-11e9-8a9e-7734826135c0.jpg)

This is the resulting image after saving:
![8-saved](https://user-images.githubusercontent.com/24613528/51745622-b92cf480-20a3-11e9-80b0-4f7565408287.jpg)

### System Configuration

- ImageSharp version: SixLabors.ImageSharp v1.0.0-beta0006
- Other ImageSharp packages and versions: None
- Environment (Operating system, version and so on): Windows 10, latest. .NET Core 2.1 console application
- .NET Framework version: .NET Core 2.1
- Additional information:

**Comment by LarsWesselius** [comment]
Opening and saving it in Paint for example produces a smaller jpeg which *does* work in ImageSharp.
![8-working](https://user-images.githubusercontent.com/24613528/51746327-09a55180-20a6-11e9-927d-cc8986252ca1.jpg)

**Comment by JimBobSquarePants** [comment]
@LarsWesselius I imagine paint is reencoding it to YCbCr. Just running a debug pass on the image now.
