### ISSUE TITLE
ImageSharp fails to build in Release UWP: invalid method body for CreateFrameQuantizer<TPixel>

### ISSUE THREAD

**Issue by Sergio0694** [SixLabors/ImageSharp#828]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
As the title says, I can't build an UWP app in Release mode once I reference the ImageSharp library. I've tested both with the .NETCore.UWP package version 6.1.9, 6.2.2 and 6.2.3, none of them worked.
I've also looked at this issue (#198) and only tried to build in x64, but the problem is still there.
These are the two errors I'm getting:

> ILT0005: 'C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\runtime.win10-x64.microsoft.net.native.compiler\2.2.1\tools\x64\ilc\Tools\nutc_driver.exe @"C:\Users\Sergi\source\repos\ImageSharpRepro\ImageSharpRepro\obj\x64\Release\ilc\intermediate\MDIL\ImageSharpRepro.rsp"' returned exit code 1

> Error: NUTC3033:Internal Compiler Error: Invalid MethodImpl body=6000353 decl=600032d when loading type 'SixLabors.ImageSharp.Processing.Processors.Quantization.PaletteQuantizer`1<TPixel>' from assembly 'SixLabors.ImageSharp' while loading MethodImpl list for 'instance SixLabors.ImageSharp.Processing.Processors.Quantization.IFrameQuantizer`1<TPixel1> SixLabors.ImageSharp.Processing.Processors.Quantization.PaletteQuantizer`1<TPixel>.SixLabors.ImageSharp.Processing.Processors.Quantization.IQuantizer.CreateFrameQuantizer<TPixel1>(SixLabors.ImageSharp.Configuration)'. while loading type 'SixLabors.ImageSharp.Processing.Processors.Quantization.PaletteQuantizer`1<TPixel>'. while computing compilation roots.

As mentioned in the title, the issue is only there in Release mode, while the Debug build works just fine.

### Steps to Reproduce

- Create a new UWP project (I'm targeting SDK 17134 and using 16299 as minimum)
- Reference the ImageSharp NuGet package (I'm using version `1.0.0-beta0006`)
- Try to build the app in Release mode (either x86 or x64), this fails with the errors above

### System Configuration
Windows 10 17763.x x64, but I should note I have the same issue on the CI build I have set up for my project, so this doesn't seem to be a problem specific to my configuration.

- ImageSharp version:
- Other ImageSharp packages and versions: `1.0.0-beta0006`
- Environment (Operating system, version and so on): Windows 10 17763.x x64
- .NET Framework version: n/a

I'm also going to send a repro to the .NET Native team, in case there's something they can do as well.
Will post an update here as soon as I hear back from them.

**Comment by antonfirsov** [comment]
Looks like an AOT compilation issue to me, similar to the mono/Xamarin ones.

I wonder whether the workaround we provided in #767 and #785 helps.

**Comment by Sergio0694** [comment]
Hey @antonfirsov - thank you for your reply!

I've tried that in my app (I'm only using the `Argb32` type, so I just added the `AotCompilerTools.Seed<Argb32>()` call in my app constructor, but I got the same error 😟

I want to note though that as I've mentioned in my first post, the compile error happens even with no code at all that references the library in my app. I mean, as soon as you reference ImageSharp, without actually using it at all, the .NET Native compiler breaks with those errors mentioned above.

I've asked the guys in the CoreRT repo if they can test this with a pre-release build of the upcoming .NETCore.UWP package, which should come out in a couple months or so and should include a new version of the .NET Native compiler, and see if the issue is solved there.
If it isn't, I hope they'll be able to at least provide a workaround at this point 😕

Thank you again for your help!

**Comment by JimBobSquarePants** [comment]
Beginning to really dislike the disconnect between MS dev teams and technologies.

**Comment by Sergio0694** [comment]
Hey @MattWhilden - glad to hear from you again!
I'm happy to hear this is currently being investigated, I'm looking forward to hearing some news about this, or even a possible workaround.

As for your question, this is the first time I've ever used ImageSharp on UWP, but hopefully someone from the ImageSharp team will be able to provide more info on previous attempts to run this combination.
Thank you again for looking into this! 😄

**Comment by JimBobSquarePants** [comment]
>I see other ImageSharp issue in our DB that are marked as fixed. Have y'all ever managed to get a version of this building for Release UWP?

@MattWhilden  I can't be sure that anyone actually has, in fact, I doubt very much someone has. We have some older issues that I closed due to a lack of support on the UWP side not ours.

**Comment by MattWhilden** [comment]
Appreciate the info. Going in to an investigation know that there may be other lurking things is often quite helpful!

**Comment by Sergio0694** [comment]
Hey @MattWhilden - any news?
I was wondering if you guys had time to start looking into this and if you managed to find out what is causing the issue. Thanks again! 😄

**Comment by MattWhilden** [comment]
I'll have to follow up with the person working on it and let you know. I don't know that I can catch them today but definitely Monday.

**Comment by Sergio0694** [comment]
@MattWhilden Sounds great, thank you so much for following up on this, I really appreciate it! 😊

**Comment by Sergio0694** [comment]
Hey @MattWhilden - sorry to bother, have you heard anything about this?
Any chance a fix for this could be included in the upcoming .NETCore.UWP 6.2.4 package?
Or, I would also be fine with some temporary workaround, maybe some compiler directives to add to the `.rd.xml` file to make ilc.exe ignore the errors in that specific method (as I'm not using that anyway), if something like this was possible (not sure if the error actually involves multiple files and VS is only showing that one in the output window)?

Even knowing an approximate ETA for a fix would help, as right now every single time I want to build a package for the Store I have to go through my code and remove all ImageSharp references, and for this reason I can't proceed to use the library in more places in my app either, as that would make building new packages even more difficult.

**Comment by cie6868** [comment]
Same bug in my UWP app in release x64 config, but downgrading to `1.0.0-beta0005` builds fine.

**Comment by Sergio0694** [comment]
@cie6868 Had no idea downgrading worked, I'll try that, thanks!
Also, FYI this bug has already been fixed by the .NET Native team, so right now we just need them to include it in the next .NETCore.UWP package update. Hopefully it'll be out soon 😕

**Comment by JimBobSquarePants** [comment]
Sigh.... Don’t downgrade, now you’ve introduced 100s of other bugs

**Comment by Sergio0694** [comment]
@JimBobSquarePants I meant to say I'd try that just to confirm it doesn't cause a crash, I'm not really going to use a months old package in a production app 😄
I mean, lacking ImageSharp entirely for now is annoying, but it's still better than introducing more crashes due to an old beta build ahahahahah

I really hope the .NET Native patch is release soon though 😆

**Comment by JimBobSquarePants** [comment]
It’s a shame their release cadence is not a bit faster. Though I can’t talk, it’s been 4 months since we did a release.

**Comment by Sergio0694** [comment]
Yeah that's a shame, especially because they were actually pretty fast once they started investigating the issue. My guess is that it's not really up to them, I imagine there are quite a few different teams involved in each .NETCore.UWP package, as it includes both the whole .NET Native toolchain as well as updates to all the various core libraries.

I'll try to ping the .NET Native team again and see if they have any news 😊

**Comment by JimBobSquarePants** [comment]
Good idea. Fingers crossed!

**Comment by ivanrlg** [comment]
Hi @Sergio0694 , could you solve the problem? I have a similar problem but with another plugin 'PdfSharpCore' that makes use of this library.

**Comment by Sergio0694** [comment]
Hey @ivanrlg - unfortunately the fix hasn't been pushed yet, no.
Last time I spoke with the .NET Naative team they confirmed they had in fact already fixed the issue and merged it into their master branch, but after that I guess it's out of their hands and it's just a matter of when MS/some other team decides to push out a new `.NETCore.UWP` NuGet package.

Since `6.2.8` was released 5 months ago, and `6.1.9` on October 2018, I'm hoping a new update will be released at some point this fall, but I don't know anything for sure unfortunately. 😟

**Comment by MattWhilden** [comment]
We're grinding through validation and things are going smoothly. I hate to say actual dates before it's completely inevitable though...

If your timelines are really tight and getting you a hacked version is helpful I'm happy to look in to that.

**Comment by MattWhilden** [comment]
Oh, what fortuitous timing. Right after I posted this a mail showed up titled "Review release notes" which is darn near the end of the train to get things shipped. I'd be pretty surprised if we didn't get this up by the end of the week (but don't quote me on that!)

**Comment by Sergio0694** [comment]
Hey @MattWhilden - great to hear from you again, and thank you for the good news! 😄
Looking forward for this new update to be shipped then!

**Comment by MattWhilden** [comment]
6.2.9 is now available on Nuget. Let me know how it goes. 

Release notes also up: https://github.com/microsoft/dotnet/tree/master/releases/UWP/net-native2.2

**Comment by Sergio0694** [comment]
I can't believe this is finally happening, just tried it and it works perfectly! 🎉
Thank you @MattWhilden and the whole team for taking the time to address this!

@JimBobSquarePants @antonfirsov I can confirm that `ImageSharp` now works just fine on UWP!

**Comment by MattWhilden** [comment]
Wonderful news. Do let us know if you have other issues. Happy to help.

**Comment by ivanrlg** [comment]
Hi, I think my case was not successful when compiling the release version x86 / x64, I can only compile the Debug version. The nutget that I am using is not exactly "ImageSharp" but the compilation error I have is very similar to the one referred to in this thread. This problem happens just by adding the nutget "PdfSharpCore" which I think refers to some element of "ImageSharp". In the same way I opened a case on the project page, but I have a feeling that I will not get an answer by that means that is why I refer it here. I hope you can help me, at least you can check it out.
Greetings. https://github.com/ststeiger/PdfSharpCore/issues/48  @MattWhilden @Sergio0694

**Comment by Sergio0694** [comment]
Hey @ivanrlg - it looks like that `PdfSharpCore` package is in fact referencing `ImageSharp`, which is why you have the same issue. If you upgrade to `.NETCore.UWP` version `6.2.9` you should be able to build in Release x64 (it works for me and other devs).
Release x86 is the only remaining broken profile, and we're tracking that in #987.

**Comment by AwsomeCode** [comment]
@MattWhilden Hi, I am getting below error on my UWP build for release mode with ImageSharp Only.
After removing ImageSharp its building find.

Min SKD Build : 16299
Microsoft.NETCore.UniversalWindowsPlatform : 6.2.9
Using Setting in csproj file : `<Use64Bitcompiler>true</Use64Bitcompiler>`

> Severity	Code	Description	Project	File	Line	Suppression State
Error		ILT0005: 'C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\runtime.win10-x86.microsoft.net.native.compiler\2.2.7-rel-27913-00\tools\x86\ilc\Tools64\nutc_driver.exe @"C:\AIGit\GoodsManV2\GoodsMan\GoodsMan.UWP\obj\x86\Release\ilc\intermediate\MDIL\GoodsMan.UWP.rsp"' returned exit code -1073740791	GoodsMan.UWP

**Comment by AwsomeCode** [comment]
@MattWhilden & @JimBobSquarePants 
Just to update the progress Its building fine for x64 Release mode but not for the x86 Release mode

**Comment by JimBobSquarePants** [comment]
We need someone to raise an issue upstream here for us to track. We can't fix issues with the AOT compiler.

**Comment by JimBobSquarePants** [comment]
@Sergio0694 Is this still valid? I thought we'd defeated all the UWP build issues?

**Comment by Sergio0694** [comment]
@JimBobSquarePants The original issue was indeed fixed, you reopened this a while back after @AwsomeCode reported a somewhat related (possibly?) issue. But I can confirm that the original issue here was indeed fixed months ago, yeah 👍

**Comment by JimBobSquarePants** [comment]
Sweet. Closing!
