### ISSUE TITLE
Segmentation fault on Linux when Resize

### ISSUE THREAD

**Issue by sunnycase** [SixLabors/ImageSharp#844]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Resize a image from 320x240 to 128x128 cause segmentation fault on Ubuntu. It runs fine on Windows.

### Steps to Reproduce
1. Clone this repo: https://github.com/sunnycase/imagesharp-issue
2. Run dotnet publish -c Release -r linux-x64
3. cd to bin/Release/linux-x64/publish
4. Run `./imagesharp-issue`

### System Configuration
Ubuntu 18.04 on WSL

- ImageSharp version: 1.0.0-beta0006
- Other ImageSharp packages and versions: N/A
- Environment (Operating system, version and so on): Ubuntu 18.04 on WSL
- .NET Framework version: dotnet core 3.0 preview2
- Additional information:

Code backup
```c#
using (var image = Image.Load<Rgb24>(typeof(Program).Assembly.GetManifestResourceStream("imagesharp_issue.0.jpg")))
{
    image.Mutate(x =>
        x.Resize(128, 128));
}
```

**Comment by JimBobSquarePants** [comment]
> * .NET Framework version: dotnet core 3.0 preview2

Hi @sunnycase 

We haven't built this against Net Core 3.0 yet. I imagine your issue will be due to a bug in 3.0 since it is only  a preview.

**Comment by sunnycase** [comment]
> 
> 
> > * .NET Framework version: dotnet core 3.0 preview2
> 
> Hi @sunnycase
> 
> We haven't built this against Net Core 3.0 yet. I imagine your issue will be due to a bug in 3.0 since it is only a preview.

Yes, .Net Core 2.0 doesn't have this issue.

**Comment by JimBobSquarePants** [comment]
>Yes, .Net Core 2.0 doesn't have this issue.

Yeah, so I would suggest raising an issue there. Referencing this one, it'll be up to Microsoft to fix.

**Comment by JimBobSquarePants** [comment]
⬆️ Thanks @sunnycase !!

**Comment by sunnycase** [comment]
Fixed in the latest .Net Core SDK.

**Comment by JimBobSquarePants** [comment]
Great stuff!
