### ISSUE TITLE
Saving JPEG Quality defaults to below 5 - ignoring default of 75

### ISSUE THREAD

**Issue by Marcel0024** [SixLabors/ImageSharp#845]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Saving certain Jpeg images without defining the JpegEnconder quality defaults to a quality below 5.
There's a few jpeg I've seem with this behavior, can't pin point an common trait. Examples further below.

### Steps to Reproduce
```       
using (var img = Image.Load("original.jpg"))
{
    using (FileStream outImage = File.Create("result.jpg"))
    {
        img.SaveAsJpeg(outImage);
    }
}
```

Results: 

![image](https://user-images.githubusercontent.com/14852157/54068210-72a5ea80-424a-11e9-8897-92e2bdd9ae4e.png)

**With Quality at 50:**
```       
using (var img = Image.Load("original.jpg"))
{
    using (FileStream outImage = File.Create("result.jpg"))
    {
        img.SaveAsJpeg(outImage, new JpegEncoder { Quality = 50 } );
    }
}
```

Results:

![image](https://user-images.githubusercontent.com/14852157/54068226-c6183880-424a-11e9-8601-82e355bef9af.png)

As you can see quality 50 produces a higher quality image.
Here are 3 examples images:
[quality-loss-example.zip](https://github.com/SixLabors/ImageSharp/files/2948335/quality-loss-example.zip)

I've managed to track it down to [SixLabors.ImageSharp.Formats.Jpeg.Components.Decoder.QualityEvaluator#EstimateQuality](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Formats/Jpeg/Components/Decoder/QualityEvaluator.cs#L79) method. 
'Normal' jpeg this method returns a 75 default quality. My example images the method returns 3 or 2.
![image](https://user-images.githubusercontent.com/14852157/54068534-062cea80-424e-11e9-93fe-fa00b2c727be.png)

### System Configuration

- ImageSharp version: 1.0.0-beta0006
- Environment (Operating system, version and so on): Windows 10 pro -Windows Server 2016
- .NET Framework version: .Net Core 2.1

**Comment by Marcel0024** [comment]
Going down the rabbit hole, it seems ImageSharp does a wrong quality estimation based on the Quantization Table. The estimation is based on a formula of ImageMagick.

Further digging i found this paper:
[Determining JPEG Image Standard Quality Factor from the Quantization Tables](https://www.researchgate.net/publication/322950128_Determining_JPEG_Image_Standard_Quality_Factor_from_the_Quantization_Tables)

The code provided in the paper is what JpegSnoop uses to determine the quality factor. JpegSnoop gives me a 98.25% approx quality factor on the same image i used above
![image](https://user-images.githubusercontent.com/14852157/54071242-236fb200-426a-11e9-9c18-5fe32ed0a08e.png)
I got a 3% in ImageSharp

The paper is also mention the method used in ImageMagick is fairly inaccurate
![image](https://user-images.githubusercontent.com/14852157/54071512-a2b2b500-426d-11e9-910b-b5eb33f55db7.png)

Is this where my problem lies? Is it worth further investigation?

**Comment by JimBobSquarePants** [comment]
We based ours on ImageMagick but I did the port and don’t read C well at all. I’ve most likely messed it up so please have a look if you can.

**Comment by dlemstra** [comment]
I can take a look at this when I am back home in two weeks. Might be possible we made some changes in ImageMagick since this was added to ImageSharp.

**Comment by JimBobSquarePants** [comment]
@dlemstra Just compared the current master source to the point in time source i ported from. It's identical so I must have missed something.

**Comment by Marcel0024** [comment]
I've compared the code to the ImageMagick one. All the logic and table seems correct.

The quality [here](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Formats/Jpeg/Components/Decoder/QualityEvaluator.cs#L100) is set to 3, and then it always keeps hitting continue on line 109, until it exits the method with quality 3.

The only thing i don't understand is ImageMagic's version of the quality variable [here](https://github.com/ImageMagick/ImageMagick/blob/f362c02083d27211b913c6e44794f0ac6edaf2bd/coders/jpeg.c#L898) what does quantval do?

**Comment by dlemstra** [comment]
There is a difference in the code. The sum does not check if the quantum tables are null.

**Comment by JimBobSquarePants** [comment]
@dlemstra Good spot! That should simply mean we're adding a bunch of zeros we don't need to but I've just realized `Block8x8F` doesn't implement `IEquatable<T>` so we might be getting issues there.


@Marcel0024 By my understanding they are simply the tables themselves.

`jpeg_info->quant_tbl_ptrs[0]->quantval[53]` is the 53rd index of the first quantization table.

**Comment by JimBobSquarePants** [comment]
@dlemstra Confirmed. Test example1.jpg now returns 99. I'll push a fix.

**Comment by Marcel0024** [comment]
Nice!
