### ISSUE TITLE
Is image sharp compatible with netcoreapp 2.2?

### ISSUE THREAD

**Issue by kgrosvenor** [SixLabors/ImageSharp#846]
Getting dependency issues as shown in screenshot below:

https://i.gyazo.com/c3dbdb565b88e27f9b41dcf3c2108805.png

**Comment by antonfirsov** [comment]
@kgrosvenor yes it is. Please upgrade to the latest beta!

If you still experience issues, please join our [gitter channel](https://gitter.im/ImageSharp/General) for discussions.
