### ISSUE TITLE
Image.Load throws an ArgumentException when loading PNG

### ISSUE THREAD

**Issue by casperOne** [SixLabors/ImageSharp#849]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Loading the following PNG (from a `Stream` or `ReadOnlyMemory<byte>` instance) throws an `ArgumentException`.

https://user-images.githubusercontent.com/561862/54476020-e3ab4c00-47ce-11e9-9cb1-2542507bf23c.png

Which has the following message:

````
Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
````

Notes:

- The image renders in Chrome correctly
- According to http://www.libpng.org/pub/png/apps/pngcheck.html, there are no problems with image integrity
- There are three IDAT sections in the PNG (this shouldn't make a difference, from what I can tell in my reading of the spec)
- The images are produced out of FFMPEG, but other PNG images output from the same process/video are able to be loaded

### Steps to Reproduce

Use the above image in a `FileStream` (or any `Stream` representation).

Load the image (this can be copied/pasted into a .NET Core 2.2 console app and the ImageSharp libraries referenced):

````
static async Task Main()
{
    try
    {
        // Use http client.
        var client = new HttpClient();

        // Make the request.
        using (Stream stream = await client.GetStreamAsync(
                "https://user-images.githubusercontent.com/561862/54476020-e3ab4c00-47ce-11e9-9cb1-2542507bf23c.png")
            .ConfigureAwait(false))
        {
            Image<Rgba32> image = Image.Load<Rgba32>(stream, new PngDecoder());
        }
    }
    catch (Exception e)
    {
        Console.WriteLine(e);
        throw;
    }
}
````

### System Configuration

- ImageSharp version: 1.0.0-beta0006
- Other ImageSharp packages and versions: None
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: .NET Core 2.2
- Additional information:

**Comment by clintonrocksmith** [comment]
Hi there,

I did find this as an issue but had to set the decoder explicitly to being a png otherwise it failed.  This was in a .NET Core solution as well whereby I loaded via a stream from Blob Storage in Azure, just giving more information to help.

**Comment by casperOne** [comment]
Oh derp, so if I set the decoder explicitly it should work?  I'll try that.

Interestingly enough, there are other images from the same FFMPEG instance that are successfully decoding (doesn't matter though, I'm happy to explicitly set it).

**Comment by JimBobSquarePants** [comment]
@casperOne @clintonrocksmith  The two issues are not related. There’s something about that png that causes our current decoder to fail. I fixed the issue locally today though.

The other issue sounds like it was due to the input stream being in the wrong position for us to identify the decoder.

**Comment by casperOne** [comment]
@JimBobSquarePants Thanks for the follow-up.  I'll keep an eye on this to be closed when a PR gets merged.  Looking forward to the next push to Nuget for the fix.

Thanks!

**Comment by JimBobSquarePants** [comment]
@casperOne Don't forget we have rock solid development releases on Myget

https://github.com/SixLabors/ImageSharp#installation

**Comment by casperOne** [comment]
@JimBobSquarePants Thanks for addressing this, I've confirmed this works, and have used the MyGet repository.
