### ISSUE TITLE
Consider adding a THIRD-PARTY-NOTICES.TXT file

### ISSUE THREAD

**Issue by tannergooding** [SixLabors/ImageSharp#856]
ImageSharp should consider adding a `THIRD-PARTY-NOTICES.TXT` file to contain notices for 3rd party code that is referenced or ported into ImageSharp.

This would be especially useful when code is copied from CoreFX to provide certain functionality downlevel on full framework.

**Comment by JimBobSquarePants** [comment]
Agreed. Super important for future license changes also.
