### ISSUE TITLE
Gradient brush

### ISSUE THREAD

**Issue by tocsoft** [SixLabors/ImageSharp#86]
Add support for a 'Gradient brush'

Place to start for anyone wanting to contribute would be to look at the other brush implementations inside the `ImageSharp.Drawing` project.

I would be nice if this supported both radial and linear gradients probably as 2 different brushes, one for each.

Features wanted;
- Linear Gradients
- Radial Gradients
- Multiple color stops

**Comment by JimBobSquarePants** [comment]
@tocsoft You know you're probably the only one with the chops to do this right? 😛

**Comment by seabass223** [comment]
I'm needing linear gradient brush functionality as well. @jongleur1983  let me know how I can help.

**Comment by jongleur1983** [comment]
@seabass223 if you want, feel free to look into the code of the PR https://github.com/SixLabors/ImageSharp/pull/542 that implements the linear gradient already. 
Currently the branch is not up to date on master, but that should not be a problem, I think as it should not interfere with other changes.
So if you want, you could even use it by compiling the library from that branch yourself.

**Comment by JimBobSquarePants** [comment]
@jongleur1983 Nah, we just forgot to tag the issue in the PR to do it automatically. Thanks for your help here. Wizard stuff! 👍
