### ISSUE TITLE
Support for IPTC

### ISSUE THREAD

**Issue by mbaumanndev** [SixLabors/ImageSharp#860]
As discussed on Gitter, ImageSharp doesn't support IPTC at the moment, it would be interesting to have support for it

**Comment by JimBobSquarePants** [comment]
If anyone wants to take this on specification information can be found here.

https://www.iptc.org/std/IIM/4.2/specification/IIMV4.2.pdf

**Comment by dlemstra** [comment]
The [Magick.NET](https://github.com/dlemstra/Magick.NET) library also contains a class for this. Feel free to borrow it.

**Comment by brianpopow** [comment]
closed with #1174
