### ISSUE TITLE
Larger PNG File Size (content) on Resize

### ISSUE THREAD

**Issue by tbasallo** [SixLabors/ImageSharp#876]
### Prerequisites

- [x ] I have written a descriptive issue title
- [x ] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x ] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Saving a PNG file always results in a bigger file - substantially larger (in disk space). This is true from PNG > PNG and from JPG > PNG (as a matter of testing).

I am using the default encoder and looking at the sizes on disk.

This is true whether resizing occurs or not.

### Steps to Reproduce
The following code using beta0006.

```  
var image = Image.Load(original);  
var size = new Size { Width = [1024](url) };  
var resize = new ResizeOptions() { Size = size.Value };
image.Mutate(x => x.Resize(resize));
using (var stream = new FileStream(finalFile, FileMode.Create))
{
        image.SaveAsJpeg(stream);
}
```

### System Configuration
- ImageSharp version: beta0006
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: ASP.NET Core 2.2
- Additional information: VS 2019

A PNG that is 49kb ends up as 67kb
A JPG that was 1749kb ends up as 9619kb

A tested with other files to the same result. JPG to PNG (not typical??) results in the biggest increases by far - 2-4 times the files size.

**Comment by antonfirsov** [comment]
Regarding JPEG > PNG:
This is 100% expected behavior, because PNG is a lossles format. (The same image encoded in PNG is usually much bigger)

Regarding PNG > PNG:
`PngEncoder.CompressionLevel` is responsible for controlling the level of compression. You can set it manually when encoding a png. There is a tradeoff between 
 encoding speed VS the result file size. @JimBobSquarePants we may consider adding this property to `PngMetaData` to reuse the original value with the default encoder. Hint for decision: how do image editors typically work, when opening+resaving a PNG with a non-default compression level?

**Comment by antonfirsov** [comment]
> A JPG that was 1749kb ends up as 9619kb

Let's not mix issues! Can you open another one with your jpeg image + reproduction code provided?

**Comment by tbasallo** [comment]
> > A JPG that was 1749kb ends up as 9619kb
> 
> Let's not mix issues! Can you open another one with your jpeg image + reproduction code provided?

Will do and I will close this one since the PNG>JPG behavior is expected.

**Comment by tbasallo** [comment]
@antonfirsov did you want to open the JPG > PNG behavior or PNG > PNG behavior?

You asked for the JPG in your comment so I an unsure.
I think the JPG > PNG is expected so that's a non-issue. The issue remaining is the increases in size from PNG> PNG.

If you let me know I will open a new issue with the correct info.

**Comment by antonfirsov** [comment]
Sorry, I may have nisunderstood you. Thought there is a significant jpeg-> jpeg increase as well. (It would be an issue related only to jpeg.)

**Comment by tbasallo** [comment]
No, JPG -> JPG is fine and works as expected.

However, PNG -> PNG results in a much bigger file. Is that a known issue or should I open one?

**Comment by JimBobSquarePants** [comment]
No, don’t open an issue. I’ve explained in Gitter why this can be expected also.
