### ISSUE TITLE
Minor typo in FillRectangle.cs benchmark

### ISSUE THREAD

**Issue by prajaybasu** [SixLabors/ImageSharp#878]
https://github.com/SixLabors/ImageSharp/blob/master/tests/ImageSharp.Benchmarks/Drawing/FillRectangle.cs

Line 39 - Fill**Ractangle**Core() should be Fill**Rectangle**Core

**Comment by dlemstra** [comment]
Feel free to open a PR to fix this 👍

**Comment by JimBobSquarePants** [comment]
I'm gonna close this. It doesn't affect any of the released code.
