### ISSUE TITLE
Passing Unmanaged Pointer as Pixels buffer in ImageSharp

### ISSUE THREAD

**Issue by ghost** [SixLabors/ImageSharp#88]
Part of Wayland development is that I create a Shared Memory Buffer that is being used between processes and I wanted to eliminate the amount of buffer copying between ImageSharp and Shared Memory Buffer. If implemented, we may actually be able to see a relatively fast User Interface on Linux for C# that is easy to use for everyone.

Can ImageSharp implement a safe api that accepts IntPtr for Argb or other image format pixel buffer? (Width/height/strides can be provided if needed.)

Please and thank you

**Comment by BernhardGlueck** [comment]
In addition especially for server side processing, as right now images allocate array on the .NET Heap ( which inevitable end up on the LOH etc.. ) it would be great to use this to store the image data in off heap memory using unsafe operations... maybe introduce a base interface like IPixelStorage<TColor> with a provider IPixelStorageProvider<TColor> that allows different strategies to be put int

**Comment by antonfirsov** [comment]
We are currently waiting for reliable VS2017 tooling (for C#7 ref returns) and for new official `corefx` packages. (for `Span<T>` and other low level memory management stuff). 

I think we could introduce design changes based on these features. :+1: for something like `IPixelStorageProvider`.

**Comment by CsharpOnLinuxDev** [comment]
I see, so it potentially possible that Mono would not be supported in this case. (I don't know if it's still maintained to backport Corefx.)

**Comment by JimBobSquarePants** [comment]
No that should be fine. Mono supports NetStandard

https://blog.xamarin.com/net-standard-library-support-for-xamarin/

**Comment by antonfirsov** [comment]
For implementations plans see: #565.
