### ISSUE TITLE
Padded image after Resizing in Mode.Min

### ISSUE THREAD

**Issue by dannsam** [SixLabors/ImageSharp#892]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When resizing an image that is smaller than the target image using Mode.Min, the resulting image is padded to be square instead of keeping the size of the original image.

I really don't feel like entering any other details, because the bug seems to be caused by a simple mistake - the Size is created using sourceWidth as width and height instead of using sourceWidth and sourceHeight.
 
https://github.com/SixLabors/ImageSharp/blob/87c0a664aed7dcc0942807cb48a778f044797ba7/src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeHelper.cs#L299

Going to create a pull request.

**Comment by JimBobSquarePants** [comment]
Yup that's a bug! Thanks for the PR. :+1:
