### ISSUE TITLE
Error trying to load a specific image / jpeg

### ISSUE THREAD

**Issue by pebezo** [SixLabors/ImageSharp#895]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
We're using beta6 to load images and resize them. It works fine except for this one image (I'll try to attach the image to this ticket) where we get:

``Image cannot be loaded. Available decoders:\r\n - PNG : PngDecoder\r\n - GIF : GifDecoder\r\n - JPEG : JpegDecoder\r\n - BMP : BmpDecoder\r\n","stack":"   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)``

### Steps to Reproduce
using (Image<Rgba32> image = SixLabors.ImageSharp.Image.Load(input, out var format)) { .. it doesn't get here ... }

### System Configuration

- ImageSharp version: beta6
- Other ImageSharp packages and versions: N/A
- Environment (Operating system, version and so on): Windows Server 2012 R2
- .NET Framework version: .NET Core 2.1
- Additional information:

![f150](https://user-images.githubusercontent.com/1287097/56810805-33852600-6805-11e9-98e4-4ea01ffe2601.jpeg)

**Comment by dlemstra** [comment]
That image is a `WEBP` image that has an `JPEG` extension:

```
identify 56810805-33852600-6805-11e9-98e4-4ea01ffe2601.jpeg
56810805-33852600-6805-11e9-98e4-4ea01ffe2601.jpeg WEBP 1440x618 1440x618+0+0 8-bit sRGB 97006B 0.000u 0:00.000
```

**Comment by pebezo** [comment]
I gather WEBP is not supported... Should I close this issue or leave it open for future reference?

**Comment by dlemstra** [comment]
WEBP is indeed not supported, see: #121
