### ISSUE TITLE
Required Version of System.Buffers?

### ISSUE THREAD

**Issue by mskincaid** [SixLabors/ImageSharp#900]
### Description
I used the Visual Studio Nuget Package Manager to update several SixLabors packages, for the solution.  Also updated System.Buffers to v 4.5.0, per the dependency info for SixLabors.Core.

Solution builds successfully, after updating.  But I'm getting errors like below, at runtime.  Note the reference to an earlier version of System.Buffers.  

Any easy fix?  Something I can change in VS, perhaps?  Thanks!

Exception:
System.AggregateException: One or more errors occurred. ---> System.TypeInitializationException: The type initializer for 'SixLabors.ImageSharp.Configuration' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
   at SixLabors.Memory.ArrayPoolMemoryAllocator.InitArrayPools()
   at SixLabors.Memory.ArrayPoolMemoryAllocator.CreateDefault()
   at SixLabors.ImageSharp.Configuration..ctor(IConfigurationModule[] configurationModules)
   at SixLabors.ImageSharp.Configuration.CreateDefaultInstance()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at SixLabors.ImageSharp.Configuration..cctor()
   --- End of inner exception stack trace ---

### System Configuration

- ImageSharp version: 1.0.0-beta0006

- Other ImageSharp packages and versions:

Sixlabors.Core v 1.0.0-beta0007
SixLabors.Fonts- v1.0.0-beta0008
SixLabors.Shapes v1.0.0-beta0008

- Environment (Operating system, version and so on): 
Windows 10 
Visual Studio 2017

- .NET Framework version:  4.7.2

**Comment by JimBobSquarePants** [comment]
See https://github.com/dotnet/corefx/issues/31718 
Not specific to ImageSharp. Also we don't depend on System.Buffers to v4.5.0. v4.4.0 is our minimum target.

https://www.nuget.org/packages/SixLabors.Core/1.0.0-beta0007#show-dependency-groups

**Comment by mskincaid** [comment]
Thanks JimBob.  I used 4.5.0 because Six.Labors.Core said >=4.4.0 was acceptable.  But perhaps 4.4.0 is required?

**Comment by JimBobSquarePants** [comment]
4.4.0 works well enough on my test machine with 4.7.2, I'm curious as to why your project chose v4.5.0 but with many of the binding redirects inherent with netstandard it's a shrug factory. 

If your app or web.config doesn't have any redirects specifying System.Buffers it's definitely an issue upstream at MS and not something we can control. I'd maybe raise an issue with CoreClr and reference both the CoreFX issue and this one.

**Comment by mskincaid** [comment]
Shrug factory, indeed : ).  4.5.0 was chosen becasue of some of the other Nuget Packages we use (unrelated to SixLabors).

I tried updating app.config on all projects, manually.  No, luck.  No references to System.Buffers in any web.config files, so can rule that out.  

Will post an update, if I figure anything out.  Thanks for the tips!

**Comment by JimBobSquarePants** [comment]
Here's the contents of a working csproj file that is using the latest bits on NetFramework 4.7.2

The dev build is rock solid and uses way less memory than the beta so I'd recommend it but you might be able to get away with using just the following line:

```xml
<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
```

Full File:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{54676B5F-C7B2-451C-9F9F-6FFDB9902E19}</ProjectGuid>
    <OutputType>Exe</OutputType>
    <RootNamespace>ImageSharp.TestFramework</RootNamespace>
    <AssemblyName>ImageSharp.TestFramework</AssemblyName>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp">
      <Version>1.0.0-dev002613</Version>
    </PackageReference>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

Interestingly. Nuget actually dropped me down to System.Buffers 4.4.0 when updating:

![Nuget update dialogue](https://user-images.githubusercontent.com/385879/57112697-82dad180-6d84-11e9-8f58-0eb26bee002a.png)
