### ISSUE TITLE
Memory usage is high and has not been released for a long time

### ISSUE THREAD

**Issue by zengqinglei** [SixLabors/ImageSharp#912]
### High memory usage

- [ ] .net core 2.2
- [ ] SixLabors.ImageSharp-1.0.0-beta0005
- [ ] Windows Server 2012 R2

### Description
In my project, when using image operations (trimming, resizing, converting format...), the memory required for the project will continue to increase and will not be released for a long time!

### Steps to Reproduce
Some sample usage code in the project is as follows:
``` csharp
using (var image = Image.Load(filePath))
{
    int width = image.Width;
    int height = image.Height;
    if (!string.IsNullOrEmpty(widthStr))
    {
        width = int.Parse(widthStr);
    }
    if (!string.IsNullOrEmpty(heightStr))
    {
        height = int.Parse(heightStr);
    }
    var resizeOptions = new ResizeOptions()
    {
        Size = new SixLabors.Primitives.Size(width, height)
    };
    if (!string.IsNullOrEmpty(mode))
    {
        resizeOptions.Mode = (ResizeMode)Enum.Parse(typeof(ResizeMode), mode, true);
    }
    image.Mutate(ctx => ctx.Resize(resizeOptions));
    image.Save(filePath);
}
```

``` csharp
using (var image = Image.Load(filePath))
{
    IImageEncoder imageEncoder;
    switch (fileExt.ToLower())
    {
        case "jpg":
        case "jpeg":
            {
                imageEncoder = new JpegEncoder() { Quality = value };
            }
            break;
        default:
            throw new UserFriendlyException(ErrorCode.BadRequest, "暂不支持该格式质量调整");
    }
    image.Save(filePath, imageEncoder);
}
```
......

**Below is a screenshot of my memory analysis**
![image](https://user-images.githubusercontent.com/7374317/58073234-a7340c00-7bd4-11e9-91fc-fa2eec9e3f08.png)

I hope to get your help as soon as possible, thank you very much!

**Comment by JimBobSquarePants** [comment]
Beta5?

**Comment by zengqinglei** [comment]
> beta5的？
> 
> 从MyGet下载最新版本。你的内存使用量应该大幅下降

OK.
let me try

**Comment by zengqinglei** [comment]
> Beta5?
> 
> Download the latest builds from MyGet. Your memory usage should fall dramatically

Hi
After updating to the beta6 version, after nearly three hours of testing, although the memory is lower than before, there is still a problem of high memory usage.

![image](https://user-images.githubusercontent.com/7374317/58085197-df484880-7bee-11e9-8e17-f75cc04e20a8.png)

![image](https://user-images.githubusercontent.com/7374317/58085236-eff8be80-7bee-11e9-9768-60f532b20816.png)

I hope to get your help as soon as possible, thank you very much!

**Comment by JimBobSquarePants** [comment]
Beta6 is Nuget not MyGet. The link is in the readme.

**Comment by antonfirsov** [comment]
The MyGet nightly version should be much better at this, but make sure to read this, to understand how memory is managed:
https://docs.sixlabors.com/articles/ImageSharp/MemoryManagement.html

**Comment by zengqinglei** [comment]
> The MyGet nightly version should be much better at this, but make sure to read the following docs, to understand how memory is managed:
> https://docs.sixlabors.com/articles/ImageSharp/MemoryManagement.html

Hi
At present, my application keeps the memory occupied between 300-400mb. According to the documentation, it belongs to the normal range, thank you very much!
