### ISSUE TITLE
Read lens from EXIF

### ISSUE THREAD

**Issue by claunia** [SixLabors/ImageSharp#919]
Hi,

I would be nice to be able to read the Lens from the EXIF information in a JPEG file.

In a PNG file they appear as a property called "aux:lens".

Edit:
I see that the tag appears but it's not getting decoded, in this photo:
https://commons.wikimedia.org/wiki/File:Independence_of_the_Seas_panorama_in_Las_Palmas.jpg

According to exiftool:
```
JPEG APP1 (1543 bytes):
  + [XMP directory, 1514 bytes]
  | XMPToolkit = XMP Core 5.1.2
  | LensID = -2147483648
  | ImageNumber = 10647
  | LensInfo = 18/1 105/1 7/2 28/5
  | Lens = AF-S DX VR Zoom-Nikkor 18-105mm f/3.5-5.6G ED
```

**Comment by JimBobSquarePants** [comment]
Questions on Gitter please.

**Comment by claunia** [comment]
This is not a question, it's a bug.

**Comment by JimBobSquarePants** [comment]
Then fill the form in properly
