### ISSUE TITLE
Resized image contains a a different layer on lower part

### ISSUE THREAD

**Issue by vikash-agrawal-arimon** [SixLabors/ImageSharp#926]
Hi,

I am using beta 6 release Image Sharp and deploying on Azure App Functions. Image resizing is working but the lower part of the resized image contains a different layer it seems. 
Below is my code to resize:

```
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Formats.Jpeg;
using SixLabors.ImageSharp.Formats.Png;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;
using SixLabors.Primitives;

public static void Run(Stream myBlob, string name, ILogger log, Stream outputBlob)
{
    log.LogInformation($"C# Blob trigger function Processed blob\n Name:{name} \n Size: {myBlob.Length} Bytes");
    using (Image<Rgba32> image  = Image.Load(myBlob))
    {
                image.Mutate(x => x.Resize(300, 200));
                image.Save(outputBlob,new PngEncoder());
 
    }
}
```

Original Image:
![DSC_0120 (1)](https://user-images.githubusercontent.com/37694376/58906947-b82f6200-872a-11e9-818c-bc5cdf93dda5.JPG)

Resized:
![DSC_0120](https://user-images.githubusercontent.com/37694376/58906955-bebdd980-872a-11e9-9b88-c59e778262b1.JPG)

**Comment by JimBobSquarePants** [comment]
Duplicated of https://github.com/SixLabors/ImageSharp/issues/890 please update to the latest build from MyGet

**Comment by vikash-agrawal-arimon** [comment]
No its not closed. I tried with dev builds mentioned in the post with the same version in dev and with current nightly build too. I am still getting the same error with JPG files. With png files its working fine.

**Comment by JimBobSquarePants** [comment]
Could you please clarify:

1. Does the issue occur when encoding or when decoding jpeg files?
2. Does the issue occur when you simply load/save the image without resizing
3. Does the issue occur in both 32 bit and 64 bit environments?
4. What framework are you targeting?

**Comment by sport-monkey** [comment]
Are you targeting Azure Functions version v1 or v2?

**Comment by fatihsokmen** [comment]
We've having the same problem, anybody solved this or any workaround?

**Comment by JimBobSquarePants** [comment]
Version number, image?

**Comment by rrasho** [comment]
I am seeing this with azure functions V3 (3.0.13139.0). Resizing book covers from large jpgs to smaller png.

I do not see the issue when running locally on my Mac, or in my parallels install of windows 10.

What my image should look like (resized locally):
![M](https://user-images.githubusercontent.com/8754709/79391766-2397b200-7f40-11ea-9024-f75ca1824781.png)

What it looks like resized by azure function:
![M](https://user-images.githubusercontent.com/8754709/79391891-5f327c00-7f40-11ea-8189-bfe3010fdd10.png)

**Comment by JimBobSquarePants** [comment]
You need to let us know the ImageSharp version. We can do nothing without it

**Comment by JimBobSquarePants** [comment]
Code samples also to replicate the issue.

**Comment by fatihsokmen** [comment]
> Version number, image?

I used 1.0.0-beta0007. I have same issue as @rrasho has

**Comment by JimBobSquarePants** [comment]
Can you try the latest build from our MyGet package source?

**Comment by JimBobSquarePants** [comment]
Also try copying the input stream to a MemoryStream then resetting the position before using it to load the image.

**Comment by JimBobSquarePants** [comment]
@rrasho @fatihsokmen does the issue only happen when saving to png? Only when resizing? or does simply loading/saving a jpeg cause the issue?

**Comment by rrasho** [comment]
I am also using 1.0.0-beta007, downloaded from nuget.org. I will try the version from the myget source.

The code works fine for the same image when run locally as seen above. It also works for most of our images in when they run through our azure function. 

```
public async Task CreateResizedImages(Stream originalImage, string path, string extension)
        {
            Dictionary<string, double> sizes = new Dictionary<string, double>
            {
                {"XL", 800},
                {"L", 600},
                {"M", 400},
                {"S", 200},
                {"XS", 100}
            };
            using var image = Image.Load(originalImage);
            // Reduce the size of the file
            image.Metadata.ExifProfile = null;
            foreach (var size in sizes.Keys)
            {
                await using MemoryStream newImageStream = new MemoryStream();
                if (image.Width > sizes[size])
                {
                    var outputWidth = sizes[size];
                    double inputWidth = image.Width;
                    var outputHeight = Math.Round(image.Height * (outputWidth / inputWidth));
                    using var newImage = image.Clone(context => context.Resize(new ResizeOptions
                    {
                        Size = new Size((int) outputWidth, (int) outputHeight),
                        Mode = ResizeMode.Max
                    }));
                    newImage.SaveAsPng(newImageStream);
                }
                else
                {
                    image.SaveAsPng(newImageStream);
                }

                newImageStream.Seek(0, SeekOrigin.Begin);

                await _blobUtility.UploadToCdnFromStream(newImageStream, $"{path}/{size}.png", "image/png");
            }
}
```

**Comment by JimBobSquarePants** [comment]
@rrasho Could you please also check to see whether you can reduce the sample to help us identify the issue? Thanks!

**Comment by JimBobSquarePants** [comment]
> What do you mean by reduce the sample, provide smaller example images?

I mean a reduced code sample. We can't tell if the issue happens only when resizing, or simply simply when encoding to a png.

**Comment by JimBobSquarePants** [comment]
How much memory are you allowing with your Azure Functions?

**Comment by rrasho** [comment]
> How much memory are you allowing with your Azure Functions?

3.5 GB

> I mean a reduced code sample. We can't tell if the issue happens only when resizing, or simply simply when encoding to a png. Your code sample has branching for both scenarios.
> 
> Does it happen only with png or does saving as jpeg produce the same issue.

I see. Here is my code to simply save as png (results in distortion):
```
await using var copyOriginalStream = new MemoryStream();
image.SaveAsPng(copyOriginalStream);
copyOriginalStream.Seek(0, SeekOrigin.Begin);
await _blobUtility.UploadToCdnFromStream(copyOriginalStream, $"{path}/O.png", "image/png");
```

And here is the code to do the same resizing, but save as jpeg (still results in distortion):
```
Dictionary<string, double> sizes = new Dictionary<string, double>
            {
                {"XL", 800},
                {"L", 600},
                {"M", 400},
                {"S", 200},
                {"XS", 100}
            };
            using var image = Image.Load(originalImage);

            foreach (var size in sizes.Keys)
            {
                await using MemoryStream newImageStream = new MemoryStream();
                if (image.Width > sizes[size])
                {
                    var outputWidth = sizes[size];
                    double inputWidth = image.Width;
                    var outputHeight = Math.Round(image.Height * (outputWidth / inputWidth));
                    using var newImage = image.Clone(context => context.Resize(new ResizeOptions
                    {
                        Size = new Size((int) outputWidth, (int) outputHeight),
                        Mode = ResizeMode.Max
                    }));
                    newImage.SaveAsJpeg(newImageStream);
                }
                else
                {
                    image.Save(newImageStream, new JpegEncoder());
                }

                newImageStream.Seek(0, SeekOrigin.Begin);

                await _blobUtility.UploadToCdnFromStream(newImageStream, $"{path}/jpeg/{size}.jpeg", "image/jpeg");
            }
```

Finally, I have copied my input Stream into a MemoryStream and resized as jpeg as shown below. This has resolved the distortion. It appears that loading an image from a Stream was the issue. The input stream is provided by an Azure EventGridTrigger as they do in the provided example ([See here line 73](https://github.com/Azure-Samples/function-image-upload-resize/blob/master/ImageFunctions/Thumbnail.cs)).

```
public async Task CreateResizedJpegs(Stream originalImage, string path, string extension)
        {
            Dictionary<string, double> sizes = new Dictionary<string, double>
            {
                {"XL", 800},
                {"L", 600},
                {"M", 400},
                {"S", 200},
                {"XS", 100}
            };
            await using MemoryStream originalImageMemoryStream = new MemoryStream();
            originalImage.CopyTo(originalImageMemoryStream);

            originalImage.Seek(0, SeekOrigin.Begin);
            originalImageMemoryStream.Seek(0, SeekOrigin.Begin);

            using var image = Image.Load(originalImageMemoryStream);

            await using var copyOriginalStream = new MemoryStream();
            image.SaveAsPng(copyOriginalStream);
            copyOriginalStream.Seek(0, SeekOrigin.Begin);
            await _blobUtility.UploadToCdnFromStream(copyOriginalStream, $"{path}/jpeg/O.jpeg", "image/jpeg");

            foreach (var size in sizes.Keys)
            {
                await using MemoryStream newImageStream = new MemoryStream();
                if (image.Width > sizes[size])
                {
                    var outputWidth = sizes[size];
                    double inputWidth = image.Width;
                    var outputHeight = Math.Round(image.Height * (outputWidth / inputWidth));
                    using var newImage = image.Clone(context => context.Resize(new ResizeOptions
                    {
                        Size = new Size((int) outputWidth, (int) outputHeight),
                        Mode = ResizeMode.Max
                    }));
                    newImage.SaveAsJpeg(newImageStream);
                }
                else
                {
                    image.Save(newImageStream, new JpegEncoder());
                }

                newImageStream.Seek(0, SeekOrigin.Begin);

                await _blobUtility.UploadToCdnFromStream(newImageStream, $"{path}/jpeg/{size}.jpeg", "image/jpeg");
            }

            originalImage.Seek(0, SeekOrigin.Begin);
        }
```

**Comment by fatihsokmen** [comment]
Copying from blob stream to memory stream seems to fixed the issue on our side. Thanks

**Comment by JimBobSquarePants** [comment]
I thought that might be the case. Could you please both let me know what the type of the input stream is. I’d like to do some deeper investigation to see if I can make the experience better.

**Comment by fatihsokmen** [comment]
We use Azure blob trigger to generate thumbnails. Azure provides an abstract **Stream** which I believe stream implementation is not suitable for ImageSharp api.  So, copying blob stream into a MemoryStream worked.

**Comment by sescandell** [comment]
> Copying from blob stream to memory stream seems to fixed the issue on our side. Thanks

Worked for me too! (on an app deployed on an App Service getting stream from a Blob)

Thanks for this usefull help!

**Comment by JimBobSquarePants** [comment]
You can now use the asynchronous API in RC3 which should avoid the copy.

**Comment by sescandell** [comment]
So nice !

Sure I will !

Many thanks,

**Comment by sescandell** [comment]
Hi @JimBobSquarePants just moved on the RC3 and async without copy: issue comes back.

I'm using the LoadWithFormatAsync() method (don't know if it is important or not).
Using the MemoryStream between my Blob Stream and ImageSharp works as expected.

I can help for tests or... anything else if in need of additional information.

**Comment by JimBobSquarePants** [comment]
What do you mean “issue comes back” the issue at the top of this thread?

**Comment by sescandell** [comment]
> What do you mean “issue comes back” the issue at the top of this thread?

Yes: part of the bottom's image is broken.
Original:
![image](https://user-images.githubusercontent.com/1559970/86243944-7f6cf100-bba7-11ea-955e-b6b788550989.png)

Resized:
![image](https://user-images.githubusercontent.com/1559970/86243840-4fbde900-bba7-11ea-95cf-28afa46e489a.png)

**Comment by JimBobSquarePants** [comment]
Can you paste a complete code sample please and I’ll look into it.

**Comment by sescandell** [comment]
I'll do
