### ISSUE TITLE
Mutation to transparent background don't work sometimes

### ISSUE THREAD

**Issue by xakep139** [SixLabors/ImageSharp#931]
### Prerequisites

- [X] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I'm not sure that it's a bug, maybe I've just missed something, Before beta006 (more specifically, on version `1.0.0-dev001621`) we made transparent background like this: https://github.com/SixLabors/Samples/blob/625dd0ace7c30ed9cb3dc7a48304471e0bd91b76/ImageSharp/AvatarWithRoundedCorner/Program.cs#L87
After #882 we moved to `1.0.0-dev002548` and changed logic to: https://github.com/SixLabors/Samples/blob/master/ImageSharp/AvatarWithRoundedCorner/Program.cs#L85 (but this could be reproduced on latest `1.0.0-dev002737` as well)
But some pictures have black background after upgrading, not transparent.

### Steps to Reproduce

Sample project https://github.com/SixLabors/Samples/tree/master/ImageSharp/AvatarWithRoundedCorner could be used with the following image: [image.zip](https://github.com/SixLabors/ImageSharp/files/3284196/image.zip)
Here's the output of different versions of ImageSharp: [outputs.zip](https://github.com/SixLabors/ImageSharp/files/3284198/outputs.zip)

### System Configuration

- ImageSharp version: `1.0.0-dev002737`
- Other ImageSharp packages and versions: `SixLabors.ImageSharp.Drawing 1.0.0-dev002737`
- Environment (Operating system, version and so on): Windows 10 Enterprise version 1809 build 17763.475
- .NET Framework version: dotnet SDK 2.1.603
- Additional information:

**Comment by JimBobSquarePants** [comment]
Hi @xakep139 

Your output images are 24bit. This can only happen when the `PngEncoder` instance has its `ColorType` property set to `PngColorType.Rgb` or when it is null and the `PngMetadata` within the image has the property set to `PngColorType.Rgb`.

You'll need to explicitly set the `PngColorType` to `RgbWithAlpha` in the encoder when encoding to the png to preserve transparency.

**Comment by xakep139** [comment]
@JimBobSquarePants, thanks for the quick response! Changing `ColorType` for the encoder worked like a charm!
Should this be reflected in samples?

**Comment by JimBobSquarePants** [comment]
Most definitely. We need to give those samples some love.

**Comment by antonfirsov** [comment]
A reminder that I should take care of this when l'll touch the samples because of #907.

**Comment by xakep139** [comment]
I suppose this issue should be closed ) Thanks for the help!
