### ISSUE TITLE
"Bit depth is not supported or not valid" on saving PNG

### ISSUE THREAD

**Issue by xakep139** [SixLabors/ImageSharp#935]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Setting `ColorType` property on `PngEncoder` settings causes `NotSupportedException`.
Here's the stacktrace:
```
   at SixLabors.ImageSharp.Formats.Png.PngEncoderCore.Encode[TPixel](Image`1 image, Stream stream)
   at SixLabors.ImageSharp.Formats.Png.PngEncoder.Encode[TPixel](Image`1 image, Stream stream)
   at SixLabors.ImageSharp.ImageExtensions.Save(Image source, String filePath, IImageEncoder encoder)
   at ImageSharpTest.Program.Main(String[] args) in C:\Users\User\Documents\Visual Studio 2019\Projects\ImageSharpTest\Program.cs:line 16
```

### Steps to Reproduce

```
using (var image = Image.Load("image.png"))
{
    image.Save("output.png", new PngEncoder { ColorType = PngColorType.RgbWithAlpha });
}
```
with image [image.zip](https://github.com/SixLabors/ImageSharp/files/3296181/image.zip)

Just adding `BitDepth = PngBitDepth.Bit8` to `PngEncoder` settings solves this problem.

### System Configuration

- ImageSharp version: 1.0.0-dev002749
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by JimBobSquarePants** [comment]
@xakep139 That's currently working as intended. 

The input image is 1 bit image, which the color type does not support. We also cannot automatically choose the correct bit depth since each color type supports multiple bit depths. 

We should improve the error message though to make it more clear by listing out the bitdepths that are available for each type.
