### ISSUE TITLE
DrawImageExtensions.DrawImage throws DivideByZeroException

### ISSUE THREAD

**Issue by IhnatKlimchuk** [SixLabors/ImageSharp#940]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
DrawImageExtensions.DrawImage throws DivideByZeroException when drawing another image out of borders.

### Steps to Reproduce
Here code sample:
```
            var previewDefaultPixels = Enumerable
                            .Range(0, 200 * 300)
                            .Select(t => Rgba32.Transparent)
                            .ToArray();

            var chunkDefaultPixels = Enumerable
                            .Range(0, 100 * 100)
                            .Select(t => Rgba32.Red)
                            .ToArray();

            using (var previewImage = Image.LoadPixelData(previewDefaultPixels, 300, 200))
            {
                previewImage.Mutate(ctx =>
                {
                    using (var chunkImage = Image.LoadPixelData(chunkDefaultPixels, 100, 100))
                    {
                        ctx.DrawImage(chunkImage, new Point(400, 150), 1);
                    }
                });
            }
```

### System Configuration

- ImageSharp version: `SixLabors.ImageSharp- 1.0.0-beta0006`
- Other ImageSharp packages and versions: `SixLabors.ImageSharp.Drawing - 1.0.0-beta0006`
- Environment (Operating system, version and so on): Windows 10 Pro 1803
- .NET Framework version: .NET Core 2.1

**Comment by JimBobSquarePants** [comment]
Hi @IhnatKlimchuk  

Does the same thing happen with the dev build from [MyGet](https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp.Drawing)?

**Comment by IhnatKlimchuk** [comment]
Hi @JimBobSquarePants 

I've tested with with `SixLabors.ImageSharp.Drawing - 1.0.0-dev002752` from MyGet. I can see `ImageProcessingException` exception with `Cannot draw image because the source image does not overlap the target image.` message. This looks fine for me, I guess we can close the issue.

Many thanks for help!

**Comment by JimBobSquarePants** [comment]
@IhnatKlimchuk Excellent. I thought that would be the case. I'm glad I could help you.
