### ISSUE TITLE
imagesharp trying to make an animated gif that count from 0 to 9

### ISSUE THREAD

**Issue by Spirch** [SixLabors/ImageSharp#942]
anyone could tell me why this generate a black only animated gif?

the code also output each in memory generated gif to show that they are different

        public static void Test()
        {
            Image<Rgba32> img = null;
            Image<Rgba32> gif = null;

            TextGraphicsOptions textGraphicsOptions = new TextGraphicsOptions(true);
            SolidBrush<Rgba32> brushYellow = new SolidBrush<Rgba32>(Rgba32.Yellow);

            FontCollection fonts = new FontCollection();
            fonts.Install(fontLocation);
            Font font = fonts.CreateFont("Liberation Mono", PngFontHeight, FontStyle.Regular);

            gif = new Image<Rgba32>(400, 400);
            for (int i = 0; i < 10;++i)
            {
                img = new Image<Rgba32>(400, 400);
                img.Mutate(x => x.Fill(Rgba32.Black));
                img.Mutate(x => x.DrawText(textGraphicsOptions, i.ToString(), font, brushYellow, new PointF(1,1)));

                gif.Frames.AddFrame(img.Frames[0]);

                using (FileStream fs = File.Create(Path.Join(Program.workingDirectory, string.Format("Test-{0}.gif", i))))
                {
                    img.SaveAsGif(fs);
                }

                img.Dispose();
            }

            using (FileStream fs = File.Create(Path.Join(Program.workingDirectory, "Test.gif")))
            {
                gif.SaveAsGif(fs);
            }
        }

if I code it to load each [individual physical file using this code][1] it make the animated gif as expected.

I want to create the animated gif in memory only.

(also I posted the same thing on https://stackoverflow.com/questions/56745785)

  [1]: https://stackoverflow.com/a/48614256/40868

**Comment by LanceUMatthews** [comment]
I posted an answer to the StackOverflow question but wanted to share my findings here as well in case either this is a bug or someone who possesses more than my limited knowledge of GIF images can explain what's happening.

1. After running the code above and opening `Test.gif` in GIMP, I see that the animation consists of one transparent frame followed by 10 all-black frames.  Further, the `Image` → `Image Properties` and `Windows` → `Dockable Dialogs` → `Colormap` dialogs show that the color table consists of only one color.

2. Removing `gif`'s initial transparent frame before saving...

       gif.Frames.RemoveFrame(0);
       using (FileStream fs = File.Create(Path.Join(Program.workingDirectory, "Test.gif")))
       {
           gif.SaveAsGif(fs);
       }

   ...creates a 10-frame, 91-color `.gif` that animates as expected.

3. Keeping `gif`'s initial frame but making it the last frame by adding frames in the `for` loop with...

       gif.Frames.InsertFrame(0, img.Frames[0]);

   ...produces an 11-frame, 98 color `.gif` that animates as expected.

4. Keeping `gif`'s initial frame at the beginning but making it opaque with something like...

       gif = new Image<Rgba32>(400, 400);
       gif.Mutate(context => context.Fill(Rgba32.Red));
       for (int i = 0; i < 10;++i)
       {
           // ...
       }

   ...produces an 11-frame, 1-color `.gif` where all 11 frames are filled with red.

I'm not sure but cases 1 and 4 above seem to suggest ImageSharp is only looking at the first frame when creating a color table.  Here's output files for those 4 cases, rendered at 100 x 100:

1. Initial frame first, transparent:
   ![Case 1 - Initial frame first, transparent](https://user-images.githubusercontent.com/29932240/60224006-5b652a00-9846-11e9-8b0a-94920b37a81a.gif)
2. Initial frame removed:
   ![Case 2 - Initial frame removed](https://user-images.githubusercontent.com/29932240/60224008-5dc78400-9846-11e9-980b-1cb086138c24.gif)
3. Initial frame last, transparent:
   ![Case 3 - Initial frame last, transparent](https://user-images.githubusercontent.com/29932240/60224013-61f3a180-9846-11e9-8d2a-04776730d77c.gif)
4. Initial frame first, red:
   ![Case 4 - Initial frame first, red](https://user-images.githubusercontent.com/29932240/60224017-63bd6500-9846-11e9-8d16-b49adc5746b7.gif)

**Comment by LanceUMatthews** [comment]
Doh.  Well, it looks like I was right about the color table being based on the first frame, but it's not a bug.  This needs to be run...

    gif.MetaData.GetFormatMetaData(GifFormat.Instance).ColorTableMode = GifColorTableMode.Local;

...so that, according to IntelliSense, "A unique color table is calculated for each frame."  The default of `GifColorTableMode.Global` means the color table from the first frame is used for all frames, which explains the behavior above.  Although, removing that initial frame entirely seems to be the correct solution here since that frame isn't desired, anyways.

**Comment by JimBobSquarePants** [comment]
@LanceUMatthews Yeah that's expected. 

Gifs can store either global or local color tables which we enumerate.  [GifColorTableMode](https://github.com/SixLabors/ImageSharp/blob/692e244f9ab4adfd57e5c7a8636fd6fc59dc86d7/src/ImageSharp/Formats/Gif/GifColorTableMode.cs#L9)

To preserve file space and reduce encoding time we default to using a global table.

You can also set that value if you use a custom encoder.

**Comment by Spirch** [comment]
thanks for all this information, is there a faq or tips or document where this is explained? if not and it is planned to have one, maybe adding this issue / question to it could be useful.

**Comment by JimBobSquarePants** [comment]
We will add samples and comprehensive documentation. It’s a ton of work though and there’s only a few of us so it will come in drips and drabs. There are existing API docs we’ll update also.
