### ISSUE TITLE
Support Reading/Writing PNG tEXt, zTXt, and iTXt Chunks

### ISSUE THREAD

**Issue by bobbahbrown** [SixLabors/ImageSharp#943]
@JimBobSquarePants requested I open this feature request.

As discussed in Glitter, the library currently cannot write (and does not expose reading) PNG tEXt, zTXt, or iTXt chunks that are used for storing data in the PNG format.

It would be a helpful feature as in some implementations of using the PNG format these data chunks are used to store critical information for consuming the file in various applications.

As posted in Glitter by JimBobSquarePants, the specification of these chunks can be found here:
https://www.w3.org/TR/PNG/#11zTXt

**Comment by JimBobSquarePants** [comment]
Note to self: We'll need to put some thought as how to store the metadata. I don't think the `ImageProperty` property collection will suffice. (I'm not even sure if we should keep that property.)

**Comment by brianpopow** [comment]
I think i can do that. @JimBobSquarePants why do you think the ImageProperty would not be sufficient?

**Comment by JimBobSquarePants** [comment]
Fixed with #951
