### ISSUE TITLE
ImageSharp is not downloadable from official MyGet repo 

### ISSUE THREAD

**Issue by chris-david-taylor** [SixLabors/ImageSharp#945]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Image sharp is not downloadable from the official Nuget feed specified in the README.  

https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp.Web

'doctype' is an unexpected token. The expected token is 'DOCTYPE'. Line 1, position 3.
### Steps to Reproduce

 Using Visual Studio 2019, add the following URL as a Nuget feed:
https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp.Web

Response: "Error occurred" 
Console: 'doctype' is an unexpected token. The expected token is 'DOCTYPE'. Line 1, position 3.

### System Configuration
- Windows 10
- Visual Studio 2019
- Dotnet Core v3.0

**Comment by JimBobSquarePants** [comment]
You’ve listed the URL for the landing page for the ASP.NET Core Middleware. The Nuget feed is listed on the following page. 

https://www.myget.org/feed/sixlabors/package/nuget/SixLabors.ImageSharp

The correct feed URL is

https://www.myget.org/F/sixlabors/api/v3/index.json
