### ISSUE TITLE
Arial could not be found

### ISSUE THREAD

**Issue by cesarmaluco** [SixLabors/ImageSharp#953]
Hi Guys im facing an issue wen running on Linux.
The following code throws an error running on Linux. ( aspnet core 2.2 , SixLabors 1.0.0-beta0007 )

 Font font = SystemFonts.CreateFont("Arial", 10);

"Arial could not be found" 

could you help me out ?

**Comment by dlemstra** [comment]
You should ask these kind of questions in gitter instead. You will need to install the `Arial` font if you want to use it. The package for this is called `msttcorefonts` on Ubuntu. Not sure what the name is on your Linux version.

**Comment by JimBobSquarePants** [comment]
Closing as not an ImageSharp issue.

**Comment by Kemsekov** [comment]
> You should ask these kind of questions in gitter instead. You will need to install the `Arial` font if you want to use it. The package for this is called `msttcorefonts` on Ubuntu. Not sure what the name is on your Linux version.

I am hate it very much. Why I need to bother with such trivial things? Why don't include one single defualt font in library supported that I can use it without thinking about installing font? This is just absurdly HARD TO GET IT WORKING!

**Comment by JimBobSquarePants** [comment]
You need to do two things right now of you will be banned from this repository. 

1. Apologise for your attitude 
2. Read the documentation at docs.sixlabors.com

We don’t write this open source software for you to abuse us online. SystemFontCollection exists exactly for this purpose.

**Comment by Kemsekov** [comment]
Okey. I am sorry for my attitude. I am read that you cannot have fonts installed in your library for several reasons, so my rage was stupid and had no any sense. I'm sorry.

**Comment by Kemsekov** [comment]
> You need to do two things right now of you will be banned from this repository. 
> 
> 1. Apologise for your attitude 
> 2. Read the documentation at docs.sixlabors.com
> 
> We don’t write this open source software for you to abuse us online. SystemFontCollection exists exactly for this purpose. 
> 
> 
> 
> 
> 

And about SystemFontCollection. It is still not able to find arial font out of the box on my linux setup, which is okey. I'll just borrow all fonts I need with application. I know you guys are working hard for this project and my attitude made you feel bad. But I just had really tight deadline so I was a bit nervous too. Now everything is fine. I love what your are doing.

**Comment by EgoPingvina** [comment]
Years have passed, and how to solve such a basic problem, there is still no answer.
What's more, I'm running the app on my Windows laptop and the system fonts aren't showing up either. So it's not operating system dependent, it's exactly the problem of `SystemFonts.CreateFont`.

**Comment by JimBobSquarePants** [comment]
What the hell are you in about?
