### ISSUE TITLE
Weird AdaptiveHistogramEqualizationProcessor output for specific dimensions

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#994]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
`AdaptiveHistogramEqualizationProcessor` is producing weird output for dimensions 110x110:
![Issue984_Rgba32_TestPattern110x110](https://user-images.githubusercontent.com/6835152/64082208-c54cf480-cd0b-11e9-93b2-18c0935551d7.png)

### Steps to Reproduce
Run test case `HistogramEqualizationTests.Issue984(110, 110)`

### System Configuration
- ImageSharp version: current main
- Other ImageSharp packages and versions: -
- Environment (Operating system, version and so on): any
- .NET Framework version: any
- Additional information: -

**Comment by brianpopow** [comment]
I know the reason for that now. The clipping is not working as intended for such small tile sizes. I need to rework the way clipping is done. I will provide a PR as soon as i find time.

**Comment by antonfirsov** [comment]
Thanks for the fix!
